### ISSUE TITLE
New site request: Please add Custom Sites to Firefox

### ISSUE THREAD

**Issue by filchef** [iamadamdev/bypass-paywalls-chrome#1005]
### New site requests - Before submitting an issue please read the following:

Only large or major sites will be considered. Usually premium articles cannot be bypassed as they are behind a hard paywall.

1. Install the uBlock Origin extension if it hasn't been installed already. See if you are still getting a paywall.
2. Check if using Cookie Remover can bypass the paywall. If not, continue to the next step.
3. First search 'Issues' to see if the site has been requested already.
4. Visit an article on the site you want to bypass the paywall for and copy the article title.
5. Open up a new incognito window (Ctrl+Shift+N on Chrome) or Private window (Ctrl+Shift+P on Firefox), and paste the article title into Google.
6. Click on the same article from the Google search results page.
7. If it loads without a paywall replace this entire template text with the word "Confirmed" and submit the request. Otherwise please do not submit an issue as this extension cannot bypass it either.

In old versions Custom Sites for Firefox still exist - please add it again

**Comment by iamadamdev** [comment]
This would require adding the all_urls permission. Most FF users are very privacy conscious and do not want this. You can do this manually on your local build.

**Comment by filchef** [comment]
I am just regular user and I cant do this for my local build.
Can you publish two variants for firefox one with custom sites and all_urls permissions and one  without custom sites.
