### ISSUE TITLE
It's not working for Quartz

### ISSUE THREAD

**Issue by rajaschava** [iamadamdev/bypass-paywalls-chrome#1010]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

I am using the latest Firefox browser and this add on is upto date. But its not working for an article on quartz which has a domain qz.com

I have Ublock origin installed. I turned it off and tried but still no luck.

[https://qz.com/india/1931018/indians-benefitted-from-payment-wars-between-google-fb-walmart/?utm_source=YPL](url)

**Comment by iamadamdev** [comment]
What's the issue exactly?

![image](https://user-images.githubusercontent.com/36013816/98885984-ed73cf80-2447-11eb-8a75-c7bdde79c89b.png)

**Comment by rajaschava** [comment]
I only see the first paragraph of the article and then the page says login to read the full article.

Regards,
Raja Chava

**Comment by iamadamdev** [comment]
It only works for free articles on that site.
