### ISSUE TITLE
https://www.houstonchronicle.com/

### ISSUE THREAD

**Issue by cstsang** [iamadamdev/bypass-paywalls-chrome#1012]
confirmed

**Comment by iamadamdev** [comment]
Where are you seeing a paywall? I just opened 10+ articles w/o paywall.

**Comment by cstsang** [comment]
It limits you after a certain number of articles.  After the limit, I can still browse it with incognito, but clearing cookies don't help.

**Comment by cstsang** [comment]
Please close this request - for some reason, uBlock was off for the site.  It is now working.  thank you.
