### ISSUE TITLE
The New Yorker not working

### ISSUE THREAD

**Issue by eandywong** [iamadamdev/bypass-paywalls-chrome#1013]
It doesn't work for _The New Yorker_ at this moment, e.g. [The Seven Pillars of Biden’s Foreign Policy](https://www.newyorker.com/news/our-columnists/the-seven-pillars-of-bidens-foreign-policy). 

The article is at first fully loaded, but after a very short time only a small part remains, it says "You’ve read your last complimentary article this month. Subscribe Now. If you're already a subscriber sign in." 

bypass-paywalls-chrome: v1.7.7 
Chrome: 86.0.4240.198 Windows 64-bit 
uBlock Origin: v1.30.6

**Comment by lawrenceearl** [comment]
Works for me in Firefox. 82.0.3

**Comment by eandywong** [comment]
> Works for me in Firefox. 82.0.3

**Comment by eandywong** [comment]
> Works for me in Firefox. 82.0.3

There seem to be 3 free articles. 
If I disable uBlock Origin and manually clear storage and cookies, I am able to see the whole article.

**Comment by lawrenceearl** [comment]
I can read all articles with uBlock Origin disabled.

**Comment by iamadamdev** [comment]
Try latest master

**Comment by eandywong** [comment]
> Try latest master

It works well now. Thank you!
