### ISSUE TITLE
Not working on SeekingAlpha

### ISSUE THREAD

**Issue by ericwbzhang** [iamadamdev/bypass-paywalls-chrome#1016]
Bypass-paywall seems not working on seeking alpha.  https://seekingalpha.com/article/4380322-netflix-seeing-big-picture

It gets stuck with a "press and hold" bar. Both Chrome and Firefox have this issue. The uBlock Origin would block the bar.

**Comment by iamadamdev** [comment]
That article works for me after pressing and holding.

**Comment by johnh245** [comment]
I had the same problem (press and hold captcha keeps repeating  over and over). Was using Brave browser. Tried with Chrome, and it worked. Back to Brave - cleared all cookies, Local Storage, Session Storage, etc., and logged back in to SeekingAlpha - this extension works like a charm again. Hope this helps someone...

**Comment by ericwbzhang** [comment]
Thanks. Clearing cookies works.

**Comment by schiz0000** [comment]
I also started experiencing the same issue a couple of days ago after it had been working perfectly for weeks in firefox. Clearing seeking alpha cookies also worked for me. Thanks johnh245.
