### ISSUE TITLE
Not working for Haartez and TheMarker

### ISSUE THREAD

**Issue by dukase** [iamadamdev/bypass-paywalls-chrome#1017]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###
Not working for https://www.haaretz.co.il/magazine/.premium.HIGHLIGHT-MAGAZINE-1.9300580 both for Firefox and Chrome. 

Error displayed -

Error 403 Forbidden
Forbidden
Guru Mediation:
Details: cache-fra19176-FRA 1605371316 1519093027
Varnish cache server

**Comment by AlizeeFR** [comment]
I'm having the same issue. Not only the .co.il version but also the .com version. Was using Haaretz are details for a thesis paper so hopefully it will be fixed soon

https://www.haaretz.com/jewish/1929-hebron-massacre-begins-1.5427655

**Comment by iamadamdev** [comment]
Both those articles still work for me (latest master).
Maybe try clearing cookies and re-installing the extension?

**Comment by iamadamdev** [comment]
Try latest master

**Comment by AlonT6** [comment]
Hey @iamadamdev 
I saw that you changed the bot to be `bing` bot instead of `google` bot.
Any idea why this change is needed? 
It's because of changes on the sites themselves that caused this?

**Comment by iamadamdev** [comment]
Hareetz seems to allow the bing bot in.

**Comment by AlonT6** [comment]
For me it's working with latest.

Thanks!

**Comment by dukase** [comment]
The latest version works great for Chrome but not the FireFox version

**Comment by dukase** [comment]
1. The latest version working great for Chrome.
2. Firefox version (xpi file) does NOT work.
3. I build the extension manually, set Firefox to load unsigned extensions (using configuration manager) and load it manually. 

Now it is working for my Firefox.
