### ISSUE TITLE
New site request: [theweek.com]

### ISSUE THREAD

**Issue by rpodric** [iamadamdev/bypass-paywalls-chrome#1018]
Given the precedent of support for Slate.com last month with just its addition to these [three areas](https://github.com/iamadamdev/bypass-paywalls-chrome/pull/974/commits/cd0230d028665233a9dc00fefa05420a81681323):
-manifest-ff.json 
-src/js/sites.js
-README.md

I recommend that you do the same for Theweek.com. I've tested it on my end, and for whatever reason, just like with Slate.com, it prevents the paywall notice coming up after X articles.

The two sites behave the same way, so if Slate.com has support now, I suggest the same be done for Theweek.com

Tested with uBO and the latest bypass-paywalls-chrome with the above changes added for theweek.com.

**Comment by iamadamdev** [comment]
You can simply clear cookies to continue reading articles there.
https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce

**Comment by rpodric** [comment]
Yes, but you don't need to when it's added to the extension.

I know you've mentioned the cookie workaround before, but then I saw the addition a few weeks ago of Slate.com, which would also work if you simply clear cookies. Was its addition for anything else? I frequent both sites, and they appear to be in the same boat.

**Comment by iamadamdev** [comment]
Slate is a lot bigger site than theweek. I don't want to add every small site under the sun if they could just be bypassed by clearing cookies.

**Comment by CalvinWu4** [comment]
Do you think we could remedy putting sites into sections on the readme and extension options site checklist?

**Comment by rpodric** [comment]
Maybe, could you go into a little more detail?

While I'm not quite sure I understand you, I wonder if a sort of "user" file might be implemented. If, say, sites.json exists, it will be read for any additional sites that someone want to add, like the one above. Those sites would then be available in the extension's menu to enable. This would neatly sidestep the problem of a site not being popular enough to add for everyone, and importantly, the sites wouldn't be wiped out each time the extension is updated.

**Comment by CalvinWu4** [comment]
Well I'm assuming he doesn't want every small site added because the sites list would be too bloated to traverse through

**Comment by iamadamdev** [comment]
@rpodric You can already do that in the Chrome version, Custom Sites tab. Although usually smaller newspapers can be bypassed with a simple cookie clear, in which I linked to my other extension for that.

**Comment by rpodric** [comment]
Wow, I never saw that tab (blind spot on my part)! That's great.

**Comment by rpodric** [comment]
Alas, doing it that way causes the formatting on the site to break substantially. It's true that the dialog warns against that kind of possibility, but I mention this to point out that for whatever reason there isn't an equivalence necessarily between adding a site in the couple files mentioned above (i.e. how Slate was done) and adding it via the UI instead.
