### ISSUE TITLE
NYT no longer works

### ISSUE THREAD

**Issue by sokolq55** [iamadamdev/bypass-paywalls-chrome#102]
New York Times no longer works. Can still get through in incognito. Thanks.

**Comment by compuguy** [comment]
This may be related to #103

**Comment by iamadamdev** [comment]
Please upgrade to v1.4.0

**Comment by samirsss** [comment]
I'm on 1.4.3 and NYT doesnt seem to work

**Comment by sokolq55** [comment]
Updating to latest version did not help - NYT, WashPo not working
