### ISSUE TITLE
Pages not working

### ISSUE THREAD

**Issue by karlic** [iamadamdev/bypass-paywalls-chrome#1021]
###
1. Found a couple of issues that mentioned 403 Forbidden and tried changing UA to use bingbot, but that didn't help
2. uBlock Origin is installed.
3. Chrome version 86.0.4240.80 (Official Build) (x86_64) with bypass-paywalls-chrome version 1.7.7 (Also tried FF without success).
4. https://www.thetimes.co.uk/puzzleclub/crosswordclub/
https://www.thetimes.co.uk/puzzleclub/crosswordclub/puzzles-list
5. The above URLs return a 403 Forbidden. All other pages on the site appear to be working.
###

Thank you. :-)

**Comment by iamadamdev** [comment]
I would consider buying a subscription if you want to play their crosswords online :)

**Comment by karlic** [comment]
Oh, I thought Bypass Paywalls was a web browser extension to help bypass paywalls. My mistake, sorry. :-)
