### ISSUE TITLE
Barron’s is not working

### ISSUE THREAD

**Issue by MrB010** [iamadamdev/bypass-paywalls-chrome#1022]
Barrons.com is not working as of now

**Comment by iamadamdev** [comment]
Still works for me on Chrome

**Comment by MrB010** [comment]
> Still works for me on Chrome

I'm on Firefox . Just checked again still not working .

**Comment by iamadamdev** [comment]
Works for me on Firefox too.

**Comment by MrB010** [comment]
> Works for me on Firefox too.
> 
> 

Just checked. It's all fine now . It works. Idk what happened. Sorry bro.
