### ISSUE TITLE
The New Yorker

### ISSUE THREAD

**Issue by senormingus** [iamadamdev/bypass-paywalls-chrome#1025]
Firefox + UBlock installed.

The New Yorker no longer works. Screenshot attached.

Thanks.
![Screen Shot 2020-11-16 at 9 34 25 AM](https://user-images.githubusercontent.com/68487520/99302488-72cafb80-281d-11eb-8576-876b1810b47c.png)

**Comment by iamadamdev** [comment]
Duplicate issue: https://github.com/iamadamdev/bypass-paywalls-chrome/issues/1013
It was fixed in Chrome, you will need to wait for the next release for FF or build it yourself.
