### ISSUE TITLE
The Epochtimes

### ISSUE THREAD

**Issue by Redback813** [iamadamdev/bypass-paywalls-chrome#1026]
https://www.theepochtimes.com/australias-most-populous-state-passes-abortion-bill-after-failed-attempt-in-2017_3096922.html

![image](https://user-images.githubusercontent.com/54433630/99341668-707ca600-28de-11eb-93d3-459482a67fd4.png)

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
