### ISSUE TITLE
Not Working on First Things

### ISSUE THREAD

**Issue by arandorion** [iamadamdev/bypass-paywalls-chrome#1029]
Bypass Paywalls is enabled for the site FirstThings.com, but it does not appear to be working. Here is an article that is still being restricted.

https://www.firstthings.com/article/2020/12/the-fury-of-the-fatherless

Thanks

**Comment by iamadamdev** [comment]
That article works for me.

**Comment by arandorion** [comment]
It's still not working for me. I cleared my cache and cookies, but there was no change. As you can see in the attached screenshot, I get the first two paragraphs of the article and then nothing. It's just blank until it gets to the ads at the bottom.

Here's my setup:

Bypass Paywalls 1.7.7
Firefox 83.0
macOS 10.15.7

Thanks

<img width="1440" alt="screen-shot 2020-11-18 at 14 29 38" src="https://user-images.githubusercontent.com/14881146/99579181-d4b96b80-29ab-11eb-951e-b2ff88b8cb87.png">

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/99580223-12aa9580-2994-11eb-948a-ecc7a96963df.png)
Also on mac, works in Chrome and FF for me.

**Comment by arandorion** [comment]
Are you using the same setup as me?

Bypass Paywalls 1.7.7
Firefox 83.0
macOS 10.15.7

Thanks

**Comment by iamadamdev** [comment]
Yup, FF 83.0 (64-bit)
10.15.7,
also have uBlock Origin installed, but that shouldn't matter in this case.

**Comment by arandorion** [comment]
I tried it on a different machine running Firefox 81 and macOS 10.13.6 and it worked. I have no idea what is going on.

Thanks for looking into it.

**Comment by arandorion** [comment]
I just tried it with a clean install of Google Chrome. It did not work in Chrome either. I can't imagine why it would not work in a clean install of either Firefox or Chrome. If anyone has ideas, please let me know.

Thanks
