### ISSUE TITLE
Obsolete since Chrome 72

### ISSUE THREAD

**Issue by chew-z** [iamadamdev/bypass-paywalls-chrome#103]
Hi,

I would like to point some changes in the latest versions of Chrome.

1) Please [read here](https://developer.chrome.com/extensions/webRequest#life_cycle_footnote)

> Starting from Chrome 72, the following request headers are not provided and cannot be modified or removed without specifying 'extraHeaders' in opt_extraInfoSpec:
> 
> Accept-Language
> Accept-Encoding
> Referer
> Cookie
> Starting from Chrome 72, the Set-Cookie response header is not provided and cannot be modified or removed without specifying 'extraHeaders' in opt_extraInfoSpec.

2) The extension is failing when user sets option to disable 3rd party cookies in Chrome.

The side effect of disabling 3rd party cookies is that extensions cannot access localStorage for Window and because contentScript.js starts with 

`window.localStorage.clear();`

You can see that your extension throws error by opening developers console.

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at file:///home/chronos/u-1d712c7159f92af9fc9c901c40c190ad19b46214/Downloads/Chrome/bypass-paywalls/contentScript.js:1:8
```

**Comment by iamadamdev** [comment]
Thanks for bringing this up. Do you have any workarounds?

**Comment by vic958420** [comment]
Hi,

After updating to Chrome 72, the bypass paywalls extension does not work anymore.

**Comment by compuguy** [comment]
Any updates on this?

**Comment by iamadamdev** [comment]
#1 Extension is now fixed for Chrome 72. However WSJ is still broken, they changed their algo.

As for #2, 'Block third-party cookies' is off by default on Chrome I believe. If someone is going to manually install this extension, and they still have problems bypassing a paywall, they can turn off 'Block third-party cookies'.

**Comment by iamadamdev** [comment]
WSJ fixed!
