### ISSUE TITLE
New site request: www.VG.no & www.aftenbladet.no

### ISSUE THREAD

**Issue by kenty953** [iamadamdev/bypass-paywalls-chrome#1031]
VG - Verdensgang is Norway's biggest newspaper site. 
Aftenbladet.no is also a big news site that usually coves the stuff VG does not cover.

**Comment by iamadamdev** [comment]
Where are you seeing a paywall?

**Comment by kenty953** [comment]
Its like this:
https://gyazo.com/412537436239f55751497a661f09b60e

**Comment by iamadamdev** [comment]
URL to paywalled article?

**Comment by kenty953** [comment]
https://www.aftenbladet.no/lokalt/i/aPWJP5/denne-jaerstranda-faar-sitt-design-do-mot-vaer-og-vind

**Comment by kenty953** [comment]
Also this one didnt work.
https://www.dagsavisen.no/rogalandsavis/nyheter/bilkollektivet-utsatt-for-svindelforsok-1.1803258?paywall=true

**Comment by iamadamdev** [comment]
Looks like a hard paywall
