### ISSUE TITLE
The Seattle Times not loading properly

### ISSUE THREAD

**Issue by maxwellyli** [iamadamdev/bypass-paywalls-chrome#1036]
Bypass Paywalls does not seem to be working for Seattle Times articles on Firefox. The page initially loads momentarily, before what I'm assuming to be a pop up appears, blurring the entire page.

Example article: 
https://www.seattletimes.com/seattle-news/transportation/mayor-durkan-wants-to-repair-not-replace-the-cracked-west-seattle-bridge/

<img width="1411" alt="Screen Shot 2020-11-19 at 3 34 17 PM" src="https://user-images.githubusercontent.com/18153529/99737208-b0798f80-2a7c-11eb-9e18-dc8c85200b30.png">

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed? That article loads fine for me.

**Comment by maxwellyli** [comment]
Odd - it works fine now. I wonder if it was a one-time popup. I'll close the issue for now and reopen if I can better replicate the issue.

**Comment by maxwellyli** [comment]
Nevermind - I realized I had disabled Bypass Paywalls, which let the site load correctly. I just reinstalled both uBlock Origin and Bypass Paywalls on Firefox, and it still seems to be happening. 

Watching the Inspector, I noticed that this style that was being applied ~5 seconds after page load.
`<div id="container" class="site container" style="filter: blur(2px);">`

Under Sources, https://www.seattletimes.com/wp-content/plugins/st-user-messaging/dist/st-user-messaging-main-bundle.js?ver=1605736952 has this specific piece of code that I think might be causing this:

```        
        {
          key: 'displayModal',
          value: function () {
            var e = this;
            if (!SEATIMESCO.browser.layout.isMobile && !SEATIMESCO.browser.layout.isTablet) {
              this.setupSocialLogin(),
              this.previouslyFocusedElement = document.activeElement,
              events && events.trigger('initialModals:disable'),
              this.triggerInteractionEvent('displayed'),
              window.dataLayer.push({
                event: 'optimize:newsletterOverlayDisplay'
              }),
              this.overlay.classList.remove('hide'),
              window.setTimeout((function () {
                e.overlay.classList.add('is-active'),
                document.getElementById('container').style.filter = 'blur(2px)'
              }), 500),
              this.input.focus();
              var t = this.model.get('messageFrequency');
              helpers && t && helpers.writeCookie(l.u.newsletterSplash, !0, t, '/', 'seattletimes.com', 'None')
            }
          }
        },
```

It does explain the ~5 mississippis I was counting for the bluring to show up.

**Comment by iamadamdev** [comment]
I'm not able to repro your issue on FF or Chrome.

**Comment by avivmu** [comment]
On FF, I see this popup:
![image](https://user-images.githubusercontent.com/19804341/99886581-56c4c100-2c46-11eb-84b9-61a3e20ea8c1.png)
But I can close it and the article looks okay
On Chrome I don't see the popup but the blur comes for about 1 second and then goes off by itself
I would be happy to help if you need more details, just tell me what and how to retrieve them.

**Comment by iamadamdev** [comment]
Try latest master for Chrome. Just made an update.
