### ISSUE TITLE
Haaretz 403 Forbidden

### ISSUE THREAD

**Issue by bundleOfBundles** [iamadamdev/bypass-paywalls-chrome#1037]
https://www.haaretz.co.il and https://www.haaretz.com, as well as all articles within them, return 403 Forbidden while Add-on is enabled. They work correctly when it is not. 
![Capture](https://user-images.githubusercontent.com/4019286/99826927-ab424080-2b61-11eb-99a8-17768c2fdc69.PNG)
I'm using Firefox, uBlock Origin is enabled.
Tried changing DNS, didn't help.
Other supported sites, such as globes.co.il, work correctly with the add-on.

**Comment by iamadamdev** [comment]
It was fixed in latest master on Chrome. It should be fixed in the next release for FF.
