### ISSUE TITLE
Business Insider shows Join Prime pop up

### ISSUE THREAD

**Issue by pavankjadda** [iamadamdev/bypass-paywalls-chrome#104]
When I open an article on BusinessInsider.com I see **Join Prime** member popup as shown below  

<img width="1242" alt="screen shot 2019-01-27 at 10 11 06 pm" src="https://user-images.githubusercontent.com/17564080/51812751-ea165080-2280-11e9-9f82-c2ef015ac36e.png">

**Comment by compuguy** [comment]
This *could* be related to #103

**Comment by iamadamdev** [comment]
Premium articles cannot be bypassed by the google referral trick.
