### ISSUE TITLE
contentScript runs on every request

### ISSUE THREAD

**Issue by ctsstc** [iamadamdev/bypass-paywalls-chrome#1043]
## Issue

Should `contentScript` run on every request on a page? It seems horribly inefficient. 

For example loading: `https://www.nytimes.com/live/2020/12/01/world/covid-19-coronavirus?action=click&module=Top%20Stories&pgtype=Homepage` will load and run `contentScript` 40 times for the 1 page load; once for every request that comes through on the network. You can verify this by throwing a `console.log` into the top of `contentScript`.

## Expectation

`contentScript` should ideally only inject once on to a page.

## Possible Issues

It's possible that this current behavior is allowing the extension to function properly. For example a new request comes through with new content it will sanitise that new content ideally, or if there's a single page application these requests could be vital to its functioning.

## Possible Fixes

I would need to dissect the code more to better understand if `contentScript` should be running on every request, and whether or not that's even the correct even to bind to.

A stop-bleed could be to debounce the injection so that it cannot be called so frequently.

Maybe there could be a mutator event watcher? This may be more applicable to actual change on the page, but it's likely it would be way noisier than the current implementation, without any proper filtering.

## Notes

- This is on Chrome. Not sure if FF functions differently, or how exactly it fits into this extension as a whole.

**Comment by iamadamdev** [comment]
There are some optimizations we can make but I don't think the end user will see any noticeable performance improvements.
