### ISSUE TITLE
humo.be not working in Firefox, fine in Chrome

### ISSUE THREAD

**Issue by sam288** [iamadamdev/bypass-paywalls-chrome#1045]
https://www.humo.be/nieuws/de-sportredactie-van-de-vrt-was-de-beste-van-west-europa-en-ver-daarbuiten~b5b20b29/

Paywall is blocked fine on Chrome but not firefox

**Comment by iamadamdev** [comment]
Will re-open next year.

**Comment by sam288** [comment]
> 
> 
> Will re-open next year.

can this be re-opened please?

**Comment by iamadamdev** [comment]
Fixed in latest master. You will need to wait until the next release, build it yourself, or use this version here I just built.

[bypass-paywalls.zip](https://github.com/iamadamdev/bypass-paywalls-chrome/files/5900458/bypass-paywalls.zip)
