### ISSUE TITLE
New site request: Newsquest sites

### ISSUE THREAD

**Issue by 5p0ng3b0b** [iamadamdev/bypass-paywalls-chrome#1046]
Confirmed

This is for multiple UK local and national publications owned by Newsquest.
Whilst each site individually would not qualify due to size, the combined usage (according to newquest) is 34m digital users per month. This would seem to meet the requirements.
All the sites seemingly use an identicle template and resolve to the same ip address of 93.174.10.103.

https://www.alloaadvertiser.com
https://www.andoveradvertiser.co.uk
https://www.ardrossanherald.com
https://www.asianimage.co.uk
https://www.ayradvertiser.com
https://www.theargus.co.uk
https://www.banburycake.co.uk
https://www.barrheadnews.com
https://www.barryanddistrictnews.co.uk
https://www.basildonstandard.co.uk
https://www.basingstokegazette.co.uk
https://www.bicesteradvertiser.net
https://www.bordercountiesadvertizer.co.uk
https://www.bordertelegraph.com
https://www.borehamwoodtimes.co.uk
https://www.bournemouthecho.co.uk
https://www.bracknellnews.co.uk
https://www.thetelegraphandargus.co.uk
https://www.braintreeandwithamtimes.co.uk
https://www.brentwoodlive.co.uk
https://www.bridgwatermercury.co.uk
https://www.bridportnews.co.uk
https://www.bromsgroveadvertiser.co.uk
https://www.bucksfreepress.co.uk
https://www.burnhamandhighbridgeweeklynews.co.uk
https://www.burytimes.co.uk
https://www.businessiqnortheast.co.uk
https://www.theboltonnews.co.uk
https://www.campaignseries.co.uk
https://www.carrickherald.com
https://www.centralfifetimes.com
https://www.chardandilminsternews.co.uk
https://www.chelmsfordweeklynews.co.uk
https://www.chesterstandard.co.uk
https://www.chorleycitizen.co.uk
https://www.clactonandfrintongazette.co.uk
https://www.clydebankpost.co.uk
https://www.cotswoldjournal.co.uk
https://www.cravenherald.co.uk
https://www.cumnockchronicle.com
https://www.dailyecho.co.uk
https://www.darlingtonandstocktontimes.co.uk
https://www.denbighshirefreepress.co.uk
https://www.dorsetbeaches.co.uk
https://www.dorsetecho.co.uk
https://www.droitwichadvertiser.co.uk
https://www.dudleynews.co.uk
https://www.dumbartonreporter.co.uk
https://www.dunfermlinepress.com
https://www.eastkilbrideconnect.co.uk
https://www.eastlothiancourier.com
https://www.echo-news.co.uk
https://www.enfieldindependent.co.uk
https://www.eppingforestguardian.co.uk
https://www.essex-media.co.uk
https://www.glasgowtimes.co.uk
https://www.eveshamjournal.co.uk
https://www.falmouthpacket.co.uk
https://www.forestryjournal.co.uk
https://www.freepressseries.co.uk
https://www.guardian-series.co.uk
https://www.gazetteandherald.co.uk
https://www.gazetteseries.co.uk
https://www.greenocktelegraph.co.uk
https://www.gazette-news.co.uk
https://www.halesowennews.co.uk
https://www.halsteadgazette.co.uk
https://www.hampshirechronicle.co.uk
https://www.harrowtimes.co.uk
https://www.helensburghadvertiser.co.uk
https://www.heraldseries.co.uk
https://www.heraldscotland.com
https://www.herefordtimes.com
https://www.hexham-courant.co.uk
https://www.hillingdontimes.co.uk
https://www.ilkleygazette.co.uk
https://www.impartialreporter.com
https://www.in-cumbria.com
https://www.countypress.co.uk
https://www.keighleynews.co.uk
https://www.kidderminstershuttle.co.uk
https://www.knutsfordguardian.co.uk
https://www.lancashiretelegraph.co.uk
https://www.thelancasterandmorecambecitizen.co.uk
https://www.largsandmillportnews.com
https://www.ledburyreporter.co.uk
https://www.leighjournal.co.uk
https://www.localberkshire.co.uk
https://www.ludlowadvertiser.co.uk
https://www.leaderlive.co.uk
https://www.maldonandburnhamstandard.co.uk
https://www.malverngazette.co.uk
https://www.messengernewspapers.co.uk
https://www.milfordmercury.co.uk
https://www.nwemail.co.uk
https://www.newforestpost.co.uk
https://www.newsandstar.co.uk
https://www.newsshopper.co.uk
https://www.northwaleschronicle.co.uk
https://www.northwalespioneer.co.uk
https://www.northwichguardian.co.uk
https://www.thenational.scot
https://www.thenorthernecho.co.uk
https://www.northernfarmer.co.uk
https://www.oxfordmail.co.uk
https://www.theoldhamtimes.co.uk
https://www.countytimes.co.uk
https://www.peeblesshirenews.com
https://www.penarthtimes.co.uk
https://www.prestwichandwhitefieldguide.co.uk
https://www.readingchronicle.co.uk
https://www.redditchadvertiser.co.uk
https://www.redhillandreigatelife.co.uk
https://www.rhyljournal.co.uk
https://www.richmondandtwickenhamtimes.co.uk
https://www.romseyadvertiser.co.uk
https://www.windsorobserver.co.uk
https://www.runcornandwidnesworld.co.uk
https://www.salisburyjournal.co.uk
https://www.sloughobserver.co.uk
https://www.somersetcountygazette.co.uk
https://www.southwalesargus.co.uk
https://www.southwalesguardian.co.uk
https://www.southwestfarmer.co.uk
https://www.southendstandard.co.uk
https://www.stalbansreview.co.uk
https://www.sthelensstar.co.uk
https://www.stirlingnews.co.uk
https://www.stourbridgenews.co.uk
https://www.strathallantimes.co.uk
https://www.stroudnewsandjournal.co.uk
https://www.surreycomet.co.uk
https://www.swanageandwarehamvoice.co.uk
https://www.swindonadvertiser.co.uk
https://www.thescottishfarmer.co.uk
https://www.tewkesburyadmag.co.uk
https://www.thisislancashire.co.uk
https://www.thisislocallondon.co.uk
https://www.thisisthewestcountry.co.uk
https://www.thisiswiltshire.co.uk
https://www.thisisoxfordshire.co.uk
https://www.thurrockgazette.co.uk
https://www.timesandstar.co.uk
https://www.times-series.co.uk
https://www.tivysideadvertiser.co.uk
https://www.thetottenhamindependent.co.uk
https://www.troontimes.com
https://www.wearevoice.co.uk
https://www.thewestmorlandgazette.co.uk
https://www.walesfarmer.co.uk
https://www.wandsworthguardian.co.uk
https://www.warringtonguardian.co.uk
https://www.watfordobserver.co.uk
https://www.westerntelegraph.co.uk
https://www.wharfedaleobserver.co.uk
https://www.whitchurchherald.co.uk
https://www.whitehavennews.co.uk
https://www.wiltsglosstandard.co.uk
https://www.wiltshirebusinessonline.co.uk
https://www.wiltshiretimes.co.uk
https://www.wimbledonguardian.co.uk
https://www.winsfordguardian.co.uk
https://www.wirralglobe.co.uk
https://www.witneygazette.co.uk
https://www.worcesternews.co.uk
https://www.yeovilexpress.co.uk
https://www.yorkpress.co.uk
https://www.yourlocalguardian.co.uk

**Comment by iamadamdev** [comment]
Randomly chose a site: forestryjournal.co.uk, opened 10+ articles, didn't see a paywall
