### ISSUE TITLE
Article Images Don't Load

### ISSUE THREAD

**Issue by gg-astoria** [iamadamdev/bypass-paywalls-chrome#1049]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

1. Not present in these issues
2. Yes, installed!
3. Chrome
4. https://www.newyorker.com/humor/daily-shouts/crimes-i-committed-with-my-boyfriend-vs-with-my-actual-partner-in-crime
5. I've noticed that when I'm reading articles (from sites the paywall supports) the article images don't load. I've uninstalled and reinstalled every extension I've got (UBlock Origin, Decentraleyes and HTTPS Everywhere, mainly) and it works then. When I uninstalled this the images start showing again. Please help!
P.S: I'm sorry if you've solved this issue before - I'm sorta new to this.

Thanks in advance, you're a godsend
A

**Comment by CalvinWu4** [comment]
Fixed in this [PR](https://github.com/iamadamdev/bypass-paywalls-chrome/pull/1053)
