### ISSUE TITLE
WSJ no longer works

### ISSUE THREAD

**Issue by jaywsjuser** [iamadamdev/bypass-paywalls-chrome#105]
as of 1/28/19, WSJ no longer works.   I was using the .3 edition of your addon and also upgraded to .4, but still am not allowed access to wsj.  The bypass addon is on firefox.  I've also tried unchecking and checking the sub boxes, restarting comp, and I use private firefox browser.  Still blocked!

**Comment by compuguy** [comment]
Not sure if its related to #103. It could be a combination of changes WSJ did and the recent Chrome 72 release.

**Comment by jaywsjuser** [comment]
I was using this addon on Firefox, not Chrome (because it hasn't worked on Chrome for over a year).  That leads me to think I'm blocked because of changes WSJ made sometime around 1-25-19.

**Comment by iamadamdev** [comment]
WSJ not working is a known issue. WSJ has changed their algorithm recently.

**Comment by jaywsjuser** [comment]
Thanks for the update.  I'm grateful to you for my years of use of this addon. I'm hoping you can fix it as you've done in the past.If possible, please let me know if and when that happens. 

    On Saturday, February 2, 2019 3:38 PM, Adam <notifications@github.com> wrote:
 

 WSJ not working is a known issue. WSJ has changed their algorithm recently.—

**Comment by 420pitts** [comment]
It's possible that it's just a temporary test to see if their traffic drops if they get rid of the referrals from Google/Facebook. They might re-enable it. Was the addon using Facebook to do referrals? Cause I'm pretty sure that worked for a while.

**Comment by pjpreilly** [comment]
1.4.0 looks like it's working for me on cloudready on 72.3.32. Thx for the fast action!

**Comment by matiarj** [comment]
yeah WSJ still not working on mac os w/ chrome

**Comment by pjpreilly** [comment]
NYT not working either.

**Comment by iamadamdev** [comment]
WSJ bypass fixed! Grab latest master.

**Comment by jaywsjuser** [comment]
With new master WSJ worked briefly, then stopped working despite recommended troubleshooting.

**Comment by 420pitts** [comment]
I'm sure the WSJ's developers are watching this project to counter any changes that are made.

**Comment by iamadamdev** [comment]
Still have some bugs to fix.

**Comment by iamadamdev** [comment]
Try v1.4.2, bugs should be squashed.

**Comment by pjpreilly** [comment]
not good still!

**Comment by mikado-cat** [comment]
Works.

**Comment by iamadamdev** [comment]
Should work fine now.

**Comment by pjpreilly** [comment]
Not working on cloudready.

**Comment by iamadamdev** [comment]
Try it on Chrome on Windows, macOS or Android.

**Comment by pjpreilly** [comment]
Failed on Google Chrome on Manjaro Linux......

**Comment by pjpreilly** [comment]
...& failing on Google Chrome on mac os x Mojave 10.14.3

**Comment by jaywsjuser** [comment]
Sort of works.  I can access wsj on chrome and can read full articles, but when trying to log in to wsj get white page and error message "The requested URL /auth/sso/login was not found on this server."  Tried to work around this by going chrome incognito (which worked fine when i used to use addon on firefox), but it now results in addon not working at all.

**Comment by sdfww** [comment]
Not working on Windows 8.1
