### ISSUE TITLE
Chrome https://www.ft.com/ articles cannot be opened any more. Please fix it and thanks very much!

### ISSUE THREAD

**Issue by vforvickyxia** [iamadamdev/bypass-paywalls-chrome#1051]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
Still works for me.
