### ISSUE TITLE
Haaretz and theMarker now block use of Bypass paywalls

### ISSUE THREAD

**Issue by saienglert** [iamadamdev/bypass-paywalls-chrome#1052]
###
1. Did not help
2. Yes
3. Chrome 
4. https://www.haaretz.com/israel-news/.premium.HIGHLIGHT-netanyahu-lost-the-vote-to-end-his-government-but-scored-a-major-victory-1.9344383 
5. On both Haaretz and theMarker - in Hebrew as well as English - Bypass Paywalls stopped working. I know get a 403 Forbidden message until I disable the extension (see example point 4).
###

**Comment by iamadamdev** [comment]
That article loaded fine for me.
