### ISSUE TITLE
Bloomberg scroll disabled

### ISSUE THREAD

**Issue by trimbe** [iamadamdev/bypass-paywalls-chrome#1055]
On Chrome - https://www.bloomberg.com/news/articles/2020-12-04/biden-clinches-electoral-college-win-as-california-certifies

A `noScroll` class is applied to body a few seconds after the page loads.

**Comment by CalvinWu4** [comment]
Fixed in PR(https://github.com/iamadamdev/bypass-paywalls-chrome/pull/1059)

**Comment by CalvinWu4** [comment]
Fixed in this PR(https://github.com/iamadamdev/bypass-paywalls-chrome/pull/1060)
