### ISSUE TITLE
NZ Herald - Not Working

### ISSUE THREAD

**Issue by NPCtom** [iamadamdev/bypass-paywalls-chrome#1056]
https://www.nzherald.co.nz/nz/gangland-book-extract-how-head-hunter-brownie-harding-ruled-northland-meth-lab/QLI2PJADUBSH2YP47TGZFQDLNE/

NZ Herald not working.

**Comment by iamadamdev** [comment]
Works for me.

**Comment by NPCtom** [comment]
Hm that's odd it isn't working for me. Any configuration profiles I need to modify?

**Comment by NPCtom** [comment]
I was using an outdated version.
