### ISSUE TITLE
Honolulu Star Advertiser  https://www.staradvertiser.com/

### ISSUE THREAD

**Issue by sandyjon** [iamadamdev/bypass-paywalls-chrome#1057]
### New site requests - Before submitting an issue please read the following:

Only large or major sites will be considered. Usually premium articles cannot be bypassed as they are behind a hard paywall.

1. Install the uBlock Origin extension if it hasn't been installed already. See if you are still getting a paywall.
2. Check if using Cookie Remover can bypass the paywall. If not, continue to the next step.
3. First search 'Issues' to see if the site has been requested already.
4. Visit an article on the site you want to bypass the paywall for and copy the article title.
5. Open up a new incognito window (Ctrl+Shift+N on Chrome) or Private window (Ctrl+Shift+P on Firefox), and paste the article title into Google.
6. Click on the same article from the Google search results page.
7. If it loads without a paywall replace this entire template text with the word "Confirmed" and submit the request. Otherwise please do not submit an issue as this extension cannot bypass it either.

**Comment by iamadamdev** [comment]
Failed to follow instructions. Also just opened 10+ articles w/o seeing a paywall.

**Comment by sandyjon** [comment]
Some of the articles from the Honolulu Star Advertiser are premium and do have a paywall.  Here is an example   Biki bikes costing Honolulu an estimated $460,728 in lost revenue, audit finds


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Biki bikes costing Honolulu an estimated $460,728 in lost revenue, audit...

Honolulu’s 3-1/2-year-old bikeshare program known as Biki has not benefited the city and lacks accountability an...
 |

 |

 |



    On Saturday, December 5, 2020, 04:12:29 PM PST, Adam <notifications@github.com> wrote:  
 
 


Failed to follow instructions. Also just opened 10+ articles w/o seeing a paywall.

**Comment by iamadamdev** [comment]
Looks like that article is behind a hard paywall.

**Comment by sandyjon** [comment]
Here is another article.  In looking at the web page the articles behind the paywall have a star.  It is probably less than 20 percent but some articles like this one are worth reading.   Court hears claims in lawsuit over church use of Hawaii school facilities


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Court hears claims in lawsuit over church use of Hawaii school facilities

A 7-year-old lawsuit alleging that two Hawaii churches defrauded the government by using public school faciliti...
 |

 |

 |



    On Saturday, December 5, 2020, 05:49:06 PM PST, Adam <notifications@github.com> wrote:  
 
 


Looks like that article is behind a hard paywall.
