### ISSUE TITLE
Medscape - Not working

### ISSUE THREAD

**Issue by Mayzie** [iamadamdev/bypass-paywalls-chrome#1058]
Using either Firefox, or Chrome, Medscape articles are now no longer bypassed. All articles on Medscape are affected (e.g. https://www.medscape.com/viewarticle/942041). Article content still briefly flashes in its entirety, before being hidden behind a wall.

**Comment by iamadamdev** [comment]
Still works for me.

**Comment by Mayzie** [comment]
Really? That is so odd. After a bit of investigation, it appears that the German language version is unaffected, whereas all other languages (English, French, Spanish, and Portuguese) are. You wouldn't happen to be browsing that edition, would you?

I have disabled all of my extensions, except your Bypass Paywalls extension, and it still doesn't work. So there's no conflict with another extension. Same in Chrome too, so no conflict with the browser, either.

**Comment by Mayzie** [comment]
For what it's worth, here is the page I am seeing: [screenshot](https://i.imgur.com/1H9KGus.png).

And here is the source code to that page: https://gist.github.com/Mayzie/6d83cf719820b9ac2bf047eefdf96dca .

Is there some obvious difference between yours and mine?

**Comment by MoonshineIndustries** [comment]
Works for me too. I have uMatrix and I use Brave browser if that makes any difference. Probably it's uMatrix tho, as it blocks 3rd party domains unless you whitelist them site-wide or browser-wide.

**Comment by Mayzie** [comment]
> Works for me too. I have uMatrix ... Probably it's uMatrix

Confirmed! I installed the uMatrix add-on to Firefox, and Medscape articles now appear in their entirety.

**Comment by Mayzie** [comment]
> Edit: I tried disabling uMatrix and Brave track/ad shields, it still works without them.

Do you have JavaScript disabled? With JS enabled, the article is present for a split second, before it is overridden by a wall as per my screenshot above. Without JS, the article remains visible.

**Comment by MoonshineIndustries** [comment]
Nope, all first-party cookies and scripts are enabled. But even when I disable uMatrix (and allow 3rd party scripts) it still continues to work. It's a weird issue for certain...

**Comment by Mayzie** [comment]
Narrowed it down. Possibly something in [this script](https://img.medscapestatic.com/medscape-core/www/js/article/news-article.js?v=20201022) is what is hiding the article. Preventing this script from loading does not hide the article behind a wall. Without it, I am getting a tonne of `Uncaught ReferenceError: webmd is not defined` errors on that pages' debug log (so the actual code that's doing the hiding could be elsewhere and only depends on this script), but it has not impacted my reading experience as far as I can tell 🙂
