### ISSUE TITLE
FT not working

### ISSUE THREAD

**Issue by Dr-Kristau** [iamadamdev/bypass-paywalls-chrome#1061]
Firefox, uBlock Origin installed, example article [here](https://www.ft.com/content/5bd5ec70-d36a-4838-a6aa-d2f0855649a8). I've been using your marvelous add-on for months (thank you!), but recently (a week or less) the FT has stopped working for me, in that I get a 'Become an FT subscriber to read' instead of the usual article. I've read a number of other issues involve websites which have stopped working recently, few of which you have been able to reproduce. Any ideas what might have changed and what I can do to change it back?

**Comment by MoonshineIndustries** [comment]
Works for me, my friend. Maybe it's because I have uMatrix? It only allows domains that you have whitelisted on websites, you can block cookies, scripts or just general ad-tracking BS...

**Comment by Dr-Kristau** [comment]
I'm not surprised it works for someone, thank you for letting me know.

What is surprising is that - without having made any changes I can remember - it stopped working for me. Oh well.

My cookies are cleared every time I close my browser, which happens at least once a day.

**Comment by MoonshineIndustries** [comment]
Very weird. Hopefully, the dev can find what's causing issues because, as you said, some other users are also having issues on certain websites, which work on my end, and I just installed the extension.

**Comment by iamadamdev** [comment]
That article works for me. Might be something on your end.

**Comment by vforvickyxia** [comment]
Same problem as Dr-Kristau. Please comment again if you find the way out. Thanks

**Comment by Dr-Kristau** [comment]
Did a fresh install of Windows 10 on a machine with a different IP (and ISP) to mine - new install of Firefox and the latest version of this bypass add-on. The FT still didn't work. So if it's not Windows, it's not the IP, and it's not Firefox, I'm left wondering what else there is at my end that could be going wrong.

**Comment by iamadamdev** [comment]
Sites are very finicky. Sometimes they work on some people's devices sometimes they don't and sometimes it might work a few days later.
(different IP and ISP might not be enough, maybe try a different country a la proxy/VPN)

**Comment by Dr-Kristau** [comment]
Yes, I am a paid subscriber to AirVPN - I've tried several of their servers without luck. I've even used [algo](https://github.com/trailofbits/algo) to create VPNs on DigitalOcean and Azure, without luck. Oh well, will have to wait for the pixie dust to float my way again I suppose.

**Comment by iamadamdev** [comment]
Try clearing data and cache in FF? Try Chrome?

**Comment by Dr-Kristau** [comment]
Got it! Don't know why I didn't think of it before - all now working with Tor Browser. Thanks again.

**Comment by Dr-Kristau** [comment]
N.B. screenshots of FF and Tor - as you can see, in FF the 'ON' label fails to appear, whereas it does in Tor. Not sure what's going on there.
![screen-2020-12-07-21-30-20](https://user-images.githubusercontent.com/32355001/101402184-b6240180-38d3-11eb-91e7-37ca8ebd70c1.jpg)
![screen-2020-12-07-21-30-45](https://user-images.githubusercontent.com/32355001/101402215-c20fc380-38d3-11eb-91a0-a73733fc9d47.jpg)

**Comment by iamadamdev** [comment]
That seems to indicate it wasn't even trying to enable itself for the domain you were on for some reason. Anyway, glad it's working for you now.
