### ISSUE TITLE
WaPo - Not working

### ISSUE THREAD

**Issue by Siress** [iamadamdev/bypass-paywalls-chrome#1062]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
Not found.
2. Make sure uBlock Origin is installed.
Affirmative.
3. Chrome or Firefox?
Firefox.
4. Paste the article URL for the site you are having issues with.
https://www.washingtonpost.com/opinions/2020/12/06/miserable-end-miserable-presidency/
5. Describe the issue.
Paywall, front and center overlay with greyed out, static background of the article.
###

**Comment by iamadamdev** [comment]
Still working for me in Chrome.
