### ISSUE TITLE
WSJ

### ISSUE THREAD

**Issue by scarylarry72** [iamadamdev/bypass-paywalls-chrome#1064]
was working well for the past week, it seems to be redirecting to google amp url and now won't load

https://www.wsj.com/amp/articles/overvalued-startups-could-be-shorted-by-new-firm-11607337001?mod=hp_lista_pos3

![wsj_issue](https://user-images.githubusercontent.com/75636348/101388949-db862080-387d-11eb-9239-75f830f337da.png)

**Comment by iamadamdev** [comment]
After redirecting it still loads for me.
