### ISSUE TITLE
sfchronicle.com is not working.

### ISSUE THREAD

**Issue by hbradlow** [iamadamdev/bypass-paywalls-chrome#1065]
The paywall still appears with this plugin activated.

https://www.sfchronicle.com/bayarea/article/Restrictive-zoning-keeps-Marin-the-most-15782840.php

**Comment by iamadamdev** [comment]
url?

**Comment by hbradlow** [comment]
Added URL.

**Comment by iamadamdev** [comment]
Still works for me. Maybe try clearing cookies & cache?

**Comment by hbradlow** [comment]
Hmm I cleared cookies and cache, but I am still being hit by the paywall. Are there any logs or anything that might be helpful here?

**Comment by llacb47** [comment]
Add this to ublock origin: `https://github.com/llacb47/miscfilters/blob/master/antipaywall.txt`

or add these filters:

```
||hearstnp.com^$third-party
@@||treg.hearstnp.com/treg.js$script
```
