### ISSUE TITLE
The New Yorker issues

### ISSUE THREAD

**Issue by snowbound** [iamadamdev/bypass-paywalls-chrome#1067]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###
Brave Version 1.17.75 Chromium: 87.0.4280.88 (Official Build) (64-bit) & Chrome Version 87.0.4280.88 (Official Build) (64-bit)
Ublock Origin installed and active on both
When going to this URL https://www.newyorker.com/news/news-desk/dianne-feinsteins-missteps-raise-a-painful-age-question-among-senate-democrats I am presented with an abbreviated article saying that I read my last article and a footer telling me that if using a adblocker I need to login.

**Comment by CalvinWu4** [comment]
This should be fixed on dev

**Comment by iamadamdev** [comment]
Works fine for me on latest master.
