### ISSUE TITLE
Site list not loading.

### ISSUE THREAD

**Issue by gbslr** [iamadamdev/bypass-paywalls-chrome#1069]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

![image](https://user-images.githubusercontent.com/69027452/101855519-24adcd00-3b29-11eb-8892-77fe685eb247.png)

Browser: Brave (also tested on Chrome)
Version: 1.7.7/8

Sites list not loading, cause uncertain. See error message above.

Replication:

1.) Install the extension from zip file on releases page.
2.) Default sites list does not load.

Note: 
Custom sites still function as intended.

**Comment by iamadamdev** [comment]
Try using latest master
