### ISSUE TITLE
The Times not working on Firefox 83.0 Mac

### ISSUE THREAD

**Issue by maykef** [iamadamdev/bypass-paywalls-chrome#1073]
Hi The UK newspaper The Times is not working anymore.

**Comment by iamadamdev** [comment]
url?

**Comment by maykef** [comment]
https://thetimes.co.uk

**Comment by iamadamdev** [comment]
Works fine for me after accepting the cookie dialogue, FF 83.0 (64-bit), macOS.

**Comment by maykef** [comment]
<img width="1057" alt="Screenshot 2020-12-11 at 21 19 45" src="https://user-images.githubusercontent.com/19354019/101955976-af103280-3bf6-11eb-947a-4cb963cb9e83.png">

**Comment by iamadamdev** [comment]
Try private mode with just uBlock Origin and my extension?
![image](https://user-images.githubusercontent.com/36013816/101956148-f5906d80-3bb3-11eb-87bf-bbc98ea285ab.png)

**Comment by maykef** [comment]
Will test and report back. 
Thanks.

**Comment by defrilitus** [comment]
This happens to me on Waterfox G3.01 (based on Firefox 78.5) on Mac every couple of weeks or so. But if I try again after five or ten minutes everything's fine. Not sure why that is, but it's not a great problem.
