### ISSUE TITLE
WSJ (again)

### ISSUE THREAD

**Issue by hhwong** [iamadamdev/bypass-paywalls-chrome#1074]
WSJ having issues on this particular article in Firefox.

https://www.wsj.com/amp/articles/company-trading-under-ticker-ai-rides-tech-friendly-stock-market-in-ipo-11607564188

![Screen Shot 2020-12-11 at 9 00 08 AM](https://user-images.githubusercontent.com/1095813/101932220-548fbb80-3b8f-11eb-9e2b-680288398af0.png)

**Comment by iamadamdev** [comment]
Works in Chrome. FF is the same code so not sure why it's not working there for that article.

**Comment by hhwong** [comment]
Yes, it works on Chrome for me too. Strange that the same code gets tripped up on Firefox (v.83)
