### ISSUE TITLE
New Functionality Request: please, add stop-reload

### ISSUE THREAD

**Issue by Montchenot** [iamadamdev/bypass-paywalls-chrome#1076]
Please, add a stop-refreshing functionality.

It might not have been the original purpose of this add-on but I think it would be a suitable addition. 

It would help in the readability of news items and, especially, in the ability to watch videos that are embedded in news but are shorter than the timer in those pages' reload script. This is very annoying and is dependent on the code of each particular website - this is why I would think of your add-on instead of a second one minding those same news websites.

I currently use some bookmarklets like:
javascript:window.clearTimeout(window.timeout); refresh=null; void(0);
and:
javascript:clearInterval(timer);void(autoRefresh=null);
but since you're already catching up to those websites' code updates, I thought of asking you for this extra effort.

Thanks for your already helpful add-on!

Regards,
C.

**Comment by iamadamdev** [comment]
Feel free to submit a PR and I can review it.
