### ISSUE TITLE
Hi everyone - looks like barron's is blocked on firefox but works on chrome. 

### ISSUE THREAD

**Issue by briguy89** [iamadamdev/bypass-paywalls-chrome#1077]
###
Hi Everyone - looks like Barron's is blocked on firefox but works on Chrome.. Followed all standard protocol i.e. uBlock Origin is installed etc. 

https://www.barrons.com/amp/articles/nio-xpeng-and-li-auto-are-not-the-next-tesla-why-its-time-to-unplug-from-chinese-ev-stocks-51607733438?mod=hp_LEAD_1

Thanks!
###

**Comment by briguy89** [comment]
https://www.barrons.com/amp/articles/nio-xpeng-and-li-auto-are-not-the-next-tesla-why-its-time-to-unplug-from-chinese-ev-stocks-51607733438?mod=hp_LEAD_1

**Comment by iamadamdev** [comment]
Will re-open next year.
