### ISSUE TITLE
no longer support bypassing bloomberg? 

### ISSUE THREAD

**Issue by lweo** [iamadamdev/bypass-paywalls-chrome#108]
v1.4.0
I have installed u-block origin, but it still pops up the subscribe prompt.
I found if I press ESC immediately after the webpage is loaded, then I could read the article through, otherwises it will load the subscribing component.

**Comment by iamadamdev** [comment]
Are you in the U.S. or EU?
Works fine for me still, the counter resets to 9 articles after each page load.

**Comment by lweo** [comment]
@iamadamdev I'm in China. But I access the site via proxy tool. Is that a thing?

**Comment by mikadocat** [comment]
Can confirm in EU counter resets to 9.
