### ISSUE TITLE
updates.xml + updates.json Grayed Out

### ISSUE THREAD

**Issue by sapote2241** [iamadamdev/bypass-paywalls-chrome#1081]
I notice that when I'm about to sideload your extension, SRC + Legacy + Build are in black.  But updates.xml and updates.json are grayed out. I don't want to pester you with newbie questions, so I won't follow-up with any reply or additional questions.  But if you could give me a yes or no as to whether that is how it is supposed to be, it'll help me to figure out a solution to this issue I'm having with the disappearance of your extension from my list of extensions a short time after loading it. Steve

**Comment by iamadamdev** [comment]
If you are following the instructions for Chrome be sure to click the thumbtack icon to pin it:
![image](https://user-images.githubusercontent.com/36013816/102045836-dbf74d80-3d8e-11eb-87a5-da78d2466908.png)
