### ISSUE TITLE
Slate isn't working anymore

### ISSUE THREAD

**Issue by lots0logs** [iamadamdev/bypass-paywalls-chrome#1083]
1. N/A
2. :heavy_check_mark: 
3. Chrome
4. https://slate.com/human-interest/2021/01/do-not-enjoy-sex-partner-wants-advice.html
5. I'm getting the paywall after reading the allowed amount of free articles. It was working previously.

**Comment by luciochagas** [comment]
Just checked. It still seems to be working on my side. Verify if you did not update Chrome and your extension was not forcefully reset or removed.

**Comment by iamadamdev** [comment]
Works for me too.

**Comment by lots0logs** [comment]
Did you try viewing several other articles? The messages says a limit has been reached. So you won't be able to reproduce it if the article I linked is the first one you've read on the site. To answer your questions, I'm sure the extension is enabled, updated to latest version, and it says its "ON" when I try to view the article.

**Comment by iamadamdev** [comment]
Try clearing cookies https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce
