### ISSUE TITLE
wsj.com part doesn't work again

### ISSUE THREAD

**Issue by yxwp9900** [iamadamdev/bypass-paywalls-chrome#1084]
code 500, ops

**Comment by xKHUNx** [comment]
> code 500, ops

I'm encountering the same problem as OP.

**Comment by iamadamdev** [comment]
Still works for me.
URL?

**Comment by xKHUNx** [comment]
> Still works for me.
> URL?

https://www.wsj.com/articles/china-president-xi-jinping-halted-jack-ma-ant-ipo-11605203556

**Comment by iamadamdev** [comment]
That article loads w/o issue for me.

**Comment by luciochagas** [comment]
> > Still works for me.
> > URL?
> 
> https://www.wsj.com/articles/china-president-xi-jinping-halted-jack-ma-ant-ipo-11605203556

Loads fine on my side, too. Did you double-check your extension?

**Comment by yxwp9900** [comment]
https://www.wsj.com/articles/how-to-care-for-aging-parents-when-you-cant-be-there-11610200808
When I close the extension and open this url, that site's response is normal (and the paywall is there, too).
And open the extension, that site's response become 500-code.   - .-

**Comment by akasaka99** [comment]
Does not work either: Error "Oops 500" (w/ ublock, cookie remover,...)

**Comment by yxwp9900** [comment]
> https://www.wsj.com/articles/how-to-care-for-aging-parents-when-you-cant-be-there-11610200808
> When I close the extension and open this url, that site's response is normal (and the paywall is there, too).
> And open the extension, that site's response become 500-code. - .-

I know what happend. IP address restriction cause it, and I just need an unlimited IP.
