### ISSUE TITLE
Seekingalpha doesn't work anymore

### ISSUE THREAD

**Issue by SvetaGit** [iamadamdev/bypass-paywalls-chrome#1085]
Might be related to this update: https://seekingalpha.com/article/4396836-important-update-for-seeking-alpha-users
I'm using Chrome

**Comment by luciochagas** [comment]
> Might be related to this update: https://seekingalpha.com/article/4396836-important-update-for-seeking-alpha-users
> I'm using Chrome

Opened 3 trending articles, no issues found. Maybe double-check your extension?

**Comment by SvetaGit** [comment]
Maybe you haven't reached the monthly limit yet, for me it displays "You've reached your limit of guest articles this month".

**Comment by SvetaGit** [comment]
My bad, it started working when I checked "General paywall bypass"
