### ISSUE TITLE
Globe and Mail not working

### ISSUE THREAD

**Issue by jamrkstrom9** [iamadamdev/bypass-paywalls-chrome#1086]
Not working in Chrome
Extension working on other sites
Stopped working about a week ago or so
Deleted all globeandmail.com cookies and added domain to block cookies in Chrome 

https://www.theglobeandmail.com/world/us-politics/article-democrats-push-toward-second-trump-impeachment-republican-support/

Globe and Mail site displays: 
Please enable cookies in your browser. To read article you must be a globeandmail.com subscriber

Thanks for the extension and any help!

**Comment by iamadamdev** [comment]
Still works for me in Chrome.. maybe an IP issue?

**Comment by jamrkstrom9** [comment]
Thanks for reply. I took the site off my blocked cookies list and enabled it on extension to solve.
