### ISSUE TITLE
Extension breaks NYT Cooking "Recipe Box"

### ISSUE THREAD

**Issue by stephendelucia** [iamadamdev/bypass-paywalls-chrome#1088]
Hi, just reporting that the extension breaks the NYT Cooking "Recipe Box":  https://cooking.nytimes.com/recipe-box/all

When the extension is enabled, the site partially loads and then the site throws the following error:  "Oops! There was an issue submitting your request. Please try again."

If you disable the extension, the site works fine.  This is happening in Firefox.

**Comment by Pezor** [comment]
It also breaks the rating part, for eg. `https://cooking.nytimes.com/recipes/1018045-chocolate-babka`

**Comment by luciochagas** [comment]
Opened 3 different recipe sections for testing. Working flawlessly here, on Chrome.

**Comment by Pezor** [comment]
Maybe it's just Firefox issue.
**Firefox: 84.0.2 (64-bit)**
**OS: macOS Big Sur 11.1 (20C69)**
Here are some before / after screenshots, just the stars disappears in my case

**Extension off:**
![obrazek](https://user-images.githubusercontent.com/6975523/104274439-23155300-54a1-11eb-8362-ca21f9c004bf.png)

**Extension on:**
![obrazek](https://user-images.githubusercontent.com/6975523/104274449-28729d80-54a1-11eb-8d55-374b214f1209.png)

**Comment by iamadamdev** [comment]
There's nothing to see on that page anyway, you can goto an actual recipe page like 
https://cooking.nytimes.com/recipes/8042-chocolate-silk-pie?surface=cooking-carousel&fellback=false&req_id=419772931&algo=cooking_doc2vec_weight_1&variant=0_cooking_doc2vec_weight_1&imp_id=878068731&action=click&module=RecirculationRibbon&pgType=recipedetails&rank=4

Just click X on the error at the top and you can still search recipes.
