### ISSUE TITLE
Error on 1.4.2 update

### ISSUE THREAD

**Issue by nanny07** [iamadamdev/bypass-paywalls-chrome#109]
I'm receiving this error after had downloaded the 1.4.2 version

![image](https://user-images.githubusercontent.com/17173586/52474658-62421780-2b99-11e9-9e57-65d28afe7222.png)

**Comment by mikado-cat** [comment]
Same issue, just cleared it and ignored it. Everything operates fine.

**Comment by iamadamdev** [comment]
I am not seeing any errors on macOS
What OS and what Chrome version is this on?
Did this appear in the console when you click 'Inspect views background page'?

**Comment by mikado-cat** [comment]
macOS HS, Chrome 71.0.3578.98.
Does not appear in console for me.
Error only appears when I first load the unpacked extension; just replicated it again.

**Comment by iamadamdev** [comment]
Can you upgrade to the latest Chrome (v72) and try again?
Mine looks like this:
![image](https://user-images.githubusercontent.com/36013816/52507572-c5867680-2ba6-11e9-9108-ab95bb6fd0d3.png)

**Comment by mikado-cat** [comment]
Upgraded Chrome; could not replicate in v72.
