### ISSUE TITLE
L'Usine Nouvelle

### ISSUE THREAD

**Issue by bettermind** [iamadamdev/bypass-paywalls-chrome#1093]
paywall_URL = https://www.usinenouvelle.com/

**Comment by luciochagas** [comment]
Working on my side. Opened 4 different articles. Windows 10, Chrome.

P.S.: Good website to practice French.

**Comment by iamadamdev** [comment]
Just add to custom sites:
![image](https://user-images.githubusercontent.com/36013816/104641369-87c9dc80-565e-11eb-810f-758e2ee68945.png)
