### ISSUE TITLE
Would you consider IMDB ?

### ISSUE THREAD

**Issue by jsEveryDay** [iamadamdev/bypass-paywalls-chrome#110]
I know this is off topic but you'll do a lot of people a favor if you do it.
We all check movie ratings, sometimes the source that directs you to IMDB may not be very DRM compliant if you know what I mean. Would you consider creating a new 'privacy' array and drop headers for the listed site.

You go on a torrent site, you click the imdb url that automatically adds the "referrer". IMDB is owned by Amazon, do you want to tell amazon where you get your movies from?

I can make the changes if you like the idea.

I also have the following on my list:
    "https://*.google.com/*",
    "https://*.cloudfront.net/*",
    "*://*.googleapis.com/*",
    "*://*.gstatic.com/*"
I don't recommend using the above.

**Comment by iamadamdev** [comment]
It's not quite related to bypassing paywalls so I don't think it makes sense to add it here. If you were going to make the changes, wouldn't you want to create your own extension for it?

**Comment by jsEveryDay** [comment]
Agreed, it is out of the scope of this extension.
I personally run it on my paywall bypass, sure it can be a separate extension, the idea is to run the least number of extensions in Chrome for performance reasons.
