### ISSUE TITLE
New site request: [https://europe.autonews.com/ & https://www.autonews.com/ & more]

### ISSUE THREAD

**Issue by Owhora** [iamadamdev/bypass-paywalls-chrome#1100]
Hi, 

Thanks for this wonderful extension. I have a request please. Could you please add: 
1. https://europe.autonews.com/
2. https://www.autonews.com/ 
3. https://www.autonews.com/china
4. https://canada.autonews.com/
5. https://www.automobilwoche.de/

I have trouble accessing to the old articles in there - It keeps asking me to be a subscriber to access the premium content. 

Thank you very much,

**Comment by iamadamdev** [comment]
I just loaded 10+ articles w/o issue on autonews.com. Where are you seeing a paywall?

**Comment by Owhora** [comment]
Interesting. I couldn't access to them. 

for examples: 
https://europe.autonews.com/automakers/ford-increases-uk-prices-fiesta-puma-performance-cars-due-brexit
https://europe.autonews.com/automakers/dacia-lada-business-unit-will-unleash-brands-power-renault-execs-say
https://europe.autonews.com/automakers/renault-committed-stronger-alliance-nissan-chairman-says
https://europe.autonews.com/automakers/renault-follow-peugeot-vw-seeking-higher-transaction-prices

Let me know if you can access to them.

**Comment by iamadamdev** [comment]
Since this is not a major newspaper I won't be adding it, but you can always disable JS in uBlock Origin to read those articles:
![image](https://user-images.githubusercontent.com/36013816/104954619-6aa64e00-597d-11eb-9f4c-475fb9575b2c.png)
