### ISSUE TITLE
https://www.institutionalinvestor.com/article/b1q07frtv7yzsr/Citadel-Millennium-Other-Multistrats-Posted-Best-Gains-in-Years-in-2020

### ISSUE THREAD

**Issue by mviola5** [iamadamdev/bypass-paywalls-chrome#1102]
Confirmed

**Comment by iamadamdev** [comment]
What did you confirm exactly?

**Comment by mviola5** [comment]
I thought I was following your instructions to add a website...I would like to add the website Institutional Investor.

Thanks.

**Comment by iamadamdev** [comment]
Did following the instructions get rid of the paywall for you?

**Comment by iamadamdev** [comment]
"If it loads without a paywall you can submit a request and replace the entire template text with the word "Confirmed". Otherwise please do not submit an issue as this extension cannot bypass it either."

**Comment by quantlife2020** [comment]
no it did not get rid of the paywall...tried the incognito tab and downloaded the other extensions as well
