### ISSUE TITLE
Harvard business review and medium does not working fine. It is showing free 2 or 3 articles only after that paywall is coming and not going even after clearing the cookies.

### ISSUE THREAD

**Issue by keshavgarg1** [iamadamdev/bypass-paywalls-chrome#1103]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
I just loaded 10+ articles w/o any problems on HBR
