### ISSUE TITLE
 New site request: www.elsiglodetorreon.com.mx

### ISSUE THREAD

**Issue by mariorcan** [iamadamdev/bypass-paywalls-chrome#1106]
Hi,

Thanks for this awesome extension. I have a request please:

    https://www.elsiglodetorreon.com.mx/

Some articles ask to login and be a subscriber to access them.

Thanks,

**Comment by iamadamdev** [comment]
Once you see the paywall, try refreshing the site (make sure uBlock Origin is installed)
