### ISSUE TITLE
New site request: [rtings.com]

### ISSUE THREAD

**Issue by aaomidi** [iamadamdev/bypass-paywalls-chrome#1107]
### New site requests - Before submitting an issue please read the following:

Specifically the insider section of the website:

e.g. https://www.rtings.com/soundbar

<img width="943" alt="image" src="https://user-images.githubusercontent.com/1465785/104857083-23b84a00-58e4-11eb-936e-fa7e76d0dd4c.png">

**Comment by iamadamdev** [comment]
Not seeing a paywall.
Please paste URL where you are seeing a paywall.

**Comment by ML-Chen** [comment]
So you can view three different reviews for free, such as https://www.rtings.com/soundbar/reviews/vmai/2-1-channel-sound-bar, https://www.rtings.com/soundbar/reviews/sonos/beam, and https://www.rtings.com/soundbar/reviews/jbl/bar-9-1, but then reading a fourth review page (e.g., https://www.rtings.com/soundbar/reviews/samsung/hw-q950t) will have the ratings and images hidden.

![image](https://user-images.githubusercontent.com/6678625/104861847-66d3e680-58ff-11eb-8e75-804b6a9605b1.png)

**Comment by aaomidi** [comment]
@ML-Chen thanks for completing the details.

**Comment by iamadamdev** [comment]
This is not a major newspaper, you can simply use a Cookie Remover to clear cookies on that site to reset the count.
https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce
Or you can add to custom sites in Bypass Paywalls:
![image](https://user-images.githubusercontent.com/36013816/104954444-1d29e100-597d-11eb-9a4a-ba654025fc51.png)
