### ISSUE TITLE
New site request: [spectator.us]

### ISSUE THREAD

**Issue by ML-Chen** [iamadamdev/bypass-paywalls-chrome#1108]
Example pages: https://spectator.us/topic/trump-twitter-suspension-crime-against-literature/, https://spectator.us/topic/france-covid-response-source-national-shame/, https://spectator.us/topic/policing-world-change-biden-foreign-policy/, https://spectator.us/topic/living-nevertrump-fantasy-universe/

The first article you view displays, but any subsequent articles (or maybe the third article onward) briefly have the text but then the text disappears a split second later, effectively acting as a paywall. You can bypass the paywall by deleting your cookies for the website. So I think this website would be a good fit for this extension.

**Comment by iamadamdev** [comment]
Added in latest master
