### ISSUE TITLE
Not working on The Economist

### ISSUE THREAD

**Issue by arann25** [iamadamdev/bypass-paywalls-chrome#111]
Tried clearing cookies, turning off my Evernote Clipper (which had worked for wsj), switching the extension off and on, nothing seemed to work. 

Chrome version 72.0.3626.109 (official build)(64-bit) running on a Windows 10. No adblocker installed btw.

**Comment by iamadamdev** [comment]
What article doesn't load for you? I loaded 10+ articles just fine.
On Windows using Chrome Version 72.0.3626.109 (Official Build) (64-bit).

**Comment by arann25** [comment]
All articles had a part of it curtailed after fully loading the page, with a box saying "register to read this article in full". 

I can actually get rid of it by clicking the 'stop loading' button before the paywall loads, but I'm not sure if it is how the extension is supposed to work.

A screen cap: 
![default](https://user-images.githubusercontent.com/25360996/53067006-3e71c080-350d-11e9-91fa-e5a7f37063dd.PNG)

**Comment by iamadamdev** [comment]
Don't use it in incognito mode, turn on uBlock Origin. Refresh the page. It works fine for me.

**Comment by arann25** [comment]
Tried and it worked. Thanks.

**Comment by podgeflat** [comment]
Hi - apologies I am having the same issue as above while not in incognito mode - uBlock Origin is installed and Cookie Remover. [This article](https://www.economist.com/united-states/2019/11/21/gordon-sondland-weakens-republican-defences-against-impeachment) for example does not work.

**Comment by magnolia1234** [comment]
Is working just fine. Check for The Economist in options in latest v1.5.9.

**Comment by podgeflat** [comment]
Ah thank you so much - I updated and it worked :)
