### ISSUE TITLE
New site request: [lemonde.fr]

### ISSUE THREAD

**Issue by MKais** [iamadamdev/bypass-paywalls-chrome#1110]
Thank you for this extension
Here's an [example](https://www.lemonde.fr/afrique/article/2021/01/16/francois-graner-plus-on-avance-et-plus-le-tableau-est-accablant-pour-la-france-au-rwanda_6066516_3212.html) from lemonde.fr

**Comment by MiloParigi** [comment]
Looking at the website and previous requests (for example https://github.com/iamadamdev/bypass-paywalls-chrome/issues/557) It is a hard paywall so it is not feasible.

**Comment by MKais** [comment]
Thanks for your effort anyway. Good luck with the rest
