### ISSUE TITLE
Extension breaks washingtonpost.com

### ISSUE THREAD

**Issue by scheng80** [iamadamdev/bypass-paywalls-chrome#1111]
https://www.washingtonpost.com/opinions/2021/01/18/video-evidence-capitol-cruz-hawley/

Washingtonpost.com appears to be actively blocking pages reloaded using the extension. It used to work before. Now, it will get an access denied error.

###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
Still loads for me.
