### ISSUE TITLE
Is there an Android version, which works for mobile devices? FF85 for Android, which is scheduled for tomorrow, will support

### ISSUE THREAD

**Issue by RotterSoft** [iamadamdev/bypass-paywalls-chrome#1113]
Add-ons Extentions, as described here: https://blog.mozilla.org/addons/2021/01/20/extensions-in-firefox-for-android-update/
After installed, would it be possible to use Bypass Paywalls on my Samsung Galaxy?
Thanks!

###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
Probably not, but you should be able to use it in Firefox for Android Nightly if you create your own collection
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by RotterSoft** [comment]
> 
> 
> Probably not, but you should be able to use it in Firefox for Android Nightly if you create your own collection
> https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

Thank you for your prompt reply! :)
And please... consider making it available for numerous Android users worldwide.

**Comment by iamadamdev** [comment]
> consider making it available for numerous Android users worldwide
What do you mean? There shouldn't be any geo restriction placed on downloading it. Unless that's something Mozilla did.
