### ISSUE TITLE
ad.nl not working anymore

### ISSUE THREAD

**Issue by shankaray** [iamadamdev/bypass-paywalls-chrome#1118]
https://www.ad.nl/dossier-eredivisie/arnhem-een-afscheppende-voetbalstad-waarin-ze-gruwelen-van-overdrijvende-ajax-mentaliteit~a1481cdf/
mx linux firefox
premium article not accessible anymore.

**Comment by zubus** [comment]
It's working fine for me, firefox and win, version 1.7.8

**Comment by shankaray** [comment]
works again after reset firefox
Sorry!
Great job!
