### ISSUE TITLE
Harvard business review not working. I tried on multiple devices but still not working. Please Help!

### ISSUE THREAD

**Issue by keshavgarg1** [iamadamdev/bypass-paywalls-chrome#1121]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
Works fine for me.
url?

**Comment by keshavgarg1** [comment]
Actually, It's just opening 3 free articles. After that, the paywall is coming and asking for subscribing, and even after clearing the cookies (using cookie remover), it's not opening the full article.
So, even if I provide you the link, you will not be able to detect the problem as it will open that but not open the 4th or 5th article in sequence as it only provides 3 free articles and asks for subscribing.
Please resolve it ASAP.

**Comment by iamadamdev** [comment]
I just opened 10+ articles w/o issue.
Just click x to close the pop up
![image](https://user-images.githubusercontent.com/36013816/106368549-26149e00-62ff-11eb-9160-e83356cf92a6.png)
