### ISSUE TITLE
NZ Herald has stopped working for one(?) page

### ISSUE THREAD

**Issue by LocalNZer** [iamadamdev/bypass-paywalls-chrome#1122]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed. YES
3. Chrome or Firefox?    ===> FIREFOX 
4. Paste the article URL for the site you are having issues with.
https://www.nzherald.co.nz/entertainment/sideswipe-january-29-pigeon-pool/A2N6DEJFUEIJRMTYWZERQC65PI/

5. Describe the issue.
The linked page shows limited content with the text "To continue reading this article and to support great journalism...." - ![image](https://user-images.githubusercontent.com/72763620/106196155-f50c6e80-6215-11eb-85cc-00fa9428cfa6.png)

Other pages, such as https://www.nzherald.co.nz/business/smart-shopping-trolley-start-up-seeks-to-raise-25-million/CB6464HZCURTNYTNENHMQOPXWA/ do not.  ![image](https://user-images.githubusercontent.com/72763620/106196399-40268180-6216-11eb-81f4-ce96a4196c91.png)  I haven't found any  other page that fails as yet.
Note also the minor, odd paragraph formatting at the start of [every] article that does bypass.  Not suggesting a big deep dive in code to fix, just looks odd but is perfectly readable ;-}
 
###

**Comment by LocalNZer** [comment]
I don't understand this notification.  All it says is closed.  I cannot see
anything in the post itself saying why, except for this which I don't
understand the meaning -
Linked pull requests

Successfully merging a pull request may close this issue.
None yet

I have also found that any page starting "
https://www.nzherald.co.nz/entertainment/sideswipe-...."

Is there anything I should do, or wait for an update to come thru Firefox's
auto-update Add-on process to do the "Successfully merging a pull request"
??

Thanks for your help in understanding this.

**Comment by iamadamdev** [comment]
No fix at the moment, most pages still work fine.
