### ISSUE TITLE
Bloomberg article does not show again on the private mode with Firefox

### ISSUE THREAD

**Issue by mickeyseo** [iamadamdev/bypass-paywalls-chrome#1123]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

User environment : Firefox 85.0 64bit, Windows 10 64bit
I use these add-ons. Absolute Enable Right Click & Copy, Autoplay No More, Bypass Paywalls, Cookie Remover, I don't care about cookies, Pouch, uBlock Origin, Universal Bypass

I generally surf the web on private mode with Firfox. After I scroll down on the article at Bloomberg.com and come back, I face a private mode warning sign and cannot read this article again. Please watch a capture video. The problem still exists when I turn off the *General Paywall Bypass*.

https://drive.google.com/file/d/1lhGy21JMFN6nNwDecyPgYdCsvNev0v3Q/view?usp=sharing

I don't want to turn off the private mode. Could you please help me?

**Comment by iamadamdev** [comment]
Please read #4

**Comment by iamadamdev** [comment]
Try disabling JS if you want to keep using Private mode:
![image](https://user-images.githubusercontent.com/36013816/106245525-6d951000-61c1-11eb-8de2-a6bbc98ca6c0.png)

**Comment by mickeyseo** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/pull/4

Thank you!
