### ISSUE TITLE
The Washington Post not working

### ISSUE THREAD

**Issue by xSlysoft** [iamadamdev/bypass-paywalls-chrome#1124]
I am using Firefox and I do have uBlock Origin installed. It was working fine at least a week ago but recently I have been getting hit with notifications. This is affecting pretty much every article that I can see but as an example one of the first articles on the page https://www.washingtonpost.com/opinions/2021/01/29/biden-reconciliation-gop-outrage/

**Comment by iamadamdev** [comment]
Still works for me

**Comment by xSlysoft** [comment]
I actually do use a vpn - Private Internet Access.

If it works for you then it must be a conflict with one of my addons, I'll try troubleshooting myself. This is a list of addons I have installed:
![image](https://user-images.githubusercontent.com/42144975/106368617-068a6f00-6319-11eb-838e-c8d42856bac3.png)

**Comment by xSlysoft** [comment]
Ok, I was able to pinpoint the issue and it was with my vpn. If I enable the "disable website referrer" option in PIA it breaks the functionality for whatever reason.
