### ISSUE TITLE
Brave does not allow us to enable this extension

### ISSUE THREAD

**Issue by include** [iamadamdev/bypass-paywalls-chrome#1126]
Hi, 

I've installed this awesome extension but looks like Brave will not allow us to enable extensions not listed anymore in their "app store".

"This extension is not listed in the Brave Web Store and may have been added without your knowledge" and then following to that page I get "Extensions that have not been published on the Chrome or Brave Web Store are grayed out and you won't be able to turn them back on."

Are we able to bypass this too?

Cheers,
F

**Comment by iamadamdev** [comment]
Not sure as I don't use Brave.
