### ISSUE TITLE
Les Echos (FR) does not work on a specific article

### ISSUE THREAD

**Issue by Pil0u** [iamadamdev/bypass-paywalls-chrome#1127]
Hello team,

I tried [this article](https://www.lesechos.fr/weekend/business-story/jeux-video-rencontre-avec-le-patron-%20francais-de-league-of-legends-1281036) on Firefox, where uBlock Origin is installed.

The website keeps refreshing the page infinitely while the extension is activated for the website. Once I deactivate it, the site stops refreshing but the bypass does not work.

However I tried a random article from the website (I do not visit this site often), it works well. [Example](https://www.lesechos.fr/monde/europe/covid-leurope-veut-controler-les-exportations-de-vaccins-produits-sur-son-sol-1285865).

Thanks!

**Comment by iamadamdev** [comment]
Not sure what's going on with that article...
