### ISSUE TITLE
New Zealand Herald - Premium article redirects to subscription sign-in

### ISSUE THREAD

**Issue by lachieee** [iamadamdev/bypass-paywalls-chrome#1128]
They've updated the [New Zealand Herald website](https://www.nzherald.co.nz/nz) so that when a Premium article is clicked and it loads in the browser window, you will be redirected to a new subscription sign-up page if you do not already have one.

[Example Premium article](https://www.nzherald.co.nz/nz/a-first-home-buyers-journey-onto-taurangas-property-ladder/HDQZBFPPKNQHUJ6OGPC5T2DNOU/)

**Comment by iamadamdev** [comment]
Works for me.
