### ISSUE TITLE
New site request: [www.zonebourse.com]

### ISSUE THREAD

**Issue by sarayliserkan** [iamadamdev/bypass-paywalls-chrome#1129]
Hello!

I have followed the guide for articles on www.zonebourse.com and can open articles in incognito mode.

Please add www.zonebourse.com.

Also, www.marketscreener.com is a subsidiary of zonebourse and I would like to request to add that website as well, please. The articles there also open in incognito mode.

Thank you!

**Comment by sarayliserkan** [comment]
Confirmed

**Comment by iamadamdev** [comment]
Disable uBlock Origin and you should be able to read most articles. Can also add to custom sites.
