### ISSUE TITLE
Android: how to do install step 5?

### ISSUE THREAD

**Issue by Jimbo213Mo** [iamadamdev/bypass-paywalls-chrome#1132]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported. 
**Done**
2. Make sure uBlock Origin is installed.
** Not on playstore? **
3. Chrome or Firefox?
** Chrome on Moto G(7) Android 10 **
4. Paste the article URL for the site you are having issues with.
** Your app instructions **
5. Describe the issue.
** How do I perform step 5 drag the folder ? **
** Easy to do on laptop **
** Sorry if this is a dumb question ⁉️ **
###

**Comment by iamadamdev** [comment]
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
