### ISSUE TITLE
Does not work for SeekingAlpha

### ISSUE THREAD

**Issue by ming-zhao** [iamadamdev/bypass-paywalls-chrome#1135]
It does not work for seeking alpha anymore. The webpage turns into gray. Thanks.

**Comment by iamadamdev** [comment]
url?

**Comment by ming-zhao** [comment]
Sorry. Here is the link
https://seekingalpha.com/article/4400910-nicks-picks-2021

**Comment by iamadamdev** [comment]
Still works for me
![Uploading image.png…]()

**Comment by ming-zhao** [comment]
I figure that I need to delete cookies/site data every time.
Could you open more than two links (in sequence) in seeking alpha? For example, for these 3 in a row

https://seekingalpha.com/article/4405235-battery-revolution-winners-and-losers
https://seekingalpha.com/article/4405285-alibaba-undervaluation-is-off-scale
https://seekingalpha.com/article/4405321-dividend-portfolio-january-2021-update

**Comment by iamadamdev** [comment]
All of those opened without any paywall for me (Chrome)
