### ISSUE TITLE
Adweek not working

### ISSUE THREAD

**Issue by dooak** [iamadamdev/bypass-paywalls-chrome#1139]
Webpage loads but doesn't seem to load the full article - Only showing a small exec summary of it.

**Comment by iamadamdev** [comment]
Please follow the template:
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###
