### ISSUE TITLE
Fantastic extension. Well done. But... extension keeps disappearing in Chrome

### ISSUE THREAD

**Issue by possomcohen** [iamadamdev/bypass-paywalls-chrome#114]
Extension works fine in Chrome... but it keeping disappearing from Chrome. I have to reinstall it several times a day. Never did that before the last update. I am running current Mac Mojave OS on new iMac. Only started doing this since I updated to the recent version of Mojave and reinstalled Chrome on the iMac. Thank you.

**Comment by iamadamdev** [comment]
I assume you installed it by dragging and dropping the folder into chrome://extensions ? and have developer mode turned on?
I am also on macOS Mojave 10.14.3 and Google Chrome Version 72.0.3626.109 (Official Build) (64-bit) and it stays installed even after fully closing (CMD+Q) Chrome.

**Comment by possomcohen** [comment]
Good Morning Adam,

Thank you for your email.

> On 18/02/2019, at 7:40 AM, Adam <notifications@github.com> wrote:
> 
> I assume you installed it by dragging and dropping the folder into chrome://extensions ?
> 

Yes, as per instructions on your Github page.

> and have developer mode turned on?
> 

Yes.

> I am also on macOS Mojave 10.14.3 and Google Chrome Version 72.0.3626.109 (Official Build) (64-bit)
> 

I am no the same versions.
> and it stays installed even after fully closing (CMD+Q) Chrome.
> 
> 

I powered on my iMac this morning and Chrome… and small miracle… the app extension was still there.

Great app. I use it many dozens of times a day when reading… WSJ, WashPo, FT etc….

I will try to figure out what triggers the disappearing act.

Regards,

Marc

**Comment by iamadamdev** [comment]
Will close for now since it appears to be WAI.
