### ISSUE TITLE
Not working for Tech in Asia

### ISSUE THREAD

**Issue by chaoniama** [iamadamdev/bypass-paywalls-chrome#1142]
Running Tech in Asia in Firefox with uBlock installed. Whenever I try to read any article, I will only be able to read the first subtopic of the article, with subsequent subtopics being title-only. Please refer to my screenshot for example of the issue. 

<img width="1280" alt="Screenshot 2021-02-25 at 9 00 51 PM" src="https://user-images.githubusercontent.com/75971083/109157081-8dadf400-77ac-11eb-8b2e-52c27836f939.png">

**Comment by iamadamdev** [comment]
URL?

**Comment by chaoniama** [comment]
Here you go.

https://www.techinasia.com/dark-side-buy-pay 

Thanks!

**Comment by iamadamdev** [comment]
Fixed in latest master (you can build the FF version yourself for now, or wait for the next release)
