### ISSUE TITLE
New site request: [https://www.naturalgasintel.com]

### ISSUE THREAD

**Issue by Youbi-msw** [iamadamdev/bypass-paywalls-chrome#1143]
Confirmed

**Comment by iamadamdev** [comment]
Since this is not a major news site try Custom Sites

**Comment by Youbi-msw** [comment]
Custom Sites does not work with Firefox, according to the documentation.
On Chrome naturalgasintel.com it works perfectly fine with Custom Sites.
Would be great to see it for Firefox somehow.

**Comment by iamadamdev** [comment]
You just need to add naturalgasintel.com to the FF manifest, and add to sites file (on your local copy).
