### ISSUE TITLE
Elmundo.es

### ISSUE THREAD

**Issue by jorgelopes94** [iamadamdev/bypass-paywalls-chrome#1146]
Hi. I know that [someone on this page has asked about the addition of elmundo.es](https://github.com/iamadamdev/bypass-paywalls-chrome/issues/413). I submitted the website to the custom sites and, so far, it has worked on most premium pages, including those that are on the AMP format.
However, I can't bypass the pages that are on some specific sections, such as the /especiales subsection, because they still have the paywall window.
On this case, such as the first photo that I posted here, I can only see the biographical data, the name and the photo, etc. I'm not able to see the remaining content.
It seems that this site is open to some paywall bypassing when it comes to simple texts, but when it comes to pages that have a lot of graphics and design, it is still unavailable. I've tried everything that I could to try to bypass the pages of the /especiales section, with installed apps like uBlock Origin, Hover, etc.
Please refer to my screenshots to see the comparison between the page with paywall and the page without paywall.

Examples: https://www.elmundo.es/especiales/los-mas-ricos/sandra-ortega-mera.html (with paywall barrier); https://amp.elmundo.es/internacional/2021/02/25/6036748cfc6c83ff0d8b45e1.html (with paywall bypassed)

![Captura de Ecrã (254)](https://user-images.githubusercontent.com/79590439/109225772-a969c800-77b5-11eb-99e6-91d9063acaf1.png)
![Captura de Ecrã (255)](https://user-images.githubusercontent.com/79590439/109225778-ab338b80-77b5-11eb-9380-6d2f27529576.png)

**Comment by jorgelopes94** [comment]
Despite the problem with the paywall still going on the /especiales subsection pages, I still can access to the normal pages of elmundo.es

**Comment by iamadamdev** [comment]
That might be a hard paywall.
