### ISSUE TITLE
Not working for outlooks on Statista.com

### ISSUE THREAD

**Issue by uddinnizar14** [iamadamdev/bypass-paywalls-chrome#1148]
After the recent update, bypass paywalls stopped working for outlooks on statista.com It is working properly for reports and simple statistics but not for outlooks. I've checked both on Firefox and Chrome. I used AdBlock too. 

For instance this page: https://www.statista.com/outlook/tmo/software/system-infrastructure-software/worldwide#key-market-indicators Screenshot:

![image](https://user-images.githubusercontent.com/65922932/109263912-f08fa180-7825-11eb-8417-8438a67d63d4.png)

**Comment by iamadamdev** [comment]
Looks to be behind a hard paywall now.

**Comment by uddinnizar14** [comment]
Any workaround?

**Comment by iamadamdev** [comment]
Not if it's a hard paywall
