### ISSUE TITLE
Unable to open the the document becasue of paywall, tried all steps.

### ISSUE THREAD

**Issue by Ubaid-98** [iamadamdev/bypass-paywalls-chrome#1149]
Hi, first of all, thanks a lot. Your extension has helped me a lot. 
I tried to open these case studies from Havard Business Review at  " https://hbr.org/case-selections " but I get a pop up due to a paywall. Please can you help? Thank you again.

**Comment by iamadamdev** [comment]
Those seem to be behind a hard paywall.
