### ISSUE TITLE
Auto Update Test Results

### ISSUE THREAD

**Issue by pjpreilly** [iamadamdev/bypass-paywalls-chrome#115]
Downloaded the 1.4.4 bypass-paywalls-chrome.crx file & dragged it into the Extensions tab. It installed & upon clicking "Update" the extension DID update. Tested on cloudready and Chrome on LXLE with success. Kudos

**Comment by pjpreilly** [comment]
...& WAPO seems to be WORKING!!!!

**Comment by iamadamdev** [comment]
Glad to hear!

**Comment by prech** [comment]
Hmm, should v1.4.5 installed from the unpacked Zip auto update to v1.4.6?

I tried clicking on the circular update button in my Chrome Extensions page, as well as the overall Update button, but it remains at v1.4.5

![image](https://i.imgur.com/w8Kfd2Xl.jpg)

**Comment by pjpreilly** [comment]
See my comment & go **[HERE](https://github.com/iamadamdev/bypass-paywalls-chrome/releases)** to download the 1.4.4 .crx file & dreag it!!!!
