### ISSUE TITLE
The Globe and Mail refresh-cycles on subcribed content load

### ISSUE THREAD

**Issue by sudo-a9** [iamadamdev/bypass-paywalls-chrome#1152]
Reproducible in Windows -> Firefox.
As example:

https://www.theglobeandmail.com/business/international-business/article-saudi-aramco-to-prioritize-energy-supply-to-china-for-50-years-says/?ref=premium

**Comment by iamadamdev** [comment]
Works fine for me, do you have uBlock Origin installed?

**Comment by sudo-a9** [comment]
> 
> 
> Works fine for me, do you have uBlock Origin installed?

I do.  Let me tinker....

**Comment by iamadamdev** [comment]
I didn't add to trusted sites in uBlock.
Are you saying it keeps refreshing?

**Comment by sudo-a9** [comment]
> 
> 
> I didn't add to trusted sites in uBlock.
> Are you saying it keeps refreshing?

Yes, I get into a refresh-cycle still.

**Comment by iamadamdev** [comment]
How about on Chrome?
