### ISSUE TITLE
Can this tool be used inside a scraper?

### ISSUE THREAD

**Issue by GiorgioBarnabo** [iamadamdev/bypass-paywalls-chrome#1153]
Hi there,

thank you for this amazing repository ;) I was just wondering whether it could be used
inside a scraper. What I mean is that it would be cool if, when running an app that tries to access
protected content automatically, pywalls were overcome automatically.

Best,

Giorgio

**Comment by iamadamdev** [comment]
That's beyond the scope of this project at this time.
