### ISSUE TITLE
washingtonpost.com videos slowdown

### ISSUE THREAD

**Issue by averissimo** [iamadamdev/bypass-paywalls-chrome#1155]
1. Searched the issues and didn't found it _(only issues where the site doesn't work)_
2. uBlock Origin is installed
3. Firefox
4. https://www.washingtonpost.com/nation/2021/03/22/boulder-shooting/?itid=hp-top-table-main
5. Videos on the washingtonpost site switch to "slow speed" when this extension is enabled _(or WaPo is enabled)_

How to reproduce:

* Open the site in a normal window with extension installed and play video _(slow speed)_
* Open a private window with extension disabled, accept GDPR and then play video _(normal speed)_
    * Enable extension on private windows and reload the page
    * Play the video _(slow speed)_

I can also reproduce the issue by opening the options and deselecting all _(plays at normal speed)_ and selecting all again _(plays video at slow speed)_

_edit_: in chrome videos play at normal speed. I also disabled all extensions in private mode except this and uBlock Origin for the test

**Comment by iamadamdev** [comment]
Tried in Chrome and Firefox. The videos play at normal speed for me.
What do you mean by slow speed? the videos are playing at .5x speed?

**Comment by cynicaljames** [comment]
> Tried in Chrome and Firefox. The videos play at normal speed for me.
> What do you mean by slow speed? the videos are playing at .5x speed?

Yeah, that's what they're referring to.

**Comment by averissimo** [comment]
Yes, at less than 1x speed. Here are more details and a screen capture of the bug in action:

https://streamable.com/s50jox 

Video is taken from Firefox 86.0 with only uBlock Origin and Bypass-paywalls installed after a refresh of the account.. so default options

Operating system: Ubuntu 21.04 _(bug present since 20.04)_

I can also reproduce this on firefox 89.0a _(nightly)_

**Comment by iamadamdev** [comment]
I'm unable to repro on Chrome or Firefox. But I pushed up a possible fix on latest master.

**Comment by averissimo** [comment]
You are a magician as you fixed this without being able to reproduce it.

I just tested master and it works.

Thanks for the brilliant work with the extension.
