### ISSUE TITLE
New site request: dallasnews.com

### ISSUE THREAD

**Issue by pogue** [iamadamdev/bypass-paywalls-chrome#1156]
Hi,
I'd like you to add dallasnews.com to the paywall extension. I tried the other methods you mentioned, including a VPN, but it still pops up and wants you to login to read a lot of the articles. If you could add this site (it is a major news source) that would be great.

Thanks,
pogue

**Comment by iamadamdev** [comment]
Where are you seeing a paywall? Url?
I just opened 10+ articles even member exclusive ones and didn't see a paywall. Do you have uBlock Origin installed?

**Comment by pogue** [comment]
Well, it seems they aren't asking for subscriptions anymore. I dug up the pages that asked for subscription logins and they're no longer asking for logins.

So, sorry for this, you can ignore this one as they apparently have gone totally free.
