### ISSUE TITLE
Doesn't work on www.lastampa.it

### ISSUE THREAD

**Issue by Andrew3000s** [iamadamdev/bypass-paywalls-chrome#1157]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. **Y**
3. Chrome or Firefox?
4. **Chrome**
4. Paste the article URL for the site you are having issues with.
5. **https://www.lastampa.it/topnews** 
5. Describe the issue.
6. **Every article on lastampa topnews**
###

**Comment by iamadamdev** [comment]
Fixed in latest master
