### ISSUE TITLE
Stopped working on wired.com again..

### ISSUE THREAD

**Issue by Safekeep** [iamadamdev/bypass-paywalls-chrome#1158]
Stopped working on wired.com again... I've already down loaded the latest version of bypass-paywall, v1.7.8

Page will load fully, then a few seconds later, only the first paragraph of the article remains while the rest of the article are hidden...  Inspecting the code sees all items under class="paywall" hidden after the page loads fully...

**Comment by iamadamdev** [comment]
Works fine for me.

###
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by Safekeep** [comment]
1. uBlock Origin is installed.
2. Happens in both Chrome and Firefox, same problem with same issue.
3. All articles are affected, but see attached screen capture on Chrome on what is happening..   [https://drive.google.com/file/d/15CkOaAnP1biCsLhnosFCnuVakwXKz7St/view?usp=sharing](url)

**Comment by iamadamdev** [comment]
Fixed in latest master

**Comment by Safekeep** [comment]
Downloaded latest master and it's fixed!  Thanks!!!
