### ISSUE TITLE
Not showing interactive data on some websites

### ISSUE THREAD

**Issue by MrMineHeads** [iamadamdev/bypass-paywalls-chrome#1165]
Interactive data on the Toronto Star and Foreign Policy are not showing. 
These are the two articles in question:

https://www.thestar.com/news/gta/2021/04/04/bike-thefts-at-toronto-apartments-and-condos-have-tripled-in-five-years-new-interactive-data-shows.html

https://foreignpolicy.com/projects/biden-first-100-days/

I can't get a true archive link to demonstrate what is not showing up in the Foreign Policy, but for the Toronto Star: https://archive.is/HJkJ1

This is on **CHROME** btw. I have uBlock Origin installed. 

Comments also don't show on the Toronto Star article/

**Comment by iamadamdev** [comment]
thestar.com fixed. The FP article might be behind a hard paywall.
