### ISSUE TITLE
Causing website to malfunction

### ISSUE THREAD

**Issue by lucaben** [iamadamdev/bypass-paywalls-chrome#1166]
###
Hi, on both chrome and firefox for mac (OS Catalina, latest versions) I am experiencing issues on the website samharris.org (login popup not working, e-commerce not working). Please note: I do not wish to view content from this website for free, I don't even think there is a paywall, and I am actually an active subscriber. I've just tested all extensions and finally found that yours is causing the problems I am observing. Clearing cookies and disabling uBlock does not help on both firefox and chrome. 
Thanks for your great extension!  
###

**Comment by kimkha** [comment]
FYI, this might be the cause

<img width="533" alt="Screen Shot 2021-04-08 at 15 41 46" src="https://user-images.githubusercontent.com/1332605/113974279-ff379280-9880-11eb-91c1-6a395c61d82a.png">

**Comment by kimkha** [comment]
@lucaben disable this option should bring the login form back on that site:
<img width="355" alt="Screen Shot 2021-04-08 at 15 44 05" src="https://user-images.githubusercontent.com/1332605/113974482-5b021b80-9881-11eb-8b6e-c38a43bdf157.png">

**Comment by lucaben** [comment]
Not sure what that option is for, but it does work. Thanks so much!

L.
