### ISSUE TITLE
WSJ not available on Firefox

### ISSUE THREAD

**Issue by msaroff** [iamadamdev/bypass-paywalls-chrome#1168]
It redirects to the AMP version, which is blocked by the paywall.

**Comment by msaroff** [comment]
It works in Chrome though.

**Comment by iamadamdev** [comment]
Thanks for the heads up. Will be fixed in next release (or you can build it yourself with the build script and a bash-compatible shell.

**Comment by iamadamdev** [comment]
Fixed https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-firefox/
