### ISSUE TITLE
New site request: MarketWatch

### ISSUE THREAD

**Issue by verxolois** [iamadamdev/bypass-paywalls-chrome#1169]
Confirmed. Wanted to check if MarketWatch's paywall can be bypassed. Thanks!

**Comment by smoke-wolf** [comment]
UG ultimate guitar? has it been done yet- there is a paywall for their professional tabs and I want to know if there's any way to get past it?

**Comment by iamadamdev** [comment]
MarketWatch can be bypassed with a simple cooker remover:
https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce

**Comment by verxolois** [comment]
> MarketWatch can be bypassed with a simple cooker remover:
> https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce
> 
> or add to the Custom Sites tab of Bypass Paywalls:
> ![image](https://user-images.githubusercontent.com/36013816/118429842-7da90080-b687-11eb-86ad-423cc1c3f405.png)

got it to work. thanks for the reply!
