### ISSUE TITLE
The Times has stopped working

### ISSUE THREAD

**Issue by e-m-m-a** [iamadamdev/bypass-paywalls-chrome#1171]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
Yes
3. Chrome or Firefox?
Chrome
4. Paste the article URL for the site you are having issues with. https://www.thetimes.co.uk/article/holiday-plans-thrown-into-chaos-by-covid-variants-psk6d5ssv
5. Describe the issue.
Article now paywalled. 

Apologies its working again now, V. odd

**Comment by gj9999** [comment]
I'm still experiencing the paywall when using Firefox, this issue has only arisen today
