### ISSUE TITLE
La Repubblica is not working anymore

### ISSUE THREAD

**Issue by antonioh501** [iamadamdev/bypass-paywalls-chrome#1172]
Online newspaper: La Repubblica
Website: www.repubblica.it
Issue: Paywall removal is not working anymore since a few weeks

**Comment by iamadamdev** [comment]
Which article? I just loaded 5+ without issue.

**Comment by antonioh501** [comment]
Actually I have the issue with every article but I'm guessing it's something affecting only me then. I also did the troubleshooting steps without success. Btw, this is the only website that doesn't work

PS: just to be sure please try this one article because I can see from my iPhone that is behind a paywall

**Comment by iamadamdev** [comment]
Which article?

**Comment by antonioh501** [comment]
I'm sorry, but I must have messed up with copy/paste

https://www.repubblica.it/politica/2021/05/18/news/covid_tinagli_riaperture-301659432/?ref=RHTP-BH-I293269148-P2-S3-T1

**Comment by iamadamdev** [comment]
Try latest master.
