### ISSUE TITLE
Apple silicon Chrome Not running on medium 

### ISSUE THREAD

**Issue by sagarp96** [iamadamdev/bypass-paywalls-chrome#1173]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
?

**Comment by alexanderswerdlow** [comment]
I don't think apple silicon has anything to do with the issue since it's just Javascript, but Medium articles also do not work for me (coincidentally also on an M1 machine).
