### ISSUE TITLE
The Times has stopped working

### ISSUE THREAD

**Issue by gj9999** [iamadamdev/bypass-paywalls-chrome#1175]
Make sure uBlock Origin is installed.
Yes
Chrome or Firefox?
Firefox
Paste the article URL for the site you are having issues with. https://www.thetimes.co.uk/article/why-cant-those-who-have-had-covid-vaccine-just-get-on-with-their-lives-7wxr8mpv2
Describe the issue.
The article is now paywalled.

I note that someone else reported this issue, and then reported it was solved, but I am still experiencing a paywall block for all Times articles using Firefox

**Comment by iamadamdev** [comment]
I was able to get the paywall once but then I cleared cookies with my [extension ](https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/)and could not get the paywall again even after opening 10+ articles.

**Comment by gj9999** [comment]
Thanks for looking into this.  I've tried your solution but it seems to fail more often than it works unfortunately.  I can't work out a pattern for why it occasionally works and then the paywall reappears.  When I get blocked, I get a popup/overlay with a one-month free digital access offer but I'm not sure whether this is a symptom or the cause of the block

**Comment by mh0w** [comment]
> Thanks for looking into this. I've tried your solution but it seems to fail more often than it works unfortunately. I can't work out a pattern for why it occasionally works and then the paywall reappears. When I get blocked, I get a popup/overlay with a one-month free digital access offer but I'm not sure whether this is a symptom or the cause of the block

Same. For me, clearing the cookies works 50% of the time. I find this to be fine though, personally.

**Comment by A-nglea** [comment]
> > Thanks for looking into this. I've tried your solution but it seems to fail more often than it works unfortunately. I can't work out a pattern for why it occasionally works and then the paywall reappears. When I get blocked, I get a popup/overlay with a one-month free digital access offer but I'm not sure whether this is a symptom or the cause of the block
> 
> Same. For me, clearing the cookies works 50% of the time. I find this to be fine though, personally.

Happening for me across platforms Linux Firefox and Android Kiwi Browser (firefox fork) Clearing cookies sometimes gives access sometime not. Not really fine for me.

**Comment by goL-prog** [comment]
The Times is no longer working for me with Chrome either. Clearing cookies and reloading the extension makes no difference.

**Comment by sentient06** [comment]
Clearing cookies makes no difference for me. I'm on Firefox. v1.7.9b, and using uBlock as well.

**Comment by Elsewhereman** [comment]
I've been hitting this too, using Waterfox G3.2.1 and W10 - open uBlock's dashboard and purge all caches. Seems to work - at least for a while. Rinse and repeat ...

**Comment by iamadamdev** [comment]
In Chrome and Firefox after I clear cookies, refresh, and then accept the cookie prompt I can get that article to load.

**Comment by iamadamdev** [comment]
In Chrome and Firefox after I clear cookies, refresh, and then accept the cookie prompt I can get that article to load.

**Comment by ImnurSayf** [comment]
For some time, Firefox worked. But I can't open both in Chrome and Firefox.

**Comment by iamadamdev** [comment]
thetimes.co.uk is finicky.
