### ISSUE TITLE
https://www.chicagobusiness.com/ (Crain's Chicago Business) for Chrome 

### ISSUE THREAD

**Issue by banchan** [iamadamdev/bypass-paywalls-chrome#1176]
This has a paywall ad pop up - it didn't before with bypass paywalls; I could recently bypass it with the escape key.  This is Crain's Chicago. 

I have done the following:.

1. Installed the uBlock Origin extension
2. Checked using the Cookie Remover and can't bypas
3. This site has not been requested already.
4. Visit an article on the site you want to bypass the paywall for and copy the article title.(https://www.chicagobusiness.com/employment/one-three-us-workers-changed-or-lost-jobs-past-year)
5. I opened up a new incognito window (Ctrl+Shift+N on Chrome) or Private window (Ctrl+Shift+P on Firefox), and pasted the article title into Google. 
6. I clicked on the same article from the Google search results page. 
7. **The paywall ad still pops up.**

**Comment by blzuber** [comment]
I'm having the same problem with Crains Chicago Business.

**Comment by iamadamdev** [comment]
You can just disable JS for that site:
![image](https://user-images.githubusercontent.com/36013816/119276295-e126b700-bbce-11eb-86fa-599d9232f3eb.png)

**Comment by iamadamdev** [comment]
Fixed in latest master
