### ISSUE TITLE
New site request: [expansion.com]

### ISSUE THREAD

**Issue by franory** [iamadamdev/bypass-paywalls-chrome#1179]
expansion.com belongs to same group than elmundo.es and it is a popular economic media in Spain.
I have checked it works just putting the same pieces of code already included for elmundo.es

**Comment by iamadamdev** [comment]
Can you submit a PR for this change since you already tested it?

**Comment by franory** [comment]
Hi 
Apologies, never used Git....

**Comment by iamadamdev** [comment]
Added in latest master.
