### ISSUE TITLE
When Chrome is closed, the extension is automatically removed.

### ISSUE THREAD

**Issue by jango0** [iamadamdev/bypass-paywalls-chrome#118]
The extension is removed when you close Chrome. Have to manually install every time.

Bypass paywall version: 1.4.6
Chrome Version 72.0.3626.119 (Official Build) (64-bit)
Developer mode is on

Did not happen with version 1.4.0 on same chrome version.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#installation-instructions

**Comment by jango0** [comment]
I did install according to the instruction. I had been using the extension for over a year without problems. Up until yesterday with the 1.4.6 version.

**Comment by najibkassis** [comment]
Same issue. Started today for me.

**Comment by jango0** [comment]
I found the cause of the problem. I have the bypass paywall folder saved in a local google drive folder. This worked fine for earlier versions, but on 1.4.6 the extension is removed on Chrome close. If the map located in a regular local folder, it works normal.

**Comment by prech** [comment]
> I found the cause of the problem. I have the bypass paywall folder saved in a local google drive folder. This worked fine for earlier versions, but on 1.4.6 the extension is removed on Chrome close. If the map located in a regular local folder, it works normal.

Interestingly, I'm experiencing the same. I use Google Backup & Sync

**Comment by esteves023** [comment]
Got the same issue. It wasn't happening in earlier versions. Do we really have to keep the folder local?

**Comment by iamadamdev** [comment]
Interesting, the only thing I did in 1.4.6 was fix ft.com
Try an earlier version, does it fix it?

**Comment by jango0** [comment]
If there is a way to download earlier versions, I can do some testing. As stated in the original post I had no problems with version 1.4.0 (or earlier).

**Comment by superfreeman1989** [comment]
Same problem. Maybe it's caused by chrome update?

**Comment by jango0** [comment]
I don't think so, because I had no problems with 1.4.0 on the same chrome version. Maybe it's caused by an update to Google Backup & Sync or it might be related to the auto-update feature in the extension introduced in 1.4.4

**Comment by iamadamdev** [comment]
Save the extension folder on your local hard drive.
