### ISSUE TITLE
New site request: https://www.spiegel.de

### ISSUE THREAD

**Issue by lekhoi228** [iamadamdev/bypass-paywalls-chrome#1184]
Confirmed

**Comment by iamadamdev** [comment]
What did you confirm exactly?

**Comment by lekhoi228** [comment]
> What did you confirm exactly?

That the premium articles on this site are impossible to bypass and this site needs to be added to the extension. Under the instruction, you specifically asked that I only need to replace the entire template with the word _Confirmed_, so that's what I did.

Regarding the other foreign news website requests you'd recently closed, RBK (https://en.wikipedia.org/wiki/RBK_Group), Kommersant (https://en.wikipedia.org/wiki/Kommersant), and Göteborgs-Posten (https://en.wikipedia.org/wiki/G%C3%B6teborgs-Posten) are major media outlets internationally known for their unbiased reporting, so I'd be grateful if you could add them to the extension as well.

**Comment by kimkha** [comment]
I can access this article without bypass: https://www.spiegel.de/politik/deutschland/gruene-annalena-baerbock-schlampt-bei-nebeneinkuenften-gefaehrlicher-fehler-im-wahlkampf-a-637d13b5-f141-4844-908a-601075c31b66

Do you have any article that need to bypass?

**Comment by lekhoi228** [comment]
> bypass

All the S+ articles (e.g., https://www.spiegel.de/politik/deutschland/annalena-baerbock-und-olaf-scholz-duett-und-duell-a-11936993-d577-427b-a8c9-00e8c16c74de).

**Comment by lekhoi228** [comment]
> I can access this article without bypass: https://www.spiegel.de/politik/deutschland/gruene-annalena-baerbock-schlampt-bei-nebeneinkuenften-gefaehrlicher-fehler-im-wahlkampf-a-637d13b5-f141-4844-908a-601075c31b66
> 
> Do you have any article that need to bypass?

All the S+ articles (e.g., https://www.spiegel.de/politik/deutschland/annalena-baerbock-und-olaf-scholz-duett-und-duell-a-11936993-d577-427b-a8c9-00e8c16c74de).

**Comment by iamadamdev** [comment]
I guess you failed to read all the instructions.
> If it loads without a paywall you can submit a request and replace the entire template text with the word "Confirmed". Otherwise please do not submit an issue as this extension cannot bypass it either.

Btw, I cannot "magically" bypass any site you want me to, especially if "the premium articles on this site are impossible to bypass".
