### ISSUE TITLE
[not-working]elmercurio.com got clever now

### ISSUE THREAD

**Issue by skoll43** [iamadamdev/bypass-paywalls-chrome#1187]
https://digital.elmercurio.com/ 
| Chrome Versión 90.0.4430.212 (Build oficial) (64 bits) | https://github.com/gorhill/uBlock 1.35.2 |
Example: https://digital.elmercurio.com/2021/05/19/A/A23VARDI
elmercurio.com got clever now

**Comment by iamadamdev** [comment]
Might need to remove it from the list.

**Comment by skoll43** [comment]
they got clever, but not impossible clever, his js for block the pages, and counting them for blocking is pretty basic, im working on it with more time

**Comment by iamadamdev** [comment]
Want to submit a PR?

**Comment by skoll43** [comment]
> Want to submit a PR?

still working on the <next page> that breaks with the local override,
