### ISSUE TITLE
Wall Street Journal stopped working

### ISSUE THREAD

**Issue by davidglavas** [iamadamdev/bypass-paywalls-chrome#1189]
Try opening an article on https://www.wsj.com/?mod=nav_top_section in chrome. They are blocked. The plugin no longer works for WSJ.

**Comment by goL-prog** [comment]
Same here. In Chrome-Win10.
BTW, thetimes.co.uk is working fine again.

**Comment by nizishirin** [comment]
yep. WSJ is dead.

**Comment by wigguslong** [comment]
Ditto. WSJ not working in Chrome.

**Comment by BambooFlower** [comment]
Same here in Firefox-Win10. I also always get redirected to the AMP version

**Comment by jeepy321** [comment]
Can confirm WSJ not working in Chrome on Mac

**Comment by iamadamdev** [comment]
I've confirmed it's not working.

**Comment by hl2533** [comment]
https://www.wsj.com/amp/articles/hamas-fires-missile-at-israeli-military-bus-at-border-11621508840?mod=hp_lead_pos1 -- i managed to get the full article in that weblink or any weblink by typed in wsj.com into the custom sites tab and it still works!

**Comment by cstsang** [comment]
strange, it started working again for me, but the article is in a narrow column, and the back button doesn't work

**Comment by iamadamdev** [comment]
Looks like it's working again.

**Comment by catdog94** [comment]
It's working now for me in Chrome.
