### ISSUE TITLE
Delfi.ee not working anymore

### ISSUE THREAD

**Issue by MJ1400** [iamadamdev/bypass-paywalls-chrome#1191]
1. Make sure uBlock Origin is installed.
Installed with custom filters added
2. Chrome or Firefox?
Chrome
3. Paste the article URL for the site you are having issues with.
https://forte.delfi.ee/artikkel/93489135/intervjuu-vastutav-asekantsler-kalle-killar-mis-juhtus-vaktsineerimisele-paasemisega
4. Describe the issue.
Extension isn't removing paywall from Delfi

**Comment by iamadamdev** [comment]
Might be behind a hard paywall now.

**Comment by iamadamdev** [comment]
Removed in latest master.

**Comment by laur89** [comment]
The logic was still valid. @MJ400 is referring to hard paywall you can't solve with js.
