### ISSUE TITLE
thetimes.co.uk no longer working

### ISSUE THREAD

**Issue by octavedo** [iamadamdev/bypass-paywalls-chrome#1192]
https://www.thetimes.co.uk/article/the-sunday-times-rich-list-2021-revealed-b3fcwcvx5

**Comment by iamadamdev** [comment]
Still works for me
![image](https://user-images.githubusercontent.com/36013816/119096508-89b6fa00-b9c8-11eb-9b60-3dc6ae5a6e69.png)
