### ISSUE TITLE
Medium stopped working

### ISSUE THREAD

**Issue by 4A47** [iamadamdev/bypass-paywalls-chrome#1194]
Chrome
https://medium.datadriveninvestor.com/how-to-quickly-embed-python-in-your-c-application-23c19694813

**Comment by iamadamdev** [comment]
![Uploading image.png…]()

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/119213983-1f5d9280-ba78-11eb-9f7d-2c313e52f5ed.png)
