### ISSUE TITLE
The Daily Telegraph not working

### ISSUE THREAD

**Issue by piketon** [iamadamdev/bypass-paywalls-chrome#1196]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
URL?

**Comment by piketon** [comment]
https://www.dailytelegraph.com.au/

**Comment by iamadamdev** [comment]
Looks like the premium articles are behind a hard paywall now. For the free articles you can just uncheck daily telegraph.

**Comment by iamadamdev** [comment]
Try latest master.

**Comment by piketon** [comment]
Works great. Thanks for your hard work.
