### ISSUE TITLE
La Repubblica not working anymore

### ISSUE THREAD

**Issue by marcocalm** [iamadamdev/bypass-paywalls-chrome#1198]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###
Haven't seen it reported
Ublock Origin is installed
Firefox
Addon version 1.7.9
https://www.repubblica.it/cronaca/2021/05/27/news/stresa_chi_sono_i_tre_indagati-302947093/?ref=RHTP-BH-I0-P1-S1-L
It used to work in the past, but it stopped working a few weeks ago.

**Comment by iamadamdev** [comment]
It's fixed in latest master (Chrome). You can build the FF version yourself or wait for the next release.
