### ISSUE TITLE
WashingtonPost just changed things and doesn't seem to work anymore

### ISSUE THREAD

**Issue by Malrama** [iamadamdev/bypass-paywalls-chrome#1200]
Hello everyone.

I'm using the lastest version of Chrome with this plugin and it seems like the washingtonpost just changed some thing and this addons is not working on the page anymore.

Whenever I go to that webside and try to open a page, [Just an example](https://www.washingtonpost.com/world/europe/putin-daughter-russia-secret/2021/06/05/a5524c98-c2eb-11eb-89a4-b7ae22aa193e_story.html), then it won't let me read it and asks for a subscription.

The icon of this pugin on the top right shows a blue [on] but it doesn't seem to work.

Just letting you guys know. Thank you

Edit: It seems like some articles work and some don't. That article that I linked is an expample of one that doesn't work.

**Comment by madhtr** [comment]
Same for me. Not working on WAPO for the past couple days.

**Comment by iamadamdev** [comment]
Url of article?

**Comment by iamadamdev** [comment]
Still working for me:
![image](https://user-images.githubusercontent.com/36013816/120912856-9afa3a80-c647-11eb-818b-f4bbfc7459ce.png)

**Comment by iamadamdev** [comment]
Works fine for me too.

**Comment by bossegranat** [comment]
Works for me to. What's the current settings of your extension? Do other sites work to?

**Comment by madhtr** [comment]
Thanks for the reply …  See screen shots. Seem like if I remove it and drop it back in sometimes it works again. Then when I close and open my browser it doesn’t work?
