### ISSUE TITLE
The Times (thetimes.co.uk) is not working

### ISSUE THREAD

**Issue by TheAA89** [iamadamdev/bypass-paywalls-chrome#1201]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###
1. No, the issue has not yet been reported.
2. uBlock origin is installed
3. Google Chrome	91.0.4472.77 (Official Build) (64-bit) (cohort: Stable)
Revision	1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS	Windows 10 OS Version 1909 (Build 18363.1500)
JavaScript	V8 9.1.269.28
4. https://www.thetimes.co.uk/article/palace-sends-for-prince-william-to-rescue-union-tmmqlbh5b
    https://www.thetimes.co.uk/article/arsenal-turn-to-ruben-neves-after-odsonne-edouard-disappointment-sp0lm98qx

5. The bypass for the thetimes.co.uk seems to be broken. I have tried clearing cookies using cookie remover as well as unchecking the "General Paywall bypass" option, but it doesn't work. I have also tried disabling uBlock origin in combination with the other two actions, but this doesn't work either.

I am using the v1.7.9 version of the extension.

**Comment by TheAA89** [comment]
The issue seems to be that the website will block you if you have a UK IP address. The extension works once if you use a VPN set to another country (confirmed working with the VPN set to France and the US). However, I've refreshed when switching to a third countries IP address, and the paywall is back. I switched VPNs (country is still set to US) and it now works for a specific article, but once I tried to read another article, the paywall comes back.

I think they're using a script to log the IP addresses of extension users who visit the site - they obviously know how to detect the extension and they seem to allow access for a single article per IP address. This all points to them logging IP addresses either for analytical purposes or for some kind of copyright enforcement.

The two VPNs I used were TouchVPN and Betternet. These are both free VPNs, so it would be prudent to disable them (in chrome://extensions) after you've finished using them so as to minimise data logging and tracking.

**Comment by goL-prog** [comment]
Near-identical experience as @TheAA89. Paid VPN use allows access to the site once or twice before the paywall kicks in. Also noticed that site access to a UK IP address may return at random after several hours' absence (even without VPN) for a handful of articles and then the paywall kicks in again.

**Comment by mdwchile** [comment]
I find the paywall is kicking in inconsistently, but it is seemingly not related to a UK IP address, or any specific country.

Access comes and goes, and I can't currently see any consistency in the behaviour.

**Comment by sj919** [comment]
This issue was raised a few times a couple of weeks ago, but was left unsolved

**Comment by stephanatgmx** [comment]
Using Linux (Ubuntu 20.04.2 LTS) and Google Chrome 91.0.4472 (Official build) (64-bit) made no difference. Paywall still active.

**Comment by Mironov-Alexander** [comment]
The plugin also stopped working with thetimes.co.uk (I am using Opera 76.0.4017.177)

**Comment by lowgold** [comment]
Some more info.... I use the same logic within my own scraper (java) bot.. i.e. google referer.. and it also failed randomly in the same manner as above. However, now it fails every time. I also put my scraper in front of a http proxy -> socks5 proxy -> TOR.. which ends up using a random IP each time.. and that also fails.

Maybe they are doing something like this?

https://developers.google.com/search/blog/2006/09/how-to-verify-googlebot

**Comment by gcohara** [comment]
I've also been unable to read articles on thetimes.co.uk for some time.

**Comment by iamadamdev** [comment]
Seems to be a hard paywall now?

**Comment by jimmylad** [comment]
I'm not in the UK and it's not working.

**Comment by iamadamdev** [comment]
Removing as it seems to be behind a hard paywall.
