### ISSUE TITLE
American Banker is not working

### ISSUE THREAD

**Issue by catdog94** [iamadamdev/bypass-paywalls-chrome#1204]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###
Here's an example article: https://www.americanbanker.com/news/investors-flock-to-bank-stocks-anticipating-higher-interest-rates

It doesn't work in Chrome - only first 9 lines of article are visible due to paywall. Same with other articles. uBlock Origin is installed.

**Comment by iamadamdev** [comment]
I was able to open 10+ articles w/o issue. Maybe also try manually [removing cookies](https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce)?
