### ISSUE TITLE
Crains chicagobusiness.com not working on Chrome

### ISSUE THREAD

**Issue by fritzhurst** [iamadamdev/bypass-paywalls-chrome#1205]
uBlock Origin is installed.

Chrome

https://www.chicagobusiness.com/health-pulse/medline-buyout-could-set-wave-private-equity-investment-cook-countys-vaccination

You must be a subscriber pop up blocks content.

###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
Still working for me.
