### ISSUE TITLE
New site request: https://towardsdatascience.com

### ISSUE THREAD

**Issue by kondakov28** [iamadamdev/bypass-paywalls-chrome#1206]
This has a paywall ad pop up.

I have done the following:

1. Installed the uBlock Origin extension
2. Checked using the Cookie Remover and can't bypass
3. This site has not been requested already.
4. Visit an article on the site you want to bypass the paywall for and copy the article title. 
(https://towardsdatascience.com/5-steps-to-develop-unique-data-science-project-ideas-6c2b3a0014b)
5. I opened up a new incognito window (Ctrl+Shift+N on Chrome) or Private window (Ctrl+Shift+P on Firefox) and pasted the article title into Google.
6. I clicked on the same article from the Google search results page.
7. The paywall ad still pops up.

**Comment by iamadamdev** [comment]
I'm not seeing any paywall. Was able to open 5+ articles.

**Comment by sztoo** [comment]
The paywall comes after you have read up to the monthly limit. There's another well-supported [extension](https://github.com/manojVivek/medium-unlimited) that specifically targets Medium (which is what towardsdatascience is based of).

**Comment by iamadamdev** [comment]
Mine seems to stick at "You have 2 free member-only stories left this month"

**Comment by sztoo** [comment]
I'm guessing that if one doesn't have an account / not signed in, it might not work? (Yet to test this theory)
