### ISSUE TITLE
NZ herald not working

### ISSUE THREAD

**Issue by steelep** [iamadamdev/bypass-paywalls-chrome#1207]
1. Done
2. Yes installed
3. Chrome
4. https://www.nzherald.co.nz/business/matthew-hooton-government-data-says-covid-vaccine-to-run-out-on-monday/SYV3QVBGOYWQ7NSVIU5XIK7QRM/
5. No content loading

**Comment by iamadamdev** [comment]
Still working for me.

**Comment by steelep** [comment]
Weird, I deleted all my cookies and upgraded my version... seems to have fixed. great product Adam. Cheers
