### ISSUE TITLE
Add to Yandex Browser for Android 

### ISSUE THREAD

**Issue by Pidus** [iamadamdev/bypass-paywalls-chrome#121]
Yandex Browser for Android supports Chrome extensions. Currently I follow the standard (Chrome's) procedure to install this extension. But, Yandex also has a few extensions available to install within the browser with no hassle (Pocket, LastPass, SaveFrom.net etc.). Please consider building this extension for Yandex Android. 
Thank you.

**Comment by JackChen007** [comment]
It works for Yandex. 

Procedures: 
1. download the zip. 
2. unzip the zip file.
3 open chrome://extension 
4. load from unpacked 
5 works.
