### ISSUE TITLE
Not on Chrome Web Store?

### ISSUE THREAD

**Issue by RVRX** [iamadamdev/bypass-paywalls-chrome#1210]
Why is the extension not on the chrome web store? If its not an issue of them not accepting/approving it (I know they are also rather slow to approve compared to AMO), i'd be willing to submit the extension.

**Comment by kimkha** [comment]
FYI https://github.com/iamadamdev/bypass-paywalls-chrome/issues/25

But I think you could try.

**Comment by RVRX** [comment]
Ah thanks. *Weird though, I searched for issues with chrome web store in them and didn't see that one*

**Comment by RVRX** [comment]
Ah thanks. *Weird though, I searched for issues with chrome web store in them and didn't see that one*
