### ISSUE TITLE
Bypass Paywalls causes reload loop

### ISSUE THREAD

**Issue by ballo** [iamadamdev/bypass-paywalls-chrome#1215]
This appears to be a problem when using this extension with the Kiwi Browser as it loads the crappy AMP version of the article (despite being in Desktop mode) which then causes this extension to go absolutely bonkers:
https://www.spectator.co.uk/article/laurel-hubbard-is-the-beginning-of-the-end-of-women-s-sports?

**Comment by iamadamdev** [comment]
1. Try turning off Bypass Paywalls for that site.
2. Try Chrome or Firefox.

**Comment by ballo** [comment]
Kiwi is currently the only android browser that supports extensions
