### ISSUE TITLE
Medium.com not working

### ISSUE THREAD

**Issue by imirzadeh** [iamadamdev/bypass-paywalls-chrome#1217]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
Already reported before but closed.
2. Make sure uBlock Origin is installed.
Installed
3. Chrome or Firefox?
Firefox
4. Paste the article URL for the site you are having issues with.
https://medium.com/swlh/mediums-top-10-most-followed-and-active-publications-3cebb3e2da69

5. Describe the issue.
The extension doesn't work for me on medium.com and some of the related websites. I'm using v1.7.9b Firefox. 
###

**Comment by iamadamdev** [comment]
Fixed in latest master.
