### ISSUE TITLE
New site request: Medium-based publications

### ISSUE THREAD

**Issue by imirzadeh** [iamadamdev/bypass-paywalls-chrome#1218]
First of all, thank you for the great extension.

Some Medium.com publications have their own domain. Sometimes they are accessible from Medium sometimes they are not. Examples of popular publications

- https://betterhumans.pub/ (https://medium.com/better-humans)
- https://uxdesign.cc
- https://betterprogramming.pub

Since all of these websites are using the Medium platform and don't have a hard paywall, I suppose it should be possible to add them to the list of supported websites.

I found a source that includes the popular publishers on Medium that might be helpful to you:
https://getgist.com/top-50-medium-publications/

**Comment by iamadamdev** [comment]
If the current bypass works feel free to submit a PR to add those sites. However I'm not seeing consistent behavior on medium sites.

**Comment by kimkha** [comment]
Curious, if that's so common, why don't we allow Medium-backed websites to work with `Custom sites` section?
