### ISSUE TITLE
New site request: thedispatch.com

### ISSUE THREAD

**Issue by JackTRametta** [iamadamdev/bypass-paywalls-chrome#1219]
Hello! 

I'd like to be able to read all content from The Dispatch, here's an example of a paywalled piece: https://capitolism.thedispatch.com/p/antitrust-is-so-hot-right-now-three

Thanks!

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
