### ISSUE TITLE
Please add sfchronicle.com

### ISSUE THREAD

**Issue by prodan1234** [iamadamdev/bypass-paywalls-chrome#122]
Please consider supporting ```sfchronicle.com``` Thanks for all the work!

**Comment by iamadamdev** [comment]
I loaded 20+ articles from there without any problems. Do you have uBlock Origin enabled?
What article are you seeing a paywall on?

**Comment by prodan1234** [comment]
I am running uBlock Origin. The article is ```https://www.sfchronicle.com/education/article/Central-Valley-school-district-won-t-ban-13676868.php?src=hp_totn``` 

Here is a screenshot https://imgur.com/a/ZCKhpVS 

Chrome 72.0.3626.121 with uBlock Origin 1.18.4 and Bypass Paywalls 1.4.6

**Comment by iamadamdev** [comment]
I can load that article fine. Try manually removing sfchronicle.com cookies `chrome://settings/siteData?search=cookies` and see how many articles you must read before you get the paywall again.

**Comment by prodan1234** [comment]
After removing all sfchronicle-related cookies, I was able to read 3 before hitting the paywall. Are you running any other additional filter listes on uBlock Origin?

**Comment by iamadamdev** [comment]
I was able to load 10+ articles again today, no bypass needed. Just uBlock Origin installed, no special filters.

**Comment by prodan1234** [comment]
Still getting this https://imgur.com/a/ypScJFn

**Comment by iamadamdev** [comment]
Added in v1.4.8
