### ISSUE TITLE
Washington Post Not Working

### ISSUE THREAD

**Issue by 13regent** [iamadamdev/bypass-paywalls-chrome#1221]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported. (Previously Reported)
2. Make sure uBlock Origin is installed. (Yes)
3. Chrome or Firefox? (Chrome)
4. Paste the article URL for the site you are having issues with. ( https://www.washingtonpost.com/local/legal-issues/trump-taxes-financial-statements-hearing/2021/07/01/78166a2c-da9f-11eb-9bbb-37c30dcf9363_story.html ). This link is now working. This one now does not: https://www.washingtonpost.com/national-security/federal-executions-halted-merrick-garland/2021/07/01/74dfb660-dac7-11eb-bb9e-70fda8c37057_story.html ![Screenshot 2021-07-02 011316](https://user-images.githubusercontent.com/28539673/124229201-debf5300-dad2-11eb-8e74-60cf6aab73ca.jpg)
5. Describe the issue. (Subscribe to continue reading popup, and cant read page.)
###

**Comment by Attis913** [comment]
Same thing here. The odd thing, though, is that it works fine on my tablet.

**Comment by 13regent** [comment]
Now the previous link works, and most others don't. Not sure what is going on, but the Washington Post works fine in Firefox with the addon.

**Comment by 13regent** [comment]
The previous link now works and most others don't on Washington Post. All links work in Firefox with the addon.

**Comment by cedo2122** [comment]
This article is not working:  https://www.washingtonpost.com/nation/2021/07/02/crestview-north-miami-beach-evacuation/

![image](https://user-images.githubusercontent.com/60177920/124342841-e25ae480-db7b-11eb-898d-8b27e117fdd4.png)

The above two Trump articles are both working for me. I have been having problems with just WaPo in Bypass Paywalls for weeks now.

**Comment by iamadamdev** [comment]
Try latest master

**Comment by iamadamdev** [comment]
No can longer repro the issue
