### ISSUE TITLE
Why not Android Firefox?

### ISSUE THREAD

**Issue by sinthome** [iamadamdev/bypass-paywalls-chrome#1226]
Hi, I know there is a work-around for people willing to install the FF nightly build. These days I have to use the FF stable release and I really miss having Bypass on my phone. Is there any hope you will make it available for us sometime?

**Comment by iamadamdev** [comment]
Please ask Mozilla. You can try downloading it on your phone https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-firefox/
(haven't tried)
