### ISSUE TITLE
thetimes.co.uk

### ISSUE THREAD

**Issue by LukaZr8** [iamadamdev/bypass-paywalls-chrome#1230]
Site not working

**Comment by iamadamdev** [comment]
Not a supported site. https://github.com/iamadamdev/bypass-paywalls-chrome#bypass-the-following-sites-paywalls-with-this-extension

**Comment by RVRX** [comment]
<img width="43" alt="image" src="https://user-images.githubusercontent.com/45409688/132439338-7865da39-1ad1-412e-bd31-2804a085c31f.png">

The extension indicator does turn on when visiting [https://www.thetimes.co.uk/](https://www.thetimes.co.uk/) though. Not sure why as I can't find any reference to it in the extension code?

**Comment by iamadamdev** [comment]
You might be on an older version when it was part of Bypass Paywalls.
