### ISSUE TITLE
Cannot access FT.com at all

### ISSUE THREAD

**Issue by VeryNaughtyCat** [iamadamdev/bypass-paywalls-chrome#124]

**Comment by JackChen007** [comment]
I also can't access ft.com, according to README, it doesn't work for ft.com.

**Comment by JackChen007** [comment]
I tried the bypass-paywall-firefox version, it worked for ft.com on Firefox.

**Comment by VeryNaughtyCat** [comment]
Thanks for that. The Firefox browser works for me too.

**Comment by iamadamdev** [comment]
try re-installing? ft still works fine for me on Chrome.

**Comment by stereorad** [comment]
It's working fine here. Make sure you don't have ad blocking or script blocking enabled here. At times it conflicts. Make sure the browser is set to accept all cookies as well.

**Comment by JackChen007** [comment]
@VeryNaughtyCat @iamadamdev 

Sorry. I found the problem. I still used the 1.0.6 version. Now I update the 1.4.6 version and it works find for Chrome on PC and Yandex on Android. 

Thanks.
