### ISSUE TITLE
Cannot access WSJ.com at all

### ISSUE THREAD

**Issue by soniariv** [iamadamdev/bypass-paywalls-chrome#128]
Chrome 72.0.3626.121 32 bit w/ bypass-paywalls-chrome 1.3.7.

**Comment by soniariv** [comment]
![WSJ grounding  ko](https://user-images.githubusercontent.com/22412790/54188998-29a39f80-44b1-11e9-980e-662e06be2fc6.jpg)

**Comment by iamadamdev** [comment]
Please upgrade to the latest version.

**Comment by soniariv** [comment]
Thanks! v 1.4.6 now it works.
However with new Chrome Version 73.0.3683.75 (Official Build) (32-bit) at the next session, now the extension disappears completely: it is not simply disabled as sometimes occurred previouslty; it is systematically trashed away by Chrome and I need to drag&drop the bypass folder again in order to install for each session.
