### ISSUE TITLE
New site request: Saturday Evening Post Archive

### ISSUE THREAD

**Issue by solitudeenbleu** [iamadamdev/bypass-paywalls-chrome#131]
https://www.saturdayeveningpost.com

**Comment by iamadamdev** [comment]
What article are you seeing a paywall on? I loaded 10+ articles without seeing a paywall.

**Comment by solitudeenbleu** [comment]
Hi Adam

Doesn't seem to work with the archive section:

https://www.saturdayeveningpost.com/issues/  (pick an issue in the1960s for
example)

Thanks

S

**Comment by iamadamdev** [comment]
Those are premium articles, it won't work for those, you will need to pay.
