### ISSUE TITLE
New Site Request: Welt.de

### ISSUE THREAD

**Issue by hhhc** [iamadamdev/bypass-paywalls-chrome#134]
URL: www.welt.de
Any article with the following icon is behind paywall.

![Bildschirmfoto 2019-03-20 um 12 28 03](https://user-images.githubusercontent.com/961087/54681061-bc74b780-4b0b-11e9-9892-d2918c7c16ba.png)

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
