### ISSUE TITLE
script for Safari?

### ISSUE THREAD

**Issue by superfreeman1989** [iamadamdev/bypass-paywalls-chrome#135]
Is it possible to have this extension as a script so Safari can load it? Thanks.

**Comment by iamadamdev** [comment]
Not in the works at the moment.

**Comment by thekiefs** [comment]
@iamadamdev I would pay to see this ported to Safari if possible!

**Comment by magnolia1234** [comment]
On iOS you can use Shortcuts scripts, I guess.
