### ISSUE TITLE
Barrons.com not working

### ISSUE THREAD

**Issue by msft013** [iamadamdev/bypass-paywalls-chrome#136]
Using 1.4.7. Tried unchecking it and refreshing the page but it didn't work.

**Comment by iamadamdev** [comment]
Which article?

**Comment by 420pitts** [comment]
Something changed because it seems to be working again.

**Comment by 420pitts** [comment]
This isn't working again. Using 1.5.0

**Comment by iamadamdev** [comment]
Fixed in v1.5.1

**Comment by msft013** [comment]
Yep it works
