### ISSUE TITLE
New site request: NYMag, and its sister sites

### ISSUE THREAD

**Issue by sjeble** [iamadamdev/bypass-paywalls-chrome#137]
http://nymag.com/
And all its subsidiary sites listed on the header, which a subscription includes access to: The Cut, Vulture, Grub Street, Intelligencer, The Strategist

**Comment by iamadamdev** [comment]
nymag.com added in v1.4.8

**Comment by sjeble** [comment]
I'm still getting paywalled by The Cut, Vulture, etc.
