### ISSUE TITLE
New Site Request: The Globe and Mail

### ISSUE THREAD

**Issue by KWTSOFT** [iamadamdev/bypass-paywalls-chrome#139]
https://www.theglobeandmail.com/

Thank you

**Comment by superfreeman1989** [comment]
^ This. This site is a soft paywall.

**Comment by iamadamdev** [comment]
Added in v1.4.8

**Comment by superfreeman1989** [comment]
> Added in v1.4.8

Some articles still blocked by script. For example:
https://www.theglobeandmail.com/investing/markets/inside-the-market/article-these-four-canadian-market-sectors-deserve-credit-for-their/
Full article loads then seemingly a script disables it.
