### ISSUE TITLE
Bypass paywalls for Android

### ISSUE THREAD

**Issue by sdean7855** [iamadamdev/bypass-paywalls-chrome#141]
Am running V6 on a Samsung Note 4, following installation institutions on Github
, I enter chrome://extensions, but it isn't found. Doesn't BP work on Android? Or is AV6 too back level

**Comment by iamadamdev** [comment]
Try looking through Settings or Options, does it say Extensions anywhere? You just need to get to that page.

**Comment by sdean7855** [comment]
It appears that you cannot add extensions to Android mobile Chrome.  You
can perhaps do so with Russian Chrome clone Yandrex,but I'm wary of Russian
software. Also you can only do that with apps on Chrome Web Store. I have
been unable to find a Chrome extensions directory.  But thanks!

**Comment by JackChen007** [comment]
@sdean7855 
Yes, You can do this on Yandex Android.  It works. Or use the Bypass-paywall-Firefox on Firefox Android.

**Comment by iamadamdev** [comment]
Chrome won't work, but Firefox on Android should.
