### ISSUE TITLE
Please add a Patreon link

### ISSUE THREAD

**Issue by lukepalmer** [iamadamdev/bypass-paywalls-chrome#145]
Your project is fantastic.

**Comment by iamadamdev** [comment]
It's okay, I am happy to work on it for free... for now.

**Comment by sztomi** [comment]
Please don't add a Patreon link or any means of payment. For people who are willing to pay for accessing the content, it's better for them to pay the content producers. Otherwise users of this extension won't get anything to bypass.

**Comment by s-mtz** [comment]
honestly is there a way to add it for the patreon too ?
