### ISSUE TITLE
It can't work on The New York Times

### ISSUE THREAD

**Issue by StephenAnboer** [iamadamdev/bypass-paywalls-chrome#148]
It can't work on The New York Times

**Comment by iamadamdev** [comment]
Works fine for me. Which article are you having trouble with?
1. Make sure NYT is checked in options.
2. Do you have uBlock Origin installed? 
3. Are you located in the EU?

**Comment by danwholikespie** [comment]
Not working on NYT for me, either. I have uBlock Origin installed, and I'm located in the US.

**Comment by StephenAnboer** [comment]
It works when I reset it!!!!! Nice

**Comment by ideologysec** [comment]
what did you reset? the extension? your browser? the cache?

**Comment by StephenAnboer** [comment]
> what did you reset? the extension? your browser? the cache?

the extension and the uBlock Origin

**Comment by iamadamdev** [comment]
What article isn't working for you?

**Comment by danwholikespie** [comment]
Honestly I don't remember. I reset both the extension and uBlock Origin and NYT works fine now.
