### ISSUE TITLE
please help  bypass-paywalls for indonesia  news wesbite

### ISSUE THREAD

**Issue by murad2019** [iamadamdev/bypass-paywalls-chrome#150]
Is there any way to bypass this Indonesia websites :

www.thejakartapost.com

I tried it doesn't work  :( 

![bypass](https://user-images.githubusercontent.com/49304034/55613933-75025280-57be-11e9-9e6a-45d69db8ae79.png)

**Comment by iamadamdev** [comment]
Premium articles are behind a hard paywall and cannot be bypassed.
