### ISSUE TITLE
bypass paywalls chrome -  Please add The Australian

### ISSUE THREAD

**Issue by Yakcall** [iamadamdev/bypass-paywalls-chrome#152]
Hi, just tried your bypass in Chrome to access a paywall article on The Australian and it worked when I googled the title of the article and open it. 
Matildas racing the clock in Women’s World Cup preparations
allowed me to open this link in Google to read the article. https://www.theaustralian.com.au/sport/football/matildas-racing-the-clock-in-womens-world-cup-preparations/news-story/566ff3ee9a158d9167c836335573a71f

**Comment by iamadamdev** [comment]
Added
