### ISSUE TITLE
Not working while I try to The Economist

### ISSUE THREAD

**Issue by Pariyara** [iamadamdev/bypass-paywalls-chrome#153]
On my mac, using Chrome Version 73.0.3683.103 (Official Build) (64-bit) 
Activated uBlock origin, is in Developer mode. But each time I refresh, paywall pops up. 

I checked other queries and tried doing the suggestions, still not working. What should I do?
<img width="1418" alt="Screen Shot 2019-04-07 at 12 58 44 PM" src="https://user-images.githubusercontent.com/48947819/55680107-e7953e80-5934-11e9-9589-aae3b05dfae6.png">

**Comment by iamadamdev** [comment]
Economist not working properly as of late is a known issue. For now I would suggest refreshing and hitting ESC as the article loads.

**Comment by jbschaff** [comment]
Refresh + ESC works for me. Thanks for your work!! 

> Economist not working properly as of late is a known issue. For now I would suggest refreshing and hitting ESC as the article loads.

[bitmoji](https://render.bitstrips.com/v2/cpanel/46cf02ca-eacf-4047-8bea-ec1cb5acbc87-dbd210a3-a0d1-4a7e-abe5-53e60f9e4304-v1.png?transparent=1&palette=1&width=246)

**Comment by iamadamdev** [comment]
Fixed in latest version. Basically it disables javascript for the site. The downside is the front page images don't always load. You could always uncheck the site, reload, and recheck before you click into an article.

**Comment by sjeble** [comment]
1.5.1, I'm still having this problem with The Economist

**Comment by iamadamdev** [comment]
Works fine for me. Make sure it is checked in options.

**Comment by magnolia1234** [comment]
uMatrix blocks paywall by default.
