### ISSUE TITLE
ESPN+

### ISSUE THREAD

**Issue by nyydynasty** [iamadamdev/bypass-paywalls-chrome#155]
if you can add ESPN+, that would be great.  Here's an example article:
http://www.espn.com/fantasy/baseball/insider/story/_/id/26432261/fantasy-baseball-prospect-rankings-updated-top-10-2019

Thanks

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
