### ISSUE TITLE
Some articles still blocked by script in theglobeandmail.com

### ISSUE THREAD

**Issue by superfreeman1989** [iamadamdev/bypass-paywalls-chrome#157]
Some articles still blocked by script. For example:
https://www.theglobeandmail.com/investing/markets/inside-the-market/article-these-four-canadian-market-sectors-deserve-credit-for-their/
Full article loads then seemingly a script disables it.

**Comment by iamadamdev** [comment]
That doesn't work in incognito either. Need to figure out which script to block.

**Comment by superfreeman1989** [comment]
BTW I can actually view the article on that site by enabling reader mode on safari. The reader mode instantly loads before the script hides the article.

**Comment by iamadamdev** [comment]
Is it working in v1.4.9 now?
