### ISSUE TITLE
New Site request: Australian Financial Review, American Banker

### ISSUE THREAD

**Issue by Saigon678** [iamadamdev/bypass-paywalls-chrome#158]
https://www.afr.com

https://www.americanbanker.com/

PS: Thanks for adding fn london. 

There is a weakness in the source code of American Banker. If you go to an article there will be a code "<div class="embargo-content">", if you delete "embaro-content", the whole article is visible.  Wondering if you can add it the bypass-paywalls-chorme to make the process automactic. I am not a programmer so I don't know if this is possible. Thanks if it does work with this method or you find another way to do this or you can't but try.

**Comment by iamadamdev** [comment]
How are you manually doing it? "delete element" in Chrome for "embargo-content" just hides the paywall, but the article still doesn't show up.

**Comment by iamadamdev** [comment]
Added afr.com in latest version.

**Comment by Saigon678** [comment]
I don't know how to explain it more precisely and proficient. So I made a video to show what i did.

https://youtu.be/HmuGQb9m0vE

**Comment by Saigon678** [comment]
PS. thanks for adding afr.com

**Comment by iamadamdev** [comment]
Added americanbanker.com
