### ISSUE TITLE
New site request: Le Monde (FR)

### ISSUE THREAD

**Issue by alanscandrett** [iamadamdev/bypass-paywalls-chrome#159]
Article still present a paywall after a few paragraphs, it would be great to see this added to your list!

e.g. https://www.lemonde.fr/afrique/article/2019/04/05/mustapha-bouchachi-figure-de-la-contestation-algerienne_5446152_3212.html

![image](https://user-images.githubusercontent.com/23227595/55691527-45339480-59e2-11e9-85db-7cf81eefe667.png)

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by iamadamdev** [comment]
That's a hard paywall.
