### ISSUE TITLE
Boston Herald Newspaper

### ISSUE THREAD

**Issue by fdaveta** [iamadamdev/bypass-paywalls-chrome#162]
The Boston Herald (bostonherald.com) recently started their subscription service and unlike the Globe, it doesn't allow any free articles. The program works great on the Globe but not at all on the Herald.

**Comment by iamadamdev** [comment]
I loaded 10+ articles w/o seeing any paywall. Do you have uBlock Origin installed?

**Comment by fdaveta** [comment]
I have Ad Blocker Plus if that’s what you mean.


--------------------------------------------------------------------------------

**Comment by iamadamdev** [comment]
delete that and use uBlock Origin
then manually remove bostonherald.com cookies

**Comment by fdaveta** [comment]
Works like a charm...thanks for your help!!! I’m 70 years old so your patience is greatly appreciated, as well...lol.


--------------------------------------------------------------------------------
