### ISSUE TITLE
News Site Request: SLTrib

### ISSUE THREAD

**Issue by scootsy** [iamadamdev/bypass-paywalls-chrome#165]
The extension works fantastically! Is there any way to include functionality for sltrib.com?

Thanks.

**Comment by iamadamdev** [comment]
I would try an extension like https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg
Once you hit the limit, just click the cookie icon to remove cookies for that site and refresh the page.
