### ISSUE TITLE
https://www.law360.com

### ISSUE THREAD

**Issue by Daniel56hudd** [iamadamdev/bypass-paywalls-chrome#169]

**Comment by mecampbellsoup** [comment]
Is it not possible to add support for this site? Any background? I could open a PR but wanted to ask if anyone knew more first @iamadamdev @Daniel56hudd

**Comment by magnolia1234** [comment]
Site seems to have a hard paywall.

**Comment by mecampbellsoup** [comment]
I see; what distinguishes hard from soft paywall @magnolia1234 ? Want to see if theblockcrypto.com could be added to this library...

**Comment by magnolia1234** [comment]
Subscription only too.

**Comment by daledali** [comment]
bump
