### ISSUE TITLE
Does not work with Chrome 67.0.3396.87

### ISSUE THREAD

**Issue by zxcvbn97** [iamadamdev/bypass-paywalls-chrome#17]
Hi there,

Thanks for the fantastic extension. however, it does not work with Chrome 67.
Can you pl take a look?

**Comment by ShintoPlasm** [comment]
Not sure this is a Chrome 67 issue specifically. BPPW seems to no longer work with Opera 53.0.2907.99, which is still based on Chromium 66. But I can confirm that the extension is currently ineffective in Chrome-ish browsers on my MacBook Pro.

The Firefox extension seems to work just fine for me.

**Comment by iamadamdev** [comment]
Tested on Chrome Version 67.0.3396.87 (Official Build) (64-bit) running on Windows and it worked fine. Try clearing cookies and/or removing and re-adding plugin.

**Comment by iamadamdev** [comment]
Make sure to have 'uBlock Origin' installed too
