### ISSUE TITLE
Could not bypass The independent/ The Hindu

### ISSUE THREAD

**Issue by zeon2017** [iamadamdev/bypass-paywalls-chrome#172]
Couldn't bypass the Paywalls of the following websites

1) The Independence: https://www.independent.co.uk
![Independence](https://user-images.githubusercontent.com/27505388/56364357-f5d43c00-620b-11e9-9679-53b4451a4c11.JPG)

2) The Hindu: https://www.thehindu.com/
![The Hindu](https://user-images.githubusercontent.com/27505388/56364563-785cfb80-620c-11e9-813c-72b50b2bf78d.JPG)

Kindly Help, Thank you <3

**Comment by pasterios** [comment]
I also could not bypass the paywall at the independent.

**Comment by iamadamdev** [comment]
? Those sites weren't on the list of supported sites anyway..

**Comment by zeon2017** [comment]
Sorry, this was meant to be a request to add those sites.
