### ISSUE TITLE
mueller hins at national security

### ISSUE THREAD

**Issue by czsmith** [iamadamdev/bypass-paywalls-chrome#173]
Following article https://www.nytimes.com/2019/04/19/opinion/mueller-report-trump-counterintelligence.html

NY Times seems to have new paywall structure.  In Incognito mode, I seemed to get a reset on the number of "free" articles.  Otherwise, no access.
[mueller 1.pdf](https://github.com/iamadamdev/bypass-paywalls-chrome/files/3099556/mueller.1.pdf)
[Mueller 2.pdf](https://github.com/iamadamdev/bypass-paywalls-chrome/files/3099557/Mueller.2.pdf)
[Mueller 2.pdf](https://github.com/iamadamdev/bypass-paywalls-chrome/files/3099558/Mueller.2.pdf)
[mueller 1.pdf](https://github.com/iamadamdev/bypass-paywalls-chrome/files/3099559/mueller.1.pdf)

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed? I can load that article fine.

**Comment by czsmith** [comment]
Installed, but I whitelisted that site trying.

After further playing, I “signed in” with my free (non-paying) account from ages ago and was able to read the article.

Chris
