### ISSUE TITLE
Incorrect uBlock Origin link in Readme

### ISSUE THREAD

**Issue by ideologysec** [iamadamdev/bypass-paywalls-chrome#178]
Hello,

the README file says that this extension works best with uBlock Origin, but the link in the readme goes to the Chrome Web Store page for the original uBlock (which is not the same thing).

the (INCORRECT) page linked to for the "original" uBlock is this:
https://chrome.google.com/webstore/detail/ublock/epcnnfbjfcgphgdmggkamkmgojdagdnn

The correct page for uBlock Origin is here:
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

**Comment by pavankjadda** [comment]
Pull request #180 should fix this

**Comment by OpenSource-Developer** [comment]
Pull request #180 should fix this

**Comment by iamadamdev** [comment]
Fixed
