### ISSUE TITLE
Request for adding Paywall Bypass 

### ISSUE THREAD

**Issue by SumedhBhagwat** [iamadamdev/bypass-paywalls-chrome#179]
Respected Sir 
Please add paywall bypass for site www.bloombergquint.com.
It has 5.6 Million visitors and has both metered as well as hard paywall 
Web Traffic Source : https://www.similarweb.com/website/bloombergquint.com
Thank You

**Comment by iamadamdev** [comment]
Unfortunately won't work for that site.
