### ISSUE TITLE
problems with barrons, ft  economist   Version 67.0.3396.87 

### ISSUE THREAD

**Issue by jlitz** [iamadamdev/bypass-paywalls-chrome#18]
doesn't work wih  barrons and ft   economist  clearing cookies and uncheck/recheck didnt help  other sites ok nyt wsj wp        tho didnt check them all

**Comment by Stenbitsrom** [comment]
Same problem with FT and WSJ

**Comment by iamadamdev** [comment]
OS? Chrome version?
Windows & Chrome Version 67.0.3396.87 (Official Build) (64-bit) work fine for me.
And you have uBlock Origin installed too?

**Comment by Stenbitsrom** [comment]
Win 10 Pro 1803
Same Chrome as you mentioned
No Ublock, but I have Adblock

On a second computer Win 10 Home 1803 with same Chrome specs as you have. FT and WSJ works normally on this machine.

I have erased all ft.com cookies from my first computer and it does not help

**Comment by Stenbitsrom** [comment]
Don't know whats wrong. I've moved to Firefox. Works well.

**Comment by jlitz** [comment]
yea Firefox works perfect.  Can't resolve the chrome FT Barrons problem  using Ublock, clearing cookies ect.  But no big thing Firefox addon is excellent great work!!

**Comment by iamadamdev** [comment]
Ft, barron's, and haaretz.com/co.il still work. Confirmed themarker doesn't (but works fine on firefox).

**Comment by ShintoPlasm** [comment]
@iamadamdev Is there any way to try and debug this? Clearly, some people are having trouble with the Chrome extension. I've tried to disable all other extensions + clearing all cookies + reinstalling/reloading, and Haaretz is still giving me grief...

**Comment by iamadamdev** [comment]
How about on v1.2.8?

**Comment by ShintoPlasm** [comment]
Happy to say that with v1.2.8 Haaretz is working once again on Chrome 67 here. Thank you!
