### ISSUE TITLE
Sorry, This was meant to be a Request to Add these sites to the list of supported site.

### ISSUE THREAD

**Issue by zeon2017** [iamadamdev/bypass-paywalls-chrome#182]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/172#issue-434773261

Couldn't bypass the Paywalls of the following websites

1) The Independence: https://www.independent.co.uk
![Independence](https://user-images.githubusercontent.com/27505388/56364357-f5d43c00-620b-11e9-9679-53b4451a4c11.JPG)

2) The Hindu: https://www.thehindu.com/
![The Hindu](https://user-images.githubusercontent.com/27505388/56364563-785cfb80-620c-11e9-813c-72b50b2bf78d.JPG)

Kindly Help, Thank you <3

**Comment by dm2912** [comment]
the Indy is not all paywalled.

Only the "Minds" section, and you can bypass the paywall there just by disabling Javascript in site settings.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
