### ISSUE TITLE
NZ Herald Please

### ISSUE THREAD

**Issue by possomcohen** [iamadamdev/bypass-paywalls-chrome#183]
Hello. Greetings from New Zealand. Your extension is fantastic.

www.nzherald.co.nz just started their partially paywalled content.
Any chance of your extension working around it?
Example: https://www.nzherald.co.nz/nz/news/article.cfm?c_id=1&objectid=12226671

"To continue reading this article
Subscribe now and get 50% off for the first 8 weeks
$5$2.50per week"

**Comment by yegamble** [comment]
Looks like the article id is article-content and the class is premium-content. The current solution is to type into the console $("#article-content").removeClass("premium-content")

**Comment by possomcohen** [comment]
Thank you very much. Works like a charm.

**Comment by possomcohen** [comment]
Quick question, please. I turn off my iMac every night. When I start it in the morning and open Chrome, the ByPassPayWalls extension disappears from Chrome extensions every morning. I drag the folder into the extensions window and it resumes operation. Is there a setting I can toggle so that the extension does not need to be reinstalled every morning? Thank you very much.

**Comment by yegamble** [comment]
You should use the NZ Herald fixer in Chrome. The Herald uses only CSS to hide content while most other sites seem to use Javascript for their paywalls.

https://chrome.google.com/webstore/detail/nzherald-fixer/akmffecaegmmjjdplhdohmligakbnmbk

**Comment by iamadamdev** [comment]
Make sure developer mode is enabled at the top right at chrome://extensions/
