### ISSUE TITLE
New Site Request: Volkskrant and Trouw

### ISSUE THREAD

**Issue by jango0** [iamadamdev/bypass-paywalls-chrome#184]
For both, a soft paywall appears after opening 7 articles. Confirmed working with incognito window.

https://www.volkskrant.nl/

https://www.trouw.nl/

**Comment by iamadamdev** [comment]
You can also remove cookies with this extension: https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg

**Comment by magnolia1234** [comment]
See PR #314
