### ISSUE TITLE
Causes cookie & sign-in failure on medium.com

### ISSUE THREAD

**Issue by voldemarz** [iamadamdev/bypass-paywalls-chrome#186]
When extension is enabled it causes the following issues
- Everytime I visit medium.com I see cookie acceptance promt
- Unable to sign in using Google account.

System:
Windows 10 Pro (version 1809)
Google Chrome version 3.0.3683.103 (Official Build) (64-bit)

**Comment by iamadamdev** [comment]
Did you uncheck medium from the options?

**Comment by voldemarz** [comment]
Oh. didn't think of that... That solves it. Thanks!
