### ISSUE TITLE
Automatic updating

### ISSUE THREAD

**Issue by DankMemeGuy** [iamadamdev/bypass-paywalls-chrome#190]
How do I go about auto updating? Or at least be notified when a new update is required?

**Comment by iamadamdev** [comment]
It's supposed to work by going to chrome://extensions/ and clicking "Update" to update all extensions. It worked once in my testing earlier but I'm not fully convinced it's reliable. Automatic updating of developer extensions not hosted official on the google chrome store might not be supported.

Firefox auto-updating is working though..

**Comment by WolfRamAlpha12** [comment]
> How do I go about auto updating? Or at least be notified when a new update is required?

You can use github's rss feature. The link for this specific repo is https://github.com/iamadamdev/bypass-paywalls-chrome/commits/master.atom . Use your favourite RSS reader, I personnaly used pushpullet
