### ISSUE TITLE
New Site: BusinessInsider

### ISSUE THREAD

**Issue by AmarettoSlim** [iamadamdev/bypass-paywalls-chrome#191]
:pray:

**Comment by iamadamdev** [comment]
Where are you seeing a paywall?

**Comment by AmarettoSlim** [comment]
I was looking at: 
https://www.businessinsider.com/canopy-growths-ceo-says-acreage-holdings-deal-will-go-through-2019-5

**Comment by iamadamdev** [comment]
Added

**Comment by AmarettoSlim** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
