### ISSUE TITLE
qz.com

### ISSUE THREAD

**Issue by prodan1234** [iamadamdev/bypass-paywalls-chrome#201]
Qz.com [recently](https://qz.com/1612900/quartz-announces-metered-paywall/) put up an article paywall. Can you please look into it? Thanks!

**Comment by iamadamdev** [comment]
Added in v1.5.1

**Comment by madzae** [comment]
Quartz still cannot be access now.

**Comment by wgordon17** [comment]
Yeah, I'm getting blocked on quartz as well, on latest 1.7.8 version @iamadamdev

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/105925654-5f929400-5ff5-11eb-95bd-548fa960db24.png)

Free articles still work for me.

**Comment by wgordon17** [comment]
Somehow I missed the `(free articles only)` 😔 

I'm assuming then, if [this](https://qz.com/1955385/what-homeowners-should-know-about-rooftop-solar-panels/) isn't working, then it's a paid article?
