### ISSUE TITLE
Suggestion for WSJ. Remove div with cx-articlecover

### ISSUE THREAD

**Issue by taktischekartoffel** [iamadamdev/bypass-paywalls-chrome#202]
A div with class cx-articlecover is preventing users from clicking in article links. 
Removing this could improve the experience.

**Comment by iamadamdev** [comment]
Can you submit a PR for the change? (if it works)

**Comment by iamadamdev** [comment]
Not sure what the problem is, I am able to click links in WSJ articles just fine.
(on Windows, Chrome)

**Comment by taktischekartoffel** [comment]
It was on osx Mojave with the latest chrome. 




— 


Kind regards,




Benjamin Ruhe


TOSHIRO




Phone: +61 491 070 973


Email: benjamin@toshiro.co


Skype: benjamin.ruhe







On Sun, May 26, 2019 at 7:13 AM +1000, "Adam" <notifications@github.com> wrote:












Not sure what the problem is, I am able to click links in WSJ articles just fine.

(on Windows, Chrome)

**Comment by taktischekartoffel** [comment]
It was on osx Mojave

**Comment by taktischekartoffel** [comment]
Ok, this may have been a WSJ issue. As it seems to have resolved itself.
