### ISSUE TITLE
Daily Telegraph?

### ISSUE THREAD

**Issue by LawSci** [iamadamdev/bypass-paywalls-chrome#204]
Hi there. 
Is there any reason why The Daily Telegraph was removed? 
Was their paywall giving issues?
I really like their articles and would like to see them added to the list again if possible. 

Thanks man!

**Comment by LawSci** [comment]
I've just checked on Firefox again, and The Telegraph works perfectly. 
Might only be a Chrome issue?
Thanks for your great work!
Cheers

**Comment by iamadamdev** [comment]
I'll add it back to Chrome

**Comment by LawSci** [comment]
Thanks man!

**Comment by CurlsOnTop** [comment]
Tried to open this article and didn't have any luck 
https://www.dailytelegraph.com.au/subscribe/news/1/?sourceCode=DTWEB_WRE170_a_GGL&dest=https%3A%2F%2Fwww.dailytelegraph.com.au%2Fnewslocal%2Finner-west%2Fsydney-chamber-choir-berth-a-dream-come-true-for-blind-soprano-ria-andriani%2Fnews-story%2Ff783ae1b1f04b6836d291dbc6c2e97f9&memtype=anonymous&mode=premium
