### ISSUE TITLE
Wired.com not working in Kiwi Browser

### ISSUE THREAD

**Issue by Safekeep** [iamadamdev/bypass-paywalls-chrome#205]
I installed the latest version of the extension on the Kiwi browser on my android device, but when I browse wired.com, it still detects that I'm not logged in/subscribed, and gives me the overlay for 2nd article, last article, etc... As usual, once I manually clear the cookies from www.wired.com, then it will reset the number of article's read... 

Wired.com works just fine on my desktop Chrome browser in Windows 10..  Not sure how I can help to troubleshoot the issue...

**Comment by iamadamdev** [comment]
I do not officially support the Kiwi Browser.. my script is indeed removing the wired.com cookies.. Kiwi browser might be doing something else

**Comment by magnolia1234** [comment]
Still weird since your Cookie Remover extension is working in Kiwi Browser.
