### ISSUE TITLE
NYT not working as of May 22, 2019.  Indognito also no longer working.  Worked two days ago.

### ISSUE THREAD

**Issue by BobMaine** [iamadamdev/bypass-paywalls-chrome#206]

**Comment by piby2** [comment]
Working for me with adblockplus, ublock origin, and disconnect me in addition to this.


![image](https://user-images.githubusercontent.com/27572901/58297551-1b71d980-7da6-11e9-99b0-c7e648345f0b.png)

**Comment by iamadamdev** [comment]
Seems to be working again?

**Comment by BobMaine** [comment]
Yes, working today. Amazing stuff.
