### ISSUE TITLE
Washingtonpost showing adblock detected

### ISSUE THREAD

**Issue by piby2** [iamadamdev/bypass-paywalls-chrome#207]
Since today (23rd May, 2019), WaPo is showing a banner that adblock has been detected. This happens with adblockplus and/or ublock and/or disconnectme.
![image](https://user-images.githubusercontent.com/27572901/58299999-fa61b680-7dae-11e9-9285-cae4fdfb5b45.png)

This goes off with javascript turned off, but then the videos and images are gone too. It would be great if you could fix this issue.
![image](https://user-images.githubusercontent.com/27572901/58300033-16655800-7daf-11e9-9bf1-be46b999aee1.png)

**Comment by iamadamdev** [comment]
I am not seeing that anymore.

**Comment by wallismith** [comment]
@iamadamdev Not OP, but here's an article in The Washington Post that I ran across just now: https://www.washingtonpost.com/technology/2019/05/28/its-middle-night-do-you-know-who-your-iphone-is-talking 

screenshot as well:
![image](https://user-images.githubusercontent.com/6549971/58658781-4ea8f100-82ef-11e9-9a70-d2fdd259dc15.png)

**Comment by piby2** [comment]
Started happening again :-(
https://www.washingtonpost.com/world/asia_pacific/malaysias-mahathir-tells-rich-nations-to-stop-dumping-their-plastic-on-poor-countries/2019/05/30/29b99a32-82b5-11e9-95a9-e2c830afe24f_story.html?utm_term=.129218e0e828

![image](https://user-images.githubusercontent.com/27572901/58680029-12e44a80-8334-11e9-9637-84521eff9139.png)

**Comment by iamadamdev** [comment]
Try unselecting wapo from my extension and just remove cookies using this (with uBlock Origin enabled):
https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg

**Comment by prech** [comment]
> Try unselecting wapo from my extension and just remove cookies using this (with uBlock Origin enabled):
> https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg

Thanks, this worked for me

**Comment by greyline** [comment]
> Try unselecting wapo from my extension and just remove cookies using this (with uBlock Origin enabled):
> https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg

Had the same issue; tried this, but to no avail. That being said, the bypass paywall extension still seems to work, even if I have to slog through obnoxious ads.

**Comment by piby2** [comment]
I have 

> > Try unselecting wapo from my extension and just remove cookies using this (with uBlock Origin enabled):
> > https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg
> 
> Had the same issue; tried this, but to no avail. That being said, the bypass paywall extension still seems to work, even if I have to slog through obnoxious ads.



> Try unselecting wapo from my extension and just remove cookies using this (with uBlock Origin enabled):
> https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg

**Comment by piby2** [comment]
> > Try unselecting wapo from my extension and just remove cookies using this (with uBlock Origin enabled):
> > https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg
> 
> Had the same issue; tried this, but to no avail. That being said, the bypass paywall extension still seems to work, even if I have to slog through obnoxious ads.

I have disconnect.me working with this extension. adblockplus and ublock do not work
