### ISSUE TITLE
New site request: De Morgen (Belgian Newspaper)

### ISSUE THREAD

**Issue by AtticusQ** [iamadamdev/bypass-paywalls-chrome#208]
Hi

"De Morgen" is one of the largest, most trustworthy news websites in Belgium with a paywall which can be bypassed with the incogitotab. Therefore I would be glad to see it added on to the list of websites covered by your extension. 
url: https://www.demorgen.be/

Thanks in advance

**Comment by iamadamdev** [comment]
Added in v1.5.1
