### ISSUE TITLE
mosaicmagazine.com

### ISSUE THREAD

**Issue by enbob** [iamadamdev/bypass-paywalls-chrome#209]
This site prompts you to subscribe after you've read a certain number of articles in a month. It forgets your read count in an incognito window. Thanks for making a great tool!

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
"Only large or major sites will be considered."

You can try: https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg

**Comment by enbob** [comment]
I understand. Let me know if your definition of "large" changes :) Thanks again.
