### ISSUE TITLE
new site request: caravanmagazine.in

### ISSUE THREAD

**Issue by illusma** [iamadamdev/bypass-paywalls-chrome#210]
The Caravan is India’s first long-form narrative journalism magazine about politics and culture.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
"Only large or major sites will be considered."

You can try: https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg
