### ISSUE TITLE
New site request: Oil & Gas Journal

### ISSUE THREAD

**Issue by 0xd1ce** [iamadamdev/bypass-paywalls-chrome#211]
"The Oil & Gas Journal, first published in 1902, is the world's most widely read petroleum industry publication. Each week the Journal delivers the latest international oil and gas news; analysis of issues and events; practical technology for design, operation and maintenance; and important statistics on international markets and activity."

Able to load premium articles via Google in incognito mode. Perhaps not news that the majority of people are interested in, though those who are will find this valuable.

Therefore, I would really appreciate if you could add support for it :)

[https://www.ogj.com](https://www.ogj.com)

**Comment by iamadamdev** [comment]
I loaded 10+ articles just fine on that site. Do you have uBlock Origin installed?
You could also always remove cookies:
https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg
