### ISSUE TITLE
London Review of Books

### ISSUE THREAD

**Issue by billypilgrim541** [iamadamdev/bypass-paywalls-chrome#213]
It would be amazing if this functionality was enabled / could work for London Review of Books (https://www.lrb.co.uk/). Thank you very much! It’s a fairly well-read site in academia.

**Comment by iamadamdev** [comment]
You can always use this https://chrome.google.com/webstore/detail/remove-cookie/oifomnalkciipmgkfgdjkepdocgiipjg to reset the counter on that site.
