### ISSUE TITLE
Quartz keeps refreshing

### ISSUE THREAD

**Issue by koovalix** [iamadamdev/bypass-paywalls-chrome#214]
I updated the extension because Quartz just started putting paywall. The paywall is gone but now an article keeps refreshing.

https://qz.com/1628726/what-the-candidates-for-uk-prime-minister-think-about-a-no-deal-brexit/

**Comment by iamadamdev** [comment]
Works fine for me, no refreshing. Do you have uBlock Origin installed?

**Comment by koovalix** [comment]
I've it. I tried in incognito mode (this extension, ublock, and nano). Working in incognito mode. Seems like it's from my end.

**Comment by Welding-Torch** [comment]
Thank you. I disabled that extension on Quartz website. It works properly now
