### ISSUE TITLE
New Site Request: Zeit.de

### ISSUE THREAD

**Issue by NotJ3st3r** [iamadamdev/bypass-paywalls-chrome#216]

**Comment by iamadamdev** [comment]
Please describe what it is, how large it is.. etc

**Comment by NotJ3st3r** [comment]
It's a very popular germany news site. The print version is the most widely read German weekly newspaper with roughly 500k weekly readers.

**Comment by iamadamdev** [comment]
Did you follow the instructions here to test if it can be bypassed?
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by NotJ3st3r** [comment]
Yeah I've already checked before submitting a request.

**Comment by iamadamdev** [comment]
Added. It can't bypass Z+ articles in red though, those are behind a hard paywall.
