### ISSUE TITLE
New york times bypass not working

### ISSUE THREAD

**Issue by testaa999** [iamadamdev/bypass-paywalls-chrome#218]
Tried on 30 may 950am sgt, 
nyt paywall keeps coming up, reinstalled the extension and still doesnt work

**Comment by iamadamdev** [comment]
What article? Do you have uBlock Origin installed?
It still works fine for me.

**Comment by testaa999** [comment]
thanks, it doesnt work as a standalone but i have gotten uorigin and it works now
