### ISSUE TITLE
Washington Post doesn't work with GDPR warning

### ISSUE THREAD

**Issue by avengah** [iamadamdev/bypass-paywalls-chrome#22]
The GDPR warning just keeps reloading and reloading. As a temporary measure I had to untick WaPo in this extension and use a Tampermonkey script: https://steemit.com/javascript/@deelawn/how-to-bypass-the-washington-post-paywall

I'm sure it's something simple, such as one particular cookie that indicates the GDPR warning has been accepted needs to be left intact; thanks for this great extension!

**Comment by iamadamdev** [comment]
At the moment I do not have a fix, but you could always add an extension like https://chrome.google.com/webstore/detail/anonymox/icpklikeghomkemdellmmkoifgfbakio?hl=en-US
 and set your location the U.S.

**Comment by kristofferR** [comment]
Please unclose this, it's super annoying.

**Comment by iamadamdev** [comment]
Can you submit a PR for the fix?

**Comment by iamadamdev** [comment]
@kristofferR does it work now (on v1.3.9)?

**Comment by kristofferR** [comment]
No, I just get a GDPR loop. I've updated to 1.3.9 and deleted all WashingtonPost cookies.

Sorry, I don't know Javascript properly yet to attempt to fix it myself.

**Comment by iamadamdev** [comment]
This is what I was referring to. @iscreamcoke we can't just remove all the cookies, you get stuck in GDPR loop.

**Comment by iscreamcoke** [comment]
You're right, except I'm not having a GDPR loophole but I have to confirm again for each page load

If you don't remove cookies after or before page load, you'll hit paywall count
If you remove them, you'll hit GDPR warning

**Comment by iscreamcoke** [comment]
I'm going to try to fix it on my fork and reach you when I find a better solution

**Comment by iscreamcoke** [comment]
You're right, except I'm not having a GDPR loophole but I have to confirm again for each article loaded

* If you don't remove cookies after or before page load, you'll hit paywall count (I don't know if they have that in place for US readers)
* If you remove them, you'll hit GDPR warning (but no loophole for me)

I'm going to try to fix it on my fork and reach you when I find a better solution

**Comment by iamadamdev** [comment]
1. WaPo readers in the U.S. should not have to remove any cookies at all, the simple google referral trick works.
2. To fix it for EU we need to allow the GDPR cookie, and remove the other WaPo cookies maybe.

**Comment by iscreamcoke** [comment]
But the edit I made fixes the issue, even if it's far from perfect as you have to confirm GDPR again for each article.

I don't understand why @kristofferR is stuck in loophole as it clears cookies **after** the page has loaded

**Comment by iamadamdev** [comment]
For EU, you get stuck in GDPR confirm cookie loop, it's not just a matter of accepting it for each article, you can't even read any articles. I remember I saw this before when I proxied myself as a EU user.

You can also try playing around with the method used here: https://github.com/burlesco/burlesco/blob/master/webext/background.js

**Comment by iamadamdev** [comment]
Just made a change to allow cookies for EU users, it worked for me on firefox using a proxy to a EU country where I got the GDPR cookie notice. Might not work for everyone though.
@kristofferR can you try again with the latest version?

**Comment by iscreamcoke** [comment]
If I may:

* it likely solves the GDPR loop but won't solve the paywall count issue. So it fixes the loop but not the paywall outside the US ;)
* there's still the loop in Firefox but that's because you didn't update the fox version

I'll let Kristoffer answer for his side, it's nighttime here. Thanks for the hard work Adam!

**Comment by kristofferR** [comment]
Uh, I don't get the GDPR loop anymore on the latest version (Chrome), but I get the paywall.

Here's how it looks:
https://streamable.com/ewnmx

**Comment by mikadocat** [comment]
I'm in the EU, I use Block-EU-Cookie-Shit-List with uBlock in conjunction with uMatrix and NoScript, I don't have this issue.

**Comment by iamadamdev** [comment]
Should be fixed now.
