### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by spekulatius** [iamadamdev/bypass-paywalls-chrome#220]
Hello again,

are you actually planning a Firefox version? Converting is pretty straight forward in most cases. Also here, happy to help

Peter

**Comment by spekulatius** [comment]
Please ignore as I just found this: https://github.com/iamadamdev/bypass-paywalls-firefox

**Comment by iamadamdev** [comment]
Actually I am considering merging these 2 extensions into one. I know the update mechanism is going to be different for Chrome and Firefox though. Also the manifests will be different. GitHub doesn't allowed a shared base repro, so this may not be possible at the moment.

**Comment by spekulatius** [comment]
Yeah, I noticed the same issue with the manifest.json file - what is required on one store end throws warnings or errors on the other.
