### ISSUE TITLE
The Economist Bypass Broken?

### ISSUE THREAD

**Issue by billypilgrim541** [iamadamdev/bypass-paywalls-chrome#224]
Apologies if it's something on my end, but it seems that the Economist isn't being bypassed anymore. Thanks!

Edit: It may have only occurred afer the latest Chrome update (75.0.3770.80)

**Comment by iamadamdev** [comment]
It is. I don't have any working solutions at the moment.

**Comment by freshry** [comment]
It does not seem to be working in Vivaldi either. One thing I did notice is that Vivaldi's Reader Mode seems to beat it. Hopefully this information is helpful to you.

**Comment by iamadamdev** [comment]
Should be working now.
