### ISSUE TITLE
Please consider adding The Philadelphia Inquirer

### ISSUE THREAD

**Issue by phlstephen** [iamadamdev/bypass-paywalls-chrome#226]
Great plugin!  I just starred you! 

Would you please consider adding The Philadelphia Inquirer? (www.inquirer.com)  

I just performed the test specified and it was successful.  Our [population](https://en.wikipedia.org/wiki/Philadelphia#Demographics) is nearing 1.6 million so I hope you will consider adding our newspaper. Thank you!

This is the [test link](https://www.inquirer.com/arts/philadelphia-orchestra-donation-biggest-gift-yannick-nezet-seguin-20190606.html) I used.

**Comment by iamadamdev** [comment]
I loaded 10+ articles and the link you pasted just fine w/o seeing any paywalls. Do you have uBlock Origin installed?

**Comment by phlstephen** [comment]
A paywall definitely [exists](https://www.screencast.com/t/DDTGXJxS), however I just installed uBlock Origin and it seems to defeat it.  Let's see how long that lasts. ;-) Thank You!
