### ISSUE TITLE
Can make this extension compatible with the Chrome Web Store by loading external data

### ISSUE THREAD

**Issue by fortran77** [iamadamdev/bypass-paywalls-chrome#23]
This extension could be made compatible with the Chrome Web Store by removing all sites and user-agents already included within it, and replacing them with external data that could be loaded by the user.

This would be similar to how the ad-blocking extensions work that load external filter lists. 

Not only would this make the extension permissible in the Chrome Web Store, but also updates would then come in the form of updated data, with few or no updates in the extension itself. Users could then also manually add sites (and user-agents) without rebuilding the extension.

Site-specific characteristics (e.g., when to clear cookies) could take the form of check-boxes.

**Comment by fortran77** [comment]
> Site-specific characteristics (e.g., when to clear cookies) could take the form of check-boxes.

Or the external data file could also include all needed site-specific options.

**Comment by iamadamdev** [comment]
Making this change would be gladly welcomed.
