### ISSUE TITLE
site request: Chemical and Engineering News (https://cen.acs.org/)

### ISSUE THREAD

**Issue by freshry** [iamadamdev/bypass-paywalls-chrome#234]
most of the details are in title.

site: Chemical and Engineering News
url: https://cen.acs.org/

incognito browsing resets the monthly quota so hopefully this is achievable. thanks a bunch.

**Comment by iamadamdev** [comment]
This site is already supported on the Firefox version. https://github.com/iamadamdev/bypass-paywalls-firefox
If you want to submit a PR for it here I will gladly accept it, otherwise I am not adding small sites anymore.
