### ISSUE TITLE
Where do I store the extension folder?

### ISSUE THREAD

**Issue by manzalawy** [iamadamdev/bypass-paywalls-chrome#239]
Where do people typically store a manually added extension like this? I have "bypass-paywalls-chrome-master" on my desktop but if I move it the extension stops working. Can I store it in the Extensions folder on my mac?

**Comment by iamadamdev** [comment]
Anywhere is fine. E.g., C:\bypass-paywalls-chrome or D:\bypass-paywalls-chrome
If you move it, you need to remove it from Chrome and drag the folder into extensions again.
