### ISSUE TITLE
Unable to install on Chrome extension. 

### ISSUE THREAD

**Issue by july93** [iamadamdev/bypass-paywalls-chrome#24]
I’m unable to install this extension on my chrome browser. I dragged the folder into the chrome extensions page, but nothing happens after that and the extension doesn’t install. 

Would appreciate any advice and tips. Thank you.

**Comment by mikhoul** [comment]
Look here, it's really easy to do it: https://blog.hunter.io/how-to-install-a-chrome-extension-without-using-the-chrome-web-store-31902c780034

Have a nice day 😊
