### ISSUE TITLE
New York Time issue

### ISSUE THREAD

**Issue by lovemath314** [iamadamdev/bypass-paywalls-chrome#240]
Hi all, 
I have this to bypass the paywall of NYT easily. But I have some issues with it.  It shows that "you're in private mode". 
![NYT  bypass](https://user-images.githubusercontent.com/52233499/60158759-05ff2d80-97f2-11e9-9888-02152e8a4255.PNG) .  
Have anyone had this  issue like me? 
thanks.

**Comment by iamadamdev** [comment]
Uncheck NYT and just enable uBlock Origin.

**Comment by lovemath314** [comment]
for the uncheck NTY, I understand that in the extension options of the application, I uncheck "The New York Times", and "enabling uBlock Origin" means installing uBlock Orgin extension from  Chrome Store web? 
Thanks alot.

**Comment by iamadamdev** [comment]
Yes

**Comment by lovemath314** [comment]
Thanks a lot. It works now. I have done those steps as you told. But before I have blocked its (NYTs) cookies, now I just let them allow to use it. 
Anyway thanks a lot. Your extension on Chrome and other web browers are really saving me and other ones. Without your app, it seems impposible for me access those sites. Again, thanks alot.
