### ISSUE TITLE
Please add a Seeking Alpha link

### ISSUE THREAD

**Issue by tienshunlo** [iamadamdev/bypass-paywalls-chrome#243]
Please add a Seeking Alpha link, thank you.

**Comment by iamadamdev** [comment]
Where are you seeing a paywall?

**Comment by tienshunlo** [comment]
Some articles has a small key under the title, please see the attachment , thank you so much.

從我的 iPhone 傳送

**Comment by iamadamdev** [comment]
Which article? Your attachment didn't work. Please paste the url.

**Comment by tienshunlo** [comment]
How about this?
CenturyLink Is Deep Value $CTL
https://seekingalpha.com/article/4267260

從我的 iPhone 傳送

**Comment by iamadamdev** [comment]
I can view that article fine. Do you have uBlock Origin installed?

**Comment by tienshunlo** [comment]
You don’t see the Subscribe Now button? 

從我的 iPhone 傳送

**Comment by iamadamdev** [comment]
No, I can view the whole article all the way to conclusion:
![image](https://user-images.githubusercontent.com/36013816/60321863-d9066400-9932-11e9-9952-278dfce2c3d8.png)

**Comment by iamadamdev** [comment]
Maybe try my Cookie Remover and refresh?
https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce

**Comment by tienshunlo** [comment]
I guess you can have three free trials, after that, you have to pay for it.
maybe you can try more than 3 articles? and make sure those articles do
have little key under the title. thank you.

Adam <notifications@github.com> 於 2019年6月28日 週五 下午2:25寫道：

**Comment by iamadamdev** [comment]
Not seeing any locked articles.
Did you try my Cookie Remover extension?

**Comment by AS-IN** [comment]
Your extension works superb for Windows. But on my Android I am not able to access FT.COM. I use kiwi browser which supports chrome extension. Apart from FT.COM I am able bypass paywall of all other news sites. Please HELP. I get this message from FT.COM(The option to upgrade from Standard Digital to Premium Digital via Google is not available.)

**Comment by tienshunlo** [comment]
yes, the Cookie Remover works well, thank you, and may I ask what's the
different between these two extensions, thanks again.

Adam <notifications@github.com> 於 2019年6月29日 週六 上午1:40寫道：

**Comment by iamadamdev** [comment]
One just removes cookies, the other tries some other techniques.
