### ISSUE TITLE
New Site request

### ISSUE THREAD

**Issue by connorhsm** [iamadamdev/bypass-paywalls-chrome#244]
Could you please take a look at this site?
[https://www.bordermail.com.au/](https://www.bordermail.com.au/)

It's only a local paper in my state but regardless, I'm having a tough time getting around the paywall.

Using Chrome, the latest version of this plugin and uBlock Origin.
I've also tried Incognito, disabling JavaScript and taking a look at HTML. No luck.

Many thanks!

**Comment by iamadamdev** [comment]
Unfortunately even disabling JS doesn't work. Seems like a hard paywall.
