### ISSUE TITLE
nyt not working at all

### ISSUE THREAD

**Issue by hiworld3** [iamadamdev/bypass-paywalls-chrome#245]
please fix, i have uBlock Origin, does nothing, please tell me if there's any way, like a filter script into uBlock Origin if this plugin is really not needed, cos both not working right now

add: other latimes etc are working, only nyt no.. thanks

**Comment by iamadamdev** [comment]
Must be you. Works fine for me, loaded 10+ articles no issues.

**Comment by Buuntu** [comment]
Works for me!  Great work @iamadamdev
