### ISSUE TITLE
The West Australian, newspaper

### ISSUE THREAD

**Issue by clara-petacci** [iamadamdev/bypass-paywalls-chrome#249]
could you please put "The West Australian" newspaper on your bypass list.
It seems many of the main newspapers in all OZ states have just put paywalls up. The Australian media is in
the hands of two major players, includes print, TV and Radio. This is not healthy, hundreds of journalists have been sacked and the content dumbed down. All we hear read and see is "The Company's" view. Murdoch owns 70% of print media plus TV etc.
Regards & thanks.

**Comment by iamadamdev** [comment]
Did you try following the instructions here? https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
