### ISSUE TITLE
Are you going to release this extension in the Chrome Web Store?

### ISSUE THREAD

**Issue by mickeyseo** [iamadamdev/bypass-paywalls-chrome#25]
Hello? I appreciate your hard work for developing this money-saving extension.

I found this extension in Firefox Add-ons website, but the extension for Chrome users have no choice but to download the source code.

1. Could you please tell me why it is not available in the Chrome Web Store?
2. Are you planning to release this extension in the Chrome Web Store?

I look forward to your kind answer. Thank you.

**Comment by Obtainz** [comment]
The add on isn’t legally compliant with the chrome web store and won’t come to it in its current form.

**Comment by mickeyseo** [comment]
OK. Thank you for your quick response. I hope you keep supporting this extension.

**Comment by iamadamdev** [comment]
It was originally in the store then it got banned.

**Comment by ShintoPlasm** [comment]
@iamadamdev A quick related question: is there any particular reason why the Chrome extension is a bit behind the Firefox one? FF currently at v1.3.4 whereas Chrome ext still at v1.2.9

**Comment by iamadamdev** [comment]
Simply because the FF version gets more requests than the Chrome one as it has more users. I don't automatically add sites to Chrome just because someone requested it on FF.
