### ISSUE TITLE
NZ Herald bypass please

### ISSUE THREAD

**Issue by possomcohen** [iamadamdev/bypass-paywalls-chrome#250]
This bypass for NZ Herald no longer operational:

"You should use the NZ Herald fixer in Chrome. The Herald uses only CSS to hide content while most other sites seem to use Javascript for their paywalls.

https://chrome.google.com/webstore/detail/nzherald-fixer/akmffecaegmmjjdplhdohmligakbnmbk

Any ideas how one can access premium now?

https://www.nzherald.co.nz/nz/news/article.cfm?c_id=1&objectid=12247988

Now displays:

To continue reading this article and to support great journalism

Thank you very much.

**Comment by possomcohen** [comment]
Also....

I just found this:

https://www.reddit.com/r/newzealand/comments/bj9fdu/nz_herald_premium_content_for_free/

Just create a new bookmark in Chrome….

Edit

Paste this code:

javascript:(function Bypass() { window.onbeforeunload = function(e) {var message = "", e = e || window.event;if (e) {e.returnValue = message;}return message;}; $("#main").css("height","auto"); $('#article-content > p, #article-content > div, #article-content > p span:nth-of-type(2)').removeAttr('style class'); $('#article-content').css({'padding-bottom':'80px'}); $('.article-offer').hide(); $('#article-content > p span:nth-of-type(1)').remove(); })();

Save

Go to a premium site…

Get blocked…. Click on the bookmark (I named mine Free)…

Voila

Access

www.nzherald.co.nz/nz/news/article.cfm?c_id=1&objectid=12247988

FYI, I also stumbled across this write-up about your extension:

https://medium.com/black-edge-consulting/how-to-bypass-virtually-every-news-paywall-705602c4c2ce

**Comment by iamadamdev** [comment]
Fixed
