### ISSUE TITLE
Chrome on Android?

### ISSUE THREAD

**Issue by kmand** [iamadamdev/bypass-paywalls-chrome#251]
I presume that there is no hope for this on Android Chrome (no extensions), and the only alternative is to use Android Firefox. A bit painful since I run chrome every where non-mobile, and lose out on shared bookmarks, history,  etc.

**Comment by iamadamdev** [comment]
No hope for the official Google Chrome (until they support extensions, not sure if that will ever happen). You might get it to work on other flavours of Chromium.

**Comment by Stellarspace** [comment]
Apple won't allow Google to support extensions on iOS.

**Comment by MattHeffNT** [comment]
I'm trying to get this extension on the Kiwi browser, seems to crash it though unfortunately, but i'm feeling hopeful. 

https://www.ghacks.net/2019/04/16/kiwi-browser-android-chrome-extensions/

**Comment by Safekeep** [comment]
> I'm trying to get this extension on the Kiwi browser, seems to crash it though unfortunately, but i'm feeling hopeful.
> 
> https://www.ghacks.net/2019/04/16/kiwi-browser-android-chrome-extensions/

I have it working on Kiwi browser on my phone, but just note that it's not 100% due to the difference in platforms.  You'll need to use Chrome on your desktop to pack the extension first before transferring it to your phone. Click on "Pack Extension" under "3 dots", "More tools", "Extensions", select the directory where you unzipped the extension, then click on "Pack Extension"... Transfer the .crx file to your phone and install it in Kiwi..

**Comment by Mentis** [comment]
I am able to install it, however extension doesn't work as expected: paywall is not bypassed on Seattle Times and Washingtonpost e.g.
It works just fine on Firefox for Android.

**Comment by crowned** [comment]
> I am able to install it, however extension doesn't work as expected: paywall is not bypassed on Seattle Times and Washingtonpost.
> It works just fine on Firefox for Android.

What is the process to get it working on firefox ?

**Comment by Mentis** [comment]
> > I am able to install it, however extension doesn't work as expected: paywall is not bypassed on Seattle Times and Washingtonpost.
> > It works just fine on Firefox for Android.
> 
> What is the process to get it working on firefox ?

You can download firefox version of this extension and install it from filesystem on Android.
