### ISSUE TITLE
New York Times not working

### ISSUE THREAD

**Issue by arsalan14** [iamadamdev/bypass-paywalls-chrome#253]
Hi, I'm trying to access NYT and it's not working. Can you take a look?

**Comment by iamadamdev** [comment]
Which article? Do you have uBlock Origin installed?

**Comment by iamadamdev** [comment]
Try using https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce

**Comment by iiedii** [comment]
It is working good after removing cookies. I can confirm :)
