### ISSUE TITLE
ForeignPolicy not working

### ISSUE THREAD

**Issue by MehmetSen** [iamadamdev/bypass-paywalls-chrome#255]
ForeignPolicy articles not working, please fix.

**Comment by iamadamdev** [comment]
Try disabling javascript

**Comment by MehmetSen** [comment]
By disabling JavaScript and new 1.5.3 version, now fp is working. thanks

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

________________________________

**Comment by kimkha** [comment]
We could close this issue now.
