### ISSUE TITLE
Haaretz.com not working

### ISSUE THREAD

**Issue by soynicoluna** [iamadamdev/bypass-paywalls-chrome#259]
Using bypass paywalls on haaretz.com seems to not be working. In the past it did the trick. Tried deleting cookies but didn't work.

**Comment by iamadamdev** [comment]
It's working for me. What article are you having trouble with?

**Comment by soynicoluna** [comment]
It happened a few times a few months ago.
I tried from several computers and the problem continued for some time.
Now it works fine

**Comment by magnolia1234** [comment]
Works fine with uBlock Origin (else anti-adblocker page).

**Comment by kimkha** [comment]
I think @soynicoluna said it works fine, we can close this issue.
