### ISSUE TITLE
Not working on certain Bloomberg articles

### ISSUE THREAD

**Issue by vertigo42** [iamadamdev/bypass-paywalls-chrome#26]
Hi there,

The extension doesn't seem to be working with certain bberg articles. For ex: https://www.bloomberg.com/news/articles/2014-12-04/colombia-s-50-billion-infrastructure-need-attracts-btg-ashmore

When I click on that link, I get a message saying that I have to be a Terminal subscriber to view the article. I have successfully bypassed the banner with ScriptSafe, but if I leave ScriptSafe on and browse other articles, the pictures on the articles are completely blurry. Thank you.

**Comment by iamadamdev** [comment]
It's not meant to bypass those articles. Google redirect won't work for it unfortunately.

**Comment by mickeyseo** [comment]
The 'Bypass Paywalls' doesn't work at Bloomberg Professional service. Ok!
