### ISSUE TITLE
SF Chronicle stopped working

### ISSUE THREAD

**Issue by Safekeep** [iamadamdev/bypass-paywalls-chrome#260]
https://www.sfchronicle.com/ seems to be forever forwarding to https://www.sfchronicle.com/hdn/hrlm/p/callback.html, and then going back to https://www.sfchronicle.com/

The page just seems to be reloading non-stop.. 

Not sure what's happening... 

Just started happening today..

**Comment by Safekeep** [comment]
The non-stop re-loading loop stopped happening after I black listed scripts from hearstnp.com..

**Comment by Safekeep** [comment]
You might want to update plug-in for the next version to fix this issue..

**Comment by mmortal03** [comment]
> You might want to update plug-in for the next version to fix this issue..

I've been getting this non-stop re-loading loop for a number of sites (WaPo just did it). I'm using v1.5.4. It seems like sometimes if I clear these looping site's cookies, it'll finally load, but this doesn't always work. As soon as I go in to the extension and uncheck the offending site and apply, it will load. Is there a more general issue that might be causing this?
