### ISSUE TITLE
Wall Street Journal

### ISSUE THREAD

**Issue by PePeHa** [iamadamdev/bypass-paywalls-chrome#263]
Could you change the bypass-code for Wall Street Journal, using the (working) Greasemonkey Script from the link below, converted into the Chrome Extension java code, please ?

WSJ loads a whole lot faster via the Greasemonkey script than the code you are currently using, so might be better to use that code in your otherwise great extension.

Thanks for all the effort you put in.

https://greasyfork.org/en/scripts/377618-the-wall-street-journal-full-text-articles/code

**Comment by PePeHa** [comment]
PS - as opposed to your current script, the above-mentioned GM-script also works on all page - for example, can't unpaywall this page (and many others) with your extension currently ... https://www.wsj.com/articles/kkr-loosens-strings-on-dress-code-at-work-11558703415?mod=rsswn

**Comment by TovPrap** [comment]
Also, is it possible to add a change. The search function on WSJ doesn't work when bypass paywalls is on. Consequently, when you come to the end of a section, let's say "Editorials", you press "read more articles", it brings you to search results, which are empty.

Thank you.

**Comment by iamadamdev** [comment]
WSJ loads plenty fast for me.

**Comment by PePeHa** [comment]
and what about this issue ? --> https://github.com/iamadamdev/bypass-paywalls-chrome/issues/263#issuecomment-516318712

**Comment by Moxville** [comment]
below link not working
https://www.wsj.com/articles/welcome-to-black-hat-where-the-attendees-are-the-threat-11565343002?mod=rsswn
![Untitled](https://user-images.githubusercontent.com/31923265/62820222-be085000-bb7e-11e9-9d76-84eccb11e3ef.png)

**Comment by iamadamdev** [comment]
Works fine for me, try refreshing the page.

**Comment by PePeHa** [comment]
you say links work fine for you, but not for me https://www.wsj.com/articles/kkr-loosens-strings-on-dress-code-at-work-11558703415?mod=rsswn

**Comment by Moxville** [comment]
I tried refreshing multiple times but I see same message again. I could not read full article

I use Vivaldi browser and Bypass Paywalls v1.5.2
When I visited "Extensions", I  see an error button and clicking it displays below message

![error](https://user-images.githubusercontent.com/31923265/62835272-ffc6f280-bc73-11e9-9a33-290e43b4969d.png)

**Comment by iamadamdev** [comment]
Try the official Google Chrome browser. Works fine there.

**Comment by Moxville** [comment]
Thanks for your reply.
I tried Chrome and Firefox (latest version). But I couldn't read the article. Reloaded the page multiple times but I still see the same message

**Comment by magnolia1234** [comment]
Regular (not amp) version of article working fine though.

**Comment by PePeHa** [comment]
i started this thread - none of my issues seem to have been solved, only denied

**Comment by iamadamdev** [comment]
Feel free to submit a working PR for the changes.

**Comment by MPlatz1** [comment]
As of today, 10/21/2019, Bypass Paywalls 1.5.2 no longer works for most wall street journal articles.
