### ISSUE TITLE
Boston Globe Not Working

### ISSUE THREAD

**Issue by goldranger** [iamadamdev/bypass-paywalls-chrome#264]
Hello,

The Boston Globe now treats me as a non-subscriber, and even if I try to read my "free" articles, they load up blank after clicking through the sign-up pop-up.

**Comment by TovPrap** [comment]
I have the same issue. I have noticed though if you use the cookie remover extension without bypass paywalls, it does work.

**Comment by bleblancdw** [comment]
I have the same problem as goldranger

**Comment by iamadamdev** [comment]
Fixed in next version (but images may not show)
