### ISSUE TITLE
Extension breaking Sign In pages for some websites

### ISSUE THREAD

**Issue by jayantr7** [iamadamdev/bypass-paywalls-chrome#266]
Apologies if this is a known issue. This happened with both the older and the latest build. After enabling the extension (not due to AdBlock), I can't seem to log in to some websites, specifically - Quora.com and HotJar.com. 
For Quora, clicking the login form button stops doing anything. If I was already logged in before, enabling the extension logs me out. Similarly, trying to log into HotJar redirects me to its error page. Enabling it while logged in refreshes to a blank page.
From what I can tell, this extension is triggering the issue as I tried disabling all extensions except Bypass-Paywall and the bug was still there.

**Comment by TheW0LVERIN3** [comment]
The extension deletes the cookies of websites where you have a limit of the amount of articles you can see, this also causes you to be logged out of the sites you selected in the extensions' options page. This is clearly described in the read.md and is not an issue and there is no way to work around it. You can't be logged in and have the extension enabled for a site at the same time.
