### ISSUE TITLE
Please add in bypass support for New Zealand Herald - Already exist for the Firefox extension

### ISSUE THREAD

**Issue by BobTheSoftwareDeveloper** [iamadamdev/bypass-paywalls-chrome#270]
As you can see from this [commit](https://github.com/iamadamdev/bypass-paywalls-firefox/commit/41b59dca084f92610eb7a50acaa82f7c1187397a), bypass support for New Zealand Herald already exist for the Firefox extension. 

It will be great if it can be added into the Chrome extension too!

Thanks

**Comment by iamadamdev** [comment]
Added in the next version.
