### ISSUE TITLE
Bloomberg not working

### ISSUE THREAD

**Issue by Akababa** [iamadamdev/bypass-paywalls-chrome#273]
How does this extension work? I found for bloomberg I have to open DevTools and then:

1. remove the div with class "paywall-inline-tout inlineTout__d907d789 "
2. remove the event listeners for pagehide from div with class "body-copy-v2 fence-body"
3. remove all the styles "display: none;" from sub-elements of that div

I don't know much about web dev but if you could kindly implement this then that would be greatly appreciated!!

Actually disabling javascript seems to work just fine.

**Comment by Safekeep** [comment]
If you have uBlock Origin installed on your browser, adding the following line to the "My filters" list will get rid of the blocking: ||assets.bwbx.io/s3/fence/v4/app.bundle.js
