### ISSUE TITLE
NYT doesn't seem to work

### ISSUE THREAD

**Issue by tjl1704** [iamadamdev/bypass-paywalls-chrome#274]
Is this just for me?

**Comment by chrisly** [comment]
doesn't work for me either right now. It did work before... so there must've been changes to the site.

**Comment by iamadamdev** [comment]
You don't need my extension to read NYT. Do you have uBlock Origin installed?

**Comment by tjl1704** [comment]
Yup.

**Comment by kwhat** [comment]
USA, disabled J's and that worked.  No idea what article it was bit I'll
keep that in mind

**Comment by Redoykhan555** [comment]
Not working for me too. Do we have to install ublock?

**Comment by tjl1704** [comment]
I have ublock but I still get the paywall

**Comment by iamadamdev** [comment]
That article works fine for me in the U.S. Install uBlock Origin and Cookie Remover.

**Comment by tjl1704** [comment]
So this doesn't work for EU? I have uBlock and Cookie Autodelete.

**Comment by pal2002** [comment]
NYTimes stopped working with Chrome 77 update with 1.5.4. I do not have ublock, previously NYT worked with only this extension. Bypassing works on all other sites.

Looks like this was previously mentioned here
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/235

Firefox with latest add on version works.

**Comment by magnolia1234** [comment]
Works for me in the EU with this extension (clears local storage) and also without uBlock Origin.
Just a 'Continue to your one article'-banner at the bottom.

**Comment by kimkha** [comment]
It works for me in Australia.

**Comment by iamadamdev** [comment]
I just loaded 10+ articles from a UK proxy w/o any issues (including the link you posted). Maybe try clearing your cache and cookies?
