### ISSUE TITLE
La Razón

### ISSUE THREAD

**Issue by fraanr10** [iamadamdev/bypass-paywalls-chrome#276]
Hi,

I'd like to know if it'd be possible to include any of the following Spanish newspapers: ABC, El Mundo, La Razón. If there is a manual way to do it please let me know as well so I can do it quicker. La Razon has a suscription plan where all the good articles and authors are included called YouNews, in case you need that. 

Thanks in advace, 

Fran

**Comment by iamadamdev** [comment]
Did you try 
https://github.com/iamadamdev/bypass-paywalls-chrome#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
?

**Comment by fraanr10** [comment]
Sorry I didn't reply, I didn't get the notification. I did try both and still doesn't work.
