### ISSUE TITLE
thetimes.co.uk request

### ISSUE THREAD

**Issue by outrunpro** [iamadamdev/bypass-paywalls-chrome#278]
Hi,

Thanks for this great extension.

Can you add thetimes.co.uk please?

https://www.thetimes.co.uk/edition/comment/soon-we-must-choose-between-the-us-and-europe-lzctq7kf5

Thanks.

**Comment by iamadamdev** [comment]
Did you try 
https://github.com/iamadamdev/bypass-paywalls-chrome#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
?

**Comment by iamadamdev** [comment]
Added in the next version.
