### ISSUE TITLE
Dutch weekly magazine: www.groene.nl

### ISSUE THREAD

**Issue by magnolia1234** [iamadamdev/bypass-paywalls-chrome#279]
New magazine request (limit of 5 articles)

**Comment by iamadamdev** [comment]
Did you try 
https://github.com/iamadamdev/bypass-paywalls-chrome#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
?

**Comment by magnolia1234** [comment]
Yes, but any part specific you're referring to?
Blocking cookie works.
Incognito tab + Google search also works.

**Comment by magnolia1234** [comment]
It works by just adding website to options.js.

**Comment by iamadamdev** [comment]
Can you submit a PR for it and I'll add it?

**Comment by magnolia1234** [comment]
PR for Dutch magazines and papers.
