### ISSUE TITLE
Dutch monthly magazine: www.vn.nl

### ISSUE THREAD

**Issue by magnolia1234** [iamadamdev/bypass-paywalls-chrome#280]
New magazine request: Vrij Nederland (limit of 3 articles).

**Comment by iamadamdev** [comment]
Did you try 
https://github.com/iamadamdev/bypass-paywalls-chrome#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
?

**Comment by magnolia1234** [comment]
Yes, but any part specific you're referring to?
Deleting cookie after every 3 articles works, but blocking not because of non-javascript cookie-message.
Incognito tab + Google search also works.

**Comment by iamadamdev** [comment]
Please submit a PR for it and I'll accept it.

**Comment by magnolia1234** [comment]
PR for Dutch magazines and papers.

**Comment by magnolia1234** [comment]
You forgot Vrij Nederland in README.md (only there). I included it in my PR though.

**Comment by iamadamdev** [comment]
Updated
