### ISSUE TITLE
Thank you. 

### ISSUE THREAD

**Issue by GrahamGreene** [iamadamdev/bypass-paywalls-chrome#282]
Hi, 

First of all, thank you very much for this extension. 

Would you consider to add at least one newspaper in Spanish? 

This is the site:

La Nación: **www.lanacion.com.ar**

Kind regards!

**Comment by iamadamdev** [comment]
Did you try 
https://github.com/iamadamdev/bypass-paywalls-chrome#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
?
