### ISSUE TITLE
Daily Telegraph (AU) Request

### ISSUE THREAD

**Issue by sydneyrookiedev** [iamadamdev/bypass-paywalls-chrome#283]
Hi,

Thanks for this chrome extension - can't believe I only discovered this now!

Could I please kindly request for an additional website to be added to this extension?

https://www.dailytelegraph.com.au

Thank you :)

**Comment by iamadamdev** [comment]
Did you try 
https://github.com/iamadamdev/bypass-paywalls-chrome#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
?

**Comment by sydneyrookiedev** [comment]
Oh right, thanks for that - yeah, the website has a hard paywall :/

Oh wells, thanks Adam.
