### ISSUE TITLE
Folder not dragging into Chrome extensions

### ISSUE THREAD

**Issue by lxz71** [iamadamdev/bypass-paywalls-chrome#285]
Hello!

First of all, thank you for taking on this project.

I downloaded and unzipped the file, and dragged it into my Chrome extensions window per instructions. However, nothing happens when I drag it and I do not know what I am doing incorrectly.

Please advise. Thank you!

**Comment by iamadamdev** [comment]
Did you drag the whole folder to your opened extensions page?

**Comment by lxz71** [comment]
Yes.

**Comment by welovfree** [comment]
![image](https://user-images.githubusercontent.com/47551447/64036916-3e9de900-cb4c-11e9-8dae-430ad2c491c4.png)
Try to directly click on **Load unpacked** and navigate to where the unzipped folder is located and click OK!
