### ISSUE TITLE
Error - Cannot load extension with file or directory name thumbs.db. The filename is illegal.

### ISSUE THREAD

**Issue by possomcohen** [iamadamdev/bypass-paywalls-chrome#287]
Error - Cannot load extension with file or directory name thumbs.db. The filename is illegal.

Screenshots are attached for your review. Thank you
<img width="414" alt="Screen Shot 2019-09-02 at 10 56 35 AM" src="https://user-images.githubusercontent.com/24848225/64083272-1216e680-cd71-11e9-8368-6de3425b99cc.png">
<img width="671" alt="Screen Shot 2019-09-02 at 10 56 46 AM" src="https://user-images.githubusercontent.com/24848225/64083273-12af7d00-cd71-11e9-8b8a-d55b6cc6d7d1.png">

 very much.

**Comment by possomcohen** [comment]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
{
	"background": {
		"scripts": ["background.js"]
	},
	"content_security_policy": "script-src 'self' https://ssl.google-analytics.com; object-src 'self'",
	"browser_action": {
		"default_popup": "popup.html"
	},
	"description": "Bypass News Sites' Paywalls",
	"icons": {
		"128": "bypass.png"
	},
	"manifest_version": 2,
	"name": "Bypass Paywalls",
	"short_name": "Bypass Paywall",
	"options_ui": {
		"chrome_style": true,
		"page": "options.html"
	},
    "permissions": [ "cookies", "<all_urls>", "storage", "webRequest", "webRequestBlocking"],
	"version": "1.4.2"
}

**Comment by iamadamdev** [comment]
Remove thumbs.db file from the folder

**Comment by iamadamdev** [comment]
https://www.computerhope.com/issues/ch000871.htm
