### ISSUE TITLE
Why is "Allow access to file URLs" on by default, and is it needed?

### ISSUE THREAD

**Issue by NotTooComputerSavvy** [iamadamdev/bypass-paywalls-chrome#288]
For starters, I'm not too sure what "Allow access to file URLs" actually means for sure, but my understanding is that it allows an extension to read files on a users computer.

I really like this extension, and it's great for reading news, but when I found that this setting was turned on by default, it got me wondering why it needs to be turned on, and if my understanding of "Allow access to file URLs" is accurate.

Does this setting need to be turned on, and as a side note, is my understanding of the "Allow access to file URLs" setting accurate?

Thanks

**Comment by iamadamdev** [comment]
https://www.reddit.com/r/chrome/comments/ql1th/what_does_allow_access_to_file_urls_mean/c3yplcn?utm_source=share&utm_medium=web2x

**Comment by NotTooComputerSavvy** [comment]
My question was sparked by the linked thread, and their alarming wording on it, which didn't exactly sound right in the first place.

Thanks for getting back to me and clearing that up.

https://www.reddit.com/r/chrome/comments/2riz05/why_does_allow_access_to_file_urls_extension/
