### ISSUE TITLE
New Site Request: The Atlantic

### ISSUE THREAD

**Issue by sjeble** [iamadamdev/bypass-paywalls-chrome#291]
https://www.theatlantic.com/
They recently went to a metered paywall model

**Comment by lifehole** [comment]
The remove cookies extension resets the 4 article limit. But I would appreciate true support.

**Comment by magnolia1234** [comment]
In Europe no article-limit, just subscription-banner (javascript).

**Comment by magnolia1234** [comment]
Correction: I already blocked cookies ...
But simple adding site to options.js also works.

**Comment by iamadamdev** [comment]
Added
