### ISSUE TITLE
Site request: caixin.com / malfunction: caixinglobal.com

### ISSUE THREAD

**Issue by lishuhang** [iamadamdev/bypass-paywalls-chrome#292]
caixinglobal.com [has been supported for once](https://github.com/iamadamdev/bypass-paywalls-chrome/issues/39), but it doesn't working now.

caixin.com is the Chinese edition of Caixin Global. Now both caixin.com and caixinglobal.com are unable to be bypassed. pics below:

![image](https://user-images.githubusercontent.com/49574/64483465-a632f300-d234-11e9-8bb0-ffbce9616895.png)

![image](https://user-images.githubusercontent.com/49574/64483440-6409b180-d234-11e9-8f82-d78c16795789.png)

**Comment by iamadamdev** [comment]
Will be removed in the next version. You can paste the article title in incognito mode and read the article by clicking from the search results on google there.
