### ISSUE TITLE
First Things

### ISSUE THREAD

**Issue by levanrami** [iamadamdev/bypass-paywalls-chrome#299]
Please add First Things https://www.firstthings.com

**Comment by cimke** [comment]
Hello @levanrami could you specify where's the problem on the page? I can't see any paywalls

**Comment by iamadamdev** [comment]
Thank you @cimke for your help with these requests. I don't have time to handle them all anymore.

**Comment by cimke** [comment]
Hello @levanrami , I've opened a PR according to your request. 👍 

Also I'm happy to see that you, @iamadamdev, are still maintaining this project. Keep it up!
