### ISSUE TITLE
Please add lanacion

### ISSUE THREAD

**Issue by Diezi** [iamadamdev/bypass-paywalls-chrome#302]
Could you add www.lanacion.com.ar
I have tried with [(https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests)] without a problem
Thank you in advance!!!

**Comment by Diezi** [comment]
Hello @cimke , thank you for your quick reply. After you read a few articles, the paywall appears, asking you to subscribe to the newspaper.
 
![2019-09-16_173450_la_nacion](https://user-images.githubusercontent.com/30753312/64991624-96f11c80-d8a8-11e9-8b5f-7802a06dccd0.png)

**Comment by cimke** [comment]
@Diezi how many pages you've to visit before the paywall appears? Or maybe there is specific route?

Sorry for asking such questions, just want to be sure 👍

**Comment by Diezi** [comment]
@cimke , you have to open between 10-15 pages (newspaper articles) There are acumulative in the month. In private mode I have to close and re open the browser after reading all these articles.

**Comment by kimkha** [comment]
This site is working now. So we can close this issue, I think.
