### ISSUE TITLE
Financial Times stopped working

### ISSUE THREAD

**Issue by gello0** [iamadamdev/bypass-paywalls-chrome#308]
Tried on multiple devices, and seems like it's not working since past 2 days

**Comment by iamadamdev** [comment]
Works fine for me. Official Google Chrome browser, located in U.S. uBlock and my extension installed.

**Comment by sapote2241** [comment]
I've been using a script on Tampermonkey (Burlesco) to access the FT for the past six months.  It stopped working a few days ago. I use a Chromebox. iamadamdev, do you have a script that could be put on Tampermonkey in order to access this newspaper?

**Comment by cimke** [comment]
Just tested it with clean install, only this extension is installed, works perfectly

**Comment by sapote2241** [comment]
Success!  I just installed the extension. I just noticed that with this extension, the subscriber comments aren't visible. When I was using the Burlesco script on Tampermonkey, the Financial Times' comments WERE visible.  Can that be enabled with this extension somehow?

**Comment by gello0** [comment]
Ok so new build 1.5.3 is working on chrome desktop but not working in kiwi browser

**Comment by sapote2241** [comment]
It's working on 1.5.3, but the comments aren't visible. Is there any way to make them accessible (aside from subscribing)?

**Comment by magnolia1234** [comment]
Updating to v1.5.6 (this extension doesn't block the comments).

**Comment by sapote2241** [comment]
> Updating to v1.5.6 (this extension doesn't block the comments).

I'm currently on v1.5.3. You say that v1.5.6 shows the FT comments. I may download that one tomorrow.  But on your main page, it says "[Prepare] for v1.5.8". The word "Prepare" implies that it's not ready yet.  Am I reading that correctly?  If I click "Download this repo as a ZIP file from GitHub" tomorrow, will I get v1.5.6 or v1.5.8? Thanks.

**Comment by magnolia1234** [comment]
You'll get v1.5.8 indeed.
And yes, prepare-commit after release is confusing.

**Comment by sapote2241** [comment]
Pedestrian question, and I was able to do this two months ago, but I have the unzipped master file in the My Drive subsection folder of Google Drive. I believe I need to move it from there to the Downloads subsection of My Files - by dragging it. I did it twice, and then deleted everything and started all over because 1.5.8 wasn't showing up on the extensions page (developer mode is enabled).

**Comment by magnolia1234** [comment]
Load unpacked folder in extensions works for me.

**Comment by sapote2241** [comment]
Says: Failed to load extension
File
~/MyFiles/Downloads/bypass-paywalls-chrome-master.zip (Unzipped Files)
Error
Manifest file is missing or unreadable
could not load manifest

**Comment by magnolia1234** [comment]
Load subfolder with extension files.

**Comment by sapote2241** [comment]
Man, that took a long time.  A lot of trial and error. But it's working now. Thanks.

**Comment by sapote2241** [comment]
> Updating to v1.5.6 (this extension doesn't block the comments).

I've updated to v1.5.8, but the FT comments aren't showing. Do they only show in v1.5.6?

**Comment by magnolia1234** [comment]
Working just fine here (comments are below recommendations though). Maybe you're using another extension like uMatrix or NoScript?

**Comment by sapote2241** [comment]
Thanks. In Chrome settings, I had it set to block cookies from that site. I unblocked it. It's working now.

**Comment by sapote2241** [comment]
Want to mention that the extension is showing a large message, taking
up maybe 1/4 of the screen, noting that there are cookies on FT sites
and to "Accept and Continue". Clicking on each article causes that
message to be shown, as well as after hitting the back button to
return to the homepage.  Is there any way to block that pop-up in
future iterations?

**Comment by magnolia1234** [comment]
Use extension 'I don't care about cookies'.
