### ISSUE TITLE
Support for seekingalpha.com?

### ISSUE THREAD

**Issue by 420pitts** [iamadamdev/bypass-paywalls-chrome#31]
Articles on seekingalpha.com go behind a paywall after a period of time (maybe a week). Is it possible to bypass that?

https://seekingalpha.com/symbol/AMZN

![image](https://i.imgur.com/JxDDgpN.png)

But if you open that paywalled article in Incognito mode you can read the first page. I think if you disable certain scripts it can load the entire article in a single page (rather than putting them behind multiple pages, with the paywall engaging when you click to page 2). Ideally being able to read the comments on the page would be good as well.

Thanks

**Comment by iamadamdev** [comment]
If you login you should be able to read the comments. I'm not getting any paywall with uBlock Origin installed.
