### ISSUE TITLE
Harper's Mag not Working :/

### ISSUE THREAD

**Issue by hammy4242** [iamadamdev/bypass-paywalls-chrome#310]
Hiya, 

 extension seems to have stopped working for Harper's Mag. Would greatly appreciate it if it could get fixed. Thanks for your work -- it's been great reading articles I wasn't able to read before. You're a life-changer!!

**Comment by iamadamdev** [comment]
Which article are you having trouble with? I can still read some articles. Maybe you are running into a hard paywall.

**Comment by cimke** [comment]
Found the paywall, I'll create a PR soon.

**Comment by iscreamcoke** [comment]
Have you submitted the PR @cimke? Can't find it

**Comment by magnolia1234** [comment]
Works just fine after blocking nagscreens in ublock Origin:
harpers.org###issuem-leaky-paywall-articles-remaining-nag
harpers.org###wmpci-popup-wrp

**Comment by cimke** [comment]
Hello, @iscreamcoke sorry I've had some troubles in the past month, now I'm back and going to proceed or maybe you already have or want to push the solution? 🥇

**Comment by cimke** [comment]
@hammy4242 quick update.
This one will be fixed after merging the #357

**Comment by kimkha** [comment]
This site is working now. So we can close this issue, I think.
