### ISSUE TITLE
Scientific American not working in Chrome or Firefox

### ISSUE THREAD

**Issue by possomcohen** [iamadamdev/bypass-paywalls-chrome#312]
https://www.scientificamerican.com/article/the-contagion-of-corruption/

Blocked. Thanks.
<img width="1220" alt="Screen Shot 2019-09-24 at 9 26 33 AM" src="https://user-images.githubusercontent.com/24848225/65464249-6d8a4f00-dead-11e9-930e-c0bb8665d92f.png">

**Comment by cimke** [comment]
Looks like this is hardcoded paywall.

**Comment by kimkha** [comment]
@iamadamdev that article has a hard paywall, there is nothing we could do here. So the issue should be closed.
