### ISSUE TITLE
Extension is causing Chrome(77.0.3865.90) for Mac to freeze

### ISSUE THREAD

**Issue by TheKCDude** [iamadamdev/bypass-paywalls-chrome#313]
So I've been having problems with Chrome just freezing, then after a restart it works fine. It isn't a connectivity issue, as Safari works all along. When extension is disable Chrome works just fine.

I isolated extensions and this was the culprit. Verified with the task manager within Chrome that it was running the processor when nothing else was. Very strange. Seemed to be working great for a long time, not sure what changed. I haven't been paying attention much so maybe a Chrome update threw everything off.

Attached is a clipping from the task manager. 
![PaywallScreenshotGithub](https://user-images.githubusercontent.com/55768776/65555192-7b61c380-def1-11e9-9717-b46a5532ac04.jpeg)

**Comment by iamadamdev** [comment]
Version 77.0.3865.90 (Official Build) (64-bit) on macOS Mojave (10.14.16) is working fine for me.
![image](https://user-images.githubusercontent.com/36013816/66003659-9e452800-e45b-11e9-9e5c-7c11bee56e0e.png)

Must be some site you are visiting that is causing it to freeze?

**Comment by TheKCDude** [comment]
Maybe, I'm not sure. I was trying multiple sites and it seemed to just
happen. I'll keep trying. Although it seems to have died down, so perhaps
it was a weird tracking cookie or something causing a ruckus. Great
extension, thanks for putting it out there for us!

**Comment by iamadamdev** [comment]
Will close this issue for now.
