### ISSUE TITLE
"Could not unzip extension for install"

### ISSUE THREAD

**Issue by ahaq0** [iamadamdev/bypass-paywalls-chrome#315]
Keep getting this error whenever I try to install the extension in Chrome developer mode. Zipped it myself and still get the same thing. Any suggestions?

**Comment by magnolia1234** [comment]
Install from folder?

**Comment by sapote2241** [comment]
I have the same problem, as of today: Failed to load extension
File
/media/fuse/drivefs-826c2e562447a7d1b2d0520c81d4908d/root/bypass-paywalls-chrome-master.zip (Unzipped Files)
Error
Manifest file is missing or unreadable
Could not load manifest

**Comment by cimke** [comment]
As @magnolia1234 already wrote, you've to **unzip the archive and then load it as a folder**. 

As long as this is how development mode extensions works (not with zip files), could we close this issue @iamadamdev
