### ISSUE TITLE
bloomberg no longer working

### ISSUE THREAD

**Issue by tarungog** [iamadamdev/bypass-paywalls-chrome#316]

**Comment by iamadamdev** [comment]
which article?

**Comment by sapote2241** [comment]
For me, this one - https://www.bloomberg.com/opinion/articles/2018-04-26/why-orthodox-christian-nations-remain-stuck

**Comment by SiliconWafer** [comment]
This article as well: https://www.bloomberg.com/news/articles/2018-01-17/how-a-22-year-old-discovered-the-worst-chip-flaws-in-history
