### ISSUE TITLE
Extension randomly disappears from browser.

### ISSUE THREAD

**Issue by DBStage1** [iamadamdev/bypass-paywalls-chrome#317]
Using chrome browser - Vivaldi - and only the bypass extension randomly disappears and have to reinstall.  Not a deal killer just weird.  Thks

**Comment by kimkha** [comment]
I've tried Vivaldi, there is no issues. Can you please confirm again? With the latest version, of course.

**Comment by DBStage1** [comment]
Sorry with new Vivaldi no more issues.  Thanks for all your great work making this.

Cheers
Kirk

⁣

Sending this from my phone call me if time sensitive. ​


-------- Original Message --------
