### ISSUE TITLE
wsj.com stopped working a week or two ago

### ISSUE THREAD

**Issue by tlongstretch** [iamadamdev/bypass-paywalls-chrome#320]
Using newest version

**Comment by kljb** [comment]
same

**Comment by kljb** [comment]
@iamadamdev any news?

**Comment by iamadamdev** [comment]
Which article isn't working for you? Where are you located?
Most front page articles still work for me.

**Comment by tlongstretch** [comment]
none work for me.  Just tried the first four headlines on front page.   

https://www.wsj.com/articles/pompeo-vows-to-block-efforts-to-bully-state-department-officials-to-testify-about-ukraine-11569940841?mod=rsswn&mod=hp_lead_pos2
https://www.wsj.com/articles/visa-mastercard-others-reconsider-involvement-in-facebook-s-libra-network-11569967023?mod=hp_lead_pos3
https://www.wsj.com/articles/tense-relationship-between-barr-and-giuliani-complicates-trump-impeachment-defense-11569942261?mod=hp_lead_pos1

All show paywall.  East coast USA, tried at home and office.

**Comment by kljb** [comment]
I tried to open this one: https://www.wsj.com/articles/since-receiving-softbanks-300-million-check-wag-has-gained-little-ground-11556232359?mod=rsswn and it's not working. Nevertheless, I still can open articles from the front page, so it's weird.  (Russia, Chrome)

**Comment by bacon8474** [comment]
I can't open articles either

**Comment by iamadamdev** [comment]
that one is a premium article, it says "PRO VC COMMENTARY ANALYSIS" at the top.
I can still open https://www.wsj.com/articles/visa-mastercard-others-reconsider-involvement-in-facebook-s-libra-network-11569967023?mod=rsswn though

**Comment by iamadamdev** [comment]
Try clearing storage manually? Right click on the WSJ page -> Inspect -> Application tab -> Clear storage -> scroll down a little to "Clear site data" under the graph

**Comment by tlongstretch** [comment]
The clearing storage manually worked to fix some articles.  I got it to work with two, but two others did not work - one still shows paywall other doesn't show paywall but only shows the first couple lines of the article that the preview normally shows.
