### ISSUE TITLE
[Request] The Hindu

### ISSUE THREAD

**Issue by Jadax** [iamadamdev/bypass-paywalls-chrome#321]
Requesting a bypass for the following site: 

https://www.thehindu.com/

**Comment by iamadamdev** [comment]
Did you try it first? https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by kimkha** [comment]
This site is working now. So we can close this issue, I think. E.g https://www.thehindu.com/data/covid-19-state-wise-tracker-for-coronavirus-cases-deaths-and-testing-rates/article31248444.ece?homepage=true
