### ISSUE TITLE
How to use in Opera?

### ISSUE THREAD

**Issue by jp-coetzee** [iamadamdev/bypass-paywalls-chrome#322]
I know that Opera can use Chrome extensions, but how can I use this one?

many thanks

**Comment by magnolia1234** [comment]
Install crx-file (releases).

**Comment by jp-coetzee** [comment]
That works, thanks. It's not possible to set any options in Opera i.e. I cannot access the page with all the tickboxes, but it seems to be working on the sites I want.

**Comment by magnolia1234** [comment]
Weird, but you can also reach the options by clicking on the extension icon (top right).

**Comment by jp-coetzee** [comment]
Perfect, thanks
