### ISSUE TITLE
Paris Review

### ISSUE THREAD

**Issue by arsalan14** [iamadamdev/bypass-paywalls-chrome#323]
Hi, can you add the Paris Review to the list of websites? Thanks! 

https://www.theparisreview.org/

**Comment by iamadamdev** [comment]
Did you try it? https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by magnolia1234** [comment]
Some articles with hard paywall.

**Comment by kimkha** [comment]
I think this website doesn't have any paywall. E.g https://www.theparisreview.org/blog/2020/04/24/staff-picks-kentuckis-kerchiefs-and-choreography/

We could close this issue.

**Comment by skiprox** [comment]
it has a paywall https://www.theparisreview.org/fiction/6170/disgust-ottessa-moshfegh

**Comment by affrxn** [comment]
@kimkha The website does have a paywall. There are a few articles available to the public that are released monthly, but otherwise there is a very substantial paywall. Please consider reopening the issue. See: https://www.theparisreview.org/poetry/3924/two-poems-ameen-alwan

**Comment by kimkha** [comment]
Okay, it has paywall.

Anyone success in bypassing it using this guide? https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

If not, then this plugin can't do anything.
