### ISSUE TITLE
Please bypass La Tercera

### ISSUE THREAD

**Issue by ronzalo** [iamadamdev/bypass-paywalls-chrome#324]
https://www.latercera.com

**Comment by iamadamdev** [comment]
Please confirm it works first: https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by ronzalo** [comment]
It works

**Comment by iamadamdev** [comment]
Can you submit a PR for it? Update background.js, options.js, and README.md

**Comment by kimkha** [comment]
This site is working now. So we can close this issue, I think. E.g https://www.latercera.com/que-pasa/noticia/de-18-a-22-horas-semanales-el-fuerte-aumento-de-uso-de-aplicaciones-de-los-chilenos/CKTPYU4FHBDLDIH6BO7KGCGGFE/
