### ISSUE TITLE
 haaretz.co.il stopped working

### ISSUE THREAD

**Issue by danid12** [iamadamdev/bypass-paywalls-chrome#325]
it seems that the extension is not working at themarker.com also

still working fine in haaretz.com

**Comment by iscreamcoke** [comment]
Hi, you can use the [Firefox version](https://github.com/iamadamdev/bypass-paywalls-firefox) until the issue is fixed for Chrome. I've just tried and it works

**Comment by kimkha** [comment]
@danid12 Can you confirm it with the latest version? I think it works now, but you need to turn off adblock (if any).
