### ISSUE TITLE
Extension not working on medium.com on Chrome

### ISSUE THREAD

**Issue by filippinheiro** [iamadamdev/bypass-paywalls-chrome#326]
Chrome version: 77.0.3865.90 64 bits
Windows 10 OS Version 1903 (Build 18362.356)

It's not bypassing the medium paywall on my Chrome, when I added the extension, the browser gave me 2 errors and 1 warning, it might be it. 

" Uncaught ReferenceError: browser is not defined
Context
popup.html
Stack Trace
version.js:1 (função anônima)
var manifestData = browser.runtime.getManifest();
var versionString = 'v' + manifestData.version;
document.getElementById('version').innerText = versionString; "

" Uncaught ReferenceError: browser is not defined
Context
_generated_background_page.html
Stack Trace
background.js:181 (função anônima)

 browser.storage.sync.get({
  sites: {}
}, function(items) {
  var sites = items.sites;
  enabledSites = Object.keys(items.sites).map(function(key) {
    return items.sites[key];
  }); "

**Comment by kimkha** [comment]
@filippinheiro Can you check again? I think it's fine now at the latest version.
