### ISSUE TITLE
businessinsider.com acting if checked on install.

### ISSUE THREAD

**Issue by pjpreilly** [iamadamdev/bypass-paywalls-chrome#329]
The Business Insider site is initially unchecked but the extension is processing it as if checked on initial install (out of sync). If you open the menu & just save it brings it back into sync.

**Comment by pjpreilly** [comment]
It was investigating why the photos weren't being displayed correctly & it led me to this issue.

**Comment by kimkha** [comment]
Is it okay now? I don't see any problem.

If it works to you now, we should close this issue.

**Comment by pjpreilly** [comment]
Close it if you fixed & tested it....

**Comment by kimkha** [comment]
I can't close it. @iamadamdev
