### ISSUE TITLE
TheStar.com is possible to bypass

### ISSUE THREAD

**Issue by agret** [iamadamdev/bypass-paywalls-chrome#332]
https://www.thestar.com/news/canada/2019/10/05/pirate-website-sci-hub-is-making-the-worlds-academic-research-free-to-all-but-at-what-cost.html

It comes up with a paywall for me immediately then when I refreshed it said i'd read my limit of free articles (it's my first time coming to this site!) but when the page is first loading I can see all of the text briefly before it's hidden by the paywall. View Source also displays that the article text is definitely sent to the user even when the paywall is presented.

**Comment by vic958420** [comment]
So what's the issue? I can assess all articles on thestar.com just fine (no images because javascript is disabled; see [https://github.com/iamadamdev/bypass-paywalls-firefox/issues/234](url))
