### ISSUE TITLE
Request: The Philadelphia Inquirer (inquirer.com)

### ISSUE THREAD

**Issue by supermarkert** [iamadamdev/bypass-paywalls-chrome#333]
Paywall bypassed with incognito Google search.

**Comment by iscreamcoke** [comment]
you can use [Adam's extension](https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce) (or [that one](https://chrome.google.com/webstore/detail/disable-cookies/lkmjmficaoifggpfapbffkggecbleang)) for now. Just click the cookie extension when you're on the website.

I'll do a pull request in the coming days.

**Comment by kimkha** [comment]
This site is working now. So we can close this issue, I think. E.g https://www.inquirer.com/eagles/carson-wentz-eagles-draft-receivers-rep1-agency-20200418.html
