### ISSUE TITLE
Not working in Kiwi browser?

### ISSUE THREAD

**Issue by magnolia1234** [iamadamdev/bypass-paywalls-chrome#336]
Extension not working in Kiwi browser (both with cookies as javascript), but no problems in Yandex browser. Both are mobile Android Chromium browsers. Any suggestions?

**Comment by magnolia1234** [comment]
Solved. Loading crx works, but not if you load by folder.
Thanks to @Safekeep in #198

**Comment by magnolia1234** [comment]
* both loading by crx or folder installs extension, but no effect on websites

**Comment by gello0** [comment]
This extension is not working for some reason you can use this extension instead 
[https://chrome.google.com/webstore/detail/eningockdidmgiojffjmkdblpjocbhgh
](url) 
![Screenshot_20191102-224915_Kiwi_Browser](https://user-images.githubusercontent.com/28871862/68074683-da093f80-fdc3-11e9-8b02-02357af75057.png)

**Comment by magnolia1234** [comment]
Right, a Header Editor ...

**Comment by magnolia1234** [comment]
Now I'm using Yandex Browser (Chromium) or Firefox on Android.
Kiwi is just terrible at extensions ...
