### ISSUE TITLE
Website request

### ISSUE THREAD

**Issue by luckydawg78** [iamadamdev/bypass-paywalls-chrome#337]
I was wondering if you could do The Athletic

**Comment by iscreamcoke** [comment]
It looks like a hardcoded paywall

**Comment by kimkha** [comment]
This site is working now. So we can close this issue, I think. E.g https://theathletic.com/1769330/2020/04/24/if-there-is-a-postseason-why-jazz-thunder-is-a-thrilling-first-round-series/
