### ISSUE TITLE
unable to bypass NYT, The Times (UK), WSJ, Telegraph (UK)

### ISSUE THREAD

**Issue by goL-prog** [iamadamdev/bypass-paywalls-chrome#340]
using Chrome v. 77 (or 76 for that matter). using ublock origin.

**Comment by anishmittal2020** [comment]
![image](https://user-images.githubusercontent.com/42092626/66640186-c03b6900-ec18-11e9-96af-5cdd87871e66.png)

![image](https://user-images.githubusercontent.com/42092626/66640176-b74a9780-ec18-11e9-8431-d60a5d131d44.png)

**Comment by waynezo** [comment]
I am having the same problem with NYT

**Comment by cpellegrino** [comment]
same problem here, can't access NYT

**Comment by tarungog** [comment]
https://www.nytimes.com/2019/10/12/business/pge-california-outage.html

can't access this myself

BP v1.5.2
Chrome Version 77.0.3865.90
uBlock Origin 1.22.4

**Comment by xih** [comment]
Can't access the NYT PG&E article as well

**Comment by linghutf** [comment]
neither do I

**Comment by magnolia1234** [comment]
All sites working (almost) just fine. But looks like cookie-delete timing issue on wsj.com and telegraph.co.uk. After page-refresh of these two sites bypass of paywall works again.
Btw extension sets user-agent to Googlebot for the English papers.

**Comment by goL-prog** [comment]
WSJ seems to work OK for now. Ditto for NYT. The Telegraph still does not (@magnolia1234: not sure whether and how the user-agent setting is relevant for the extension use with the UK papers -- please explain if possible).

**Comment by magnolia1234** [comment]
Some papers give access to Google/Facebook for linking or indexing, hence the feature to set referer or user-agent in background.js.
Someone had a issue with the Firefox extension on thetimes.co.uk while using a custom user-agent extension.

**Comment by sjeble** [comment]
Add The Atlantic to those sites that no longer work as well

**Comment by magnolia1234** [comment]
No problems with the Atlantic here either (latest Chrome 77 version)  ...
Maybe some interference with other extensions (uBlock Origin and Disconnect are fine)?

**Comment by vacy3** [comment]
NYT not working for me. Using with uBlock Origin

**Comment by iscreamcoke** [comment]
I did a small modification on the background.js that should fix the issue for the New York Times. Can you test it on your side from [my fork](https://github.com/iscreamcoke/bypass-paywalls-chrome) so that I'm sure it works for everyone. I'll do pull request thereafter

**Comment by walthowd** [comment]
@iscreamcoke Your fork is working for my on NYT.  Mac, Chrome Version 77.0.3865.90, uBlock Origin
1.22.4

**Comment by iscreamcoke** [comment]
Great to hear! I'm going to try fixing the other sites when I have the time to do so

**Comment by iscreamcoke** [comment]
Quick follow-up: the WSJ works for me (just had to close a pop-up), as did The Telegraph and the Times (the "continue reading" is moved at the end but the articles appear complete).

At first sight, we just need to hide the pop-up on the WSJ and the "continue reading" on the Times.

MacOs 10.14.5
Chrome 78.0.3904.50 (Official Build) beta
Tested with Nano Adblocker 1.0.0.128, then with uBlock Origin 1.22.4

**Comment by iscreamcoke** [comment]
The Atlantic:

www.theatlantic.com##.c-nudge__spacing-container
www.theatlantic.com##.c-nudge-compressed__container.c-nudge__container

The WSJ

www.wsj.com###cx-article-cover-image

The Times

www.thetimes.co.uk##.Article-container.ArticleMarketing--footer.ArticleMarketing.subscription-block

**Comment by waynezo** [comment]
still not working on NYT.  Is there some kind of update  I need to do?

**Comment by magnolia1234** [comment]
NYT working either way fo me, but a Mac fix may be usefull.
Footers and banners can be hidden by uBlock Origin (or other Adblocker). Maybe more flexible over time?

**Comment by iscreamcoke** [comment]
@matnolia1234 a middle solution would be to create a block-elements.txt in the repo. 

You’ll thus be able to either import the .txt to your Adblock or call it from background.js.

But the main issue now is that Adam, the repo owner, hasn’t accepted a PR merging for 2 weeks now haha

**Comment by magnolia1234** [comment]
Patience, Adrien ;-)

**Comment by waynezo** [comment]
> @waynezo you can use my fork until Adam comes back. You’ll find the link above

Your fork works for NYT :)  Thanks for the help!

**Comment by goL-prog** [comment]
> using Chrome v. 77 (or 76 for that matter). using ublock origin.



> The Atlantic:
> 
> [www.theatlantic.com##.c-nudge__spacing-container](http://www.theatlantic.com##.c-nudge__spacing-container)
> [www.theatlantic.com##.c-nudge-compressed__container.c-nudge__container](http://www.theatlantic.com##.c-nudge-compressed__container.c-nudge__container)
> 
> The WSJ
> 
> [www.wsj.com###cx-article-cover-image](http://www.wsj.com###cx-article-cover-image)
> 
> The Times
> 
> [www.thetimes.co.uk##.Article-container.ArticleMarketing--footer.ArticleMarketing.subscription-block](http://www.thetimes.co.uk##.Article-container.ArticleMarketing--footer.ArticleMarketing.subscription-block)

your fork works for me - WSJ, the times, NYT, FT... thk u!!!!

**Comment by goL-prog** [comment]
will leave this thread open for others...

**Comment by magnolia1234** [comment]
@goL-prog interesting, new fork 'only' contains fix for NYT :-)

**Comment by goL-prog** [comment]
duh... maybe I messed the original install -- it stopped working after Chrome auto-upgraded a couple of  days ago.  i plead ignorance - whatever works ;-)

**Comment by asquonk** [comment]
@waynezo I don't see a fork under your name in the Forks list. Am I missing something?

**Comment by iscreamcoke** [comment]
@asquonk et al., I wrote a tuto [here](https://github.com/iamadamdev/bypass-paywalls-chrome/issues/347) so that everyone can easily fix the issue

**Comment by vacy3** [comment]
Thanks @iscreamcoke your fork works for me as well. Windows 10

**Comment by iscreamcoke** [comment]
@iamadamdev has updated the extension. Everything is back on track now

**Comment by goL-prog** [comment]
all good  @iamadamdev @iscreamcoke - thank you!
