### ISSUE TITLE
Bypass Paywalls Site Request: San Diego Union Tribune

### ISSUE THREAD

**Issue by mittalar** [iamadamdev/bypass-paywalls-chrome#341]
Opening this article through incognito Google search worked, so hopefully you're able to add this the San Diego Union Tribune to your list of sites.

https://www.sandiegouniontribune.com

Thanks, and I love your extension!

**Comment by iscreamcoke** [comment]
you can use [this extension](https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce) or [that one](https://chrome.google.com/webstore/detail/disable-cookies/lkmjmficaoifggpfapbffkggecbleang) for now. Just click the cookie extension when you're on the website.

I'll do a pull request in the coming days.

**Comment by kimkha** [comment]
This site is working now. So we can close this issue, I think. E.g https://www.sandiegouniontribune.com/business/tourism/story/2020-04-19/a-zoo-without-visitors-animal-care-goes-on-as-revenue-stream-disappears
