### ISSUE TITLE
Chrome on Windows: instructions on enabling custom extension

### ISSUE THREAD

**Issue by nakigoe** [iamadamdev/bypass-paywalls-chrome#342]
Hello Adam,
I've gathered awesome instructions on how to enable Your wonderful extension for Chrome on Windows without any irritating remarks from the Chrome itself:
<h2>Custom Chrome Extension Installation</h2>
	<ol>
	<li>UnZip the extension, remember the folder location</li>
	<li>Run Chrome</li>
	<li>Open chrome://extensions/</li>
	<li>Choose Pack extension</li>
	<li>Choose the unpacked folder, press Pack extension</li>
	<li>Drag and drop the formed .crx file into the Chrome window chrome://extensions/</li>
	<li>Mark the ID of the extension (Copy and Paste into any text editor)</li>
	<li>Click Start, Run, or press <kbd>Win</kbd> + <kbd>R</kbd></li>
	<li>run Group Policy Editor to whitelist the extension: <em>gpedit.msc</em></li>
	<li>Pick User Configuration / Administrative Templates / Google Chrome / Extensions / Configure extension installation whitelist</li>
	<li>Choose "Enabled", then click "Show..."</li>
	<li>Double-click to enter the ID for the extension, Apply</li>
	<li>Restart Chrome</li>
	</ol>

**Comment by kimkha** [comment]
Correct me if I'm wrong, but I feel like this is a spam message.

**Comment by nakigoe** [comment]
You should have been grateful for the list of instructions...

**Comment by kimkha** [comment]
First, I'm not the owner, I have no right to do. If you want, please make a PR, instead of filling an issue here.

Second, WSJ works for me. If it doesn't fit you, please provide the URL.

Third, I don't think a grateful behaviour is sending another tool and ask people to leave this extension. We should help the author to improve it.
