### ISSUE TITLE
Request: Los Angeles Business Journal (labusinessjournal.com)

### ISSUE THREAD

**Issue by antiguestism** [iamadamdev/bypass-paywalls-chrome#343]
Paywall bypassed with incognito Google search

**Comment by iscreamcoke** [comment]
you can use[ this extension](https://chrome.google.com/webstore/detail/disable-cookies/lkmjmficaoifggpfapbffkggecbleang) for now. Just click the cookie extension when you're on the website.

I'll do a pull request in the coming days.

**Comment by kimkha** [comment]
This site is working now. So we can close this issue, I think. E.g https://labusinessjournal.com/news/2020/apr/17/la-county-unemployment-rate-jumped-march-6-percent/
