### ISSUE TITLE
Statista paywall not being bypassed

### ISSUE THREAD

**Issue by niseione** [iamadamdev/bypass-paywalls-chrome#344]
The Statista website allowed a single view of a page. Upon returning a pop-down covered the content requesting membership to view. I deleted the cookies from the site, and the paywall still blocked the content/page. Hopefully, there will be a fix to get around this one.
Thanks for the great add-on!

![Screenshot_2019-10-14 U S cable news network viewership 2019 Statista](https://user-images.githubusercontent.com/20881073/66770112-a2b20d80-ee6b-11e9-94c1-41508a34b22f.png)

**Comment by iscreamcoke** [comment]
I'm not able to replicate the issue. Can you try reinstalling both the extension and your adblocker?

MacOs 10.14.5
Chrome 78.0.3904.50 (Official Build) beta
uBlock Origin 1.22.4
