### ISSUE TITLE
[How-To] Fix the NYT issue

### ISSUE THREAD

**Issue by iscreamcoke** [iamadamdev/bypass-paywalls-chrome#347]
An issue has appeared on the New York Times recently. This is, at first sight, a Mac-only one. I have already proposed a pull request on this repo. It should fix the problem. But as the repo owner and original creator of the extension, Adam (all credits to him), hasn't logged in for 15 days, you can use the following solution to fix the issue until he comes back:

You can either:
- modify the background.js file on your computer according to this [pull request](https://github.com/iamadamdev/bypass-paywalls-chrome/pull/346)
- or, if you don't want to modify code, just use [the fork](https://github.com/iscreamcoke/bypass-paywalls-chrome) I did that already contains my two pull requests (it fixes the NYT & adds [Loeb Classical Library](https://www.loebclassics.com/))

When the extension is eventually updated, you'll just have to re-install Adam's version, which is the only definitive one.

The Atlantic, the WSJ and The Times (of London) should work without any change, but if you're bothered with the pop-ups and footers, you can add those lines into the filter/block list of your Adblocker (on uBlock Origin: open the dashboard > click "my filters"):

```
www.theatlantic.com##.c-nudge__spacing-container
www.theatlantic.com##.c-nudge-compressed__container.c-nudge__container
www.wsj.com###cx-article-cover-image
www.thetimes.co.uk##.Article-container.ArticleMarketing--footer.ArticleMarketing.subscription-block
```

**Comment by pal2002** [comment]
This worked for me. It's not a mac only issue btw.

**Comment by rpodric** [comment]
Does the above possibly relate to a relatively new issue with NYT (seemingly Chrome only) in which URLs starting with "interactive," like this one:

`https://www.nytimes.com/interactive/2019/10/15/us/elections/debate-speaking-time.html`

Are blocked, coming up with a "Keep reading The Times by creating a free account or logging in" message?

_Note that I'm speaking here only of once you've exceeded your free article count, not before._  If you clear NYT cookies to reset the count, you can view "interactive" articles until you hit the count again.

All links without "interactive" at the start of the URL work fine regardless of count and without worrying about cookies, so it's a very specific issue with just those kind of URLs, which are in the definite minority of URLs on that site, thankfully.
