### ISSUE TITLE
The Globe and Mail isn't working

### ISSUE THREAD

**Issue by andtheseashalltell** [iamadamdev/bypass-paywalls-chrome#348]
Mac OS/X

**Comment by iscreamcoke** [comment]
I'm not able to replicate the issue. Can you link which article isn't working please?

**Comment by andtheseashalltell** [comment]
https://www.theglobeandmail.com/business/article-snc-lavalin-lays-off-unannounced-number-of-canadian-employees/?fbclid=IwAR3FhKbdDbG-EPW6aJ1VIaPli_SgotXcyS67fb-U--GAXDKGKw3NUkj7h7A

**Comment by andtheseashalltell** [comment]
er, https://www.theglobeandmail.com/business/article-snc-lavalin-lays-off-unannounced-number-of-canadian-employees/

sorry, no id intended

**Comment by iscreamcoke** [comment]
![gif](https://user-images.githubusercontent.com/17458353/66908241-07579e80-f00b-11e9-8a0d-c026a8aea614.gif)

I'm not hitting the paywall. The only issue is the pictures not loading (MacOS/Chrome 78.0.3904.50 beta). You should try reinstalling the extension and/or your adblocker

**Comment by janvier25** [comment]
https://www.theglobeandmail.com/canada/toronto/article-mark-saunders-stepping-down-as-torontos-police-chief/
We're sorry but we are unable to validate your access to this article. Please adjust your browser settings or turn off any extensions that may be causing this issue.

**Comment by iamadamdev** [comment]
Still working fine for me:
![image](https://user-images.githubusercontent.com/36013816/84096273-6319d200-a9b6-11ea-8e42-a871c4e7d2d1.png)

**Comment by llacb47** [comment]
The code responsible:
```
                (function() {
                    function verifyContent(skip) {
                        if (!skip) {
                            var isStory = document.documentElement.classList.contains("story");
                            var status = isStory && window.tgam.meta.paywallStatus;
                            var protectedContent = isStory && ["red", "yellow"].includes(status);
                            if (!isStory || !protectedContent)
                                return
                        }
                        document.documentElement.classList.add("no-linkedjs");
                        var body = document.querySelector(".js-c-article-body");
                        var p = document.createElement("p");
                        p.setAttribute("id", "nolinkedjs-message");
                        p.setAttribute("class", "c-article-body__text");
                        p.innerHTML = 'We\'re sorry but we are unable to validate your access to this article. Please adjust your browser settings or turn off any extensions that may be causing this issue.\x3cbr/\x3e\x3cbr/\x3eFor more help please visit our \x3ca href\x3d"/about/help/troubleshooting/"\x3eDiagnostic \x26 Troubleshooting page\x3c/a\x3e.';
                        body && body.appendChild(p)
                    }
                    if (window.tgam.linkedScriptIntegrity !== 258958)
                        verifyContent();
                    window.addEventListener("contentIntegrityCompromised", function() {
                        verifyContent(true)
                    })
                }
                )();
```
