### ISSUE TITLE
Installation instructions are incorrect

### ISSUE THREAD

**Issue by gsdefender** [iamadamdev/bypass-paywalls-chrome#35]
Hi, I've tried installing the extension by drag-and-dropping the folder into chrome://extensions but it doesn't work.

I did this instead:

1. Open chrome://extensions, and switch "Enable developer mode" on.
2. Click on "Pack extension", and choose the bypass-paywalls-chrome-master folder you have extracted from the ZIP file. 
3. Drag-and-drop the generated .crx file into chrome://extensions. It's in the bypass-paywalls-chrome-master parent directory.

**Comment by mikhoul** [comment]
Here what I use in my extension to show to users how to install, feel free to use it if you want:

**How to install the extension:**

    1- Download the zipped chrome-extension directory
	2- Unzip the archive on your computer in a folder
	3- Go to "chrome://extensions
	4- Enable the Dev Mode in Chrome
	5- Click "load unpacked extension"
	6- Choose the directory you downloaded it to.



Regards :octocat:
