### ISSUE TITLE
Quora does not work correctly

### ISSUE THREAD

**Issue by ivigamberdiev** [iamadamdev/bypass-paywalls-chrome#351]
For long answers Quora used button 'Continue Reading', but with extension this button replaced with '(more)'. After click on '(more)' a notification appears 'Something went wrong. Please try again.'. If you turn off Quora inside the extension options, then everything works.
Example:
https://www.quora.com/What-is-a-FPGA-and-what-does-it-do
Screenshot for Firefox only because I don't use Chrome on this PC, but bug is reproducing also in Chrome now, where I first discovered it.
![Screenshot from 2019-10-18 13-53-38](https://user-images.githubusercontent.com/26900553/67088883-f0ea4800-f1ae-11e9-8bbd-57626ab48092.png)

**Comment by wonjoonSeol** [comment]
I have the same issue on Chrome

**Comment by kimkha** [comment]
I think this issue is solved. Can anyone confirm?
