### ISSUE TITLE
Belgian Newspaper request?

### ISSUE THREAD

**Issue by MrKim42** [iamadamdev/bypass-paywalls-chrome#352]
Awesome work man ! 
Would it be easy for you to add this website to the list? 

www.lecho.be

**Comment by kimkha** [comment]
This site is working now. So we can close this issue? E.g https://www.lecho.be/entreprises/construction/l-image-positive-chez-deceuninck-va-changer-radicalement/10221653.html

**Comment by iamadamdev** [comment]
Thank you for all your help @kimkha
