### ISSUE TITLE
Bypass For Foreign Policy Not Working

### ISSUE THREAD

**Issue by sapote2241** [iamadamdev/bypass-paywalls-chrome#355]
https://foreignpolicy.com/

**Comment by magnolia1234** [comment]
Still working fine, but site is reloading if you disable 3rd party cookies in Chrome settings (you can't set an exception for a single site).

**Comment by sapote2241** [comment]
I went into Chrome settings and blocked cookies from that one site. It seems to be working  O.K. now. Is that what you were suggesting to do?

**Comment by magnolia1234** [comment]
Not exactly, but that's indeed working even better than extension. It also worked for me with extension, but lots of reloading while blocking 3rd party cookies.

**Comment by magnolia1234** [comment]
Adguard app on Android also blocks FP paywall:
||onecount.net^$third-party

**Comment by sapote2241** [comment]
After blocking cookies on Chrome, which bypasses the paywall, I notice that none of the  images in articles are loading, just a circle turning round and round. If I instead, choose "clear [cookies] on exit", I get the images but wind up outside the paywall.

**Comment by kimkha** [comment]
This site is working now, e.g https://foreignpolicy.com/2020/04/20/brazil-jair-bolsonaro-coronavirus-denialism-fire-mandetta-mourao-wont-hurt-him/. We should close this issue.
