### ISSUE TITLE
Bypass Paywalls Site Request: Le Monde

### ISSUE THREAD

**Issue by MrKim42** [iamadamdev/bypass-paywalls-chrome#356]
It's a big French newspaper. Like the New York Times, but for France. 
That'd be amazing if it could be added to the list !

**Comment by MrKim42** [comment]
I'm not a very good coder at all. 

I tried to play with the html source of the page, and I think the only thing that needs to be deleted to get access to the rest of the article is deleting those lines: 

1) <section class="paywall"> ... </section>
2) <footer class="footer footer--free  old__footer"> ... </footer>

**Comment by magnolia1234** [comment]
See PR #357 for removing paywall while keeping recommendations and footer.

**Comment by kimkha** [comment]
@iamadamdev I think you just removed this site, then close this issue?
