### ISSUE TITLE
bizjournals problem

### ISSUE THREAD

**Issue by buckrogerss** [iamadamdev/bypass-paywalls-chrome#358]
Hi, The Business Journals domain hasn't been working for a while for me (blank pages or no photos), but the new version throws an "Additional security check is required" error that goes into an endless loop of checking the captcha. This is w/ and w/o ublock and javascript. Screenshot attached
![bizjournals](https://user-images.githubusercontent.com/49368126/67241514-90167600-f421-11e9-9e32-06733db06879.gif)

**Comment by magnolia1234** [comment]
No captcha's for me though, but BP blocks javascript on this site (hence no pictures in articles).

**Comment by kimkha** [comment]
I just tried to bypass this https://www.bizjournals.com/sanjose/news/2020/04/16/pandemic-has-startups-looking-for-help-from-source.html, but thing's a bit complicated. Anyone has time to dig deeper on this site? I'm pretty sure that we can, just need the proper way to do so.

**Comment by iamadamdev** [comment]
After arriving at the locked page, just refresh it. I was able to load all the paywalled articles including the one you posted this way.

**Comment by kimkha** [comment]
I'm not sure how, the only way that I can see the article is disabling JS.

**Comment by kimkha** [comment]
Oh, now it works. 🤷‍♀️
