### ISSUE TITLE
Seeking Alpha

### ISSUE THREAD

**Issue by mxxmxm** [iamadamdev/bypass-paywalls-chrome#359]
Requesting seekingalpha.com be added. Have tested paywall and works through google search link.

**Comment by oneninetyeight** [comment]
I second this. Thanks!

**Comment by christonagu** [comment]
I agree.. Pleaseee add seekinglpha.com

**Comment by BalintFarkas** [comment]
I think it's been added. I have version 1.6.3 and SeekingAlpha.com is in the options list.

**Comment by kimkha** [comment]
@iamadamdev this issue should be closed. Thanks
