### ISSUE TITLE
WSJ Not Working

### ISSUE THREAD

**Issue by khxv** [iamadamdev/bypass-paywalls-chrome#361]
WSJ stopped working.  Anyone having the same issue?

Thanks!

**Comment by MPlatz1** [comment]
Yes, same issue

**Comment by SantaCruzJoe** [comment]
Same for me

**Comment by njchurchill** [comment]
Same for me

**Comment by ajscalia** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/360#issuecomment-545911860

**Comment by operahouserat** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/360#issuecomment-545911860

**Comment by khxv** [comment]
working again for me, thanks!

**Comment by iamadamdev** [comment]
Merged the fix (thanks guys), try v1.5.6
