### ISSUE TITLE
Add Le Parisien

### ISSUE THREAD

**Issue by jimmydeuxfois** [iamadamdev/bypass-paywalls-chrome#363]
Please add Le Parisien. http://www.leparisien.fr/culture-loisirs/tv/chez-didier-la-star-de-l-amour-est-dans-le-pre-20-10-2019-8176713.php

You just have to hide .relative.piano-paywall.below_nav.sticky and .margin_bottom_md (with document.querySelector and removeDOMElement), then to change the style of the class 'content' to unblur the article.

**Comment by kimkha** [comment]
This site is working now. So we can close this issue, I think.
