### ISSUE TITLE
Request: support for DarkReading and csoonline

### ISSUE THREAD

**Issue by Moxville** [iamadamdev/bypass-paywalls-chrome#367]
I request to add support for the following sites (Chrome and Firefox)
I use Chromium based Vivaldi browser and Firefox browser in Windows 10 

DarkReading >> 2 articles is the limit. Beyond that user need to register and login
https://www.darkreading.com/
![Untitled1](https://user-images.githubusercontent.com/31923265/67579667-88790900-f762-11e9-8d92-a49f9f511511.png)

csoonline >> Need to register to continue reading the article
https://www.csoonline.com/article/3446458/5-cloud-security-basics-and-best-practices.html
![Untitled2](https://user-images.githubusercontent.com/31923265/67579714-a6df0480-f762-11e9-95a9-434ff4ace145.png)

Thanks in Advance :)

**Comment by iamadamdev** [comment]
Dark Reading can be bypassed with https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce

**Comment by Moxville** [comment]
Thanks a lot. Cookie Remover worked in Dark Reading
