### ISSUE TITLE
Endless loop on SF Chronicle

### ISSUE THREAD

**Issue by prodan1234** [iamadamdev/bypass-paywalls-chrome#368]
Every page on SF Chronicle leads to an endless loop. I tried clearing cache and cookies for both `sfchronicle.com` and `hearstnp.com` but it didn't work. 

Example: `sfchronicle.com/business/article/SFO-runway-construction-will-end-a-week-early-14449267.php` 

[Video](https://imgur.com/a/4ONCJfC)

**Comment by iscreamcoke** [comment]
I'm not experiencing the issue on Mac. Do you have any other extension working in the background?

**Comment by prodan1234** [comment]
No, I opened it in a incognito browser with just Bypass Paywalls enabled. Chrome version is `78.0.3904.70`

**Comment by iamadamdev** [comment]
That article works fine for me (non-incognito mode).
Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by prodan1234** [comment]
I removed and reinstalled the extension and the issue is fixed.
