### ISSUE TITLE
Request to add Law.com to paywall bypass

### ISSUE THREAD

**Issue by izakthegreat23** [iamadamdev/bypass-paywalls-chrome#377]
https://www.law.com/americanlawyer/2019/05/22/the-2019-am-law-200-ranked-by-gross-revenue/

**Comment by magnolia1234** [comment]
Article moved to Lexis Nexis (with hard paywall = subscription).

**Comment by kimkha** [comment]
I think this website has a hard paywall, this extension can't bypass it either. So this issue should be closed.
