### ISSUE TITLE
Doens't work for NY Times

### ISSUE THREAD

**Issue by willashley23** [iamadamdev/bypass-paywalls-chrome#380]
On Chrome 78. 

![image](https://user-images.githubusercontent.com/9400869/67890960-eb75f180-fb0e-11e9-9fe1-900a88d9de3e.png)

**Comment by magnolia1234** [comment]
Never had that popup in Europe though.
Still working for me.

**Comment by iscreamcoke** [comment]
Having an issue with the NYT too

<img width="1211" alt="Screenshot 2019-11-01 at 13 36 16" src="https://user-images.githubusercontent.com/17458353/68025245-9d96f000-fcac-11e9-9c81-26b256ec078f.png">

**Comment by magnolia1234** [comment]
You can close that 2nd popup or filter it with uBlock.

**Comment by iscreamcoke** [comment]
The popup can be closed, but blocking it in uBlock (either .css-121kum4 or .css-8atqhb) doesn't result in the full article being shown

**Comment by magnolia1234** [comment]
Maybe close it with line of javascript or preserve specific nyt cookie.
But still I've never seen the first (account)popup.

**Comment by iscreamcoke** [comment]
I have solved this particular issue and submitted it in PR #376 

I don't know if it was the same one as @willashley23's however.

**Comment by magnolia1234** [comment]
First popup can be blocked by uBlock indeed.

**Comment by davidszpak** [comment]
Using "Block Javascript on this site" in uBlock works for me.

**Comment by magnolia1234** [comment]
By blocking javascript you're losing the comments and recommendations.
uBlock Origin with the right filterlists does the job though.
