### ISSUE TITLE
wsj.com stopped working

### ISSUE THREAD

**Issue by enbob** [iamadamdev/bypass-paywalls-chrome#382]
https://www.wsj.com/articles/the-facebook-pressure-campaign-11572391241?mod=rsswn

**Comment by magnolia1234** [comment]
Mod=rsswn is old way of bypassing Wsj paywall. Are you using latest v1.5.6 of extension?

**Comment by getsadzeg** [comment]
I am using latest v1.5.6 of extension and it doesn't work for me either.

**Comment by magnolia1234** [comment]
Somehow your extension is disabled or user agent is blocked to be set to googlebot.

**Comment by enbob** [comment]
Updating worked for me. Thanks!

**Comment by sivakrishnat** [comment]
I just updated and it worked for me. Thanks

**Comment by tming4** [comment]
I am using the extension on Firefox for the first time on a  new MAC Pro and it is not working for the WSJ.I am using the latest update v1.5.6 (dated Oct. 2) and the extension is enabled for the WSJ.
Thanks for any possible help.

**Comment by tming4** [comment]
An error in my previous comment.I meant 1.5.9 not  1.5.6.

**Comment by magnolia1234** [comment]
Latest v1.5.8 for Chrome is working though.

**Comment by tming4** [comment]
An error in my previous comment.I meant 1.5.9 not  1.5.6.

**Comment by tming4** [comment]
My Firefox extension on My MAC pro says it is up-to date with v1.5.9 and there is no newer update.
I guess this is wrong and I should delete bypass and install bypass v1.6.0
