### ISSUE TITLE
Request: Washington Times (washingtontimes.com)

### ISSUE THREAD

**Issue by TheHungryGeek** [iamadamdev/bypass-paywalls-chrome#383]
Hi, request to add the Washington Times. They are ranked #36 in terms of largest US news websites.

After a certain number of free articles, we get the following paywall:

![image](https://user-images.githubusercontent.com/16078559/67999306-bb595a80-fc96-11e9-8fd4-e5a2e27ce3a5.png)

Followed the instructions - no paywall on incognito or via Google through incognito mode.

Thank you!

**Comment by iamadamdev** [comment]
This can be bypassed with https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce
