### ISSUE TITLE
Le Monde's articles are not complete

### ISSUE THREAD

**Issue by iscreamcoke** [iamadamdev/bypass-paywalls-chrome#384]
Compare the online version — partially bypassed — with the electronic newspaper (5/9 paragraphs missing):

https://www.lemonde.fr/international/article/2019/10/31/chili-face-a-la-crise-sociale-le-gouvernement-annule-la-cop25_6017565_3210.html

<img width="553" alt="Screenshot 2019-11-01 at 16 09 00" src="https://user-images.githubusercontent.com/17458353/68034520-1785a400-fcc2-11e9-9493-a81b73ba2c81.png">

This is the case for any article tested.

**Comment by magnolia1234** [comment]
Hard paywall, no more paragraphs available.

**Comment by iscreamcoke** [comment]
Yeah that's what I thought. Maybe precise "(extended preview)" in options.html, or deprecate support.

**Comment by iscreamcoke** [comment]
Maybe if you choose the "extended preview" option, move the popup below the article instead of hiding it, in order to avoid ambiguity.

**Comment by magnolia1234** [comment]
Googlebot fixes issue ;-)

**Comment by iscreamcoke** [comment]
Nice, good job

**Comment by iscreamcoke** [comment]
Cool, nice work Magnolia!
