### ISSUE TITLE
The Economist not working

### ISSUE THREAD

**Issue by oneninetyeight** [iamadamdev/bypass-paywalls-chrome#387]
Similar issue like we saw with WSJ.com. The article loads fully but then reloads with clipped text and a subscription prompt. Please fix this! Thanks.

**Comment by magnolia1234** [comment]
No problems here. The Economist is not enabled by default in the options though.

**Comment by oneninetyeight** [comment]
I had an older version, sorry about that. Thanks for the prompt response!
