### ISSUE TITLE
Simplification for adding new sites

### ISSUE THREAD

**Issue by jordanmendler** [iamadamdev/bypass-paywalls-chrome#389]
Just came across the project -- thanks for the great contribution. I was wondering why the chrome and firefox repositories are maintained in two different repositories? And then also wondering, why is the list of sites gets replicated in multiple files, as opposed to just having something like an include or having everything get parsed in from a common text file? I just wonder because it seems to be more work every time a site is added -- adding a new site to at least 6 places (readme and 2 js files, each on 2 separate projects), as opposed to being adding it to one common file and committing it.

PS, I am not trying to criticize your work/design -- I am sure there is some good reason for this and/or some legacy reason. Just curious as I would think something like a "sites-to-block.txt" would make it simpler and more compelling for people to add sites with paywall rather than just using your other plugin to clear cookies on their one local machine only. Or better yet, you can let the user click the bypass-paywalls plugin button in their browser to then block paywall for the current site. Then this click also submits the new url to a common DB for the project that aggregates submissions and pushes out updates every so often. Just an idea -- I don't expect anyone to do that work for free, but it certainly would be cool. Though I can think of more than one way to monetize the data you would collect if you were so inclined.

**Comment by cimke** [comment]
As far as I remember google extensions don't let include files easily. I mean you've to modify `manifest` file to make it work.

**Comment by iamadamdev** [comment]
I don't think you can use a shared file across 2 different repos on github?
Also the manifests are slightly different on firefox vs chrome.

**Comment by kimkha** [comment]
That's actually good idea, @jordanmendler . I'm thinking about allowing users to add some rules via local setting.

**Comment by iamadamdev** [comment]
The two repos are going to be merged soon.
