### ISSUE TITLE
caixinglobal

### ISSUE THREAD

**Issue by JackChen007** [iamadamdev/bypass-paywalls-chrome#39]
Thanks for your plugin.

Can you add caixinglobal.com to bypass-paywall-chrome? The websites is on bypass-paywall-firefox.

And hope you can add caixin.com

**Comment by iamadamdev** [comment]
Doesn't work for premium articles.

**Comment by JackChen007** [comment]
> Doesn't work for premium articles.

@iamadamdev With Yandex Browser, when opening the READ mode,  I can bypass the paywall or the Premium articles.
