### ISSUE TITLE
New Site request

### ISSUE THREAD

**Issue by Jeff-Stelling** [iamadamdev/bypass-paywalls-chrome#393]
For the athletic please 

https://www.google.co.uk/search?rlz=1C1CHBF_en-GBGB701GB701&ei=9C7LXbyYL5CW8gKTiK_oAg&q=https%3A%2F%2Ftheathletic.co.uk%2F1371780%2F2019%2F11%2F12%2Ffull-on-food-everywhere-sterlings-clash-gomez-southgate-u-turn%2F&oq=https%3A%2F%2Ftheathletic.co.uk%2F1371780%2F2019%2F11%2F12%2Ffull-on-food-everywhere-sterlings-clash-gomez-southgate-u-turn%2F&gs_l=psy-ab.3..0i71l8.29564.29564..29881...0.5..0.0.0.......0....2j1..gws-wiz.4itAVVqUDe0&ved=0ahUKEwi84vmp2eXlAhUQi1wKHRPECy0Q4dUDCAs&uact=5

**Comment by omersen147** [comment]
Great idea. I hope we can read the articles from The Athletic thanks to this extension.

**Comment by magnolia1234** [comment]
Hard paywall (subscription).

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
