### ISSUE TITLE
Anti-ad block banner in "The Washington Post"

### ISSUE THREAD

**Issue by Moxville** [iamadamdev/bypass-paywalls-chrome#397]
Hi,
Currently using version 1.5.8
The adblock banner does not go away
https://www.washingtonpost.com/technology/2019/11/07/future-autonomous-delivery-may-be-unfolding-an-unlikely-place-suburban-houston/
![Untitled](https://user-images.githubusercontent.com/31923265/68766518-05eab780-0645-11ea-840f-acefa5c2bb85.png)

Any workaround for this. Thanks

**Comment by magnolia1234** [comment]
For now, disable adblocker or javascript.

**Comment by stevendom1987** [comment]
Wash post isn't working for me at all now, anyone else?

**Comment by kimkha** [comment]
@stevendom1987 work for me with the article above.

@Moxville I don't think this extension should remove that banner. It's good if you just turn off your adblocker. Otherwise, request the adblocker extension to remove that banner for you.
