### ISSUE TITLE
Add Miami Herald

### ISSUE THREAD

**Issue by bryonthomas** [iamadamdev/bypass-paywalls-chrome#398]
Add miamiherald.com

For example
https://www.miamiherald.com/news/local/obituaries/article237255069.html

Thanks!

**Comment by kimkha** [comment]
I don't see this website has any paywall, if it's about the adblock popup, then turn off adblock and you can read the article.

Nothing to do from this extension. This issue should be closed.

**Comment by bryonthomas** [comment]
Thanks for following up. Here is an example of a paywall article.
https://www.miamiherald.com/news/local/community/miami-dade/article242259536.html#storylink=mainstage_card5

Thanks,
Bryon

**Comment by kimkha** [comment]
Okay, I pushed a PR for that.

I don't know why but the article you sent has no paywall. The new one is fine, we can bypass it.

**Comment by bryonthomas** [comment]
Great. Thanks for the quick response.

**Comment by iamadamdev** [comment]
Added in latest master
