### ISSUE TITLE
Bloomberg issue

### ISSUE THREAD

**Issue by Wheaties466** [iamadamdev/bypass-paywalls-chrome#399]
I did attempt all of the troubleshooting steps and it looks like the site loads all of the text for a second while it is still loading, then it continues with the paywall.

![image](https://user-images.githubusercontent.com/5346303/68775469-876a2780-05fc-11ea-86b3-37616b6966fe.png)

link to the article.

https://www.bloomberg.com/news/articles/2016-09-19/silicon-valley-vcs-pay-the-highest-rent-in-the-u-s

**Comment by magnolia1234** [comment]
Yes, new soft paywall.

**Comment by Wheaties466** [comment]
@magnolia1234 It looks like the new merge fixes this so I'll self close this issue.
