### ISSUE TITLE
SFChronicle gets stuck in reload loop

### ISSUE THREAD

**Issue by themadthinker** [iamadamdev/bypass-paywalls-chrome#406]
Trying to use the SF Chronicle with the plugin, and it gets stuck in an eternal reload loop where the page keeps redirecting away and coming back. Using Chrome version 78.0.3904.97, no ad blockers. Tried wiping cookies, but still happens.

**Comment by magnolia1234** [comment]
Just disable SFChronicle in options and delete cookies if you hit the paywall.
Cookie-block causes loop.
