### ISSUE TITLE
Please add "La Stampa"

### ISSUE THREAD

**Issue by Flavio94** [iamadamdev/bypass-paywalls-chrome#408]
http://www.lastampa.it/
It has paywalls for some articles, for istance: https://www.lastampa.it/topnews/primo-piano/2019/11/19/news/cosi-il-canale-sull-arno-ha-evitato-l-inondazione-di-pisa-1.37918325

Thank you!

**Comment by magnolia1234** [comment]
Hard paywall (subscription).
