### ISSUE TITLE
WSJ

### ISSUE THREAD

**Issue by dbslf** [iamadamdev/bypass-paywalls-chrome#411]
Doesn't appear to load without paywall anymore.  Re-installed both UBlock and Bypass.
https://www.wsj.com/articles/inside-a-chinese-developers-nearly-3-billion-bet-on-the-storied-waldorf-astoria-11573667699?mod=rsswn.

**Comment by magnolia1234** [comment]
You're using old version of extension (current v1.5.8).
mod=rsswn is obsolete since v1.5.6.

**Comment by dbslf** [comment]
https://www.wsj.com/articles/derek-jeters-players-tribune-gets-new-owner-11574343001?mod=business_lead_pos11

this is as of today.

**Comment by WLVGuy** [comment]
Check that the extension hasn't been removed automatically. That's what happened to me; reinstalled it and WSJ now works again.

**Comment by magnolia1234** [comment]
Indeed, weblink working just fine.

**Comment by dbslf** [comment]
> Check that the extension hasn't been removed automatically. That's what happened to me; reinstalled it and WSJ now works again.

did that - same issue.  was working fine up until a couple days ago

**Comment by magnolia1234** [comment]
BP extension is working just fine though ...
Maybe conflict with another extension?
