### ISSUE TITLE
ESPN+

### ISSUE THREAD

**Issue by dmurphy235** [iamadamdev/bypass-paywalls-chrome#412]
https://www.espn.com/mlb/insider/story/_/id/28130724/chicago-white-sox-take-big-step-contending-signing-yasmani-grandal

**Comment by magnolia1234** [comment]
ESPN+ has hard paywall (subscription).

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
