### ISSUE TITLE
Bypass Paywalls Site Request, the Spanish elmundo.es

### ISSUE THREAD

**Issue by abigail68** [iamadamdev/bypass-paywalls-chrome#413]
Could you add www.elmundo.es ?

It's the first/second Spanish newspaper, and the first one that add a paywall.

Thank you!

**Comment by magnolia1234** [comment]
Hard paywall (subscription).

**Comment by kimkha** [comment]
Have you tried this? https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#new-site-requests

**Comment by kimkha** [comment]
I don't see this website has any paywall, if it's about the adblock popup, then turn off adblock and you can read the article.

Nothing to do from this extension. This issue should be closed.

**Comment by yh1m** [comment]
I think it does have a paywall. It appears for example here https://www.elmundo.es/espana/2020/05/23/5ec951b921efa02f548b457f.html

**Comment by llacb47** [comment]
> I think it does have a paywall. It appears for example here [elmundo.es/espana/2020/05/23/5ec951b921efa02f548b457f.html](https://www.elmundo.es/espana/2020/05/23/5ec951b921efa02f548b457f.html)

Regular site is hard paywall.

AMP version is soft paywall: `https://amp-elmundo-es.cdn.ampproject.org/v/s/amp.elmundo.es/espana/2020/05/23/5ec951b921efa02f548b457f.html?amp_js_v=0.1`
