### ISSUE TITLE
Haaretz not working

### ISSUE THREAD

**Issue by Z-A-R** [iamadamdev/bypass-paywalls-chrome#415]
The extension is not working on Haaretz.co.il
I'm using uBlock Origin and cookies remover and still can't get pass paywall for articles that require a subscription

For example - https://www.haaretz.co.il/gallery/.premium-MAGAZINE-1.7895904

**Comment by magnolia1234** [comment]
Fixed in PR #414, but not yet merged in new release.

**Comment by Z-A-R** [comment]
How do I use google bot fix to overcome it now?

**Comment by magnolia1234** [comment]
If possible, add the domain(s) in your local background.js file.

**Comment by kimkha** [comment]
This website is working now, we can close this issue. @iamadamdev
