### ISSUE TITLE
webpages stuck "processing request" in 1.5.9 until extension disabled

### ISSUE THREAD

**Issue by trickdoll** [iamadamdev/bypass-paywalls-chrome#420]
Once in a while, webpages on Chrome will say they are stuck "processing request" -- at first I thought it was my internet connection but determined that was not the case.

I believe I have isolated the problem to this extension -- when I go to chrome://extensions/ and disable this extension any pages that were stuck instantly begin to load again.

**Comment by magnolia1234** [comment]
Which sites/pages though?

**Comment by trickdoll** [comment]
every page stopped loading at once. off the top of my head -- spotify web player, reddit, nytimes, google. disabling the extension or attempting to load the page in an incognito window (all extensions disabled) would work fine though.

**Comment by magnolia1234** [comment]
Mostly sites not affected by this extension (besides enabled site check).

**Comment by trickdoll** [comment]
for now i've just turned the extension off until i know i'm going to visit a paywalled site as a workaround. not sure if anyone else has experienced what i am experiencing.

**Comment by magnolia1234** [comment]
Never had this ...

**Comment by Fazuul** [comment]
I just recently started experiencing this with 1.6.1 and Vivaldi.  The site that triggers it is The Hill (https://thehill.com/).  Visiting The Hill frequently, but not always, causes the extension to max out the cpu.

**Comment by magnolia1234** [comment]
BP extension not active on thehill.com ...
Stable 25 MB for BP here (Win10).

**Comment by Fazuul** [comment]
It shouldn't be, but I haven't encountered this issue elsewhere.  This is what happens: 

![2020-01-08 17_00_42-Task Manager - Vivaldi](https://user-images.githubusercontent.com/952128/71969485-504d7680-3239-11ea-82dd-edda241fa7f3.png)

**Comment by magnolia1234** [comment]
For me processor tops at 5% for BP.
What's the 2nd BP-line in your taskmanager though?

**Comment by Fazuul** [comment]
I don't know.  It sometimes shows like that in the task manager.  It doesn't seem to affect the issue.  Which is to say it happens regardless of how it appears in the task manager.  Anyway, as you can see, it grabs the cpu and holds it for a few minutes.

**Comment by magnolia1234** [comment]
Yes, but I can't reproduce it on my laptop.
Have you checked the console log (also background of extension)?

**Comment by har5ha** [comment]
> for now i've just turned the extension off until i know i'm going to visit a paywalled site as a workaround. not sure if anyone else has experienced what i am experiencing.

I have had the same experience. Only option is to disable the extension and re-enable it while visiting a pay-walled site. I was able to reproduce it more frequently while switching from one Wi-Fi (access point) to another. FWIW.

**Comment by fiveolddogs** [comment]
This has been happening to me several times a week for two months. First I thought I was having ISP issues, as all sites stop responding. But other browsers were working fine. Then I thought I had a problem with my Chrome install, so I started disabling extensions one-by-one. As soon as I disable bypass-paywalls, it's like I plugged the internet back in, and all pages resume loading. 

I do keep a lot of tabs open at all times, but I have not noticed any particular activity or site which triggers the problem.

**Comment by otto-dev** [comment]
Also reporting the same issue. CPU usage at 100% while the extension appears to occupy the entire Event Loop, blocking any resource from loading in any tab. This happens for no apparent reproducible reason, even when no article-website is open.

**Comment by MrWido** [comment]
I have the same issue, couple times a day. Don't know what triggers it, sometimes I even don't have a paysite open. But the issue stops when I disable this extension.

**Comment by iamadamdev** [comment]
Thanks for the reports, seems like the same issue as https://github.com/iamadamdev/bypass-paywalls-chrome/issues/578.
Not sure what the root cause is yet.

**Comment by iamadamdev** [comment]
We can consolidate this issue to https://github.com/iamadamdev/bypass-paywalls-chrome/issues/578
