### ISSUE TITLE
American Affairs Journal

### ISSUE THREAD

**Issue by osdiab** [iamadamdev/bypass-paywalls-chrome#423]
https://americanaffairsjournal.org/2019/11/the-real-class-war/

I don't really know what strategies are effective, but I may try to contribute something if I can figure it out

**Comment by iscreamcoke** [comment]
Block cookies with an extension and add this line in your adblocker:
`americanaffairsjournal.org##.is-at-top.is-stuck.sticky.paywall-notification-bar`

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
