### ISSUE TITLE
v1.5.9 Wired.com stopped working

### ISSUE THREAD

**Issue by aiblis** [iamadamdev/bypass-paywalls-chrome#424]
😢

**Comment by magnolia1234** [comment]
You mean like the membership-popup?
https://www.wired.com/story/uber-london-rivals-plotting-its-downfall

**Comment by aiblis** [comment]
yes :(

**Comment by magnolia1234** [comment]
Some new Google Pay scheme, but disabling javascript works for now.

**Comment by aiblis** [comment]
Sweet! Thanks :)

**Comment by magnolia1234** [comment]
Blocking Javascript also hides some pictures, but removing cookies with Adam's Remove Cookies extension works better (3rd party cookies).

**Comment by magnolia1234** [comment]
Wired works again with just BP (no Javascript-block needed anymore).
Looks like some Google Pay-test.
