### ISSUE TITLE
The Athletic to work?

### ISSUE THREAD

**Issue by djmigz** [iamadamdev/bypass-paywalls-chrome#426]
https://theathletic.com/

**Comment by magnolia1234** [comment]
Search issues first:
https://github.com/iamadamdev/bypass-paywalls-chrome/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+athletic

**Comment by iscreamcoke** [comment]
The Athletic (US) is now supported by Bypass Paywalls Clean

https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by djmigz** [comment]
THANK YOU!!!
 

    On Wednesday, January 15, 2020, 02:08:35 PM PST, iscreamcoke <notifications@github.com> wrote:  
 
 
The Athletic (US) is now supported by Bypass Paywalls Clean

https://github.com/magnolia1234/bypass-paywalls-chrome-clean
