### ISSUE TITLE
manifest.json in 1.6.0 zip still has 1.5.9

### ISSUE THREAD

**Issue by eris23** [iamadamdev/bypass-paywalls-chrome#427]
"version": "1.5.9"

is last line in manifest.json in 1.6.0 zip

**Comment by svenrenhoek** [comment]
Yes - this has happened a few times in versions past

**Comment by magnolia1234** [comment]
Master-file contains latest version-commit.
But indeed commit after release is confusing.

**Comment by iamadamdev** [comment]
crx file is fine though
