### ISSUE TITLE
Bring Bypass Paywall to Iphone

### ISSUE THREAD

**Issue by tacosteak** [iamadamdev/bypass-paywalls-chrome#430]
Just wondering whether it's possible to write a javascript that can be used on the Apple Shortcuts app? I know that people are using the shortcuts app to bypass the paywall. However, this only applies to an article at a time. I'm thinking about doing something on a massive scale. Like you only have to click on the app and it will automatically download all of the articles of that day for you so you can read them offline.

**Comment by iscreamcoke** [comment]
Block cookies with an extension and add this line in your adblocker:
`americanaffairsjournal.org##.is-at-top.is-stuck.sticky.paywall-notification-bar`

**Comment by tacosteak** [comment]
I'm not an expert here so I don't know about that. But I know people are playing with javascript on the Apple Shortcuts. Here is an example: https://www.reddit.com/r/shortcuts/comments/agh6ro/using_javascript_in_your_shortcuts/

and this too: https://medium.com/@chrishutchinson/hacking-around-with-javascript-and-shortcuts-in-ios-12-95f8d7190777

**Comment by magnolia1234** [comment]
Can't you use custom adblocker like AdGuard with cookieblocker on iOS?
My main news-platform is Android though, but i've used both on my iPad.

**Comment by aeivy** [comment]
I've been trying to make a shortcut that when a webpage is shared, the shortcut is executed and the content displays itself without refreshing the page. 
It can be done and an example of it working was made on theathletic. I hope someone can at least lay the basic script and we'll try from there.

**Comment by magnolia1234** [comment]
Fix of TheAthletic paywall?

**Comment by inigma1** [comment]
Hello, I did not quite follow the above thread. I would like to use this add-in on iOS. Is there a way to do it? It would be so cool if there was!
