### ISSUE TITLE
bypass-paywalls-chrome

### ISSUE THREAD

**Issue by davidmreid** [iamadamdev/bypass-paywalls-chrome#432]
Followed the directions from below but the extension does not load:
(Set Extensions to Developer mode, extracted files, and loaded folder but nothing happens)

Google Chrome is up to date: Version 79.0.3945.79 (Official Build) (64-bit)

Download this repo as a ZIP file from GitHub.
Unzip the file and you should have a folder named bypass-paywalls-chrome-master.
In Chrome go to the extensions page (chrome://extensions).
Enable Developer Mode.
Drag the bypass-paywalls-chrome-master folder anywhere on the page to import it.
Notes

Every time you open Chrome it may warn you about running extensions in developer mode, just click 🗙 to keep the extension enabled.
You will be logged out for any site you have checked.
This extension works best along side the adblocker uBlock Origin.

**Comment by magnolia1234** [comment]
Use button 'load unpacked folder' and select folder with actual javascript-files (zip-file contains subfolder).

**Comment by davidmreid** [comment]
Most Excellent!
Thank you very much.
Now, can we add the SacBee.com to the Bypass List?
Regards,David Reid209-294-5349dm.reid@yahoo.com
 

    On Tuesday, December 10, 2019, 02:35:13 PM PST, magnolia1234 <notifications@github.com> wrote:  
 
 
Use button 'load unpacked folder' and select folder with actual javascript-files (zip-file contains subfolder).

**Comment by magnolia1234** [comment]
Cookie Remover also works though.
https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#sites-with-limited-number-of-free-articles
