### ISSUE TITLE
spectator.co.uk not working

### ISSUE THREAD

**Issue by lamby** [iamadamdev/bypass-paywalls-chrome#434]
Hi,

Viewing, for example, https://www.spectator.co.uk/2019/12/changing-the-script-the-shifting-character-of-our-political-parties/ results in:

![image](https://user-images.githubusercontent.com/133209/70707752-d6c17780-1cd0-11ea-8d32-41b7344b2c94.png)

Let me know how I can help.

**Comment by magnolia1234** [comment]
uBlock Origin (Fanboy’s Enhanced Tracking List) can also block paywall script: ||tinypass.com^$3p

**Comment by lamby** [comment]
So, I'm still seeing this issue - is this to be expected? (ie. there has not been a new release which matches that this issue is still marked as 'open'?)

**Comment by lamby** [comment]
Ah, no, I forgot I was installing this via an unpacked extension - updated. :)
