### ISSUE TITLE
Liberation.fr under a hard paywall?

### ISSUE THREAD

**Issue by iscreamcoke** [iamadamdev/bypass-paywalls-chrome#435]
A bunch of articles on liberation.fr seem now behind a hard paywall. I suggest we may remove this newspaper from the list of supported websites

https://www.liberation.fr/planete/2019/12/12/le-niger-en-plein-desert-securitaire_1768936

**Comment by magnolia1234** [comment]
Likewise for Die Zeit's plus-articles.
Both sites have no free article limit.
The Irish Times has premium-articles with hard paywall, but a free article limit (fixed by BP).

**Comment by iscreamcoke** [comment]
Then maybe deprecate Libération and die Zeit, and precise (limited) for The Irish Times

**Comment by magnolia1234** [comment]
Maybe make a PR?

**Comment by iscreamcoke** [comment]
PR #442

**Comment by LaBoiteRouge** [comment]
Liberation added premium articles (with hard paywall) still use a limit for free articles. Liberation shouldn't have been bypassed.

**Comment by iscreamcoke** [comment]
@LaBoiteRouge le support des articles gratuits sur liberation.fr a été réintroduit dans la nouvelle version [Bypass Paywall Clean](https://github.com/magnolia1234/bypass-paywalls-chrome-clean)
