### ISSUE TITLE
https://www.tubantia.nl/

### ISSUE THREAD

**Issue by DaniWinter** [iamadamdev/bypass-paywalls-chrome#436]
https://www.tubantia.nl/

Just places cookie for 3 free articles.

**Comment by magnolia1234** [comment]
Just block cookie temptationTrackingId (with EditThisCookie).

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#sites-with-limited-number-of-free-articles
