### ISSUE TITLE
More

### ISSUE THREAD

**Issue by Stenbitsrom** [iamadamdev/bypass-paywalls-chrome#44]
Spectator.co.uk

**Comment by ShintoPlasm** [comment]
That's already supported in the current version.

**Comment by Stenbitsrom** [comment]
Thanks, maybe some articles just require log-in and cannot be bypassed. For instance:

https://blogs.spectator.co.uk/2018/09/what-happens-when-steve-bannon-is-given-a-platform/

**Comment by iamadamdev** [comment]
Unfortunately doesn't work for all articles on that site.
