### ISSUE TITLE
New Site Request: The Caravan Magazine (https://caravanmagazine.in)

### ISSUE THREAD

**Issue by abdullahau** [iamadamdev/bypass-paywalls-chrome#440]
https://caravanmagazine.in

It's one of the most reputable news outlets in India and they seem to have a paywall on quite a few of their long-form articles. Would it possible to do something about this for the next update? The help of this community would be greatly appreciated.

**Comment by abdullahau** [comment]
Example: https://caravanmagazine.in/reportage/anjana-om-kashyap-star-hindi-news-television

**Comment by kimkha** [comment]
Have you tried this? https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#new-site-requests
