### ISSUE TITLE
Can't unzip/can't send .js bits

### ISSUE THREAD

**Issue by WordwizardW** [iamadamdev/bypass-paywalls-chrome#443]
I sent the link to the bypass-paywalls-chrome to a homeless friend, but my friend can't unzip the file without buying some premium thingie. I tried to send the unzipped file to him, since I can unzip files for free, but couldn't send .js bits.

**Comment by iscreamcoke** [comment]
Send the extension as a .zip. Your friend can either use 7zip for Windows, or Keka for Mac to unzip the file and import it in Chrome

**Comment by WordwizardW** [comment]
| 
| 
|  |

 |
| 
| Dear IsCreamCoke:
I think my friend Scott (cc-ed) might not have either, and might be using a phone. I am sending the zipped file attached to this email, but is there no way to send a complete unzipped version?
-- EXCELSIOR! 

  |

 |
| 
|  |

 |

 |
| 
|  | Yahoo Mail Stationery |

 |

    On Monday, December 16, 2019, 03:31:10 PM EST, iscreamcoke <notifications@github.com> wrote:  
 
 
Send the extension as a .zip. Your friend can either use 7zip for Windows, or Keka for Mac to unzip the file and import it in Chrome

**Comment by iscreamcoke** [comment]
If he has an Android phone, I guess he can install the extension with Kiwi browser using the [.crx file](https://github.com/iamadamdev/bypass-paywalls-chrome/releases). He either way unzip the .zip file on Android with the app [Files by Google](https://www.lifewire.com/unzip-files-on-android-4178981).

Hope this helped

**Comment by WordwizardW** [comment]
| 
| 
|  |

 |
| 
| My friend was unable to get it to work whatever they tried.
Also, the Washington Post paywall bypass worked when I first tried it, but then quickly stopped working.
-- EXCELSIOR! 

  |

 |
| 
|  |

 |

 |
| 
|  | Yahoo Mail Stationery |

 |

    On Tuesday, February 25, 2020, 1:48:48 AM EST, Adam <notifications@github.com> wrote:  
 
 
Closed #443.
