### ISSUE TITLE
[New site requests] Techinasia

### ISSUE THREAD

**Issue by winstonma** [iamadamdev/bypass-paywalls-chrome#444]
* Visit an article on the site you want to bypass the paywall for and copy the article title.
* Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
* Click on the same article from the Google search results page. If it loads without a paywall you can submit a request to add the site, otherwise my extension cannot bypass it either.

I tried [Beauty-booking platform...](https://www.techinasia.com/beautybooking-platform-gowabi-beat-odds-rivals-fall) using the method above but have no luck. Then I read the article content by opening the [Chrome DevTools Console](https://developers.google.com/web/tools/chrome-devtools/console) and entering the following command:
> $("div.paywall-content").classList.remove("paywall-content");

**Comment by iamadamdev** [comment]
Added
