### ISSUE TITLE
Paywall request

### ISSUE THREAD

**Issue by alexswe404** [iamadamdev/bypass-paywalls-chrome#446]
Thank you iamadamdev for this extension, works just as promised!
As per your instructions I've verified that the following site would work with your plugin and humbly ask if you could update to include them:
https://www.caixinglobal.com/ (basically the Chinese WSJ in English)
https://www.businessoffashion.com/ (quality journalism around fashion and retail)

Thank you!

**Comment by iscreamcoke** [comment]
businessoffashion.com can be bypassed by disabling javascript on the article

**Comment by alexswe404** [comment]
> businessoffashion.com can be bypassed by disabling javascript on the article

Thanks for the info, much appreciated!
