### ISSUE TITLE
 The manifest file could not be read

### ISSUE THREAD

**Issue by keyynot** [iamadamdev/bypass-paywalls-chrome#447]
Developer mode has been activated
I still can't install to the chrome extension

appear
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by iamadamdev** [comment]
What version of Chrome? How are you installing the extension?

**Comment by keyynot** [comment]
> What version of Chrome? How are you installing the extension?

Sorry my bad , works good now 
is there ways to install it on chrome mobile?? 
more comfortable using chrome browser
Thanks bro

**Comment by iscreamcoke** [comment]
Use Kiwi browser to run Chrome extensions on Android

**Comment by magnolia1234** [comment]
Kiwi browser doesn't support BP extension.
I use Yandex Browser on Android.
