### ISSUE TITLE
pls  add http://www.caixin.com/

### ISSUE THREAD

**Issue by ghost** [iamadamdev/bypass-paywalls-chrome#452]
http://www.caixin.com/ 
tks

**Comment by iscreamcoke** [comment]
See issue #446

**Comment by magnolia1234** [comment]
Caixin is not equal to Caixin Global (English) though.

**Comment by iscreamcoke** [comment]
Yes, I have an automatic redirection to Caixin Global. Need to add ?HOLDZH to URL to reach Chinese version

**Comment by magnolia1234** [comment]
Different domain.

**Comment by iscreamcoke** [comment]
I meant that I needed to add ?HOLDZH to reach caixin.com and not caixinglobal.com; not that it's the same domain

**Comment by magnolia1234** [comment]
Reference to my PR is useless.
Caixin has a hard paywall.

**Comment by iscreamcoke** [comment]
Yes I had realised I was automatically redirected and removed the comment from your PR back then, but GitHub has kept the reference here for some reason
