### ISSUE TITLE
Add Valeurs Actuelles please

### ISSUE THREAD

**Issue by jimmydeuxfois** [iamadamdev/bypass-paywalls-chrome#453]
The paywall can be bypassed by disabling Javascript (although it removes images and adds a space above articles). The script responsible for checking subscription status appears to be poool.min.js, specifically

https://www.valeursactuelles.com/clubvaleurs/politique/solitaire-et-narcissique-comment-lenigme-macron-sest-retournee-contre-le-president-113861

Thanks

**Comment by magnolia1234** [comment]
Add to uBlock Origin (my)filter:
||assets.poool.fr/poool.min.js$script,domain=www.valeursactuelles.com

**Comment by iscreamcoke** [comment]
poool.fr seems actually to be a paywall service shared by several websites in France. If you block '||assets.poool.fr/poool.min.js$script', you can not only bypass ValeursActuelles, but also Challenges.fr (tested), and [surely others](https://poool.fr/references)

maybe consider adding a grouped checkbox in the extension: [options.js] 'x = VA, Challenges, Newspaper 3, etc.'

**Comment by iscreamcoke** [comment]
Block everything coming from '||assets.poool.fr' indeed, as other scripts are located in the subdomain. It doesn't break anything other than the controlled access (i.e., the paywall).

@magnolia1234 why wouldn't we do a global blocking for any script loading from paywall services like poool, tinypass/piano, cleeng, pelcro, blendle, qiota, etc.?

**Comment by magnolia1234** [comment]
Possible, but maybe people with a subscription need the scripts (also add disable option).
Don't start a paywall revolution at Christmas eve ;-)
Joyeux Noël.

**Comment by iscreamcoke** [comment]
You'd be interested to read this study from Brave Software, bypass-paywall is mentioned in it: https://arxiv.org/pdf/1903.01406.pdf [2009, pages 10-11] (poke @iamadamdev)

Regarding this subject, I quote: "However, by using the list of known paywall libraries from Section 5 and
by blocking requests to these domains we were able to bypass 48% of the paywalls without breaking the website’s main functionality."

---------------
I had been preparing mockups for a BP 2.0, but my limited JS skills actually hinder me from reworking the extension. This is just draft, I'll do a more proper version on Sketch if you're interested in the design.

![screenshot](https://user-images.githubusercontent.com/17458353/71422636-fdde5880-2683-11ea-9f6d-6f3ad7896646.png)
![screenshot2](https://user-images.githubusercontent.com/17458353/71422637-fdde5880-2683-11ea-91e1-6ce98485beb4.png)
![screenshot3](https://user-images.githubusercontent.com/17458353/71422638-fdde5880-2683-11ea-888a-736fe0aa0ea0.png)
![settings](https://user-images.githubusercontent.com/17458353/71422640-fe76ef00-2683-11ea-9bbd-2f6439de7763.png)

Merry Christmas to y'all!

**Comment by magnolia1234** [comment]
PS Tinypass is blocked already for some sites in BP, but can also be blocked by uBlock Origin (if you select specific filterlist).

**Comment by iscreamcoke** [comment]
Hi, afte running some test, I have abandoned the idea of doing a global ban on paywall services. It can have surprising effects for the user when the website is not supported (e.g., obfuscation of text)

**Comment by magnolia1234** [comment]
Which sites are not supported (in BP you mean)?

**Comment by iscreamcoke** [comment]
Yes, exactly. For instance, if we do a global ban of `||laterpay.net` on uBlock, the website [Bergedorfer-Zeitung](https://www.bergedorfer-zeitung.de/) sends obsfucated text instead of the subcribing window.

Blocking paywall services should therefore be done site by site. I doesn't word each time, but it's a powerful method.

**Comment by magnolia1234** [comment]
You're also reading local German papers now? ;-)

**Comment by iscreamcoke** [comment]
No, I've just taken the list of most common paywall services (see above), and I looked at what effects it had on websites using those services ;-)

**Comment by jimmydeuxfois** [comment]
Many thanks to both of you, it works by blocking in uBlock! I'm waiting for new updates of the extension :) great work, jimmy

**Comment by iscreamcoke** [comment]
Btw Magnolia, since doing a global blocking of paywall services like `assets.poool.fr` in uBlock brings collateral issues to other websites, could you just help me add the support of challenges.fr or valeursactuelles.com to the extension, as it was requested in issues.

I've tried to block the regex in background.js with no result...

Samples of premium articles for [Challenges](https://www.challenges.fr/automobile/actu-auto/tesla-numero-un-des-des-vehicules-electrifies-devant-bmw-et-renault_691349) and [Valeurs Actuelles](https://www.valeursactuelles.com/clubvaleurs/culture/j-r-r-tolkien-le-forgeur-de-mythes-114366)

**Comment by magnolia1234** [comment]
These articles are readable with above mentioned filter in uBlock Origin.
