### ISSUE TITLE
BP not working on Chromium mobile browser Kiwi

### ISSUE THREAD

**Issue by jcarrollpe** [iamadamdev/bypass-paywalls-chrome#455]
Recently installed Kiwi browser for Android. Have installed multiple extensions and tested them. Ublock Origin works perfectly.  BP version 1.61 installs and configuration options are available, however it  is not working. Sites tested were WSJ and The Daily Telegraph (UK). No extensions are blocked from installing in Kiwi, and there is no warning/checks extensions are not from the Chrome store. What is truly amazing is the implemenation of uBO, down to the dropper function and importing of filters from a desktop browser. Hopefully someone who is interested in chromium-based mobile browsers that allow extensions can look into this because I don't think Chrome (mobile) will ever allow extensions. Cheers!

**Comment by magnolia1234** [comment]
BP is not working on Kiwi Browser indeed.
Use Yandex Browser with uBlock Plus Adblocker instead.

**Comment by jcarrollpe** [comment]
Can anyone confirm this is broken on the browser end? Kiwi hasn't been updated in a while, but there is no way (for me) to know if this is the extension or the browser needs fixing?  If the browser I can chase this up on arnaud's XDA thread. Cheers.

**Comment by magnolia1234** [comment]
Lots of cookie-related extensions are not working on Kiwi Browser ...
BP is working fine on the Yandex Browser though.

**Comment by jcarrollpe** [comment]
> Lots of cookie-related extensions are not working on Kiwi Browser ...
> BP is working fine on the Yandex Browser though.

I could not sideload any extensions in Yandex Android (mobile) ...only the built in few. Will go back and look at this again. Thanks.

**Comment by magnolia1234** [comment]
Check instructions in my fork (readme.md).

**Comment by jcarrollpe** [comment]
Gotcha. Thanks!
