### ISSUE TITLE
Bug: Quora cookies get removed on non-Quora websites

### ISSUE THREAD

**Issue by steakscience** [iamadamdev/bypass-paywalls-chrome#457]
Hi,
I realized that the cookies for connections to Quora were being removed on non-Quora websites. This potentially breaks certain sites (that use Quora Pixel)

**Comment by magnolia1234** [comment]
Collateral damage, but it's an ad-trackingpixel anyway.

**Comment by magnolia1234** [comment]
Now allow cookies for Quora (and more sites) in PR #449
