### ISSUE TITLE
Articles on lesechos.fr don't have pictures

### ISSUE THREAD

**Issue by jimmydeuxfois** [iamadamdev/bypass-paywalls-chrome#458]

**Comment by magnolia1234** [comment]
Pictures are visible for me though.
Could you add a screenshot?

**Comment by jimmydeuxfois** [comment]
mmhm ok it appears this is indeed advertisement not fully removed:
<img width="1439" alt="Screenshot 2019-12-29 at 21 05 22" src="https://user-images.githubusercontent.com/56964267/71562113-00272500-2a7f-11ea-8366-15d166e80cfb.png">
![Uploading Screenshot 2019-12-29 at 21.05.32.png…]()

**Comment by jimmydeuxfois** [comment]
sorry

**Comment by magnolia1234** [comment]
Yes, some weird advertisement-classes are used.
Ads are blocked, but html-elements are still visible.
uBlock Origin also blocks recommendations (slideshow) at the bottom though.
