### ISSUE TITLE
Add lequipe.fr

### ISSUE THREAD

**Issue by jimmydeuxfois** [iamadamdev/bypass-paywalls-chrome#459]
Please...Do it for the people 

https://www.lequipe.fr/Football/Article/Ligue-des-champions-erling-braut-haaland-attaquant-de-salzbourg-l-itineraire-d-un-surdoue/1084011

**Comment by magnolia1234** [comment]
Looks like hard paywall on premium articles.

**Comment by jimmydeuxfois** [comment]
thanks for efforts
