### ISSUE TITLE
Pop-up cookie loop on Dagens Nyheter

### ISSUE THREAD

**Issue by iscreamcoke** [iamadamdev/bypass-paywalls-chrome#460]
I'm facing a popup which cannot be closed when trying to reach https://www.dn.se/

<img width="1306" alt="Screenshot 2019-12-30 at 10 14 23" src="https://user-images.githubusercontent.com/17458353/71575429-34392f00-2aed-11ea-871e-98c560530a04.png">

Probably due to specific cookie not being held

**Comment by iscreamcoke** [comment]
Now hitting the paywall on some articles with last fix @magnolia1234...
https://www.dn.se/kultur-noje/bjorn-ulvaeus-dags-att-gora-upp-med-alderismen-i-sverige/
<img width="1306" alt="Screenshot 2019-12-30 at 10 14 23" src="https://user-images.githubusercontent.com/17458353/71584566-6493c400-2b13-11ea-8b98-6d26e39678f6.png">

**Comment by iscreamcoke** [comment]
Now hitting the paywall on some articles with last fix @magnolia1234...
https://www.dn.se/kultur-noje/bjorn-ulvaeus-dags-att-gora-upp-med-alderismen-i-sverige/
<img width="1189" alt="Screenshot 2019-12-30 at 14 47 35" src="https://user-images.githubusercontent.com/17458353/71584580-770dfd80-2b13-11ea-9e7d-122aed8b7c52.png">

**Comment by magnolia1234** [comment]
Premium articles have hard paywall.
