### ISSUE TITLE
Doesn't work on DynaMed

### ISSUE THREAD

**Issue by iscreamcoke** [iamadamdev/bypass-paywalls-chrome#461]
BP isn't working on all articles indeed:
https://www.dynamed.com/management/pediatric-advanced-life-support-pals#VASCULAR_ACCESS__LI_F51_NRN_DKB

**Comment by magnolia1234** [comment]
Hard paywall for pages besides general information.

**Comment by iscreamcoke** [comment]
Then deprecate?

**Comment by magnolia1234** [comment]
Yes, useless while active in BP.
