### ISSUE TITLE
Some articles on Bloomberg Quint are behind a paywall

### ISSUE THREAD

**Issue by iscreamcoke** [iamadamdev/bypass-paywalls-chrome#463]
https://www.bloombergquint.com/bq-blue-exclusive/stocks-that-surprised-and-disappointed-the-most-in-2019

**Comment by magnolia1234** [comment]
Looks like articles on the EDITORS PICK - LIST have a hard paywall.

**Comment by magnolia1234** [comment]
BQ Blue Exclusive articles have hard paywall, it seems.

**Comment by RipperCode9** [comment]
can you pleas include couple of indian news websites in this bypass script as well.
1) Economic Times:   **https://prime.economictimes.indiatimes.com/news/76591968/transportation/butschek-has-the-humongous-task-of-steering-tata-motors-through-the-current-precarious-situation?utm_source=ETnotifications&utm_medium=editpush&utm_campaign=ETPromotions&utm_content=bigimage**

2) Moneycontrol Pro: https://www.moneycontrol.com/

3) Livemint: https://www.livemint.com/
