### ISSUE TITLE
Help to add financial website in your paywall

### ISSUE THREAD

**Issue by ADB369** [iamadamdev/bypass-paywalls-chrome#466]
Hi

i am new in Github and i come to know bypass paywalls from one of my friend and it is very very useful to me and thank you for developing such nice program and i am also referring my other friend to install bypass paywalls

Following website very popular in india for financial news, can you please help me to add these website in your bypass paywalls.

https://economictimes.indiatimes.com
https://www.moneycontrol.com/
https://www.business-standard.com/

and once again thank you for this

**Comment by magnolia1234** [comment]
> https://economictimes.indiatimes.com

ET Prime is already in BP, but which articles of ET you can't read (didn't find a paywall yet)?
> https://www.moneycontrol.com/

same, paywall?
> https://www.business-standard.com/

Looks like a hard paywall.

**Comment by ADB369** [comment]
Hi,
IN ETPRIME
I am not able to open below mentioned ET Prime article like that there are so many article in which ask me to subscribe.
Lambretta-maker Scooters India is gasping for breath. Can an EV ride take it to safety? - ET

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Lambretta-maker Scooters India is gasping for breath. Can an EV ride tak...

The ailing PSU, which was put up for sale in March 2018, hasn’t received a single bid. Now, the management is pl...
 |

 |

 |



In Moneycontrol 

https://www.moneycontrol.com/news/business/earnings/sbis-bad-loan-under-reporting-shows-balance-sheets-still-cant-be-trusted-4719061.html

Thanks with kind Regards,
Nieo


    On Thursday, 2 January 2020, 7:42:16 pm GMT+4, magnolia1234 <notifications@github.com> wrote:  
 
 

https://economictimes.indiatimes.com


ET Prime is already in BP, but which articles of ET you can't read (didn't find a paywall yet)?


https://www.moneycontrol.com/


same, paywall?


https://www.business-standard.com/


Looks like a hard paywall.

**Comment by magnolia1234** [comment]
ET Prime article is fine for me while using BP v1.6.1.
MoneyControl's Pro-articles have hard paywall.
BusinessStandard has also a hard paywall for subscription-articles.
