### ISSUE TITLE
Header image or video will not load (on Bloomberg and WSJ)

### ISSUE THREAD

**Issue by Castle999** [iamadamdev/bypass-paywalls-chrome#467]
Upon opening the website, the image and/or video that heads the article will not display/load. Please advise, thank you and happy new year!

**Comment by magnolia1234** [comment]
Do you have a screenshot for both?
Seems more like a adblocker issue to me though.

**Comment by Castle999** [comment]
Hello!

Many thanks for your prompt reply, time and efforts. I’ve gone ahead and attached an example from Bloomberg and WSJ for your reference. Prior to running the paywall bypass, I was able to view the leading image and/or videos. I am not sure what is causing this although if I am the sole outlier, I may try a combination of uninstalling and reinstalling both. Many thanks again and happy new year!


Best Regards,

Aaron.

On 2 Jan 2020, at 10:19 PM, magnolia1234 <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have a screenshot for both?
Seems more like a adblocker issue to me though.

**Comment by Castle999** [comment]
Quick follow-up. Just disabled adblocker and the problem persists.


Best Regards,

Aaron.

On 2 Jan 2020, at 11:29 PM, Aaron Wong <AWong@outlook.com<mailto:AWong@outlook.com>> wrote:

Hello!

Many thanks for your prompt reply, time and efforts. I’ve gone ahead and attached an example from Bloomberg and WSJ for your reference. Prior to running the paywall bypass, I was able to view the leading image and/or videos. I am not sure what is causing this although if I am the sole outlier, I may try a combination of uninstalling and reinstalling both. Many thanks again and happy new year!


Best Regards,

Aaron.
<1.pdf>
<2.pdf>

On 2 Jan 2020, at 10:19 PM, magnolia1234 <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have a screenshot for both?
Seems more like a adblocker issue to me though.

**Comment by magnolia1234** [comment]
Add screenshots to comment on GitHub website (not attached to mail).

**Comment by Castle999** [comment]
[1.pdf](https://github.com/iamadamdev/bypass-paywalls-chrome/files/4018438/1.pdf)
[2.pdf](https://github.com/iamadamdev/bypass-paywalls-chrome/files/4018439/2.pdf)

**Comment by magnolia1234** [comment]
No issue with image/video for me though.

**Comment by iscreamcoke** [comment]
No issue for me neither. Try reinstalling the extension @Castle999

**Comment by Castle999** [comment]
Just reinstalled and the problem persists. Worth noting that at first, the video will load (not play) for ~1 second prior to blacking out entirely... disabled adblock and still happens as well.

**Comment by iscreamcoke** [comment]
Have you tried disabling your adblocker (or any other extension that could load on the page)?

**Comment by iscreamcoke** [comment]
What other extensions are you running on Chrome?

**Comment by magnolia1234** [comment]
Happened once today to me with uBlock Origin, but not anymore.
Which browser are you using?

**Comment by Castle999** [comment]
Google Chrome Version 79.0.3945.88 (latest)
Adblock by getadblock.com (most popular one when searching "adblock" in Chrome Web Store.

Application Launcher for Drive (by Google)
Awesome Screenshot: Screen Video Recorder
Boomerang for Gmail
Chrome Remote Desktop
Google Docs Offline
Just Read
Rakuten Ebates: Get Cash Back For Shopping
Wayback Machine

**worth noting that I did not have this issue prior to running the paywall
***thank you!

**Comment by magnolia1234** [comment]
Try disabling BP for WSJ once and reload page?
Maybe Googlebot setting blocks video at first.
uBlock Origin works better (less resources) than Adblock though.

**Comment by Castle999** [comment]
Many thanks for your time and efforts.

I tried disabling AdBlock, then Bypass Paywall and even both.
I suspect the problem is related to a compatibility issue b/w Chrome and Flash.
Working on that now.

Side note, I've disabled the AdBlock extension for your suggested uBlock Origin.
Going to see if there is a noticeable difference, if any.

**Comment by Castle999** [comment]
I unblocked cookies and now it works fine...

I blocked cookies as a way to get around some paywalls as well as sense of privacy.
Will weigh the decision and proceed accordingly.

Many thanks again!

**Comment by magnolia1234** [comment]
You can always block 3rd-party cookies in Chrome.

**Comment by Castle999** [comment]
I've always elected for the blocking of 3rd-party cookies, although now I am thinking if it is necessary to block 1st-party cookies? I did so to enhance privacy at the cost of ease of use. My knowledge is limited to  a brief google search and any thoughts would be appreciated. Thank you all.

**Comment by iscreamcoke** [comment]
1st-party cookies are necessary for the local functioning of a website (subscriber access and metered paywalls included)

3rd-party cookies are what tracks you across website to build a marketing profile

**Comment by iscreamcoke** [comment]
1st-party cookies are necessary for the local functioning of a website (subscriber access and metered paywalls included, which we block on a case by case basis in Bypass Paywalls)

3rd-party cookies are the ones tracking users across websites in order to build a marketing profile 

They're not even that effective. For instance, cookies are only right 50% of the time when trying to guess the gender of a user. The most powerful solutions for retargeting are Google Tag Manager and Facebook Pixel (they know a lot about you) – block those trackers specifically and log out from your Google account when browsing the web

**Comment by Castle999** [comment]
I see, thank you for sharing. With WSJ cookies blocked, I occasionally still get the header/leading image blank. Although, those graphic(s) are mostly for aesthetics.

**Comment by iscreamcoke** [comment]
The upper block of ad on the WSJ is not fully removed by uBlock default lists.

You need to add this line in your uBlock 'My Filter' : `www.wsj.com###wrapper-AD_PUSH`

We are currently working on a uBlock list to improve all this cosmetic layout issues. Stay tuned for new releases on Magnolia's repo [Bypass Paywall Clean](https://github.com/magnolia1234/bypass-paywalls-chrome-clean)

**Comment by Castle999** [comment]
Many thanks for your time and efforts!

I added your line to my uBlock (Origin 1.24.2) in 'My filters' although the problem persists.

**Comment by iscreamcoke** [comment]
Are you running the [1.6.1.4 version](https://github.com/magnolia1234/bypass-paywalls-chrome-clean/releases) of Bypass Paywalls? 

If so, and based on the previous information you gave, I see no other solution than resetting your Chrome cookie settings. Copy and paste `chrome://settings/content/cookies` in your search bar and see if there's any problematic setting (beware when cleaning cookies, it'll log out from the website). If nothing work, maybe try reinstalling Chrome and your extensions if it's worth the effort.

**Comment by Castle999** [comment]
Am running 1.6.1 and will try to reinstall Bypass Paywalls extension once more. Otherwise, I think I'll just wait for a uOrigin update or just ignore this problem. Many thanks for your time and efforts!
