### ISSUE TITLE
Add The Daily Beast

### ISSUE THREAD

**Issue by jimmydeuxfois** [iamadamdev/bypass-paywalls-chrome#468]
https://www.thedailybeast.com/qassem-soleimanis-death-has-us-bracing-for-irans-counterpunch?ref=home

Thank you and great work

**Comment by magnolia1234** [comment]
Looks like hard paywall on members-only articles.

**Comment by sjeble** [comment]
Echo this request. 5 free articles a month seems like. Once limit reached can open in Incognito

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by Scrotastic** [comment]
Not working.
