### ISSUE TITLE
request please

### ISSUE THREAD

**Issue by E1derone** [iamadamdev/bypass-paywalls-chrome#469]
https://www.newcastleherald.com.au/

**Comment by magnolia1234** [comment]
Added to my fork: https://github.com/magnolia1234/bypass-paywalls-chrome

PS stay strong with the terrible Australian bushfires though ...

**Comment by jcarrollpe** [comment]
Although this (1.5.3) fork loads and is usable, some of the major sites have not been updated in months.  I see new adds, recent activity... any plans to update wsj or others? thanks!

**Comment by magnolia1234** [comment]
No new releases on my fork (yet), but you could use the master zip-file (v1.6.1+):
https://github.com/magnolia1234/bypass-paywalls-chrome/archive/master.zip
Download-button not visible on mobile GitHub-site though (switch to Desktop).

**Comment by magnolia1234** [comment]
PS i've added a BP v1.6.1a release (just zip-file):
https://github.com/magnolia1234/bypass-paywalls-chrome/releases

**Comment by jcarrollpe** [comment]
Sweet! Working great thanks.

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean
