### ISSUE TITLE
Request please, if possible

### ISSUE THREAD

**Issue by severing77** [iamadamdev/bypass-paywalls-chrome#470]
Hi! Great work! I am admired!

Can I ask you? Would you be so kind as to try to make with some of your updates bypass paywall for these:

Slovenian newspaper - Delo: [https://www.delo.si/](url)

German newspapers - Süddeutsche Zeitung: [https://www.sueddeutsche.de/](url)
                                  - Frankfurter Allgemeine Zeitung: [https://www.faz.net/](url)

Also, if there is some way to donate and to contribute to your work, please share me a link.

All the best in 2020. to all developers!

**Comment by magnolia1234** [comment]
Faz+ articles seem to have a hard paywall.
Süddeutsche Zeitung you can read by activating EasyPrivacy-list in uBlock Origin (or other adblocker):
||met.vgwort.de^
