### ISSUE TITLE
New Request from Brazil

### ISSUE THREAD

**Issue by lecotrobe33** [iamadamdev/bypass-paywalls-chrome#471]
Hello,

Thank you for providing such an amazing work!

I'm from Brazil and i want to request you if you can add these famous journals from my country:
- Folha de São Paulo ( https://www.folha.uol.com.br/ )
- Valor Econômico ( https://valor.globo.com/ )
- O Globo ( https://oglobo.globo.com/ )
- Exame ( https://exame.abril.com.br/ )

Thank you!

**Comment by magnolia1234** [comment]
Have you tried Burlesco?
https://github.com/burlesco/burlesco

**Comment by iscreamcoke** [comment]
Bulesco hasn't been updated for 2 months though. Several sites didn't work when I tried a couple of days ago (e.g. O Globo).

Those sites can be bypassed, it would be good to add them

Btw, O Globo already works by blocking TinyPass. @lecotrobe33  download from Magnolia's fork to try the 'beta' version of Bypass Paywalls: https://github.com/magnolia1234/bypass-paywalls-chrome

**Comment by magnolia1234** [comment]
> * Folha de São Paulo ( https://www.folha.uol.com.br/ )

Use uBlock Origin with (default) filter Easylist -> /publicidade.
> * Valor Econômico ( https://valor.globo.com/ )
> * O Globo ( https://oglobo.globo.com/ )
> * Exame ( https://exame.abril.com.br/ )

Use uBlock Origin and enable filter Fanboy’s Enhanced Tracking List -> ||tinypass.com^$3p

**Comment by magnolia1234** [comment]
Added to https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean
