### ISSUE TITLE
Project Syndicate

### ISSUE THREAD

**Issue by severing77** [iamadamdev/bypass-paywalls-chrome#472]
Do you consider Project Syndicate as worthy to be bypassed for older articles (Archive) and those in the On point section?

e.g. https://www.project-syndicate.org/onpoint/why-china-s-growth-model-will-fail-by-daron-acemoglu-and-james-a--robinson?barrier=accesspaylog

Is there also a hard paywall?

Thanks for your previous answers as well.

**Comment by magnolia1234** [comment]
Also seems like a hard paywall for the mentioned sections.
