### ISSUE TITLE
WSJ isn't working

### ISSUE THREAD

**Issue by heikuroki** [iamadamdev/bypass-paywalls-chrome#473]
Not sure if I'm just not troubleshooting correctly, but even when I turn off uBlock Origin and refresh, I still can't get around the WSJ paywall. I've also tried reinstalling the extension and it didn't help.

**Comment by magnolia1234** [comment]
WSJ should be working just fine (BP v1.6.1).

**Comment by heikuroki** [comment]
Huh, it's working now. I guess I did something wrong, idk.
