### ISSUE TITLE
Statista Issue

### ISSUE THREAD

**Issue by guilthub** [iamadamdev/bypass-paywalls-chrome#475]
Statista is listed as one of the supported websites for this extension; it looks like they have it structured in such a way that you are unable to view full reports.  Will this still work?  If so- anyone know how?

**Comment by magnolia1234** [comment]
Do you get the premium-banner after a few statistics?
My fork is working just fine (not merged yet), but it seems the current release isn't working anymore.

**Comment by magnolia1234** [comment]
PS I tested the release by Firefox add-on, but that one was not complete (manifest fixed now).
Btw BP 'only' unlocks statistics/graphs/read more (no additional information).

**Comment by guilthub** [comment]
Thank you for your help!

I'm using the Chrome Extension.  The more I look at this, the more I think it's working properly.  My issue was that I couldn't access the full reports, but it seems like the way they provide access to those is actually not via a paywall.  Unfortunate, but it makes sense for them to do it that way.

**Comment by magnolia1234** [comment]
I didn't add this site or test it any further though.
