### ISSUE TITLE
The Globe and Mail isn't working

### ISSUE THREAD

**Issue by smnlng** [iamadamdev/bypass-paywalls-chrome#476]
"We're sorry but we are unable to validate your access to this article. Please adjust your browser settings or turn off any extensions that may be causing this issue.

For more help please visit our Diagnostic & Troubleshooting page."

Any article should trigger, try: https://www.theglobeandmail.com/world/us-politics/article-ukraine-plane-shot-down-by-iranian-missile-trudeau-says/

**Comment by magnolia1234** [comment]
My fork is working just fine #449

**Comment by smnlng** [comment]
Will check and confirm.

**Comment by smnlng** [comment]
Upgraded to master 1.6.1 and still have the same issue:

> We're sorry but we are unable to validate your access to this article. Please adjust your browser settings or turn off any extensions that may be causing this issue.

For more help please visit our Diagnostic & Troubleshooting page.

**Comment by magnolia1234** [comment]
Yes, just videos and photo galleries are not working (blocked specific Javascript).
Indeed Adam's master is equal to his release v1.6.1.

**Comment by magnolia1234** [comment]
PS for the latest fixes you can also use the master zip-file in my fork (available in desktop view).

**Comment by magnolia1234** [comment]
Fixed in https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
Fixed
