### ISSUE TITLE
Handelsblatt  issue

### ISSUE THREAD

**Issue by severing77** [iamadamdev/bypass-paywalls-chrome#477]
Handelsblatt has an issue, where I can open links like this once and later it shows the paywall banner,

https://www.handelsblatt.com/finanzen/anlagestrategie/trends/aktieninvestments-2020-diese-15-aktien-schlagen-den-dax/25397062.html?ticket=ST-629963-e3AAcZQLfdnZ4OPxNWo6-ap1

**Comment by magnolia1234** [comment]
Fixed in my PR/fork.

**Comment by severing77** [comment]
> Fixed in my PR/fork.

Thank you!
