### ISSUE TITLE
Daily Telegraph isn't working

### ISSUE THREAD

**Issue by avengah** [iamadamdev/bypass-paywalls-chrome#481]
Example: https://www.telegraph.co.uk/family/relationships/guilty-secret-embarrassed-husbands-lack-education/

The full page loads but then some of it is obscured by a sign in box.

**Comment by sapote2241** [comment]
Second that. https://www.telegraph.co.uk/technology/2020/01/16/britain-poised-let-huawei-boris-johnson-doesnt-have-choice/

**Comment by iscreamcoke** [comment]
Hi, this repo hasn't been update for a month and the project has moved to [Bypass Paywall Clean](https://github.com/magnolia1234/bypass-paywalls-chrome-clean)

Both links work for me with version 1.6.1.4 (and uBlock adblocker)

**Comment by iamadamdev** [comment]
The project has not moved anywhere. Please do not advertise someone else's repro here when they ripped of 90% of my project and didn't even credit me.

**Comment by iamadamdev** [comment]
Not seeing that issue anymore

**Comment by jimmydeuxfois** [comment]
Use this extension instead: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

It supports way more websites, it's more regularly updated and it doesn't track you with Analytics

**Comment by LawSci** [comment]
Daily Telegraph articles still don't load correctly. The sign-in box/paywall lingers when the page has finished loading. 
Please have another look.

**Comment by iamadamdev** [comment]
I can repro now. Don't have a fix yet. For now I would recommend just hitting ESC as it loads.

**Comment by iamadamdev** [comment]
Fixed in latest version.
Enable the new "\*General Paywall Bypass\*" option.
