### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by Skates1616** [iamadamdev/bypass-paywalls-chrome#482]
With Microsoft Edge officially launching and based on Chromium, would it be possible to implement Edge support?

**Comment by bmoura8** [comment]
Microsoft Edge Chromium works with Bypass Paywalls.  Simply download the Chrome version, unzip and manually add to Edge Chromium with the "Load Unpacked" option.

**Comment by Droyk** [comment]
> Microsoft Edge Chromium works with Bypass Paywalls.  Simply download the Chrome version, unzip and manually add to Edge Chromium with the "Load Unpacked" option.

This is what happens if I try to load this extension on Microsoft edge 
![image](https://user-images.githubusercontent.com/15848350/73119092-15f70f80-3f83-11ea-8de8-b768f8f81408.png)
needs a new value for key field.

**Comment by Droyk** [comment]
@bmoura8 
> Microsoft Edge Chromium works with Bypass Paywalls.  Simply download the Chrome version, unzip and manually add to Edge Chromium with the "Load Unpacked" option.

This is what happens if I try to load this extension on Microsoft edge 
![image](https://user-images.githubusercontent.com/15848350/73119092-15f70f80-3f83-11ea-8de8-b768f8f81408.png)
needs a new value for key field.
@iscreamcoke [**Instructions are incomplete!**](https://github.com/iscreamcoke/bypass-paywalls-chrome-clean/blob/master/README.md)

**Comment by iscreamcoke** [comment]
@Droyk have you tried using the same method as for Chrome? Enable developer mode on the extension page, then drag and drop the folder of the extension.

**Comment by phly95** [comment]
You should try uploading it to the Microsoft Store. They haven't been as strict as the other guys, and might actually allow it. I mean, Github is a Microsoft site after all.
