### ISSUE TITLE
El Pais paid articles and question

### ISSUE THREAD

**Issue by severing77** [iamadamdev/bypass-paywalls-chrome#484]
Is it possible to add El Pais and unlock paid articles, like:

elpais.com/elpais/2020/01/16/opinion/1579199440_591772.html

Also, does this extension update automatically in Chrome browser? I set up also Pack Extension settings, but still not sure is it auto update or I need to follow your work regularly and download every new release?

**Comment by magnolia1234** [comment]
Added in https://github.com/magnolia1234/bypass-paywalls-chrome-clean
Only auto-update for crx-file in Chromium browser.

**Comment by severing77** [comment]
Thanks!
