### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by fountainofdata** [iamadamdev/bypass-paywalls-chrome#486]
Hi thank you for the extension! It works perfectly.
Would it be possible to add [Towards Data Science](towardsdatascience.com)? It's a subset of Medium.
Also one question, does this extension log the visited websites in any way? Thank you in advance!

**Comment by magnolia1234** [comment]
Yes, this extension uses Google Analytics (like so many extension) ...
Clean version: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by jimmydeuxfois** [comment]
This website is supported by the extension: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

It supports way more websites, it's more regularly updated and it doesn't track you with Analytics

**Comment by jimmydeuxfois** [comment]
I'm using [the new repo](https://github.com/magnolia1234/bypass-paywalls-chrome-clean) and I'm almost sure this website is supported.

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
I'm not getting any paywall there.
