### ISSUE TITLE
Chicago Business partially working

### ISSUE THREAD

**Issue by redditGuinness** [iamadamdev/bypass-paywalls-chrome#489]
Greetings,

Most of the links on the site are bypassed but I noticed this one, no matter what I did, forced a login request. I thought I would report it to see if there was an issue with the plugin.

URL in question: chicagobusiness dot com/greg-hinz-politics/powerful-union-pushes-change-illinois-constitution (don't want to deeplink/show up in referrals)

**Comment by magnolia1234** [comment]
Try https://github.com/magnolia1234/bypass-paywalls-chrome-clean
Blocks TinyPass paywall-script by default.

**Comment by iamadamdev** [comment]
What is the issue with that article exactly? I can view it just fine.

**Comment by jimmydeuxfois** [comment]
Use this extension instead: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

It supports way more websites, it's more regularly updated and it doesn't track you with Analytics
