### ISSUE TITLE
Haaretz.co.il blank page

### ISSUE THREAD

**Issue by ShintoPlasm** [iamadamdev/bypass-paywalls-chrome#49]
Hi Adam,

I've started getting completely blank pages on Haaretz.co.il with the latest versions on both Chrome and Firefox. Disabling the 'Haaretz' item in the extension's website list immediately fixes this, with the website showing as normal.

Any idea what this might be, please?

**Comment by iamadamdev** [comment]
Will remove in the next version, for now just keep it unchecked. Seems like they removed the paywall for some articles.

**Comment by ShintoPlasm** [comment]
I beg to differ: Haaretz still have a paywall for most articles (pretty much everything that falls under the 'Premium' sub-domain). Clicking on any such article, the text itself is truncated after a paragraph or two, with a box asking if you want to take a subscription. They used to have a small number of articles which were reachable without paywall even prior to this...

Do you think they've changed the algorithm?

**Comment by iamadamdev** [comment]
Try now with the latest version. Be sure to turn off uBlock.

**Comment by iamadamdev** [comment]
which article? I just loaded 7 different articles (ublock enabled) and they all loaded fine, and you can read the whole article.
