### ISSUE TITLE
Straits Times

### ISSUE THREAD

**Issue by severing77** [iamadamdev/bypass-paywalls-chrome#490]
Hello!

Is it possible to add in the extension The Straits Times? It is a respectful newspaper for both Singapore and South Asia region.

https://www.straitstimes.com/opinion/the-word-of-the-year-for-2019-predictable

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by jimmydeuxfois** [comment]
lol, you had the same reaction haha You better using the new repo. Adam is spamming the same message on every new request, while the other dudes clearly tell you if you're site can be supported or not.
