### ISSUE TITLE
Request for Herald Sun

### ISSUE THREAD

**Issue by TP328** [iamadamdev/bypass-paywalls-chrome#491]
Hi, I would like to request Herald Sun | https://www.heraldsun.com.au/ to be added through bypass paywalls.

Cheers.

**Comment by iscreamcoke** [comment]
Added in my fork https://github.com/iscreamcoke/bypass-paywalls-chrome-clean

**Comment by iscreamcoke** [comment]
Added in my fork

**Comment by iamadamdev** [comment]
Please do not advertise your own repo in my repo. If you want to contribute to my repo I can give you credit for it though.

**Comment by TP328** [comment]
> 
> 
> Added in my fork

It finally works, it got rid of the subscription pop up. Cheers!
