### ISSUE TITLE
The Globe & Mail

### ISSUE THREAD

**Issue by marathone** [iamadamdev/bypass-paywalls-chrome#492]
Doesn't seem to work, despite being enabled in the extension. Tried on this url: https://www.theglobeandmail.com/arts/television/article-cbc-tv-is-a-shambles-nobody-watches-tv-out-of-patriotism/

**Comment by llacb47** [comment]
Test in uBlock Origin: `theglobeandmail.com##+js(set, keytar.accessAllowed, true)`

**Comment by magnolia1234** [comment]
Was fixed already, but just not is this repo.

**Comment by iamadamdev** [comment]
@magnolia1234 Are you not going to contribute to my repo anymore? Just work on your own fork? I've appreciated all your PRs. I can change it to give you credit if that is what you are after..

**Comment by magnolia1234** [comment]
Actually a mirror, so you can't delete my comments/issues anymore: https://github.com/magnolia1234/bypass-paywalls-chrome-clean
Bypass Paywalls Clean for Chrome (no Google Analytics, lot of updates and bug-fixes)

**Comment by magnolia1234** [comment]
> Test in uBlock Origin: `theglobeandmail.com##+js(set, keytar.accessAllowed, true)`

Works well, but what does it actually set (for conversion to BP)?
No sign of new cookie or key in local storage.

**Comment by iamadamdev** [comment]
I only deleted comments where you are advertising your own repo and not contributing to this one.. I think that is only fair.

**Comment by iamadamdev** [comment]
You still didn't answer my question.

**Comment by magnolia1234** [comment]
We moved on after fixing countless bugs in your repo and adding new sites (also in our free time). So should you ...
PS people know where to find this repo.

**Comment by iamadamdev** [comment]
Works fine on latest master

**Comment by marathone** [comment]
Thanks!
