### ISSUE TITLE
Can marketingweek and campaign UK be included?

### ISSUE THREAD

**Issue by Shubham-Kanoria** [iamadamdev/bypass-paywalls-chrome#493]
https://www.campaignlive.co.uk/article/ikeas-first-christmas-ad-tackles-home-shame-during-festivities/1665020
https://www.marketingweek.com/getting-started-tiktok-guide-marketers/

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by jimmydeuxfois** [comment]
You better using [the new repo](https://github.com/magnolia1234/bypass-paywalls-chrome-clean). Adam is spamming the same message on every new request, while the other dudes tell you clearly if you're site can be supported or not.
