### ISSUE TITLE
Old WSJ articles do not load

### ISSUE THREAD

**Issue by smnlng** [iamadamdev/bypass-paywalls-chrome#494]
example: https://blogs.wsj.com/marketbeat/2011/03/23/q-why-did-qqqq-drop-a-q-to-become-qqq/

not sure if hard paywall. using 1.6.2 latest.

**Comment by iamadamdev** [comment]
Not necessarily old articles, but I think blog posts are behind a hard paywall.

**Comment by iscreamcoke-official** [comment]
> Not necessarily old articles, but I think blog posts are behind a hard paywall.

This is obviously wrong. WSJ blog articles have been bypassed in bypass paywalls clean.

btw this repo is tracking you with a [Google Analytics script](https://github.com/magnolia1234/bypass-paywalls-chrome-clean). We don't.

**Comment by iscreamcoke-official** [comment]
This is obviously wrong. WSJ blog articles have been bypassed in [Bypass Paywalls Clean](https://github.com/magnolia1234/bypass-paywalls-chrome-clean).

btw this repo is using a Google Analytics script to track. It has been removed from Bypass Paywalls Clean.

**Comment by iscreamcoke-official** [comment]
> Not necessarily old articles, but I think blog posts are behind a hard paywall.

This is obviously wrong. WSJ blog articles have been bypassed in [Bypass Paywalls Clean](https://github.com/magnolia1234/bypass-paywalls-chrome-clean).

**Comment by llacb47** [comment]
Look, you are allowed to fork the repo. But you've been asked to stop multiple times promoting your repo and with your attacks on the maintainer.

**Comment by iscreamcoke-official** [comment]
> Look, you are allowed to fork the repo. But you've been asked to stop multiple times promoting your repo and with your attacks on the maintainer.

He's spreading misinformation. Half the websites which are supposed to be under "hard paywalls" can be indeed bypassed.

Plus, Adam has been recently threatening another developer, who is totally unrelated to his repo, of serious legal issues (calling News Corp to report someone.)

**Comment by iscreamcoke-official** [comment]
> Look, you are allowed to fork the repo. But you've been asked to stop multiple times promoting your repo and with your attacks on the maintainer.

He's spreading misinformation. Half the websites which are supposed to be under "hard paywalls" can be indeed bypassed.

Plus, Adam has been recently threatening another developer, who is totally unrelated to his repo, of serious legal issues (calling News Corp to report his work so that they can sue him.) 

I quote: `Since you used your real name and you live in ****, California, under the jurisdiction of the United States, enjoy getting sued by News Corp.`

Are you really supporting this type of behavior @llacb47?

**Comment by iscreamcoke-official** [comment]
> with your attacks on the maintainer.

By the way, I and Magnolia are the indeed the maintainers of this repo. Adam hasn't been committing a single PR since September 2018. The last fixes were copied from our repo (which is totally okay, it's MIT-licensed).

**Comment by iscreamcoke-official** [comment]
> with your attacks on the maintainer.

By the way, Magnolia and I are the indeed the maintainers of this repo. Adam hasn't been committing a single PR since September 2019. The last fixes were copied from our repo (which is totally okay, it's MIT-licensed).
