### ISSUE TITLE
https://www.business-standard.com/

### ISSUE THREAD

**Issue by aki-sud** [iamadamdev/bypass-paywalls-chrome#495]
### New site requests - Before submitting an issue please read the following:

Only large or major sites will be considered. For small sites try the [Cookie Remover](https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce) extension to remove cookies (might not work though).

1. Visit an article on the site you want to bypass the paywall for and copy the article title.
2. Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
3. Click on the same article from the Google search results page. If it loads without a paywall you can submit a request here, otherwise my extension cannot bypass it either.

Usually premium articles cannot be bypassed as they are behind a hard paywall.

**Comment by iamadamdev** [comment]
Did following those steps work?

**Comment by aki-sud** [comment]
No, the articles still can't be accessed even after following all the mentioned steps.
