### ISSUE TITLE
Request to add pub

### ISSUE THREAD

**Issue by copyvet** [iamadamdev/bypass-paywalls-chrome#496]
Please ad adweek.com to your list of pubs (the whole ad industry will thank you). I followed your instructions, searching for an AdWeek article title from an incognito window, and it worked, so you should be able to add it to your app.

Thanks!

**Comment by iscreamcoke-official** [comment]
Already supported in [Bypass Paywalls Clean](https://github.com/magnolia1234/bypass-paywalls-chrome-clean).

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
Added!
