### ISSUE TITLE
New site request: thecourier.com.au

### ISSUE THREAD

**Issue by danielgruber8** [iamadamdev/bypass-paywalls-chrome#500]

**Comment by iamadamdev** [comment]
Did you try the steps here?
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by danielgruber8** [comment]
Yes, it works incognito mode with a limit of 5 articles. If you have UBlock Origin, the article will half appear, if you disable UBlock Origin, the full text shows up.

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
Added!
