### ISSUE TITLE
Request for Financieel Dagblad

### ISSUE THREAD

**Issue by sarayliserkan** [iamadamdev/bypass-paywalls-chrome#501]
Hello!

Is it possible to add a bypass for the Dutch financial news website Financieel Dagblad at www.fd.nl?

Thanks!

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
Added

**Comment by sarayliserkan** [comment]
Thanks! Works perfect
