### ISSUE TITLE
Disabled with Chrome 80

### ISSUE THREAD

**Issue by orefalo** [iamadamdev/bypass-paywalls-chrome#502]
Extension is disabled with the latest Chrome, any solution?

Use disabled extensions
If you need to use a disabled extension, you can contact the extension’s developer and ask them to upload their extension to the Chrome Web Store. This will allow you, and other people who use Chrome, to install that extension from the Chrome Web Store, or if you already have it installed, to manually re-enable it from your list of extensions.

**Comment by linghutf** [comment]
I have met the same problem too!

**Comment by iamadamdev** [comment]
I'm on Version 80.0.3987.100 (Official Build) (64-bit) and it works fine for me. Do you have developer mode enabled at the top right?

**Comment by orefalo** [comment]
Chrome Version 80.0.3987.100

Developer Mode: On

Bypass Paywalls
 This extension is not listed in the Chrome Web Store and may have been added without your knowledge. Learn more.

**Comment by lqxyz** [comment]
I have the same issue with Chrome version 80.0.3987.106. One possible solution (at least it works for me) is that you can rename the `bypass-paywalls-chrome.crx` to `bypass-paywalls-chrome.zip`, then drag the `.zip` file into the extension page in developer mode.

**Comment by joker327** [comment]
On which platform could you still install local crx-file (not from Chrome webstore) though, Linux or MacOS?

**Comment by lqxyz** [comment]
Sorry, I forgot to mention that it is on MacOS.

**Comment by joker327** [comment]
Just use the master zip-file (no auto-update though).

**Comment by orefalo** [comment]
Thank you @lqxyz , using the zip rather than .crx worked!

**Comment by joker327** [comment]
Master-zip contains post-release commits though.
