### ISSUE TITLE
Belgium news papers

### ISSUE THREAD

**Issue by Dimitronn** [iamadamdev/bypass-paywalls-chrome#503]
Hi,

Is it possible to add a few Belgium newspapers like: 
https://www.gva.be
https://www.hln.be
https://www.nieuwsblad.be
(These are the most important ones in Belgium.)

Best regards Dimitri

**Comment by iamadamdev** [comment]
Did you try https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests ?
