### ISSUE TITLE
The Economist not working

### ISSUE THREAD

**Issue by nasr8** [iamadamdev/bypass-paywalls-chrome#504]
Keep getting a login prompt when clicking into articles

**Comment by ksbrar** [comment]
Bump.

**Comment by kachristophe** [comment]
Bump :)

**Comment by ksbrar** [comment]
Fixed for me as of v1.6.2, AKA: https://github.com/iamadamdev/bypass-paywalls-chrome/commit/6054ee4b666ac276f6925b7252e73965d0c03ff2

**Comment by iamadamdev** [comment]
How are you installing the extension? I've updated the repro w/ the fix. I haven't released the fix in the releases yet though.

It should work if you follow these instructions: https://github.com/iamadamdev/bypass-paywalls-chrome#installation-instructions

**Comment by kingkong914** [comment]
> How are you installing the extension? I've updated the repro w/ the fix. I haven't released the fix in the releases yet though.
 
The fix is actually merged in the latest release 1.6.2 though ...
Or did you forget about that (or more people using this account)?

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by ksbrar** [comment]
Like @kingkong914 said, it does seem to be merged in. Just checked the unzipped files in the 1.6.2 release and the changes are there. (Thanks btw!)
