### ISSUE TITLE
La Tercera and El Mercurio

### ISSUE THREAD

**Issue by manuelbarrosr** [iamadamdev/bypass-paywalls-chrome#507]
Dear sir,

I really appreciate your work. I think you deserve a Nobel Prize for your outstanding contribution to the liberation of information and the democratization of journalism around the world hahahaha.

I was wondering if you could update the bypass for La Tercera (https://www.latercera.com), is not working anymore. And if you could also include a bypass for the digital version of the Chilean newspaper, El Mercurio (https://digital.elmercurio.com).

That would be amazing!

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
latercera.com is still working for me. Do you have uBlock Origin installed?
What article are you seeing a paywall on?
