### ISSUE TITLE
Add this extension to Microsoft Store (For Edge Chromium)

### ISSUE THREAD

**Issue by phly95** [iamadamdev/bypass-paywalls-chrome#509]
Microsoft is much more lenient with what they allow on their store. 

Some examples include (please note, I do not know the quality or safety of any of these extensions, these are just ones I found on the front page):
https://microsoftedge.microsoft.com/addons/detail/ieldcidmneadgefinkaeglpjdfodjife?hl=en-US (a nsfw uncensor plugin)
https://microsoftedge.microsoft.com/addons/detail/ehpddkgglmclkjplannjoedcplahddbc?hl=en-US (a tool to download music from VK)
https://microsoftedge.microsoft.com/addons/detail/nbljcphcplbaiejdofbmlndimbhkblid?hl=en-US (an e-book finder)

I'm sure if they allow these extensions, that bypass paywalls would also be allowed. Also, this very repository is being hosted by Microsoft (Github is owned by them), so I think it would make a great home for this extension.

This would also resolve the developer warning every time you start the browser when installing it with the current method.

**Comment by iamadamdev** [comment]
But how many people use Edge Chromium?

**Comment by phly95** [comment]
Currently, according to netmarketshare, about 5.77% are using some variant of Edge (though that would include legacy Edge). 
Of course, I think the new edge is a nice middle ground between Chrome and Firefox, as it does have Built-in tracking protection and doesn't scan your hard drive, unlike Chrome. I think edge is the perfect substitute for Chrome users that have some reason not to use Firefox.

**Comment by joker327** [comment]
This extension will never be allowed in Microsoft Store though.

**Comment by phly95** [comment]
really? I'm pretty sure Microsoft would be one of the few that _would_ allow it based on this search page https://www.microsoft.com/en-us/search/shop/apps?q=anime . 

Keep in mind, I remember Anime Tube being on the Microsoft store ever since Windows 8 came out, so I don't think Microsoft cares (as long as it doesn't affect their own products).

**Comment by joker327** [comment]
Content Policies
2.8  Prohibited Content, Services and Activity
The extension contains content that provides unauthorized access to web content.
