### ISSUE TITLE
Bypass https://www.americanbanker.com/

### ISSUE THREAD

**Issue by nizishirin** [iamadamdev/bypass-paywalls-chrome#512]
The site does not work. The extension does not bypass the articles

**Comment by kingkong914** [comment]
Check repo: https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
Thanks for notifying me.
Fixed in latest version.
Enable the new "\*General Paywall Bypass\*" option.
