### ISSUE TITLE
Hi Adam, hope you're keeping well!

### ISSUE THREAD

**Issue by rsd1995** [iamadamdev/bypass-paywalls-chrome#515]
Hey Adam,

Was wondering how you are doing? Thanks so much for all the continued work. This is super helpful and I don't really know where you get the time to maintain this for this long - thanks a lot (on behalf of everyone!).

NewScientist has this interesting article about the Coronovirus and I was just wondering if you could apply your wiz-kid coding skills to bypass their paywall if possible. 

I know you have a super busy job and your own life to live so I can completely respect that - if you do happen to have some time lying around, I would really appreciate it if you didn't mind giving the NewScientist magazine a zap of your wizardry wand!

Thanks a lot once again, and I wish you all the best - take care.

Rishi

**Comment by iamadamdev** [comment]
I tested all the options but unfortunately it has a hard paywall.
