### ISSUE TITLE
telegraph.co.uk not working

### ISSUE THREAD

**Issue by Floydvincent** [iamadamdev/bypass-paywalls-chrome#518]
over the last month or so, starting off with just a couple of articles a day, now all articles.

**Comment by iamadamdev** [comment]
Works fine for me, are you on v1.6.3? Make sure general paywall bypass at the bottom of the sites in options is checked.

**Comment by Floydvincent** [comment]
Downloaded 1.6.2 today from GitHub

No option for general paywall bypass


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#installation-instructions
