### ISSUE TITLE
New site request: medscape

### ISSUE THREAD

**Issue by tyjohnnew** [iamadamdev/bypass-paywalls-chrome#519]
### medscape
https://www.medscape.com/

When you initially load the page, it shows the full article for a second, and then shows a cover `To continue reading this article`. I tried [Cookie Remover](https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce/related?hl=en), and Incognito window.

**Comment by joker327** [comment]
What's the use when though you can register for a free account?

**Comment by joker327** [comment]
https://help.medscape.com/hc/en-us/articles/360001482252-I-heard-that-Medscape-is-free-Is-that-true-
