### ISSUE TITLE
The new york Times error

### ISSUE THREAD

**Issue by XmansGhost** [iamadamdev/bypass-paywalls-chrome#52]
When i check the "The New York Times" checkbox for bypassing the paywall it crashes the login for nytimes.com and cooking.nytimes.com it does the same on firefox too please fix this

**Comment by iamadamdev** [comment]
What is the issue? You aren't supposed to be able to login to sites if you have it checked.
I just loaded 5 recipes from cooking.nytimes.com no problem.

**Comment by XmansGhost** [comment]
The recipe isnt the problem. The problem is the login break is causing some issue and it shows "Opps,cannot process your request" or something like that and that breaks images on the webpage

**Comment by iamadamdev** [comment]
I get that too..
