### ISSUE TITLE
Wall Street Journal not working

### ISSUE THREAD

**Issue by arsalan14** [iamadamdev/bypass-paywalls-chrome#521]
Hello, I'm trying to get access to this link but it's not working. Please have a look. 

Best.

https://www.wsj.com/articles/people-dont-save-enough-for-emergencies-but-there-are-ways-to-fix-that-11581951601?mod=rsswn

**Comment by iamadamdev** [comment]
Works fine for me, are you on v1.6.3? uBlock Origin also installed?

**Comment by arsalan14** [comment]
Hello. It works now. Thanks!
