### ISSUE TITLE
I am getting this pop up "The proxy http://proxysrv:3128 requires a username and password." so I can't access certain websites

### ISSUE THREAD

**Issue by twelvebutterflies** [iamadamdev/bypass-paywalls-chrome#526]
![Screen Shot 2020-02-23 at 12 52 19 PM](https://user-images.githubusercontent.com/61371664/75104417-62457600-563b-11ea-9040-e8e15a6f0759.png)
I can access most websites because of this pop up (sample of websites that I can't access: https://ads.google.com/ and http://www.jimthompsonhouse.com ). I tried to remove the bypass extension in chrome setting and un-install chrome and re-install chrome again, but I still get the same issue.
I really need to fix this issue, I don't mind lose the bypass access as long as I can access any websites like I used to. Looking forward for the help. Any help would be greatly appreciated.

**Comment by frantzkamus** [comment]
I don't think this is related to BypassPaywalls as the extension doesn't use a proxy. Try to look in your Windows or MacOS network configuration
