### ISSUE TITLE
New site request: thelocal.se

### ISSUE THREAD

**Issue by eyadsibai** [iamadamdev/bypass-paywalls-chrome#527]
I was able to see the article with google search

**Comment by iamadamdev** [comment]
I just opened 10+ articles fine w/o seeing any paywall. Do you have uBlock Origin installed?

**Comment by eyadsibai** [comment]
I don't have uBlock Origin installed.

Could you try this link?

[https://www.thelocal.se/20180223/how-to-manage-your-pension-in-sweden-even-if-youre-not-planning-to-stay](url)

**Comment by iamadamdev** [comment]
It opened fine for me. Maybe try installing uBlock Origin?

**Comment by eyadsibai** [comment]
thanks a lot. will close this issue
