### ISSUE TITLE
Seeking Alpha Paywall Bypass

### ISSUE THREAD

**Issue by Shyam-R204** [iamadamdev/bypass-paywalls-chrome#529]
Hi, 
Could you please add Seeking Alpha premium articles to the bypass list.

For e.g. https://seekingalpha.com/article/4323624-micron-spoke-bullish-tuesday-china-new-virus-cases-peaking

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
Did this work?

**Comment by Shyam-R204** [comment]
Thanks for the quick response

**Comment by texas560** [comment]
Quick, but not correct though.

**Comment by iamadamdev** [comment]
Added

**Comment by Shyam-R204** [comment]
Thanks a ton. You are incredible!

**Comment by spoetnik412** [comment]
Copied from https://github.com/magnolia1234/bypass-paywalls-chrome-clean
