### ISSUE TITLE
Extension doesn't install on Chrome 70.0.3538.45 (Official Build) beta (64-bit)

### ISSUE THREAD

**Issue by alex5723** [iamadamdev/bypass-paywalls-chrome#53]
There is no response from the browser, either blocking, error,...
Developer mode is on.

**Comment by XmansGhost** [comment]
Did u try the Load unpacked extension method?

**Comment by alex5723** [comment]
By unpacked you mean CRX ?
I tried to load version 1.2.1 crx and got an error : extension not on
Google store.

alex.

**Comment by alex5723** [comment]
By unpacked you mean crx ?

How do you load unpack ?

alex

**Comment by XmansGhost** [comment]
If you get the disable developer mode extensions popup here is the fix,
https://stackoverflow.com/questions/23055651/disable-developer-mode-extensions-pop-up-in-chrome/38011386#38011386

**Comment by alex5723** [comment]
Chrome deleted the extension.
Looks like I'll have to load the extension each time I open Chrome.

Regarding disabling developer mode extensions popup this doesn't work anymore :

As of July 2018, this approach no longer works: it seems Google has stopped honoring the "whitelist"

**Comment by XmansGhost** [comment]
> 
> 
> Chrome deleted the extension.
> Looks like I'll have to load the extension each time I open Chrome.
> 
> Regarding disabling developer mode extensions popup this doesn't work anymore :
> 
> As of July 2018, this approach no longer works: it seems Google has stopped honoring the "whitelist"
> 
> update : suddenly bypass-paywall loads when launching Chrome. Developer popup doesn't bother me.
> 
> Thanks.
> 
> Alex.

You mean you don't get the popup or are you ok with it?

**Comment by alex5723** [comment]
I do get the popup and close the  window.
I never close Chrome until I go to sleep, so closing that popup 1 time isn't a problem.

alex

**Comment by XmansGhost** [comment]
Well that's fine but if u do get irritated later you know where to look.
https://stackoverflow.com/questions/23055651/disable-developer-mode-extensions-pop-up-in-chrome/38011386#38011386
