### ISSUE TITLE
Cannot access nytimes

### ISSUE THREAD

**Issue by kfchou** [iamadamdev/bypass-paywalls-chrome#530]
NYTimes is requesting me to log in to continue reading articles. If I do log in, I'm redirected to a page about purchasing subscriptions. Does anyone else have this issue?

**Comment by iamadamdev** [comment]
Working fine for me.
![image](https://user-images.githubusercontent.com/36013816/75503792-867ebb00-598b-11ea-9b7b-62b2a1fbd081.png)

e.g., https://www.nytimes.com/2020/02/27/business/stock-market-coronavirus.html?action=click&module=Top%20Stories&pgtype=Homepage

Do you have uBlock Origin installed?
Are you located in the EU or US?

**Comment by kfchou** [comment]
I installed uBlock Origin and disabled adBlock Plus, still not working for me.

I'm located in the US.

**Comment by llacb47** [comment]
Try clearing nytimes cookies, updating ublock origin lists (right click on uBO -> options -> filter lists -> update now), and adding this to My filters in uBlock origin: `||nytimes.com/*/metered_assets/`

**Comment by kfchou** [comment]
Tried the three steps suggested by @llacb47, still not working...

**Comment by spoetnik412** [comment]
https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by kfchou** [comment]
Tried the extension "bypass-paywalls-chrome-clean" - still experiencing the issue.

**Comment by spoetnik412** [comment]
Probably conflict with an user-agent extension.
Is WSJ.com working for you though?
Maybe make an issue on @magnolia1234 repo?

**Comment by kfchou** [comment]
WSJ and bloomberg are both wroking fine

**Comment by spoetnik412** [comment]
Maybe try BP Clean Firefox addon (uses Javascript block)?
