### ISSUE TITLE
Spiegel online

### ISSUE THREAD

**Issue by 4ware** [iamadamdev/bypass-paywalls-chrome#535]
HTTP://spon.de

**Comment by iamadamdev** [comment]
There is no paywall on spiegel.de at least when tested with uBlock Origin on.

**Comment by xrow** [comment]
Not true. Here is one example: 

https://www.spiegel.de/wissenschaft/medizin/corona-weihnachten-als-treiber-der-pandemie-eine-analyse-der-wichtigsten-zahlen-a-11a409bb-0e16-426a-bc52-6fe8b91908be

**Comment by iamadamdev** [comment]
That's a hard paywall.
