### ISSUE TITLE
Hyperlinks in articles on economist.com don't work

### ISSUE THREAD

**Issue by AFlyingBird90** [iamadamdev/bypass-paywalls-chrome#536]
Hi, hyperlinks in articles on economist.com don't work when clicked. Normally without using the chrome extension, a new tab will appear after clicking. Now nothing will appear. Weirdly, hyperlinks in wsj.com function correctly.
Thank you for your time.

**Comment by iamadamdev** [comment]
Fixed!

**Comment by london617** [comment]
Indeed, fix copied from https://github.com/magnolia1234/bypass-paywalls-chrome-clean
