### ISSUE TITLE
maybe more?

### ISSUE THREAD

**Issue by theandychung** [iamadamdev/bypass-paywalls-chrome#54]
datacamp.com

**Comment by iamadamdev** [comment]
? you can make a free account there

**Comment by theandychung** [comment]
Only the first few videos are free, after that there will be a paywall blocking users watching the videos. For instance, in the [Introduction to Machine Learning](https://www.datacamp.com/courses/introduction-to-machine-learning-with-r) course, there is a paywall after the first chapter. Everything in the first chapter, *What is Machine Learning*, is free, but users have to pay to watch the videos in the later chapters (Performance measures, Classification, Regression, and Clustering). I can see the videos have been downloaded and ready to play, but there is a script or something pausing me whenever I click the play button. I wonder if you could help me figure out what that is. It will be even more awesome if we could just play the videos without registering.
