### ISSUE TITLE
WSJ no longer working with Chrome update to 80.0.3987.149

### ISSUE THREAD

**Issue by sbmechanics** [iamadamdev/bypass-paywalls-chrome#542]
Wall Street Journal no longer works after updating Chrome to 80.0.3987.149 on Windows 10.

**Comment by Anguria33** [comment]
Doesnt work also on Mac Chrome version

**Comment by sbmechanics** [comment]
For reference, still works in Firefox 74 / Windows 10 /v1.6.6, but only in a Private Window.

**Comment by Xibalba1** [comment]
> For reference, still works in Firefox 74 / Windows 10 /v1.6.6, but only in a Private Window.

For other users: This also works for me. Ensure you allow this Add-On to run in private windows.

**Comment by cgmcnama** [comment]
Latest version of Chrome it no longer works.  Noticed it about 12 hours ago.  Tried "Incognito" as well as turning off adblockers.

**Comment by iamadamdev** [comment]
Fixed in latest version.
