### ISSUE TITLE
Vivaldi - CPU Usage Spike

### ISSUE THREAD

**Issue by Traveller1701** [iamadamdev/bypass-paywalls-chrome#556]
This is similar to the user back in February who had the issue with Chrome freezing on his Mac when using the extension. In my case, running Vivaldi on Windows 10 1909, the extension appears to use a high number of CPU cycles (up to 20% CPU usage) and is not freeing them up. I have to go into Task manager and end the offending task eating up CPU cycles. As soon as I do I get a message that Bypass Paywalls has stopped, and anything I was attempting just prior immediately executes. For example, I was looking at pics on one page while watching (more accurately listening) to a video on YouTube. The video stopped streaming, clicking on a picture refused to load it into a new tab, and opening a new tab did nothing. As soon as Bypass Paywalls was stopped everything returned to normal.

**Comment by iamadamdev** [comment]
Seems like the same issue as https://github.com/iamadamdev/bypass-paywalls-chrome/issues/578

**Comment by Traveller1701** [comment]
It is, though in my case it takes a lot longer than 15 minutes for the issue to appear on Vivaldi. 

    On Sunday, April 26, 2020, 03:49:43 PM EDT, Adam <notifications@github.com> wrote:  
 
 


Seems like the same issue as #578

**Comment by iamadamdev** [comment]
Try latest master and let me know if the issue still persists.

**Comment by iamadamdev** [comment]
We can consolidate this issue to #578
