### ISSUE TITLE
Maz-Online.de

### ISSUE THREAD

**Issue by fschu64** [iamadamdev/bypass-paywalls-chrome#563]
Can you try to add MAZ Online?

https://www.maz-online.de/Lokales/Potsdam/Abiturpruefung-in-der-Coronapandemie-So-lief-der-erste-Pruefungstermin

**Comment by kimkha** [comment]
Have you tried this? https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#new-site-requests
