### ISSUE TITLE
request to add site to list of "Bypass Paywalls"

### ISSUE THREAD

**Issue by HansLoepfe** [iamadamdev/bypass-paywalls-chrome#565]
Hello,
would be nice if you could add "Der Aktionär" (www.deraktionaer.de) a site in German to the list of Bypass Paywalls.
Below a link to one of their articles:
[https://www.deraktionaer.de/artikel/gold-rohstoffe/gold-aktien-die-nummer-1-weist-den-weg-20200051.html](https://www.deraktionaer.de/artikel/gold-rohstoffe/gold-aktien-die-nummer-1-weist-den-weg-20200051.html)

Thanks for your efforts.
Greetings, Hans.

**Comment by kimkha** [comment]
Have you tried this? https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#new-site-requests

**Comment by HansLoepfe** [comment]
Hello, 

thanks for your answer.

YES, that is what I tried first.
Using the site-request was/is my last resort.

Hope there will be a solution soon.

Thanks for your efforts.

Kind regards, Hans.

**Comment by kimkha** [comment]
Well, I really meant that if you couldn't bypass by following that guideline, the website may have a hard paywall, and the extension is unable to bypass it neither.

**Comment by kimkha** [comment]
I just checked, looks like it has a hard paywall. We can't bypass it. The issue could be closed, I think. @iamadamdev
