### ISSUE TITLE
Please Add: Der Bund (Major Swiss Newspaper)

### ISSUE THREAD

**Issue by SecureCook** [iamadamdev/bypass-paywalls-chrome#566]
https://www.derbund.ch/kantone-lassen-maturanden-zappeln-915665859632

**Comment by kimkha** [comment]
Have you tried this? https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#new-site-requests

**Comment by iamadamdev** [comment]
Unfortunately it is behind a hard paywall.
