### ISSUE TITLE
bypass_dealstreetasia.com

### ISSUE THREAD

**Issue by lexquocxkhanh** [iamadamdev/bypass-paywalls-chrome#568]
Hi Adam,
Please help to bypass this website https://www.dealstreetasia.com/
Thanks,
Harry

**Comment by kimkha** [comment]
Have you tried this? https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#new-site-requests

**Comment by kimkha** [comment]
@lexquocxkhanh I added the website, would you mind to check? Download link here https://github.com/kimkha/bypass-paywalls-chrome/archive/dealstreetasia.zip

**Comment by iamadamdev** [comment]
Those seem to be behind a hard paywall.
