### ISSUE TITLE
bypass for subscribestar paywall

### ISSUE THREAD

**Issue by HotFemBoy47** [iamadamdev/bypass-paywalls-chrome#569]
any way to bypass subscribestars paywalld nsfw art the site https://subscribestar.adult/burgerkiss?redirect_notice=true

**Comment by kimkha** [comment]
Have you tried this? https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#new-site-requests

**Comment by HotFemBoy47** [comment]
yea just tryd it dostnt work sadly the site has this hole locking thing for the images and bluers them out and to unlock them you have to pay and it charges up front so fake card wouldnt work to bypass

**Comment by kimkha** [comment]
Oh, thanks for confirming, but that means this site has a hard paywall. So this plugin can't bypass either. This issue should be closed. cc @iamadamdev

**Comment by HotFemBoy47** [comment]
ok
