### ISSUE TITLE
Bypass-Paywalls doesn't affect a site anymore

### ISSUE THREAD

**Issue by alex5723** [iamadamdev/bypass-paywalls-chrome#57]
Bypass-Paywalls v1.3.4 doesn't affect https://www.haaretz.co.il/captain on new Chrome 71.0.3578.20 (Official Build) beta (64-bit). Bypass-Paywalls used to bypass the paywall on previous Chrome 70 beta.

**Comment by alex5723** [comment]
Thanks. I don't use Firefox.

**Comment by alex5723** [comment]
Site is blocked on Firefox ESR 60.3.0 Portable as well.

**Comment by iamadamdev** [comment]
removed

**Comment by alex5723** [comment]
Will there be an updates version to fix my problem ?

Regards,
