### ISSUE TITLE
NY Mag sites not working

### ISSUE THREAD

**Issue by sjeble** [iamadamdev/bypass-paywalls-chrome#572]
E.g. I've been getting blocked by Vulture's article limit lately. NY Mag sites include NYMag, Vulture, Grub Street, The Cut, Intelligencer, The Strategist

https://nymag.com/

**Comment by iamadamdev** [comment]
NY mag itself is working fine for me. The others are not supported yet.

**Comment by sjeble** [comment]
> NY mag itself is working fine for me. The others are not supported yet.

Can I request those sites be added then?

https://www.thecut.com/
https://www.grubstreet.com/
https://www.vulture.com/

**Comment by kimkha** [comment]
Have you tried this for other sites? https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#new-site-requests

**Comment by kimkha** [comment]
I just tried the cut and Vulture, there is no limit at all...

**Comment by sjeble** [comment]
> I just tried the cut and Vulture, there is no limit at all...

I cleared my browser data and now it's working fine, huh. I could have sworn I'd done that recently and still encountered the limit.

And I requested these sites [in the past](https://github.com/iamadamdev/bypass-paywalls-chrome/issues/137) and the issue was closed, that's why I assumed they were already included.
