### ISSUE TITLE
The Athletic does not work

### ISSUE THREAD

**Issue by Castle999** [iamadamdev/bypass-paywalls-chrome#573]
Sample link below, thank you!

https://theathletic.co.uk/1759832/2020/04/21/newcastle-takeover-bruce-charnley-transfers/?article_source=search&search_query=newcastle%20united

**Comment by kimkha** [comment]
Can you use https://theathletic.com/1759832/2020/04/21/newcastle-takeover-bruce-charnley-transfers/ instead? It works for me. And then, from now on, you should use theathletic.com. 😄 

I'm not sure if @iamadamdev is okay with an alias domain.

**Comment by Castle999** [comment]
Unfortunately not... thanks for trying though!

**Comment by kimkha** [comment]
@Castle999 could you please checkout my PR and see if the problem is fixed?

**Comment by Castle999** [comment]
Not sure how to go about the PR, please advise and excuse me

**Comment by kimkha** [comment]
oh, sorry. Download here: https://github.com/kimkha/bypass-paywalls-chrome/archive/theathletic-uk.zip, unzip and install. (You may need to remove the old extension first)

Let me know if anything happen.

**Comment by kimkha** [comment]
@iamadamdev merged the PR to master, this issue should be closed.
