### ISSUE TITLE
WashingtonPost.com isn't working anymore

### ISSUE THREAD

**Issue by xjapanboy** [iamadamdev/bypass-paywalls-chrome#576]
Tested on several devices and several time in 23 April 2020, this awesome hack(?) doesn't work anymore on https://www.washingtonpost.com/

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed?
Works fine for me.

**Comment by xjapanboy** [comment]
well i wasn't, just installed it then retry reinstall the code as well,
yet it still doesn't work on washingtonpost.com

Just for your information, this is the version of chrome i use.
"Google Chrome is up to date
Version 81.0.4044.122 (Official Build) (64-bit)"

here's the preview of the site
did i miss something?

>

**Comment by xjapanboy** [comment]
whether the adblock is on or not, it still the same

**Comment by llacb47** [comment]
Try adding this to your filters in uBlock origin: `||washingtonpost.com^*/pwapi-$script`

(by the way, you don't even need an extension to bypass the paywall on wapo)

**Comment by kimkha** [comment]
No problem to me too, note: I have no adblock.
