### ISSUE TITLE
Add support for investing.com ad-block wall

### ISSUE THREAD

**Issue by lucmult** [iamadamdev/bypass-paywalls-chrome#579]
It adds a wall if you have the ad-block enabled.

<img width="871" alt="Screen Shot 2020-04-24 at 4 33 07 pm" src="https://user-images.githubusercontent.com/33389/80182054-609f2b00-8649-11ea-81e0-b4674fe8489c.png">

**Comment by lucmult** [comment]
Let me see if I can quickly add a PR for this.

**Comment by iamadamdev** [comment]
Try using uBlock Origin instead, it's better than ABP. Also I don't get that popup.

**Comment by lucmult** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/pull/580

**Comment by lucmult** [comment]
Thanks, I hadn't seen you message about uBlock. :-)

Yes, I've installed uBlock and it doesn't show the popup. I'm use it for a few days to see.

As of for the PR, up to you if you want to merge or not.
