### ISSUE TITLE
update_url causing chromium-web-store to fail

### ISSUE THREAD

**Issue by RainmakerRaw** [iamadamdev/bypass-paywalls-chrome#581]
As per the [issue logged with NeverDecaf/chromium-web-store](https://github.com/NeverDecaf/chromium-web-store/issues/17), an extension that allows Ungoogled Chromium to add and update .crx extensions. The update_url in bypass-paywalls-chrome causes the webstore extension's update check to fail, and the suggested fix is to change the update_url to https://raw.githubusercontent.com/iamadamdev/bypass-paywalls-chrome/master/src/updates/updates.xml

I don't know if this is possible or if it's even appropriate to ask, but I'm filing this issue because the inability to update (with update checks on the chromium-web-store extension) affects me too. I searched to check whether it had already been filed here but it hasn't that I could see.

**Comment by iamadamdev** [comment]
Thanks for letting me know, fixed in latest master.
Btw, what Chromium browser do you use? And do updates for Bypass Paywalls work?

**Comment by RainmakerRaw** [comment]
Thanks for the speedy fix! I veer between [Eloston's Ungoogled Chromium](https://github.com/Eloston/ungoogled-chromium) and [Marmaduke's build](https://chromium.woolyss.com/) based off it, depending on platform. 
I can't tell you whether updating Bypass Paywalls works yet as the chromium-webstore extension can't check until there's a new release with the fixed update URL. To test from master I'd have to uninstall the current extension, add the master as unpacked in developer mode, check if it works and then redo it. I might be able to later but I don't have time at the present sorry. I can tell you that so far chromium-webstore allows normal installation of crx files without need for unpacking or dev mode, and updates them fine even from outside the Google Play Store / GitHub.
