### ISSUE TITLE
Lemonde.fr not displayingg full article

### ISSUE THREAD

**Issue by galafrin** [iamadamdev/bypass-paywalls-chrome#587]
Since a few weeks , lemonde.fr is not displaying articles in full length although the length is larger than without this extension at anywhere between 20 and 50%. This length is greater with Firefox than  Chrome, to add more puzzle, and at the same time weighting on the side of  no hard paywall set up yet.  
The extension still woks great in other sites I read, Keep up the fantastic job.

![bypass](https://user-images.githubusercontent.com/18517026/80283466-08832a00-8718-11ea-8317-80abe9ddc363.png)

**Comment by kimkha** [comment]
I think Lemonde.fr has a hard paywall now, that's why Adam removed it in https://github.com/iamadamdev/bypass-paywalls-chrome/commit/f780cf9e5103dedcdf3a1fcfd762d302546d1327

**Comment by galafrin** [comment]
I am not sure what hard paywall means here but yes, Lemonde being removed from options might say that Bypass no longer supports it.
