### ISSUE TITLE
some WSJ articles don't open

### ISSUE THREAD

**Issue by amiralizb** [iamadamdev/bypass-paywalls-chrome#588]
is it just me or some articles no longer work: 

https://www.wsj.com/graphics/from-brooklyn-to-beijing-portrait-photos-isolation-coronavirus/?mod=article_inline&mod=hp_lead_pos7

https://www.wsj.com/graphics/coronavirus-projections-for-shutdown-reopening-states/?mod=article_inline&mod=hp_lead_pos8

**Comment by kimkha** [comment]
I'm not sure why but there is a restriction on WSJ:

https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/src/js/background.js#L5

The URL above is `/graphics/` which is ignored by the restriction.

I will have a fix, and let Adam decides to adopt or not.

**Comment by iamadamdev** [comment]
Fixed! Thank you @kimkha
