### ISSUE TITLE
https://www.news-mail.com.au

### ISSUE THREAD

**Issue by TesterMan247** [iamadamdev/bypass-paywalls-chrome#59]
https://www.news-mail.com.au articles still are not working.

EG: https://www.news-mail.com.au/news/mumstobe-flee-private-sector-due-to-soaring-costs/3570105/

**Comment by iamadamdev** [comment]
Why should it? That domain was never added to the list. The google referral trick won't work for that site.

**Comment by TesterMan247** [comment]
I understand that.

I raised this issue to see if this page could be newly added so that it does work in the future.

Thanks.
