### ISSUE TITLE
[Bug]  Whatsapp Web - Involuntarily Logged Out

### ISSUE THREAD

**Issue by HoraceYim** [iamadamdev/bypass-paywalls-chrome#591]
https://web.whatsapp.com

v1.7.0 introduced a bug where the extension would auto log-out any Whatsapp web sessions.

v1.6.4 does not have this problem

To replicate:
1. Go to https://web.whatsapp.com
2. Click "keep me logged in"
3. Click and add Whatsapp Web on Whatsapp (Android or iOS)
4. Scan the QR code 
5. Logged-in successfully to  https://web.whatsapp.com
6. Refresh page  https://web.whatsapp.com
7. v1.6.4 would stay logged in.   v1.7.0 would be logged out

**Comment by iamadamdev** [comment]
Try unchecking all the sites, does it keep you logged in?
Then try checking all the sites except '*General Paywall Bypass*', does it keep you logged in?

**Comment by HoraceYim** [comment]
**v 1.7.0**

1) Unchecked all sites 
Result:  automatically LOGGED OUT

2) Checked all sites except "General Paywall Bypass"  
Result:  automatically LOGGED OUT

3) Checked all the sites 
Result:  automatically LOGGED OUT

---

**v 1.6.7**

1) Unchecked all sites 
Result:   remained LOGGED IN

2) Checked all sites except "General Paywall Bypass"  
Result:   remained LOGGED IN

3) Checked all the sites 
Result:   remained LOGGED IN


Appreciate your help!   Thanks, Adam!

**Comment by HoraceYim** [comment]
**v 1.7.0**

1) Unchecked all sites 
Result:  automatically LOGGED OUT

2) Checked all sites except "General Paywall Bypass"  
Result:  automatically LOGGED OUT

3) Checked all the sites 
Result:  automatically LOGGED OUT

---

**v 1.6.4**

1) Unchecked all sites 
Result:   remained LOGGED IN

2) Checked all sites except "General Paywall Bypass"  
Result:   remained LOGGED IN

3) Checked all the sites 
Result:   remained LOGGED IN


Appreciate your help!   Thanks, Adam!

**Comment by iamadamdev** [comment]
Fixed in latest master.
