### ISSUE TITLE
Package in invalid: ''CRX_HEADER_INVALID'.

### ISSUE THREAD

**Issue by perfect7gentleman** [iamadamdev/bypass-paywalls-chrome#592]
1 - clone repo
2 - run 'sh build/build.sh'
3 - drag-n-drop build/output/bypass-paywalls.crx to install

**Comment by iamadamdev** [comment]
That it expected: https://stackoverflow.com/questions/57034873/chrome-package-is-invalid-crx-header-invalid

Please install following the instructions https://github.com/iamadamdev/bypass-paywalls-chrome#installation-instructions

**Comment by perfect7gentleman** [comment]
I don't get it why it is expected. CRX downloaded from Release section are fine.

**Comment by iamadamdev** [comment]
From the release section is okay because I packed those CRXs from Chrome manually.
Using the build script just creates a zip file and renames it CRX. (it might work on other Chromium-based browsers)

**Comment by bre7** [comment]
If you still want to generate your own CRX, just follow the docs: https://developer.chrome.com/extensions/linux_hosting#create

**Comment by realdimas** [comment]
Or just rename `bypass-paywalls.crx` to `bypass-paywalls.zip` and upload it like this.
