### ISSUE TITLE
https://www.themarker.com/wallstreet/1.8804711?fbclid=IwAR0WtIsxZuUvgiLSz2sqeOA8DM2OP8OdEaLi3DFhiBpxHjdftgfhSUmxOx8New site request: [site here]

### ISSUE THREAD

**Issue by acetriper** [iamadamdev/bypass-paywalls-chrome#596]
Confirmed

**Comment by kimkha** [comment]
I think we already bypassed this website. If you installed adblocker, please disable it and try again.

**Comment by acetriper** [comment]
Hi, if I have ublock origin the website detects an adblocker, and doesnt work at all, if the ublock origin is disabled, there are big pop ups on the page to pay for the website/ register etc., so reading the articles is difficult, what is the best way to fix this?
thank you!

**Comment by llacb47** [comment]
Make sure you have the hebrew list enabled.
