### ISSUE TITLE
New site request: Espn +

### ISSUE THREAD

**Issue by vigneshvelu** [iamadamdev/bypass-paywalls-chrome#597]
Here is an example article: https://www.espn.com/nfl/draft2020/insider/story/_/id/29056681/2020-nfl-draft-grades-mel-kiper-all-32-classes-best-picks-steals-sleepers 

Is it possible to bypass this paywall please? Thank you so much

**Comment by kimkha** [comment]
I think this website is behind a hard paywall, the extension can't bypass it either.
