### ISSUE TITLE
https://www.themercury.com.au

### ISSUE THREAD

**Issue by TesterMan247** [iamadamdev/bypass-paywalls-chrome#60]
https://www.themercury.com.au articles cannot be opened.

EG: https://www.themercury.com.au/news/scales-of-justice/armed-and-dangerous-man-jailed-for-drugfuelled-series-of-assaults/news-story/14d06896f770924d52e785e75884b334

**Comment by iamadamdev** [comment]
That site was never added in the first place. The google referral trick won't work on that site.

**Comment by TesterMan247** [comment]
I understand that.

I raised this issue to see if this page could be newly added so that it does work in the future.

Thanks.

**Comment by iamadamdev** [comment]
The google referral trick won't work on that site.

**Comment by iamadamdev** [comment]
No unless you can figure one out..
