### ISSUE TITLE
New site request: nationalgeographic.com

### ISSUE THREAD

**Issue by karapastour** [iamadamdev/bypass-paywalls-chrome#600]
### New site requests - Before submitting an issue please read the following:

Only large or major sites will be considered. For small sites try the [Cookie Remover](https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce) extension to remove cookies (might not work though).
Usually premium articles cannot be bypassed as they are behind a hard paywall.

1. Install the uBlock Origin extension if it hasn't been installed already. See if you are still getting a paywall. If so, continue to the next step.
2. Visit an article on the site you want to bypass the paywall for and copy the article title.
3. Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
4. Click on the same article from the Google search results page.
5. If it loads without a paywall replace this entire template text with the word "Confirmed" with the site in the title and submit the request. Otherwise please do not submit an issue as this extension cannot bypass it either.

**Comment by kimkha** [comment]
@karapastour Can you give an paywalled link?

**Comment by iamadamdev** [comment]
Please read the instructions carefully.
