### ISSUE TITLE
NYT, LAT prompt login when shared on facebook. 

### ISSUE THREAD

**Issue by Steevow** [iamadamdev/bypass-paywalls-chrome#603]
I noticed when sharing a NYT story on fb, I got a please login window from facebook. It appears suddenly, probably when the preview loads. The window has two buttons, login and cancel.  The login request which goes away on it's own by reloading the page without me touching anything, which of course flushes the story link I pasted in.  Oops. 
This happens as soon as I paste a story from these outlets in, I do not have to click post. It seems to come from the preview. 

I notice now it happens with an LAT story, and a Bloomberg story. 
Here is the most recent: 
https://www.bloomberg.com/news/articles/2020-04-29/beef-prices-hit-record-with-trump-ordering-plants-to-stay-open
. 
I am already logged in on facebook. This may be a facebook problem, not an extension problem. 
Disabling the bypass paywalls chrome extension stops this from happening. 
There does not seem to be a way to whitelist facebook on the extension, but that might work to solve this issue.

**Comment by kimkha** [comment]
Oh, I know why @iamadamdev , apparently because the url is like: `https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.bloomberg.com%2F...` which matches `bloomberg.com`. 😄

**Comment by kimkha** [comment]
Okay, the fix is coming.
