### ISSUE TITLE
Economist not working

### ISSUE THREAD

**Issue by iameremortal** [iamadamdev/bypass-paywalls-chrome#605]
The Economist isn't working. I have tried to solve this by installing the latest version, turning off uBlock and refreshing, and unchecking the General Paywall Bypass. Unfortunately, none of them work. Other people also asked me about this problem this morning. I wonder if there is a problem with The Economist site. Thank you.

**Comment by originalthoughts** [comment]
While he's working on it, you can use outline.com to access articles on the economist.

**Comment by llacb47** [comment]
Add this filter to uBlock Origin: `economist.com##+js(json-prune, props)`

By the way, 95% of paywalls can be solved without additional extensions just using uBlock Origin.

**Comment by iamadamdev** [comment]
Fixed in latest master.
