### ISSUE TITLE
The Economist; Does not work

### ISSUE THREAD

**Issue by mumtazbey** [iamadamdev/bypass-paywalls-chrome#609]
Whenever i wanna read an article that published on economist(https://www.economist.com) the page I wanna read is reloading again and again and it keeps telling me that "please Subscribe to The Economist". By the way, i use google chrome with the latest version of bypass paywalls. Could you fix this? Please take a loook at this situation.

**Comment by kimkha** [comment]
may I know the url of that article please?

**Comment by oxdc** [comment]
I encounter this issue here: https://www.economist.com/briefing/2020/04/30/the-90-economy-that-lockdowns-will-leave-behind

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed and are you running off latest master?
That article works fine for me.

**Comment by kimkha** [comment]
I don't have uBlock Origin or Adblock, and it works fine for me too.
