### ISSUE TITLE
https://www.haaretz.co.il/ stopped work

### ISSUE THREAD

**Issue by MrTal** [iamadamdev/bypass-paywalls-chrome#61]
Hi
thr site: https://www.haaretz.co.il/news/politi/.premium-1.6636204  stopped work ad now have ad on premium
link exmpke: https://www.haaretz.co.il/news/politi/.premium-1.6636204
https://www.haaretz.co.il/sport/mitbonen/.premium-1.6635944
screenshot: http://prntscr.com/lgax82
tank you!

**Comment by ShintoPlasm** [comment]
Agreed, Haaretz.co.il no longer works for me - all Premium articles are now truncated and showing the 'Subscribe/Login' overlay. Disabling uBO doesn't seem to help, nor does removing all cookies, re-enabling the extension, de/reselecting Haaretz in the extension menu, or restarting Chrome entirely.

Extension version: 1.3.4

**Comment by iamadamdev** [comment]
Removed Haaretz.co.il, too many issues with that site. So many annoying popups too.

**Comment by MrTal** [comment]
@iamadamdev 
Too bad...

**Comment by richards1052** [comment]
I am so sorry you gave up on Haaretz.co.il.  It was such a useful plugin for me.  Next time you update you should remove it as an option in the pub list.
