### ISSUE TITLE
The Economist not working

### ISSUE THREAD

**Issue by raresnicolaide** [iamadamdev/bypass-paywalls-chrome#611]
The Economist is not working - website keeps refreshing every second or so, paywall still there

**Comment by iamadamdev** [comment]
Which article?

**Comment by alabama2552** [comment]
> Which article?

unfortunately, any article you choose. thanks

**Comment by iamadamdev** [comment]
I loaded 10+ articles no problem on latest master.

**Comment by alabama2552** [comment]
> I loaded 10+ articles no problem on latest master. Google Chrome Version 81.0.4044.129 (Official Build) (64-bit).

I was using Firefox. I tried with ublock turned on/off. Thanks.

**Comment by iamadamdev** [comment]
What version of Bypass Paywalls are you using on Firefox? Make sure you are on the latest.

**Comment by kimkha** [comment]
Duplicates #613 ?

**Comment by pimmelpiet** [comment]
Using Chrome Version 83.0.4103.34 (Official Build) beta (64-bit) it does not seem to work either, tried a couple of times with some tweaks. There was a similar problem a few months ago and it was fixed very efficiently and fast, might be the same issue?

**Comment by bearngrin** [comment]
Same here using Chrome 81.0.4044.138(stable) 64-bit. Infinite reloads withou showing the full article. Example article: https://www.economist.com/books-and-arts/2020/05/09/how-pandemics-have-inspired-art-music-and-literature

**Comment by iamadamdev** [comment]
That article works fine for me. 
You can always disable javascript in uBlock Origin by clicking on the <> icon at the bottom right:
![image](https://user-images.githubusercontent.com/36013816/81507883-2ecacd00-92b5-11ea-83c4-eec3dabaed0c.png)
