### ISSUE TITLE
Tried all troubleshooting methods, but still not working for The Economist

### ISSUE THREAD

**Issue by YIYUNZ** [iamadamdev/bypass-paywalls-chrome#613]
Hi, thanks for your contribution. About a week ago, I could not view The Economist pages without logging in. I tried all the troubleshooting methods and reinstalled the latest version of this extension, but things still don't work out. When I click onto a passage in The Economist websites, the page keeps refreshing automatically. I don't know what's going on. Looking forward to you reply.

**Comment by iamadamdev** [comment]
You can always use uBlock Origin to disable JS:
![image](https://user-images.githubusercontent.com/36013816/81141976-152b2d80-8f23-11ea-8b1a-8071ceb2b3ae.png)

**Comment by YIYUNZ** [comment]
solved. Thx a lot.

**Comment by kimkha** [comment]
Duplicates #611 ?
