### ISSUE TITLE
Seekingalpha.com

### ISSUE THREAD

**Issue by mxxmxm** [iamadamdev/bypass-paywalls-chrome#614]
Cannot bypass captcha page

https://seekingalpha.com/

**Comment by llacb47** [comment]
Are you a robot? 😄

**Comment by mxxmxm** [comment]
Select all the traffic lights 🤔

**Comment by mxxmxm** [comment]
Here's a screen shot
![Capture](https://user-images.githubusercontent.com/11645390/81369307-6c085100-9135-11ea-842d-ed2c803627e8.PNG)

**Comment by kimkha** [comment]
I can access this https://seekingalpha.com/article/4344085-second-wave. No captcha or anything.

Did you have adblock or alike?
