### ISSUE TITLE
not working on foreign policy

### ISSUE THREAD

**Issue by haidernawaz99** [iamadamdev/bypass-paywalls-chrome#616]
I am trying to read an article at **foreign policy**, but I get hit by a message to pay. I have also tried accessing with AdBlock off, and still no luck. The icon of the extension turns blue with the word 'ON' when I am accessing [**foreign policy**](foreignpolicy.com), but unfortunately, it doesn't work.

[The link of the article I am trying to access](https://foreignpolicy.com/2020/05/08/botched-venezuela-operation-boon-nicolas-maduro-american-mercenaries-jordan-goudreau-juan-guaido/)

![image](https://user-images.githubusercontent.com/29353361/81511622-1221aa00-9334-11ea-89be-0683ba5604a3.png)

**Comment by iamadamdev** [comment]
Get rid of AdBlock and try uBlock Origin.
Works for me:
![image](https://user-images.githubusercontent.com/36013816/81511677-eb318c80-92cf-11ea-94cf-18e3aff5ce34.png)

**Comment by haidernawaz99** [comment]
Still same issue 


![image](https://user-images.githubusercontent.com/29353361/81511777-169a9280-9335-11ea-8474-3769245d9188.png)

But, it does work with the JavaScript disabled.
Thank you for a really fast reply!

**Comment by haidernawaz99** [comment]
disabling JS breaks down some features like pictures not loading

**Comment by llacb47** [comment]
add `||tinypass.com^` to your filters in Ubo.

**Comment by haidernawaz99** [comment]
Yes, it is working now with the JS enabled. Thank you again for replying me quick!

**Comment by lovemath314** [comment]
It still does work for me. Here is the trick. If a subscribe pop up appears, I use the cookie remover extension to remove cookies and refresh the site, then I could read the page.
