### ISSUE TITLE
Subsection of New York Times seems not to work

### ISSUE THREAD

**Issue by lovemath314** [iamadamdev/bypass-paywalls-chrome#617]
I am able to access the NYT in general, I mean the [home page](https://www.nytimes.com) or a section page, for example [OPINION section](https://www.nytimes.com/section/opinion).  But if I want to go deeper, for example, a subsection [Paul Krugman opinion](https://www.nytimes.com/column/paul-krugman), then the page appears nothing, as the photo below.  
![Snapshot_2020-05-11_005253_www nytimes com paul-krugman-opinion](https://user-images.githubusercontent.com/52233499/81512594-e5fd2d80-9321-11ea-90ff-8265ce0b681d.png)

Thank you.

**Comment by iamadamdev** [comment]
Really strange but if you open up Chrome inspector (CTRL+SHIFT+I) and then refresh the page it works..
Also I'm not sure my extension is even needed on NYT anymore...

**Comment by iamadamdev** [comment]
Pushed up a possible fix, try latest master

**Comment by lovemath314** [comment]
> Really strange but if you open up Chrome inspector (CTRL+SHIFT+I) and then refresh the page it works..

Yes. It works now. 
Many thanks.
