### ISSUE TITLE
New site request: globes.co.il

### ISSUE THREAD

**Issue by electric3055** [iamadamdev/bypass-paywalls-chrome#620]
Confirmed

**Comment by kimkha** [comment]
I tried multiple articles, such as https://www.globes.co.il/news/article.aspx?did=1001328054, there is no paywall.

Can you give me a paywalled url?

**Comment by electric3055** [comment]
I think they are allowing to view some articles every month for free, and perhaps some articles are not blocked at all.
In any case, you can try the following: https://www.globes.co.il/news/article.aspx?did=1001328505
I'm attaching screenshots of that page in paywalled mode and through a google search, as you can see the paywalled article shows only the first two lines of text.
uncensored: https://imgur.com/t7uy0uN
censored: https://imgur.com/EOc2SpI

**Comment by iamadamdev** [comment]
I copied the link to a new tab and the full article still loads.
Do you have uBlock Origin installed?

**Comment by kimkha** [comment]
I also copied the link, it showed a censored version a few seconds, and then the full article.

**Comment by electric3055** [comment]
I have it installed
