### ISSUE TITLE
Medium signs you out when extension is enabled

### ISSUE THREAD

**Issue by dmdque** [iamadamdev/bypass-paywalls-chrome#621]
When accessing parts of medium.com (seems to happen when accessing user-specific features, like your own profile), it logs you out. Attempting to log in redirects to medium.com with unsuccessful login.

**Comment by iamadamdev** [comment]
Even when Medium is unchecked in options?

**Comment by Zegna1224** [comment]
> When accessing parts of medium.com (seems to happen when accessing user-specific features, like your own profile), it logs you out. Attempting to log in redirects to medium.com with unsuccessful login.

> Even when Medium is unchecked in options?

Hello, same problem.  Tried everything did not work.  Please help

**Comment by iamadamdev** [comment]
Does the Firefox version have this issue?

**Comment by Mik2020** [comment]
> Does the Firefox version have this issue?

Good afternoon, yes i am using Firefox. Thanks

**Comment by iamadamdev** [comment]
Uncheck all the sites. 
Visiting https://medium.com/me/settings still keeps me logged in.

**Comment by SyntrophicConsortium** [comment]
I am having this issue with the Firefox add-on, as well. I've found that I can circumvent the issue by opening medium.com in a container, but then Bypass Paywall no longer works for Medium. 

I tried unchecking medium.com, but it doesn't seem to stay checked. If I go back into the add-on options, it will appear checked again (that is a separate issue, though).

**Comment by iamadamdev** [comment]
What is the problem exactly?
I cannot reproduce. Medium keeps me logged in.

**Comment by jctam** [comment]
I might be having the same problem with Feedly? Feedly is not a site covered by this extension, so I can't uncheck it. But I've been consistently logged out of feedly every time I close the tab for the past few days. I disabled all my extensions and reenabled them one by one, and this is the one that was causing the problem.
I'm not sure if it's the same problem that's happening with medium, but I do have feeds on feedly from sites on this extension's list, like the NY Times.

**Comment by enilsen16** [comment]
I have this issue. It seems to happen when you log into medium with the extension enabled. If you previously loggedin before then this doesn't happen.

**Comment by iamadamdev** [comment]
That's because medium uses a magic link to log you in, you need to uncheck medium first, login, then turn it back on.
