### ISSUE TITLE
some wsj.com pages not working

### ISSUE THREAD

**Issue by oneninetyeight** [iamadamdev/bypass-paywalls-chrome#623]
While most pages on wsj.com work, some run into the paywall. The issue seems to be connected to the various subsections on the site.
Articles under https://www.wsj.com/news/business?mod=breadcrumb for example can be accessed. 
Articles under https://www.wsj.com/news/types/central-banks?mod=breadcrumb can not. Any way to work around this?
Thanks!

**Comment by iamadamdev** [comment]
Those are behind a hard paywall. No work around at the moment.

**Comment by oneninetyeight** [comment]
Got it, thanks for looking in to this as well as all your work here!
