### ISSUE TITLE
New site request: [elcomercio.pe] [gestion.pe] 

### ISSUE THREAD

**Issue by marce2209** [iamadamdev/bypass-paywalls-chrome#624]
I would be thankful if you can help with this websites from Peru:
elcomercio.pe
gestion.pe
There are same pages that need subscription

**Comment by kimkha** [comment]
Hi, main question is: Did you try the instruction here? https://github.com/iamadamdev/bypass-paywalls-chrome/blob/master/README.md#new-site-requests And did it work?

**Comment by marce2209** [comment]
Yes, I tried the instruction and didn't work. But there are some pages like this https://elcomercio.pe/economia/dia-1/ministra-munoz-queremos-incentivar-un-descuento-sobre-los-arbitrios-por-segregar-los-residuos-noticia/ , that have a paywall. I am really grateful for your time.

**Comment by iamadamdev** [comment]
That's a hard paywall.
