### ISSUE TITLE
The Hindu - Older pages don't load

### ISSUE THREAD

**Issue by axanup682** [iamadamdev/bypass-paywalls-chrome#629]
Site: The Hindu (https://www.thehindu.com)

Access to older pages through SEARCH requires a subscription (older than approx. 2.5 months) -  URLs that change to /todays-paper/ don't load

https://www.thehindu.com/todays-paper/tp-features/tp-sundaymagazine/easy-like-sunday-morning/article30717372.ece

New pages load fine - 
https://www.thehindu.com/life-and-style/food/a-taste-of-retro-china/article30974557.ece

Please check if something can be done. Thanks!

**Comment by iamadamdev** [comment]
You can always disable Javascript in uBlock Origin to get the older pages to load:
![image](https://user-images.githubusercontent.com/36013816/82127984-3cc49600-976c-11ea-929b-bbd1737c2f0c.png)
