### ISSUE TITLE
Version 1.7.0 works better with Boston Globe

### ISSUE THREAD

**Issue by paravantis** [iamadamdev/bypass-paywalls-chrome#630]
While version 1.7.0 displays Boston Globe pages without any dialog boxes, e.g. warning about the number of free articles left, version 1.7.1 has reverted to the older behavior of warning and having to click to display an entire article.

This is annoying. I am guessing you had to do this in 1.7.1 to address some issue(s). Is it possible to retain the behavior of 1.7.0?

**Comment by iamadamdev** [comment]
Boston Globe was removed for performance reasons.

**Comment by sevilla2021** [comment]
> Boston Globe was removed for performance reasons.

Too bad, it was working well before ...

**Comment by kimkha** [comment]
Could anyone find a better way to bypass it in efficient method?

**Comment by sevilla2021** [comment]
It's not working at all now for most articles.
A refresh after clearing cookies does.

**Comment by kimkha** [comment]
Wait, are you saying that if people use some cookie remover, or disable cookies of the website, then most articles work without this extension?

If that so, then is the [cookie remover](https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce) enough?

**Comment by iamadamdev** [comment]
Yes, that's partly why I removed it. You can just use Cookie Remover.

**Comment by sevilla2021** [comment]
On every single page ...?

**Comment by sevilla2021** [comment]
Worked only once on mobile.
