### ISSUE TITLE
Unable to log in to Samharris.org

### ISSUE THREAD

**Issue by Luomint** [iamadamdev/bypass-paywalls-chrome#633]
I couldn't log in to samharris.org with this extension enabled. On Samharris.org you have to click login at the very top 
![image](https://user-images.githubusercontent.com/10950598/82097447-d3586f00-96fa-11ea-9183-80e3a267745a.png)

which in turn loads this page on top of it:

![image](https://user-images.githubusercontent.com/10950598/82097273-7a88d680-96fa-11ea-93ac-cac41b69e7e0.png)

This page wouldn't load and I couldn't log in until I disabled this extension. 

Browser: Firefox 76.0.1

**Comment by iamadamdev** [comment]
What version of Bypass Paywalls?

**Comment by iamadamdev** [comment]
Uncheck "*General Paywall Bypass*"
