### ISSUE TITLE
Asia New site request: [Asia Insurance Review]

### ISSUE THREAD

**Issue by clago7** [iamadamdev/bypass-paywalls-chrome#636]
Hi Sir, would greatly appreciate it if you could help to bypass premium articles on this site, thank you!

Site url: **https://www.asiainsurancereview.com/**

Sample Article: **https://www.asiainsurancereview.com/News/View-NewsLetter-Article/id/61663/Type/AirPlus/Pandemic-shows-need-to-update-insurance-products**

**Comment by Anguria33** [comment]
Hi there, 
I really appreciate what is done here. I know Switzerland is little. However, I wanted to ask if we can have access to NZZ. Is the biggest journal here, I would really love it! The website is: 
https://www.nzz.ch/
Thanks in advance :)

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by iamadamdev** [comment]
@clago7 asiainsurancereview.com's paywall is a hard paywall.
@Anguria33 Added in latest master.
