### ISSUE TITLE
The Economist Not Working

### ISSUE THREAD

**Issue by ryanlararr** [iamadamdev/bypass-paywalls-chrome#641]
Paywall flashes on and off repeatedly on articles for seconds and stops with the paywall still up.

**Comment by iamadamdev** [comment]
Which article?
I just loaded 5+ articles no problem.

**Comment by ryanlararr** [comment]
None of the articles are working for me both in incognito and regular and with all other extensions turned off. My chrome is up to date and I’ve tried redownloading the extension in case there was an update but that didn’t work as well. The extension successfully blocks paywalls on sites like WSJ.com like normal.

Incognito mode with only bypass-paywalls as an extension
[Article link](https://www.economist.com/europe/2020/05/19/russias-covid-19-outbreak-could-be-far-worse-than-the-kremlin-admits)
![image](https://user-images.githubusercontent.com/17973877/82384660-4e24d100-99fe-11ea-925e-206adfc7bb69.png)

**Comment by kimkha** [comment]
Perfectly works for me.

<img width="1093" alt="Screen Shot 2020-05-20 at 09 29 34" src="https://user-images.githubusercontent.com/1332605/82388231-70f5ca80-9a7c-11ea-96c5-181c8f3b15a5.png">

**Comment by iamadamdev** [comment]
That article works fine for me.

You can also try disabling Javascript in uBlock Origin:
![image](https://user-images.githubusercontent.com/36013816/82392618-339c2900-99f9-11ea-9130-685c025145c5.png)
