### ISSUE TITLE
NYTimes World News

### ISSUE THREAD

**Issue by keefengws** [iamadamdev/bypass-paywalls-chrome#643]
For the NYTimes website under the "World News" section, clicking on the sub-categories i.e. Africa, Americas, Asia etc yield a blank page without showing any news articles. I appended a screenshot for reference
<img width="1262" alt="Screenshot 2020-05-19 at 12 06 31" src="https://user-images.githubusercontent.com/65583362/82283523-2f581780-99c9-11ea-9781-6e4a45bb63ed.png">

**Comment by kimkha** [comment]
<img width="1256" alt="Screen Shot 2020-05-19 at 14 54 46" src="https://user-images.githubusercontent.com/1332605/82286287-b49af680-99e0-11ea-9031-466c8a1b922f.png">

This is mine, no problem.

**Comment by iamadamdev** [comment]
Same here, no issues:
![image](https://user-images.githubusercontent.com/36013816/82392702-647c5e00-99f9-11ea-92d0-1f2e8a9daa68.png)

**Comment by keefengws** [comment]
I checked it again using both Chrome and Firefox browsers and it does work for Chrome but not for Firefox. Attached both screenshots below. Is it possible that the problem is browser specific?
<img width="1119" alt="Screenshot 2020-05-20 at 09 57 24" src="https://user-images.githubusercontent.com/65583362/82396507-a7354900-9a80-11ea-8b8c-8ae6969dbd69.png">
<img width="1142" alt="Screenshot 2020-05-20 at 09 58 13" src="https://user-images.githubusercontent.com/65583362/82396521-adc3c080-9a80-11ea-8b9e-3b35e2d24304.png">

**Comment by iamadamdev** [comment]
I can repro now. Firefox release is slightly behind Chrome latest master, it will be fixed in the next release.
You also actually might not need need Bypass Paywalls for NYT. You can use uBlock Origin and [Cookie Remover](https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/).
For now you can also uncheck NYT in options and it should load.
