### ISSUE TITLE
The times not working!

### ISSUE THREAD

**Issue by LuyangCAT** [iamadamdev/bypass-paywalls-chrome#650]
I've disabled the adblock and tampermonkey, but the article is still not working for me. The article link is [https://www.thetimes.co.uk/article/merkel-backs-500bn-recovery-fund-jv8plz2ln](url)

**Comment by kimkha** [comment]
works fine to me.

<img width="1223" alt="Screen Shot 2020-05-20 at 15 08 00" src="https://user-images.githubusercontent.com/1332605/82407134-bc739d00-9aab-11ea-9af6-775004eb1a5b.png">

Are you on the latest master?

**Comment by LuyangCAT** [comment]
> works fine to me.
> 
> <img alt="Screen Shot 2020-05-20 at 15 08 00" width="1223" src="https://user-images.githubusercontent.com/1332605/82407134-bc739d00-9aab-11ea-9af6-775004eb1a5b.png">
> 
> Are you on the latest master?

I reinstalled the extention,but the result is same as before. It works on other websites, like WSJ, but failed in The Times.

**Comment by LuyangCAT** [comment]
> works fine to me.
you need scroll to the end of this webpage, you will find that the extension is not working. I've changed 3 broswers, and got the same result.

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed?
Works fine for me too, scrolled to the bottom:
![image](https://user-images.githubusercontent.com/36013816/82479959-ed41db00-9a87-11ea-97e9-092dcdf28dcc.png)
