### ISSUE TITLE
Firefox fails: 1) Miami Herald (Confirmed) 2) Wall Street Journal - Both Work Fine in Chrome

### ISSUE THREAD

**Issue by ResQtech** [iamadamdev/bypass-paywalls-chrome#653]
CONFIRMED

Miami Herald worked in private window.  Wall Street Journal can not be confirmed (ie., fails in private window as well)
BUT extension works in Chrome using Chrome Extension no problem.

Both sites work fine in Chrome using bypass chrome extension.

Problem only with FF specific extension.

Thank you!

**Comment by iamadamdev** [comment]
What is the problem with WSJ? It still works fine for me in Chrome and FF.

Will look into the other site.

**Comment by llacb47** [comment]
WSJ works with googlebot. You can also use AMP.

**Comment by ResQtech** [comment]
Update - rebooted computer, WSJ now works in Firefox (sorry for WSJ false alarm.)

Problem still exists on Miami Herald site.

Thank you iamadamdev for this awesome extension!

@llac47 Thanks for the tips.

**Comment by iamadamdev** [comment]
Actually I've removed miamiherald in the latest version as it can be beat with a simple [Cookie Remover](https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/)
