### ISSUE TITLE
Idea: Allow user to add custom site

### ISSUE THREAD

**Issue by kimkha** [iamadamdev/bypass-paywalls-chrome#654]
Basically, this extension do two basic thing for supported sites:

1. Set referrer to google.com (all sites)
2. Remove cookie (some sites)

I think we can create an option in settings to add custom site, something like that:

Domain: `________________`
Remove cookie? `✅`

It should be easy, and I can do it. But I want to see what do you think, @iamadamdev ?

**Comment by iamadamdev** [comment]
That sounds good. But as you know it's not a one size fits all, for some sites it may work and may not. Some sites we have custom blocking, javascript manipulation, etc.
Basically for a site to be added to the official list for everyone it still needs to be submitted as a PR and manually tested.

**Comment by kimkha** [comment]
Ya, actually, I don't plan to implement all custom blockings, JS manipulations,... in this custom option. Well, I may, in future, but not this time. So I just want to rollout the referrer manipulation first, and come with cookie removing second. And the rest, we will consider when we need to.

I also think that adding an option to remove cookie is not super helpful, since anyone could install another extension (such as Cookie Remover) to do that. But referrer manipulation seems to be unique from this extension, and it should be useful with custom settings.

We may discuss more about other features, but here I want to ask your opinion: is it helpful to allow users set referrer on any website?

**Comment by iamadamdev** [comment]
> is it helpful to allow users set referrer on any website?

I don't think it is particularly useful since there are only a few sites where it should not be Google.
