### ISSUE TITLE
Interfering with Feedly.com "Error 929"

### ISSUE THREAD

**Issue by wilberfan** [iamadamdev/bypass-paywalls-chrome#656]
Browsing Feedly RSS feeds gets interrupted with an "Error 929: Authenticated request with no session" error after reading 10-15 articles.   Toggling off bypass paywall restores normal functioning.    Other users reported same issue this week via Twitter.  Incognito Mode also restores normal functioning. 

Chrome-based browsers only?   Haven't had the issue when using bp with Firefox.

**Comment by iamadamdev** [comment]
All these Twitter users are using Bypass Paywalls? Can you link me to the thread?

**Comment by llacb47** [comment]
> Can you link me to the Twitter thread?

https://twitter.com/pwnedsleeper/status/1263377475708555264

**Comment by iamadamdev** [comment]
What if you deselect all the sites in Bypass Paywalls, do you still get an error?

**Comment by iamadamdev** [comment]
I need exact repro steps to try and debug. I am logged into Feedly and added a bunch of feeds. Clicked on some articles. I am still logged in.

**Comment by iamadamdev** [comment]
What version of Bypass Paywalls are you on?

related: https://github.com/iamadamdev/bypass-paywalls-chrome/issues/652
Upgrading to latest version fixed it for this user it seems.

**Comment by wilberfan** [comment]
Typically I'll browse 10-15 articles (using keyboard shortcuts), then click on a different feed.  Often it's when selecting the different feed the error will show up.   Here's another twitter thread: 
 https://twitter.com/jonrandy/status/1262805886671613957

**Comment by wilberfan** [comment]
> What version of Bypass Paywalls are you on?
> 
> related: #652
> Upgrading to latest version fixed it for this user it seems.

I didn't realize there was a brand-new version.  I'll test it this evening.

**Comment by wilberfan** [comment]
Updating to v1.7.2 did not solve the issue for me.  (Vivaldi)

**Comment by iamadamdev** [comment]
Should be fixed in latest master.
