### ISSUE TITLE
World Politics Review

### ISSUE THREAD

**Issue by defrilitus** [iamadamdev/bypass-paywalls-chrome#658]
Confirmed to work (see below).  Sorry, I should be submitting a pull request but that's beyond my limited GitHub capabilities.

Sites.js:
  'Wired': 'wired.com',
  'World Politics Review': 'worldpoliticsreview.com',
  '*General Paywall Bypass*': 'generalpaywallbypass'

Manifest.json:
    "*://*.wired.com/*",
    "*://*.worldpoliticsreview.com/*",
    "*://*.wsj.com/*",

README.md:
[Winston-Salem Journal](https://journalnow.com)\
[World Politics Review](https://www.worldpoliticsreview.com)\
[Wired](https://www.wired.com)

**Comment by kimkha** [comment]
Pushed a PR.

**Comment by defrilitus** [comment]
Thanks.
