### ISSUE TITLE
New site request: nydailynews

### ISSUE THREAD

**Issue by mfisher224** [iamadamdev/bypass-paywalls-chrome#659]
Confirmed.

**Comment by kimkha** [comment]
Could you please give me an article with paywall? I tried some, looks like no paywall at https://www.nydailynews.com/news/national/ny-massive-fire-breaks-out-california-pier-45-20200523-m5stvkzuqvelbasbibh3okme7e-story.html

**Comment by mfisher224** [comment]
I think the paywall is triggered after an article limit.

[image: image.png]

**Comment by kimkha** [comment]
how many?

**Comment by mfisher224** [comment]
10

**Comment by kimkha** [comment]
I think you can continue if you disable cookie on that site. Does that help?

**Comment by iamadamdev** [comment]
Try using https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce
