### ISSUE TITLE
Options are not in the middle and cut-off the screen

### ISSUE THREAD

**Issue by CHEF-KOCH** [iamadamdev/bypass-paywalls-chrome#66]
Extension Version: 1.3.5
Browser: Chromium 70.0.3538.110

## Problem

The options dialogue is not centered and hard to access. 

![grh](https://user-images.githubusercontent.com/727123/49282964-c016fc80-f490-11e8-9605-fffa47b139f8.png)

### Expected

The dialog should be in the middle of the screen or not at the bottom in order to handle it better.

**Comment by iamadamdev** [comment]
Please submit a PR to fix. It works fine on all my displays.
