### ISSUE TITLE
New site request: sacbee.com

### ISSUE THREAD

**Issue by chimpo13** [iamadamdev/bypass-paywalls-chrome#660]
Confirmed

**Comment by kimkha** [comment]
Any article with paywall please? There is no paywall at https://www.sacbee.com/news/local/education/article242903156.html

**Comment by chimpo13** [comment]
That URL brings up a paywall for me.  It takes me to
https://account.sacbee.com/paywall/stop?resume=242903156

**Comment by kimkha** [comment]
Oh, look like you can bypass after clear cookies for that website. Can you try it?

**Comment by chimpo13** [comment]
Yes, that works.  That site has been paywalled for a long time but today was the 1st time I've had an issue with it.

**Comment by kimkha** [comment]
Well, in this case, I think we shouldn't implement bypass by this extension. You can easily disable cookie on that website, and continue to read without any limitation.

**Comment by chimpo13** [comment]
Ok. Thanks for your time!
