### ISSUE TITLE
Autoupdate Not Working...

### ISSUE THREAD

**Issue by pjpreilly** [iamadamdev/bypass-paywalls-chrome#666]
Stuck on version 1.7.0. Clicking update fails to produce an update on Google Chrome stable as well as cloudready chromebook.

**Comment by iamadamdev** [comment]
Was it ever working for you on Google Chrome?
I don't think auto-update works for developer mode extensions.

**Comment by pjpreilly** [comment]
> Was it ever working for you on Google Chrome?
> I don't think auto-update works for developer mode extensions.

I thought it was, I remember a meta package to fix/test autoupdate. (was that just Firefox?)

**Comment by iamadamdev** [comment]
Auto-update works for Firefox. I don't think it works for the official Google Chrome browser.
I still have update in there because it might work for other Chromium browsers (I haven't tested any though) and it was left over from when this extension was in the Chrome store.

**Comment by pjpreilly** [comment]
> Auto-update works for Firefox.

So you remember the meta update was to test just Firefox autoupdate then?

**Comment by Buckchoi** [comment]
> Was it ever working for you on Google Chrome?
> I don't think auto-update works for developer mode extensions.

It was working for me up until version 1.7.0, which was the last auto-update that I received.
Once an extension is whitelisted it can be installed from the crx file and it can auto-update.
[https://smartbear-cc.force.com/portal/KbArticleViewer?name=How-do-I-whitelist-an-extension-in-Chrome-if-Chrome-Web-Store-is-blocked-in-our-company&sp=testcomplete](url)

**Comment by Buckchoi** [comment]
It was working for me up until version 1.7.0, which was the last auto-update that I received.
Once an extension is whitelisted it can be installed from the crx file and it can auto-update.
https://smartbear-cc.force.com/portal/KbArticleViewer?name=How-do-I-whitelist-an-extension-in-Chrome-if-Chrome-Web-Store-is-blocked-in-our-company&sp=testcomplete

**Comment by Buckchoi** [comment]
> Was it ever working for you on Google Chrome?
> I don't think auto-update works for developer mode extensions.

It was working for me up until version 1.7.0, which was the last auto-update that I received.
Once an extension is whitelisted it can be installed from the crx file and it can auto-update.
https://smartbear-cc.force.com/portal/KbArticleViewer?name=How-do-I-whitelist-an-extension-in-Chrome-if-Chrome-Web-Store-is-blocked-in-our-company&sp=testcomplete

**Comment by iamadamdev** [comment]
Can you try to update now? I restored the previous location of the updates file.

**Comment by pjpreilly** [comment]
Bingo!!!!! Works NOW!!!!!

**Comment by iamadamdev** [comment]
Awesome.

**Comment by Buckchoi** [comment]
Yes, it is working now, thank you.

**Comment by pjpreilly** [comment]
Developer:    "It breaks when I do that!"
Users:           "..... Don't do THAT!!"
