### ISSUE TITLE
Some articles in The Spectator are no longer accessible

### ISSUE THREAD

**Issue by defrilitus** [iamadamdev/bypass-paywalls-chrome#670]
Some articles published on https://www.spectator.co.uk are no longer accessible, including all the articles on [this page](https://www.spectator.co.uk/writer/rod-liddle) for example. This is quite recent; any hope of unblocking them? Thanks in advance.

**Comment by iamadamdev** [comment]
Looks like those are behind a hard paywall.

**Comment by defrilitus** [comment]
I figured that, but I thought that I'd run it past you, just in case. Thanks for checking.

**Comment by llacb47** [comment]
> Looks like those are behind a hard paywall.

Please don't spread misinformation. You can read the articles simply by disabling javascript.

**Comment by iamadamdev** [comment]
I'm not trying to spread misinformation. I disabled Javascript on the site and still couldn't read the article, therefore assumed it was behind a hard paywall.

**Comment by sevilla2021** [comment]
> > Looks like those are behind a hard paywall.
> 
> Please don't spread misinformation. You can read the articles simply by adding these filters to ublock origin (but this breaks images). Alternatively, you can even view source and read the article -- therefore, not a hard paywall.
> 
> ```
> spectator.co.uk##+js(aopr, JSON.parse)
> spectator.co.uk##.HardPayWallContainer-module__overlay
> ```

Only first paragraph is visible with your ublock 'fix'.

**Comment by defrilitus** [comment]
In any case, I've figured out that all the Spectator articles mentioned in my original post are totally accessible with Outline (including images)

**Comment by llacb47** [comment]
> > > Looks like those are behind a hard paywall.
> > 
> > 
> > Please don't spread misinformation. You can read the articles simply by adding these filters to ublock origin (but this breaks images). Alternatively, you can even view source and read the article -- therefore, not a hard paywall.
> > ```
> > spectator.co.uk##+js(aopr, JSON.parse)
> > spectator.co.uk##.HardPayWallContainer-module__overlay
> > ```
> 
> Only first paragraph is visible with your ublock 'fix'.

I can see full article.

![image](https://user-images.githubusercontent.com/16567977/82936317-66e03a00-9f5c-11ea-9d2d-88744a2744bf.png)

Worth noting that my fix is quite bad. Better way to read the article is using AMP.
Add this to your filters: `||tinypass.com^$3p`
And just add `/amp` to the end of the URL. 
For example: `https://www.spectator.co.uk/article/why-schools-should-stay-shut/amp`

**Comment by sevilla2021** [comment]
Still ublock-fix sometimes blanks out page (for me), but amp works fine.
Outline has no images (obviously in reader mode).

**Comment by defrilitus** [comment]
Apologies @sevilla2021, you're right about images on the Outline version.
But amp works perfectly, @llacb47, even without adding ||tinypass.com^$3p to my filters.
@iamadamdev, any possibility of integrating this fix into the extension? Just asking ;-)
Still learning, so thanks to all for your input. Much appreciated.

**Comment by iamadamdev** [comment]
Fixed in latest master.
