### ISSUE TITLE
TheInformation.com

### ISSUE THREAD

**Issue by kimjiwongit** [iamadamdev/bypass-paywalls-chrome#673]
https://www.theinformation.com/articles/bytedances-big-ambitions

The site requires yearly subscription to view articles.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by JeffreyYun** [comment]
The first article you access could be read if you enter a valid email.
Using the link-from-Google technique does not work by itself.

Does this mean the articles are behind a hard paywall?

**Comment by kimjiwongit** [comment]
@JeffreyYun What is a link-from-Google technique? Can you please link a article explaining the technique or maybe explain it here : )

**Comment by JeffreyYun** [comment]
Step 6 of https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by iamadamdev** [comment]
Seems to be behind a hard paywall (you can try disabling JS to see that).
