### ISSUE TITLE
New site request: [History Extra]

### ISSUE THREAD

**Issue by levanrami** [iamadamdev/bypass-paywalls-chrome#674]
Please, add History Extra [https://www.historyextra.com/]

**Comment by kimkha** [comment]
any paywalled article?

**Comment by iamadamdev** [comment]
https://www.historyextra.com/period/victorian/bethlem-royal-hospital-history-why-called-bedlam-lunatic-asylum/

**Comment by iamadamdev** [comment]
Added in latest master.
