### ISSUE TITLE
demorgen.be no longer works

### ISSUE THREAD

**Issue by bucovaina** [iamadamdev/bypass-paywalls-chrome#676]
Hi, some articles are behind a paywall on demorgen.be (red star) since this week, version 1.7.2 no longer seems to work. I also tried searching the URL in google in a new private window and that also no longer works. Not sure if it's still fixable ... .

**Comment by morrogenduath** [comment]
I can confirm demorgen.be no longer works.

**Comment by iamadamdev** [comment]
Fixed in latest master.

**Comment by bucovaina** [comment]
You're officially a star! :)
