### ISSUE TITLE
Doesn't work on WSJ anymore?

### ISSUE THREAD

**Issue by KWTSOFT** [iamadamdev/bypass-paywalls-chrome#68]
It doesn't seem to work anymore, even after I removed the cookies from WSJ. Is anyone else having the same problem?

**Comment by iamadamdev** [comment]
Should still work, try manually removing all wsj cookies from Chrome, reinstall plugin and make sure wsj is selected, then hit save.

**Comment by 420pitts** [comment]
> Should still work, try manually removing all wsj cookies from Chrome, reinstall plugin and make sure wsj is selected, then hit save.

Tried this but it's not working for me.

**Comment by 420pitts** [comment]
Actually it seems to be certain WSJ stories. Everything else works fine for some reason.

Example where it doesn't work: https://www.wsj.com/articles/for-companies-it-can-be-hard-to-think-long-term-1543846491

**Comment by iamadamdev** [comment]
Weird, even google referral in incognito mode doesn't work for that article. Not much I can do here.
