### ISSUE TITLE
New site request: [https://www.campaignlive.co.uk/]

### ISSUE THREAD

**Issue by TahirSI** [iamadamdev/bypass-paywalls-chrome#682]
Confirmed

**Comment by kimkha** [comment]
I think you just need to remove cookie, then everything is good. Such as https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce or https://chrome.google.com/webstore/detail/cookie-autodelete/fhcgjolkccmbidfldomjliifgaodjagh

**Comment by iamadamdev** [comment]
Try custom sites in the latest master.
