### ISSUE TITLE
New site request: Bloomberg Law

### ISSUE THREAD

**Issue by Greigh** [iamadamdev/bypass-paywalls-chrome#683]
Confirmed. 
https://news.bloomberglaw.com/tech-and-telecom-law/apple-escapes-trade-secrets-claims-over-startup-employee-hires 

Bloomberg Law.

**Comment by kimkha** [comment]
The link you gave has no paywall, doesn't it? Seems like no paywalled article to me.

**Comment by Greigh** [comment]
Hmm strange it didn't a few minutes ago when I went to Private/Incognito. That's my fault.

**Comment by annorax** [comment]
There is  paywall there after all. Example:

https://news.bloomberglaw.com/bankruptcy-law/tect-aerospaces-31-million-bankruptcy-sale-of-facility-okd

Can you please reopen?

**Comment by kimkha** [comment]
Okay, can you follow the step here to see if it works? https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
