### ISSUE TITLE
demorgen.be no longer working

### ISSUE THREAD

**Issue by ilnumerotre** [iamadamdev/bypass-paywalls-chrome#685]
Hi,
Since a few days, the site demorgen.be does no longer seem to be working. I have tried
- Firefox;
- Chrome;
- with or without *General Paywall Bypass* selected;
- switching uBlock Origin off, and;
- removing site related cookies.
None have been successful. Thanks for having a look!

**Comment by iamadamdev** [comment]
Try latest master, I pushed up a fix yesterday.

**Comment by ilnumerotre** [comment]
Thanks Adam! Works on Chrome! Not on Firefox though, but possibly because it is not packaged up yet as extension? (It says 1.7.2 in the Firefox extension).

**Comment by iamadamdev** [comment]
Will be fixed in Firefox in the next release.

**Comment by ilnumerotre** [comment]
Thanks Adam!
