### ISSUE TITLE
Bloomberg.com not working

### ISSUE THREAD

**Issue by Montoyosvg** [iamadamdev/bypass-paywalls-chrome#688]
Just logged in for the afternoon to read some articles and got blocked with paywall, is this a known issue?

**Comment by iamadamdev** [comment]
You aren't supposed to login to Bloomberg to read articles. This extension will log you out.

**Comment by Montoyosvg** [comment]
I apologize about my choice of words, I mean't "log in" as into my laptop, then navigating to the site NOT being signed in. Although now for some reason I can move around without the paywall in my face, but I am still presented with a message at the bottom stating this is my last free article for every article.

**Comment by Montoyosvg** [comment]
Although I can just delete the elements from the webpage in the console, so its no big deal.

**Comment by iamadamdev** [comment]
Sounds good. That is expected behavior for now.
