### ISSUE TITLE
The economist menu not working

### ISSUE THREAD

**Issue by Lisa11122** [iamadamdev/bypass-paywalls-chrome#690]
Some websites are working , such as The times. But The economist and The New York Times are not working. I'm using Firefox.  I've updated the Bypass Paywalls (v1.7.3).
I've tried so many ways, but.....
I'm eager for your help.
Thank you very much!

**Comment by iamadamdev** [comment]
Still works for me. What version are you on?

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed?

**Comment by HEPBO3AH** [comment]
The Economist: Menu navigation not working
I have uBlock Origin but it is disabled on the website. The Menu starts working only after `bypass-paywalls-chrome` is disabled

**Comment by HEPBO3AH** [comment]
If it helps, the toggle for specific website (The Economist in this case) will not make the Menu work. I have to disable the entire extension for it to regain functionality.

**Comment by iamadamdev** [comment]
For now you can uncheck The Economist and *General Paywall Bypass* at the bottom to get the menu working.

**Comment by iamadamdev** [comment]
Fixed in latest master.
