### ISSUE TITLE
New site request: [Jane's Defence Weekly]

### ISSUE THREAD

**Issue by ghost** [iamadamdev/bypass-paywalls-chrome#691]
Could you please add 'Jane's Defence Weekly' [https://www.janes.com/defence-news].

Example article: [https://www.janes.com/defence-news/news-detail/5165b4a5-5b27-4ad4-853c-9d2549ff8021]

**Comment by kimkha** [comment]
Could you confirm after these steps? https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
