### ISSUE TITLE
New site request: Cincinnati Enquirer

### ISSUE THREAD

**Issue by bokbokwhoosh** [iamadamdev/bypass-paywalls-chrome#692]
Could you please add The Cincinnati Enquirer [https://www.cincinnati.com/]
Example article: [https://www.cincinnati.com/story/news/2020/06/02/george-floydprotestersmillennials/5313474002/]

Thank you!

Confirmed.

**Comment by kimkha** [comment]
Can you check that article with uBlock Origin installed? Let me know if it doesn't bypass.

**Comment by bokbokwhoosh** [comment]
> 
> 
> Can you check that article with uBlock Origin installed? Let me know if it doesn't bypass.

Hey, already did - I have the Annoyances filter turned on, and the subscribe/limit message disappears, but after a certain number of articles, it asks me to subscribe (clearing cookies resets it).

**Comment by kimkha** [comment]
Okay, I just asked to confirm. Let's see if @iamadamdev wants to add this site to his extension.

**Comment by iamadamdev** [comment]
As you mentioned, a simple cookie clear will fix it.
https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce
