### ISSUE TITLE
Please fix The Wall Street Journal 

### ISSUE THREAD

**Issue by I-Halder** [iamadamdev/bypass-paywalls-chrome#695]
Dear Mr. Genius,

I installed the extension offered by you. It is working very nicely in some of the websites mentioned, thank you for the excellent work.

I tried opening **The Wall Street Journal** today, its showing an error saying "Internal Server Error" (in an otherwise blank page) both in Chrome and in Firefox. Please fix it.

Thank you again.

**Comment by rpodric** [comment]
That's very strange. Check for a conflict with another extension etc. I've never seen it happen.

**Comment by iamadamdev** [comment]
Still works fine for me, must be some other extension or setting you have.

**Comment by chrisly** [comment]
I did get an error when going to this url:

https://www.wsj.com/articles/may-jobs-report-coronavirus-2020-11591310177?mod=rsswn

Screenshot: 

![image](https://user-images.githubusercontent.com/3066225/83934109-367a7600-a77c-11ea-8643-5f20b4c2db6d.png)
