### ISSUE TITLE
New site request: [simplywall.st]

### ISSUE THREAD

**Issue by AleRi8** [iamadamdev/bypass-paywalls-chrome#702]
please add this site to the list it works on scroll function which when you scroll down it will add the code just above </ head> section ty

<style type="text/css" id="blur-css">
			#root {
				filter: url(#blur-filter);
				filter: blur(6px);
			}
		</style>

[](https://simplywall.st/stocks/fi/energy/hel-neste/neste-oyj-shares)

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
