### ISSUE TITLE
New site request: [https://www.businesspost.ie/]

### ISSUE THREAD

**Issue by GettingThere123** [iamadamdev/bypass-paywalls-chrome#703]
Please add the the Sunday Business Post. Example of an article "https://www.businesspost.ie/media-marketing/inms-paywall-created-by-firm-owned-by-financier-desmond-4789e4e0"

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests

**Comment by GettingThere123** [comment]
I thought I tried all the steps. Is it not possible to get this site to work?
