### ISSUE TITLE
New site request: [https://briefing.economist.com]

### ISSUE THREAD

**Issue by SheenkhunWong** [iamadamdev/bypass-paywalls-chrome#708]
New site request: [https://briefing.economist.com] 

It is the full edition of The Economist Morning Briefing.

As mentioned by the title, the site [https://briefing.economist.com] cannot be accessed. But it is an audible site to hear the insightful daily world news from _the Economist_. So, please add it to the bypass paywalls list. Thank you in advance.

**Comment by iamadamdev** [comment]
That is premium content, you need a login to read that site. If you just want the site to load and use your own login, you can uncheck The Economist and *General Paywall Bypass*.
