### ISSUE TITLE
Submit extension to addons.mozilla.org (AMO) (firefox extension store)

### ISSUE THREAD

**Issue by wyattscarpenter** [iamadamdev/bypass-paywalls-chrome#710]
The AMO doesn't seem to have any policy against what this addon does (I am not a lawyer). In fact, https://addons.mozilla.org/en-US/firefox/search/?q=paywall reveals quite a few addons that attempt the same thing. So, this is something you may want to consider, for the convenience of firefox users.

**Comment by iamadamdev** [comment]
My extension used to be there (along with Chrome web store), Mozilla banned it claiming it violated one of their policies.
