### ISSUE TITLE
New site request: [https://qt.com.au]

### ISSUE THREAD

**Issue by Jalit6** [iamadamdev/bypass-paywalls-chrome#712]
The Queensland Times
Seems to be using a similar paywall to The Courier Mail.

**Comment by kimkha** [comment]
No, it's not. I just tried the 5th step of https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests, it didn't work. So, next time, please do exactly the guideline.

**Comment by Jalit6** [comment]
> No, it's not. I just tried the 5th step of https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests, it didn't work. So, next time, please do exactly the guideline.

You are right, the 5th step does not work. But that method does not work for the Courier Mail either and yet it is still bypassed by this extension. You can tell it is owned by the Courier Mail by the styling and by looking at the Terms and Conditions on the paywall.

**Comment by kimkha** [comment]
oh, interesting. I don't know how the courier mail did. Let ask the extension's owner @iamadamdev

**Comment by Jalit6** [comment]
I find this in the background.js source code which may help, could this apply to qt.com.au?

// Override User-Agent with Googlebot
  'couriermail.com.au',
 
// Block external scripts
'thecourier.com.au': /.+cdn-au\.piano\.io\/api\/tinypass.+\.js/

**Comment by iamadamdev** [comment]
Yes I tried it, did you? The same bypass wasn't working.

**Comment by Jalit6** [comment]
test
