### ISSUE TITLE
Guardian.com is not working

### ISSUE THREAD

**Issue by anishmittal2020** [iamadamdev/bypass-paywalls-chrome#713]
Example:

[The 20 best Spanish recipes: part 4](https://www.theguardian.com/lifeandstyle/2015/jul/02/20-best-spanish-recipes-part-4-ofm-stew-gazpacho-ice-cream)

**Comment by kimkha** [comment]
What do you mean by not working? The Guardian is always free, if you open an account. And if you already logged in but still unable to read the full article, just contact them in case there is a problem somewhere in their website.

**Comment by iamadamdev** [comment]
Works fine for me.
