### ISSUE TITLE
New site request: Forbes

### ISSUE THREAD

**Issue by satp42** [iamadamdev/bypass-paywalls-chrome#715]
Confirmed

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed?
Where are you seeing a paywall?

**Comment by satp42** [comment]
I do have uBlock installed. The paywall is when you have an ad blocker on. Does this not support that kind of paywall? Based on the code I saw, I thought I saw no possibility of bypassing this type of paywall, but I wanted to give it a try.

**Comment by iamadamdev** [comment]
I'm not seeing any paywall with uBlock Origin.

**Comment by llacb47** [comment]
There should be no anti-adblock with uBlock Origin. If you still are seeing it after updating your filters report an issue here: https://github.com/uBlockOrigin/uAssets
