### ISSUE TITLE
Seattle Times Stopped Working

### ISSUE THREAD

**Issue by buchananwp** [iamadamdev/bypass-paywalls-chrome#72]
Thanks for making this! I've installed ublock origin, and the latest extension and was testing out various sites, but found ST's paywall: 

https://www.seattletimes.com/subscribe/signup-offers/?pw=redirect&subsource=paywall&return=https://www.seattletimes.com/business/real-estate/seattle-area-home-prices-drop-again-with-6-month-decline-among-largest-ever/

**Comment by iamadamdev** [comment]
Fixed in v1.3.7

**Comment by buchananwp** [comment]
Thanks @iamadamdev
