### ISSUE TITLE
WSJ paywall bug?

### ISSUE THREAD

**Issue by amiralizb** [iamadamdev/bypass-paywalls-chrome#720]
not sure why but this page still gets the paywall.

https://www.wsj.com/articles/judge-to-rule-on-hertzs-controversial-stock-sale-in-bankruptcy-11591980720

**Comment by iamadamdev** [comment]
Usually only articles from the front page (and above the fold) work.

**Comment by iamadamdev** [comment]
Not all articles will work using googlebot.

**Comment by iamadamdev** [comment]
Try latest master for AMP redirect.
