### ISSUE TITLE
New site request: https://www.independent.ie/

### ISSUE THREAD

**Issue by nigeymc** [iamadamdev/bypass-paywalls-chrome#728]
Confirmed

**Comment by wigguslong** [comment]
Indepedent.ie operates a paywall that cannot be bypassed.

**Comment by llacb47** [comment]
Wrong, use AMP version.

Take article URL: `https://www.independent.ie/business/farming/news/politics/the-big-farming-questions-that-remain-unanswered-in-government-deal-39288196.html`

Replace `www` with `amp`.

Add these to your uBlock Origin filters:
```
amp.independent.ie##amp-list[items="prices"]
amp.independent.ie##[amp-access^="NOT"]
amp.independent.ie##[amp-access="subscriber"]:style(display:block!important)
amp.independent.ie##amp-iframe[src*="&adUnitURL"]
amp.independent.ie##amp-ad
```
