### ISSUE TITLE
lemonde.fr bypass paywall doesn't work

### ISSUE THREAD

**Issue by Fahlstrom** [iamadamdev/bypass-paywalls-chrome#729]
Hello,

Since last update, the puglin (I'm using chrome) doesn't work anymore on lemonde.fr

Would be neat if you could take a look at it whenever it is possible !

Best regards, F.

**Comment by iamadamdev** [comment]
That was not a supported site to begin with...

**Comment by Fahlstrom** [comment]
Oddly, it used to be. I could bypass paywalls on this website by using this plugin.
![lemonde](https://user-images.githubusercontent.com/66974705/85778713-27576a00-b723-11ea-9065-ca5ea9c37674.JPG)

**Comment by iamadamdev** [comment]
It was removed because it doesn't work anymore.. they have a hard paywall up now. I suggest paying for a subscription for it.
