### ISSUE TITLE
New site request: tricycle.org

### ISSUE THREAD

**Issue by siksaw33** [iamadamdev/bypass-paywalls-chrome#730]
Confirmed

**Comment by kimkha** [comment]
You just need to remove cookies to unlock paywall, https://github.com/iamadamdev/bypass-paywalls-chrome#sites-with-limited-number-of-free-articles

**Comment by iamadamdev** [comment]
https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce
