### ISSUE TITLE
New site request: [valor.globo.com]

### ISSUE THREAD

**Issue by LF76** [iamadamdev/bypass-paywalls-chrome#737]
Biggest financial site in Brazil.

I did the following test:

Sample article (locked) https://valor.globo.com/empresas/noticia/2020/06/16/cinemark-e-cinepolis-vao-a-justica-para-reduzir-gastos.ghtml

Searching in Google and clicking on it: Still locked as above:

But, by clicking in the cached article, on the Google search above, it opens without any restriction: https://webcache.googleusercontent.com/search?q=cache:PiCab9zqLNIJ:https://valor.globo.com/empresas/noticia/2020/06/16/cinemark-e-cinepolis-vao-a-justica-para-reduzir-gastos.ghtml+&cd=1

**Comment by iamadamdev** [comment]
Doesn't work for that article.
