### ISSUE TITLE
New site request: [timesmachine.nytimes.com]

### ISSUE THREAD

**Issue by ahmed4119** [iamadamdev/bypass-paywalls-chrome#740]
I tried googling the title but It's not working.
https://www.nytimes.com/1955/02/04/archives/text-of-peiping-note-to-un.html 
the above link is the leading post to the timesmachine website which will lead you to:
https://timesmachine.nytimes.com/timesmachine/1955/02/04/85675783.html

I don't really have high hopes for this one but I just wanted to try :D 
Thanks ^_^

**Comment by iamadamdev** [comment]
You will need to pay and subscribe for that.

**Comment by llacb47** [comment]
Not possible. Your public library is your best bet. 

That's how I got your article: https://gofile.io/d/sb52X4
