### ISSUE TITLE
New site request: TechCrunch Extra Crunch

### ISSUE THREAD

**Issue by ygnawk** [iamadamdev/bypass-paywalls-chrome#747]

**Comment by llacb47** [comment]
Confirmed? What? How did you bypass it?

**Comment by ygnawk** [comment]
Was not able to bypass. Deleted my message.

**Comment by llacb47** [comment]
`If it loads without a paywall you can submit a request and replace the entire template text with the word "Confirmed". Otherwise please do not submit an issue as this extension cannot bypass it either.`
