### ISSUE TITLE
barrons.com stopped working

### ISSUE THREAD

**Issue by VernonStow** [iamadamdev/bypass-paywalls-chrome#748]
Using latest version 1.7.3, uBlock Origin 1.27.10, Firefox 77.0.1
Almost all Barrons articles now require subscription or sign up.
Unchecking general paywall rules and refreshing page multiple times did not help.
Example of problem article: hxxps://www.barrons.com/articles/why-the-widening-wealth-gap-is-bad-news-for-everyone-51592617966?mod=hp_HERO
![Why the Widening Wealth Gap Is Bad News for Everyone - Barrons 20200620](https://user-images.githubusercontent.com/15573459/85211512-f4663e00-b2fe-11ea-884f-ec87acb9ab01.png)

ETA: I can't reply, but the user script from @llacb47 solves the problem. Thanks.

**Comment by llacb47** [comment]
Try my userscript: https://gist.github.com/llacb47/b3f233f59871e741dac3dd6d2c9125d3

**Comment by iamadamdev** [comment]
@llacb47 Do you want to submit a PR for that so everyone can use it?

**Comment by llacb47** [comment]
Well it doesn't work for WSJ Graphics articles, and the mobile design is objectively worse on desktop.

**Comment by iamadamdev** [comment]
Added amp redirect in latest master.

**Comment by MalikDeann** [comment]
> Try my userscript: https://gist.github.com/llacb47/b3f233f59871e741dac3dd6d2c9125d3
> 
> if this fix works then it can be added.

How can I use it? Can you help me?
