### ISSUE TITLE
New site request: [qt.com.au]

### ISSUE THREAD

**Issue by Jalit6** [iamadamdev/bypass-paywalls-chrome#749]
This paywall can be bypassed by adding the following value to the cookie for qt.com.au
**subscribed = true**
I am not very familiar with JS. If someone could add a section to background.js to add values into cookies that would be fantastic.

**Comment by Scrotastic** [comment]
You can bypass the QT paywall by setting the User Agent to Googlebot.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
