### ISSUE TITLE
MIT Tech Review Not Working

### ISSUE THREAD

**Issue by buchananwp** [iamadamdev/bypass-paywalls-chrome#75]
Same as previous issues.

Happy to contribute if i'm given some guidance

**Comment by iamadamdev** [comment]
I loaded 10+ articles just fine. Which article specifically isn't working for you? I want to see if it loads fine on my setup.

**Comment by buchananwp** [comment]
Upgraded to 1.3.7. and it appears to have fixed the issue. Thanks!
