### ISSUE TITLE
Keeps disappearing from Chrome

### ISSUE THREAD

**Issue by slbrown85** [iamadamdev/bypass-paywalls-chrome#752]
I don't know much about how any of this works, but for some reason the extension keeps disappearing from chrome. I have the unzipped folder saved, so I can easily add it again, but I don't know why it keeps vanishing.

**Comment by iamadamdev** [comment]
Do you get a warning about running extensions in developer mode?

**Comment by slbrown85** [comment]
No I haven't seen one. I've kept it in developer mode. When I hover over the red icon it says unpacked extension. 
<img width="1036" alt="Screen Shot 2020-06-23 at 5 36 24 PM" src="https://user-images.githubusercontent.com/64947617/85466626-3352f880-b578-11ea-8f13-2c55c05f5018.png">

**Comment by iamadamdev** [comment]
Windows or mac?

**Comment by slbrown85** [comment]
mac

**Comment by slbrown85** [comment]
Thank you to whomever made this, btw. Very useful for me to get a variety of sources for my writing.

**Comment by iamadamdev** [comment]
Not sure what's happening. On mac the only known issue is the sites get automatically unselected after some period of time.
I keep the unzipped extension folder in Documents. Closed Chrome with Option+Q, reopened it, the extension is still there.

**Comment by slbrown85** [comment]
Ok thanks. It works well for a week or so, but then I notice the little icon is no longer there. But I will try what you said.
