### ISSUE TITLE
"URL constructor" errors in Firefox console

### ISSUE THREAD

**Issue by gitdine** [iamadamdev/bypass-paywalls-chrome#754]
Ever since the codebase was merged this extension has been throwing "URL constructor" errors in the Firefox console whenever "_about:_" tabs are opened (e.g. _about:newtab_, _about:support_ etc). 

For example this occurs every time you open a new tab, which results in the console being spammed. It's annoying because it drowns out important messages.

![image](https://user-images.githubusercontent.com/55441362/85504012-9d9c8500-b5da-11ea-83ef-738ab3f270c2.png)

**Comment by iamadamdev** [comment]
Can you submit a PR for a fix?
