### ISSUE TITLE
Washington Post articles show a gray "veil" at the top of the page when the user scrolls down

### ISSUE THREAD

**Issue by odysseus90210** [iamadamdev/bypass-paywalls-chrome#756]
In the Brave browser, I'm seeing a gray "veil" at the top of every page when I scroll down.

Can anything be done?
![Screenshot 2020-06-24 16 54 50](https://user-images.githubusercontent.com/43247311/85631740-b5f0bc00-b63b-11ea-92d3-997d715dcb02.png)

**Comment by llacb47** [comment]
If you have uBlock Origin, you shouldn't see this. Add this:

`washingtonpost.com###leaderboard-wrapper`

**Comment by odysseus90210** [comment]
Do I need uBlock Origin in addition to Brave's built-in defenses? I'm basically finding that Bypass Paywalls doesn't work very often on washingtonpost.com.

**Comment by llacb47** [comment]
It can't hurt.

**Comment by odysseus90210** [comment]
Is it normal to see this at the bottom of the WP pages?
![Screenshot 2020-06-24 17 34 00](https://user-images.githubusercontent.com/43247311/85634451-0cacc480-b641-11ea-94aa-cf6be2688bb8.png)

**Comment by odysseus90210** [comment]
Where do I add this? in uBlock Origin?

Best,
Marc

**Comment by llacb47** [comment]
Yes, my filters tab
