### ISSUE TITLE
medium.com not working

### ISSUE THREAD

**Issue by nairahul** [iamadamdev/bypass-paywalls-chrome#757]
Medium doesn't loads up with the paywall blocker enabled. I have to uncheck Medium and reload it to use it

**Comment by iamadamdev** [comment]
Which article?

**Comment by nairahul** [comment]
All articles. Not able to login with my mail until I disable it.

**Comment by iamadamdev** [comment]
"Selected sites will have their cookies cleared and referer set to Google. You should uncheck sites you are logged in to otherwise you will be logged out on every visit."

**Comment by llacb47** [comment]
RTFM
