### ISSUE TITLE
Indian News Sites behind Paywall; ET Prime, Livemint,Moneycontrol.

### ISSUE THREAD

**Issue by RipperCode9** [iamadamdev/bypass-paywalls-chrome#758]
Can you please help bypass a couple of Indian News websites if possible?
Listing them down here: 1
1) https://www.livemint.com/
2) https://prime.economictimes.indiatimes.com/
3) https://www.moneycontrol.com/

Also what all Indian Websites does the script bypass, if not please add as we have a lot of them.

Big fan of your work, best wishes :)

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
