### ISSUE TITLE
New site request: www.theguardian.com

### ISSUE THREAD

**Issue by willlowther** [iamadamdev/bypass-paywalls-chrome#759]
Confirmed

Site requires an account to browse, which should be bypassable.

EDIT: I don't have permissions to reply to your comment below, but yes it works fine adding to a custom site in Chrome. I use Firefox therefore can't just add it there for my main browsing.

**Comment by iamadamdev** [comment]
Did you add it to custom sites and it works?

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed? I just loaded 10+ articles without seeing any paywall.
Which article are you seeing a paywall on?
