### ISSUE TITLE
NZ Herald

### ISSUE THREAD

**Issue by possomcohen** [iamadamdev/bypass-paywalls-chrome#762]
Greetings. The Java script that you recommended about a year ago... stopped functioning on the NZ Herald site. Any idea if there is a bypass for NZ Herald now? Thank you very much.

https://www.nzherald.co.nz/nz-government/news/article.cfm?c_id=144&objectid=12342828

**Comment by iamadamdev** [comment]
Are you using latest master and have uBlock Origin installed?
That article loaded fine for me:
![image](https://user-images.githubusercontent.com/36013816/85960145-222e3100-b956-11ea-83a4-803f6346ddf1.png)

**Comment by possomcohen** [comment]
Hello Adam,

Fantastic. I installed the new version... and voila. Displayed perfectly.

Thank you very much.
