### ISSUE TITLE
New site request: [Singaproe News Media]

### ISSUE THREAD

**Issue by kchio0331** [iamadamdev/bypass-paywalls-chrome#765]
Hello,

Will you be able to make the following news media paywall free?

1) Singapore's Strait Times. This article cannot be read https://www.straitstimes.com/asia/east-asia/taiwans-refuge-offer-to-hong-kong-residents-measured-mass-exodus-unlikely
2) Singapore's Business Times. This article cannot be read https://www.businesstimes.com.sg/opinion/are-companies-more-productive-in-a-pandemic
3) Singapore's Lianhe Zhaobao. This article cannot be read https://www.zaobao.com.sg/zopinions/views/story20200629-1064873
4) Christian Science Monitor at https://www.csmonitor.com/

Thank you.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
