### ISSUE TITLE
Financial Times and World Politics Review stop working

### ISSUE THREAD

**Issue by yichen0084** [iamadamdev/bypass-paywalls-chrome#767]

**Comment by yichen0084** [comment]
It works on Firefox but not on Chrome though.

**Comment by iamadamdev** [comment]
Which articles? Are you on latest master and do you have uBlock Origin installed?
Both still work fine for me.

**Comment by yichen0084** [comment]
Hey,

Just realized bypasspaywall works poorly side-by-side with Adguard. I can
access  those articles freely after disabled it.Cheers.
