### ISSUE TITLE
Medium the Atlantic

### ISSUE THREAD

**Issue by kg27r** [iamadamdev/bypass-paywalls-chrome#768]
I almost always have two free stories left this month ;). Here is a link I am having trouble with on Android phone in Firefox. Tried with and without JavaScript via ublock origin. Issue applies to all the Atlantic articles I tried.
https://medium.com/the-atlantic/the-voting-disaster-ahead-a415b893f4a2
Thank you. I love bypass.
PS A page to find links to Medium for testing
https://toppubs.smedian.com
Off topic: Do you have a how to use on iPhone and Mac guide?

**Comment by iamadamdev** [comment]
No fix at the moment, I would suggest just reading it at the source: https://www.theatlantic.com/politics/archive/2020/06/voter-suppression-novembers-looming-election-crisis/613408/

iOS doesn't allow Chrome and Firefox to use non-apple-approved extensions.
