### ISSUE TITLE
Bloomberg mulfunction

### ISSUE THREAD

**Issue by lishuhang** [iamadamdev/bypass-paywalls-chrome#770]
![](https://lishuhang.me/img/2020/07/20200703115851.png)

Indefinite loop of the page above appeared when entering every single Bloomberg.com article. Page returned to normal after disable the extension.

URL is like 

https://www.bloomberg.com/tosv2.html?vid=&uuid=279aeeb0-bce1-11ea-809f-071e4f55014c&url=L25ld3MvYXJ0aWNsZXMvMjAyMC0wNi0zMC9pbmRpYS1zLWFwcC1iYW4tdGhyZWF0ZW5zLWNoaW5hLXMtcmlzZS1hcy1hLWdsb2JhbC10ZWNoLXBvd2Vy

**Comment by iamadamdev** [comment]
https://www.bloomberg.com/news/articles/2020-07-02/boeing-quietly-pulls-plug-on-the-747-closing-era-of-jumbo-jets?srnd=premium loads fine for me.
