### ISSUE TITLE
New release/update?

### ISSUE THREAD

**Issue by bob-kiefer** [iamadamdev/bypass-paywalls-chrome#773]
Do we have to build our own unsigned release?
Not everyone is using the latest Chrome-master in developer mode.

**Comment by iamadamdev** [comment]
You can use the Firefox version, or see https://github.com/iamadamdev/bypass-paywalls-chrome/issues/772

**Comment by bob-kiefer** [comment]
Thanks for the signed Firefox build (xpi).
