### ISSUE TITLE
nzz.ch stopped working

### ISSUE THREAD

**Issue by wcz-txp** [iamadamdev/bypass-paywalls-chrome#774]
Hello, 
two weeks or so ago the bypassing stopped working. Reloading the site or other workarounds didn't help.
Two fresh examples:
https://www.nzz.ch/wirtschaft/swiss-die-lufthansa-laesst-mit-der-hilfe-vorerst-auf-sich-warten-ld.1565146
https://www.nzz.ch/international/brasilien-coronavirus-bolsonaro-ist-infiziert-ld.1565231

Think, that they changed something in awareness of the existence of this plugin.

**Comment by iamadamdev** [comment]
Fixed in latest master
