### ISSUE TITLE
Site Not Working: [The Hindu]

### ISSUE THREAD

**Issue by louisnow** [iamadamdev/bypass-paywalls-chrome#779]
https://www.thehindu.com/todays-paper/tp-features/tp-literaryreview/fallen-tharavads/article28499015.ece

Is completely replaced behind paywall.

https://www.thehindu.com/todays-paper/tp-international/china-censors-internet-in-hong-kong/article32017475.ece

Partially replaced behind paywall.

Both pages load if I disable Javascript execution

Edit: I noticed that this is not a new site request, but the site stopped working. I changed the title but I can't change the label after I've created the issue

**Comment by iamadamdev** [comment]
For now just disable JS in uBlock Origin.

**Comment by iamadamdev** [comment]
Fixed in latest master.

**Comment by ujjwal123123** [comment]
It appears they are using variable `isNonSubcribed` (sic) to decide if user is a subscriber or not. Using uBlock Origin to set this to `false` disables all the paywalls. This is the rule I used: `thehindu.com##+js(set, isNonSubcribed, false)`

**Comment by iamadamdev** [comment]
Which articles aren't working? The two above still work for me.
