### ISSUE TITLE
The Wall Street Journal Not Working

### ISSUE THREAD

**Issue by Cloudwind9** [iamadamdev/bypass-paywalls-chrome#78]
Having problems with The Wall Street Journal, Updated to 1.3.7.

for example https://www.wsj.com/articles/u-k-conservative-lawmakers-trigger-no-confidence-vote-over-theresa-mays-leadership-11544601105

**Comment by 420pitts** [comment]
Same. Using Chrome Version 71.0.3578.80 and 1.3.7. Cookies have been deleted.

**Comment by iamadamdev** [comment]
WSJ has been acting up lately.

I did not change anything with regards to wsj. It looks like they put up a hard paywall. Visit any article and copy the article title, then open up incognito mode and paste into Google, and click on the same article link from Google search results. If the article still won't load, then unfortunately my extension cannot bypass it either.

**Comment by Cloudwind9** [comment]
It's still not working...

**Comment by 420pitts** [comment]
They must be changing something on their end because it started working again for me.

**Comment by orensdailyroast** [comment]
same here!
