### ISSUE TITLE
WSJ extremely slow loading

### ISSUE THREAD

**Issue by dragonhailstone** [iamadamdev/bypass-paywalls-chrome#781]
Too slow on  ff mobile.
I will stick to 1.7.3.

**Comment by bob-kiefer** [comment]
Looks like no proper testing is done on Firefox.

**Comment by iamadamdev** [comment]
I tested it on Firefox 78.0.2 (64-bit), didn't see any unnecessary memory usage or anything, WSJ loaded fine.

**Comment by bob-kiefer** [comment]
@iamadamdev weird then that v1.7.3 is still working for @dragonhailstone though ...
