### ISSUE TITLE
Another Paywall/Subscribe Request

### ISSUE THREAD

**Issue by Redback813** [iamadamdev/bypass-paywalls-chrome#782]
G"day All
I have a request for the following url below if possible please.

https://www.newscientist.com/article/2248638-the-moon-may-have-stopped-the-early-earth-from-being-a-frozen-snowball/

Cheers
And many thanks

**Comment by iamadamdev** [comment]
Have you tried adding them to the Custom Sites tab on Chrome?
![image](https://user-images.githubusercontent.com/36013816/87183475-0e11fa00-c29b-11ea-9b25-d487a19231aa.png)

**Comment by Redback813** [comment]
Sorry that leave even more confused, where would I find what your asking in either Firefox or Brave?

**Comment by iamadamdev** [comment]
It's not available in Firefox. Not sure about Brave. You can use Google Chrome and install the latest version of Bypass Paywalls.
