### ISSUE TITLE
Possible to exclude url patterns?

### ISSUE THREAD

**Issue by dwaxe** [iamadamdev/bypass-paywalls-chrome#786]
Imagine you pay for a NYT crossword subscription which you need to be logged in to access. However you don't have a regular NYT subscription, so you want to keep bypassing its regular paywall. Is it possible to have an exclude list that prevents browser storage clearing while on the crossword urls, `nytimes.com/crossword(s?)(.*)` and `nytimes.com/puzzle(s?)(.*)`?

**Comment by iamadamdev** [comment]
Do you want to submit a PR for that specific case?
