### ISSUE TITLE
New Site Request (with how-to): BOF Professional

### ISSUE THREAD

**Issue by theoryforcestudio** [iamadamdev/bypass-paywalls-chrome#788]
`www.businessoffashion.com`

The paywall is a two-layered overlay, article becomes visible after removing the class `article-locked` from its element, and the same for `article-locked-overlay` to remove the semi-transparent layer.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
