### ISSUE TITLE
Safari extentions

### ISSUE THREAD

**Issue by krstp** [iamadamdev/bypass-paywalls-chrome#790]
As title states, Safari extension, please.

**Comment by iamadamdev** [comment]
Apple most likely wouldn't approve it.

**Comment by krstp** [comment]
Thanks for the quick turnout. There is no way to have out-side of store solution to Safari, like custom copy and paste into the Library folder?

**Comment by ericboehs** [comment]
Has this changed with the [recent Safari 14 changes](https://developer.apple.com/news/?id=kuswih5l)?
