### ISSUE TITLE
Site Not Working: [Seeking Alpha]

### ISSUE THREAD

**Issue by smartini87** [iamadamdev/bypass-paywalls-chrome#791]
Issues while browsing on that Domain when suddenly a site occurs asking me whether I am a robot or not. After solving the Captcha puzzle the site still remains the same instead of passing me through to the article.

"Please click “I am not a robot” to continue
To ensure this doesn’t happen in the future, please enable Javascript and cookies in your browser."

E.g.: https://seekingalpha.com/article/4298365-goodfood-strong-fundamentals-presenting-delicious-upside?source=content_type:react|section:All|sectionAsset:Analysis|first_level_url:symbol|button:Title|lock_status:Archived|line:1

Happening in both, Chrome and Firefox.

**Comment by iamadamdev** [comment]
Try refreshing, still works fine for me:
![image](https://user-images.githubusercontent.com/36013816/87507958-2ed3aa00-c623-11ea-93eb-babf3dc571f9.png)

**Comment by AshNL** [comment]
Got the CAPTCHA, solved it, waited ~3 seconds and it redirected me to the full article.
So also still working for me in both Firefox and Edge.

**Comment by smartini87** [comment]
I waited even longer but nothing happened. anything else I could try? There must be an issue with the redirecting function.
