### ISSUE TITLE
Extension Randomly Disappear

### ISSUE THREAD

**Issue by DBStage1** [iamadamdev/bypass-paywalls-chrome#794]
Every so often the Bypass extension randomly disappears (Vivaldi Chromium Browser| 3.1.1929.45 (Stable channel) (64-bit) and have to reinstall.  Doesn't happen with any other extension.

Weird.

-Kirk

**Comment by iamadamdev** [comment]
Where are you saving the extension folder?

**Comment by PranjalChaitanya** [comment]
Yeah when you use the chrome extension you load it from your desktop, keep in mind google does not actually upload it, it just references your files. So whenever you delete or move the file google extensions doesn't know how to reference it.
