### ISSUE TITLE
https://www.theglobeandmail.com/

### ISSUE THREAD

**Issue by blitz111** [iamadamdev/bypass-paywalls-chrome#797]
Issue just started today.
We're sorry but we are unable to validate your access to this article. Please adjust your browser settings or turn off any extensions that may be causing this issue.

**Comment by jacquesbedard** [comment]
Actually, started yesterday afternoon. Tried to open an issue, but was not authorized to do so.

**Comment by fenomenalb** [comment]
You guys beat me to it. Kindly help.

**Comment by bpither** [comment]
Yup ... same here with Firefox and Chrome versions

**Comment by llacb47** [comment]
Add these filters to uBlock Origin:
```
theglobeandmail.com##+js(set, keytar.accessAllowed, true)
theglobeandmail.com##+js(aopr, tgam.darwin.tests.segments.push)
```

**Comment by smnlng** [comment]
> Add these filters to uBlock Origin:
> 
> ```
> theglobeandmail.com##+js(set, keytar.accessAllowed, true)
> theglobeandmail.com##+js(aopr, tgam.darwin.tests.segments.push)
> ```

This had no effect for me - still has the blocked text.

**Comment by llacb47** [comment]
Example article?

**Comment by smnlng** [comment]
> Example article?
> 
> Also try and disable Bypass Paywalls when testing.

Thanks, that solved it. Disabling Bypass Paywalls along with the uBlock code did the trick!

**Comment by jacquesbedard** [comment]
> Example article?
> 
> Also try and disable Bypass Paywalls when testing.

Filters and Bypass work in Brave as well. Thanks !

**Comment by blitz111** [comment]
Yes , uFilters and Bypass worked in Chrome.

**Comment by bpither** [comment]
uBlock code works on Chrome when you disable Bypass Paywalls for the Globe and Mail. To read the Economist or other paywall entrenched media sites, enable BP again. Easy Peazy.

**Comment by jacquesbedard** [comment]
> uBlock code works on Chrome when you disable Bypass Paywalls for the Globe and Mail. To read the Economist or other paywall entrenched media sites, enable BP again. Easy Peazy.

Just disable the Globe and Mail in Options, not the entire Bypass Paywalls extension.

**Comment by bpither** [comment]
> `Just disable the Globe and Mail in Options, not the entire Bypass Paywalls extension.` Yes quite right ... thanks jacquesbedard

**Comment by speedbump101** [comment]
Still a no go here with jacquesbedard‘s fix... works for a few links then goes to the subscribe page... Using Firefox

**Comment by bpither** [comment]
On Chrome it worked fine at my end (Vancouver) **speedbump101**

**Comment by speedbump101** [comment]
Ok... I think its ok now. I added the filters (listed above, courtesy of llacb47) to uBlock Origin , and together with the jacquesbedard fix, FF seems to be working properly with the G&M now. I didn’t realize that I needed both the filters and the options / unchecking G&M in PW bypass to fix this issue.

Thanks for the help guys.

**Comment by iamadamdev** [comment]
Fixed in latest master.

**Comment by iamadamdev** [comment]
Fixed, update to the latest version for FF here: https://github.com/iamadamdev/bypass-paywalls-chrome/releases/latest/download/bypass-paywalls-firefox.xpi
