### ISSUE TITLE
Caixin

### ISSUE THREAD

**Issue by johntosmith** [iamadamdev/bypass-paywalls-chrome#799]
CONFIRMED

Caixin Global is currently on the Bypass Paywalls list, but paywalls apply to articles directly navigated from the main website: http://www.caixin.com/?HOLDZH, for the Chinese website, or http://en.caixin.com/ for the English translation of the main website. 

Would it be possible to add these two websites to the list?

Many thanks!

**Comment by iamadamdev** [comment]
Doesn't work for that site.
