### ISSUE TITLE
Israeli sites still blocked by paywalls

### ISSUE THREAD

**Issue by alex5723** [iamadamdev/bypass-paywalls-chrome#80]
Version 1.3.7 : 
https://www.haaretz.co.il/ still blocked by paywall. 
https://themarker.com still block by paywall.

**Comment by iamadamdev** [comment]
Try the firefox version for haaretz. That site is a known issue (trouble maker). They constantly change their site and this paywall breaks a lot. If you find a fix though please submit a PR.

**Comment by alex5723** [comment]
Thanks.

It does work with Firefox.
