### ISSUE TITLE
Medium.com not working

### ISSUE THREAD

**Issue by havilson** [iamadamdev/bypass-paywalls-chrome#803]
It's not working anymore, it's showing me the counter for the monthly free reads.

**Comment by SethuSenthil** [comment]
Do you have it enabled in the extension?

**Comment by iamadamdev** [comment]
article?

**Comment by havilson** [comment]
Yes I do have it enabled in the extension. I figured out the following:
I'm logged out of my account and when I tried to login back I simply can't. Even though I authorize using my google account to authenticate and login this simply don't work.
So, I turned Medium off in the extension and login into my account.
Now, I can login.
I turn Medium back on inside the extension.
It works till next logout situation.

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/88862254-a4f41700-d1b4-11ea-9150-1ab024f11e68.png)
