### ISSUE TITLE
Economist.com - some articles from the latest issue 25 July 2020 cannot be accessed

### ISSUE THREAD

**Issue by Logen72** [iamadamdev/bypass-paywalls-chrome#805]
Some articles from the latest issue of the economist cannot be accessed with the following error message

ERR_TOO_MANY_REDIRECTS

I have attached an example of the link from the issue of 25 July for your reference:

https://www.economist.com/asia/2020/07/23/central-asian-governments-admit-they-have-a-problem-with-covid-19

Have tried clearing cookies but to no avail, appreciate your help in resolving this. Same issue pops on firefox and chrome.

Regards

Logen

**Comment by llacb47** [comment]
Happens in guest mode too, not this extension's issue.

**Comment by iamadamdev** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/36013816/88844889-343f0180-d198-11ea-8dcb-06c8c4830bd3.png)

**Comment by Logen72** [comment]
Yes, all works now. Probably was a problem on economist.com, not an issue with the extension. I will close the thread.

**Comment by Logen72** [comment]
Closing thread.
