### ISSUE TITLE
Telegraph.co.uk bypass not working

### ISSUE THREAD

**Issue by deerhunter91** [iamadamdev/bypass-paywalls-chrome#807]
The content is displayed but then disappears a second later. Examples:

https://www.telegraph.co.uk/cricket/2020/07/23/england-consider-leaving-dom-bess-final-test-ben-stokes-likely/

https://www.telegraph.co.uk/news/2020/07/24/harry-meghan-sue-photographers-los-angeles-alleged-pictures/

Thank you for consideration. 

I am using the latest Firefox.

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed?
Works fine for me:
![image](https://user-images.githubusercontent.com/36013816/88762149-7aa74880-d125-11ea-84c8-b286e3c01ff8.png)
