### ISSUE TITLE
Medium.com Bypass not working with account login

### ISSUE THREAD

**Issue by shubhank-saxena** [iamadamdev/bypass-paywalls-chrome#808]
I login into my account and as soon as this plugin is opened, I  am getting logged out of it. Thus, I wont be able to save/track it in my account. Is it the underlying working of this plugin, or a bug?

**Comment by iamadamdev** [comment]
Did you uncheck medium in the sites list?

**Comment by shubhank-saxena** [comment]
Nopes. I actually had to uncheck as plugin wasn't allowing me to login. I logged in and then enabled it again

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/89107600-07345e00-d3e7-11ea-9bc1-a5d770dc9f7e.png)
