### ISSUE TITLE
Cannot log into NY Times

### ISSUE THREAD

**Issue by DrBB01** [iamadamdev/bypass-paywalls-chrome#809]
Running version 1.7.4 (updated July 16, 2020). I cannot log into the NY Times website (I have an account) unless I disable Bypass Paywalls or start Firefox in Safe Mode. As long as BP is disabled, I can navigate nytimes.com without problem. However, as soon as I enable BP and try to load a new page on the site or refresh the current page, I am immediately logged out and cannot log back in — until I disable BP.

**Comment by iamadamdev** [comment]
Did you uncheck NYT in Bypass Paywalls?

**Comment by DrBB01** [comment]
Adam,

I did, but apparently forgot to save. Just tried it again and it works
fine. Thanks!

Bruce

**Comment by iamadamdev** [comment]
Glad to hear!
