### ISSUE TITLE
The Age bypass is no longer working

### ISSUE THREAD

**Issue by tobtoh** [iamadamdev/bypass-paywalls-chrome#81]
The Age bypass is no longer working. If I use Incognito mode, I can load the pages though..

Example page: https://www.theage.com.au/politics/federal/morrison-government-suffers-another-setback-as-ipsos-poll-points-to-landslide-loss-20181216-p50mjm.html

**Comment by iamadamdev** [comment]
Looked into it briefly, couldn't find a permanent fix at the moment, but this temporarily resets your article limit:
If it doesn't work for an article try unchecking the site in Options, save, refresh the article, then re-check the site, save and refresh the article again.

**Comment by tobtoh** [comment]
Unchecking The Age in options, saving, and then reloading the site let's me through now (I assume because it reset the 'free views' counter). 

Re-enabling it in options causes the problem to reoccur. Will leave it unchecked for now until a permanent fix can be found.

Thanks for all the work you do on this by the way - it's one of the essential extensions for me!

**Comment by iamadamdev** [comment]
Actually an easier way is to just run into the paywall and then refresh the page (no unchecking needed).

**Comment by tobtoh** [comment]
Hmmm that doesn't work for me. With the The Age option ticked, I get a'400 Error - Sorry we can't display this page at this time' (This is a 'The Age' branded page, not a Chrome error page.) with the paywall banner ad overlaid at the bottom.

**Comment by iamadamdev** [comment]
Right, I get that too, but I refresh once, and then it loads properly and doesn't show again (sometimes need to refresh a second time too)

**Comment by tobtoh** [comment]
If I leave the option ticked, the reload trick doesn't work for me at all (even with multiple refreshes). However, it appears if I check or uncheck the option once, then reload once or twice, it works. Previously I was unticking, reload, then reticking and reload to view the page ... so I guess that is a small improvement :)

**Comment by tobtoh** [comment]
So I've done a bit more experimenting. If I do a hard reload (shift + reload) to bypass the cache, I get the page to load without paywalls or errors. Strangely though, doing it once or twice doesn't seem to work, I have to rapidly hard reload 4-5 times in rapid succession for it to work.
