### ISSUE TITLE
New site request: theguardian.com

### ISSUE THREAD

**Issue by dollhaus** [iamadamdev/bypass-paywalls-chrome#812]
Steps to remove registration wall: 

- remove `display:none` from div class `content__article-body`
- delete all elements with class `signin-gate` and `signin-gate__first-paragraph-container`

Job done.

**Comment by iamadamdev** [comment]
Please submit a PR for this.

Job done.

**Comment by llacb47** [comment]
@dollhaus just use uBlock Origin.
