### ISSUE TITLE
San Fransisco Chronicle not working.

### ISSUE THREAD

**Issue by JimboUS** [iamadamdev/bypass-paywalls-chrome#814]
San Fransisco Chronicle not working.

**Comment by iamadamdev** [comment]
Which article? I just loaded 5+ articles w/o issue.

**Comment by JimboUS** [comment]
Any article. See the attached pdfs for instance.Latest version 1.7.4.No problems with the Wall Street Journal, Financial Times, The New York Times, etc.
    On Monday, July 27, 2020, 1:46:59 PM EDT, Adam <notifications@github.com> wrote:  
 
 


Which article? I just loaded 5+ articles w/o issue.

**Comment by JimboUS** [comment]
Using Firefox latest version.

    On Monday, July 27, 2020, 2:17:32 PM EDT, D K <tieag@yahoo.com> wrote:  
 
  
Any article. See the attached pdfs for instance.Latest version 1.7.4.No problems with the Wall Street Journal, Financial Times, The New York Times, etc.
    On Monday, July 27, 2020, 1:46:59 PM EDT, Adam <notifications@github.com> wrote:  
 
 


Which article? I just loaded 5+ articles w/o issue.

**Comment by JimboUS** [comment]
Just tried Google Chrome browser with no problems for the SFChronicle.So it has problems with Firefox.
But Firefox has no issues/no problems with the Wall Street Journal, Financial Times, The New York Times, etc.
    On Monday, July 27, 2020, 2:20:24 PM EDT, D K <tieag@yahoo.com> wrote:  
 
  Using Firefox latest version.

    On Monday, July 27, 2020, 2:17:32 PM EDT, D K <tieag@yahoo.com> wrote:  
 
  
Any article. See the attached pdfs for instance.Latest version 1.7.4.No problems with the Wall Street Journal, Financial Times, The New York Times, etc.
    On Monday, July 27, 2020, 1:46:59 PM EDT, Adam <notifications@github.com> wrote:  
 
 


Which article? I just loaded 5+ articles w/o issue.

**Comment by iamadamdev** [comment]
Any article works for me.
Do you have uBlock Origin installed? Maybe try clearing cookies?

**Comment by iamadamdev** [comment]
On Firefox it works fine for me. Do you have uBlock Origin installed? Also try clearing your cookies.

**Comment by JimboUS** [comment]
In Firefox:
NO uBlock Origin installed.Did NOT clear cookies.ONLY changed the Privacy and Security settings from STRICT to STANDARD, and it WORKED for the SFChronicle.STRICT does not allow SFChronicle to load but it allows the NYT, WSJ, and FT to work fine.

    On Monday, July 27, 2020, 2:49:25 PM EDT, Adam <notifications@github.com> wrote:  
 
 


On Firefox it works fine for me. Do you have uBlock Origin installed? Also try clearing your cookies.
