### ISSUE TITLE
The Globe and Mail no longer working

### ISSUE THREAD

**Issue by scoius** [iamadamdev/bypass-paywalls-chrome#815]
Globe and Mail is no longer working. Message: We're sorry but we are unable to validate your access to this article. Please adjust your browser settings or turn off any extensions that may be causing this issue.

**Comment by iamadamdev** [comment]
Works for me.
Which article?
Do you have uBlock Origin installed?

**Comment by scoius** [comment]
I do have it installed but I still get the same error if I disable it. I've
attached a screenshot showing the add-ons I am using.

**Comment by llacb47** [comment]
Stop using email to reply, no-one can see the attachments.

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/88843467-2ba5f580-d1af-11ea-8ce4-35061e58c4ef.png)

Also it happens on every article. This still works: https://github.com/iamadamdev/bypass-paywalls-chrome/issues/797#issuecomment-660526063

**Comment by scoius** [comment]
Sorry, I didn't know that. Here is the screenshot. Thank you for your help.
![Screenshot_20200729-131104](https://user-images.githubusercontent.com/18366894/88843567-96026a00-d19e-11ea-955f-b17ab5617347.jpg)

**Comment by scoius** [comment]
Just tried the ublock filter option and it works, thank you! Hopefully bypass paywalls works again soon.
