### ISSUE TITLE
barron's

### ISSUE THREAD

**Issue by mpou1985** [iamadamdev/bypass-paywalls-chrome#816]
Hey there,

I noticed that the website Barrons.com is not bypassed anymore. Do you think it would be possible to check this out? 

I love this extension.

Thanks guys

**Comment by mpou1985** [comment]
Well, it looks like an IP issue
As soon as I turned the VPN on with a US IP, Barron's could be bypassed. Weird, though, I'm not sure why they would block specific countries. I guess they must have customers all around the world. Or is it possible they can see IPs that bypass their paywall and block them accordingly?

**Comment by jklipsch** [comment]
Barrons' paywall is back up.
