### ISSUE TITLE
Logged out from Quora and the login option was greyed out forcing me to turn off this extension

### ISSUE THREAD

**Issue by Bharadwajvarma** [iamadamdev/bypass-paywalls-chrome#819]
So, I use quora regularly and its logged in always in my Firefox (latest version). I also use windows 10. After installing this extension suddenly today quora got auto-logged out. I didnt understand why but even the login button was greyed out. I suspected it might be due to some extensions and hence restarted firefox with add-ons disabled and it prompted to ask whether to start in safe mode. I clicked yes and tried quora.com again and surprisingly it was already logged in now. So, I close safe mode and again open normal mode and now quora is logged out again. I tried disabling bypass paywalls (this extension) and it worked. I don't know but somehow this extension is causing Quora to get logged out and I cant even log in again because of greyed out login button. 
![bhmvmmb](https://user-images.githubusercontent.com/29541851/88761518-ec66ad00-d18c-11ea-865d-d96070fe4b8d.PNG)
![gcbghnvbjmb](https://user-images.githubusercontent.com/29541851/88761551-fab4c900-d18c-11ea-840a-49acca8b96c0.PNG)

**Comment by iamadamdev** [comment]
Try unchecking Quora in options.
![image](https://user-images.githubusercontent.com/36013816/88763582-39fcfe80-d128-11ea-9dad-db76d1f16ae7.png)

**Comment by Bharadwajvarma** [comment]
Yes, it worked. I didn't see Quora in the list of options initially. Must have scrolled past through it. Thank you
