### ISSUE TITLE
WSJ article when synched to pocket needs subscriber login details

### ISSUE THREAD

**Issue by Logen72** [iamadamdev/bypass-paywalls-chrome#821]
###
1. Make sure uBlock Origin is installed.
2. Paste the article URL for the site you are having issues with.
3. Describe the issue.

Requests not following these instructions will be ignored.
###
https://www.wsj.com/articles/what-polling-can-tell-us-100-days-from-the-election-11595768400

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/65835550/88867324-0fcd3e80-d205-11ea-9fa3-b3bc8c97e65e.png">

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/89107613-19160100-d3e7-11ea-9257-67cfc4e4ad70.png)

**Comment by Logen72** [comment]
Thank you, removed google access from connected services and applications it now works.
