### ISSUE TITLE
Installation Instructions Not Working

### ISSUE THREAD

**Issue by jdolbeer** [iamadamdev/bypass-paywalls-chrome#822]
Drag and drop of the unzipped folder doesn't trigger any actions within Chrome.  Console shows no actions.  

Attempting to drag the Zip file prompts an error (Error Loading Extension: Failed to load extension from: C:\Users\~\bypass-paywalls-chrome-master.zip. Could not unzip extension for install.)

**Comment by armarion** [comment]
unzip to a folder then try dragging that folder

**Comment by iamadamdev** [comment]
Or clicked Load unpacked and select the folder after unzipping:
![image](https://user-images.githubusercontent.com/36013816/89108481-c429b900-d3ed-11ea-8b9d-f1990c9a271f.png)
