### ISSUE TITLE
Not able to log in on medium

### ISSUE THREAD

**Issue by alextraykov** [iamadamdev/bypass-paywalls-chrome#825]
###
1. Make sure uBlock Origin is installed.
2. Paste the article URL for the site you are having issues with.
3. Describe the issue.

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/89132936-9f584300-d4cc-11ea-8bdc-cb2d5ca73287.png)
