### ISSUE TITLE
New site request: [ynet.co.il]

### ISSUE THREAD

**Issue by Crapy** [iamadamdev/bypass-paywalls-chrome#827]
I have tried to use a google bot agent, removed cookies after page load and before, I know they do use tinypass/piano?
Also I have found the paywall.js in their site but can't figure out how to bypass this I don't know if it is possible

Example of a premium article https://www.ynet.co.il/articles/0,7340,L-5775256,00.html

**Comment by iamadamdev** [comment]
Seems like a hard paywall.
