### ISSUE TITLE
Not working with firefox for Android 79

### ISSUE THREAD

**Issue by Crapy** [iamadamdev/bypass-paywalls-chrome#830]
The firefox for Android fenix (version 79) has been released and it appears the extension does not support it.

**Comment by iamadamdev** [comment]
I think it's the other way around, the new Firefox for Android does not support most extensions.
https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/
https://www.xda-developers.com/mozilla-firefox-79-for-android-preview-nightly-update-without-extensions-add-ons/

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/836
