### ISSUE TITLE
New site request: https://www.weeklytimesnow.com.au/

### ISSUE THREAD

**Issue by thebrowndog** [iamadamdev/bypass-paywalls-chrome#831]
This is a major regional newspaper in australia that should work the same as the herald sun, NT news, Sudney Daily Telegraph.

**Comment by iamadamdev** [comment]
Works if you add to custom sites:
![image](https://user-images.githubusercontent.com/36013816/89717236-4aec1200-d969-11ea-9fc3-e7e1598c1c37.png)
