### ISSUE TITLE
Site Not Working [The Globe and Mail]

### ISSUE THREAD

**Issue by mzarglis** [iamadamdev/bypass-paywalls-chrome#835]
- Firefox 79
- Extension version 1.7.4
- uBlockOrigin Installed 

https://www.theglobeandmail.com/politics/article-saudi-crown-prince-sent-hit-squad-to-canada-exiled-spy-chief-alleges/

Error: We're sorry but we are unable to validate your access to this article. Please adjust your browser settings or turn off any extensions that may be causing this issue.

**Comment by iamadamdev** [comment]
Works fine on Chrome:
![image](https://user-images.githubusercontent.com/36013816/89608115-107b5b80-d829-11ea-8769-e1ffddcb398d.png)

**Comment by mzarglis** [comment]
I am using firefox 79

**Comment by bpither** [comment]
Not working on Chrome here ...

**Comment by mzarglis** [comment]
I just tested on chrome 84.0.4147.105 and it works fine, just firefox 79 seems to be the issue

**Comment by iamadamdev** [comment]
Will be fixed in next FF release.

**Comment by iamadamdev** [comment]
Fixed, update to the latest version for FF here: https://github.com/iamadamdev/bypass-paywalls-chrome/releases/latest/download/bypass-paywalls-firefox.xpi
