### ISSUE TITLE
elpais.com.co

### ISSUE THREAD

**Issue by andresmorago** [iamadamdev/bypass-paywalls-chrome#838]
Confirmed 

Hello
Can you please add elpais.com.co ?
https://www.elpais.com.co/contenido-premium/balance-positivo-tras-primer-dia-de-cuarentena-voluntaria-en-el-centro-de-cali.html

**Comment by iamadamdev** [comment]
You can add it to custom sites on the Chrome version:
![image](https://user-images.githubusercontent.com/36013816/89717083-d8c6fd80-d967-11ea-8d62-a1ebb17bccff.png)
