### ISSUE TITLE
Cannot log on to The Spectator (https://www.spectator.co.uk/) even though relevant checkbox is off

### ISSUE THREAD

**Issue by jgbustos** [iamadamdev/bypass-paywalls-chrome#841]
###
1. Make sure uBlock Origin is installed.
2. Paste the article URL for the site you are having issues with.
3. Describe the issue.

Requests not following these instructions will be ignored.
###
Hi,

uBlock Origin is definitely installed, and the checkbox for The Spectator is off, but when I try to access "My Account" something breaks. Problem does not happen when I disable the Bypass Paywalls extension.

Steps to replicate:

1. Open Firefox with uBlock Origin installed and the checkbox for "The Spectator" off inthe add-on settings
2. Open https://www.spectator.co.uk/
3. Click on "Account", at the top right of the screen

What you see: 
![image](https://user-images.githubusercontent.com/35463898/89772696-63d7fd00-dafa-11ea-8e25-b821baa163f2.png)

What you should see:
![image](https://user-images.githubusercontent.com/35463898/89772790-8ec25100-dafa-11ea-96b5-b973f352a410.png)

Many thanks in advance

JGB

UPDATE: Unchecking "General Paywall Bypass" as suggested below does fix the issue. Very much appreciated

**Comment by iamadamdev** [comment]
Uncheck General Paywall Bypass;
![image](https://user-images.githubusercontent.com/36013816/89847016-a79d2780-db37-11ea-9cc0-e79a8990dfa2.png)
