### ISSUE TITLE
Globe and Mail Covid' issue

### ISSUE THREAD

**Issue by senormingus** [iamadamdev/bypass-paywalls-chrome#842]
Hi there,

The Globe and Mail is back up and running (thanks!) except for any story related to Covid19 that they deem 'free'. When clicked, the site blocks the story and asks you to sign up. Using Firefox.
Thanks.

**Comment by iamadamdev** [comment]
link?

**Comment by senormingus** [comment]
Link + screenshot.

![Screen Shot 2020-08-11 at 2 45 34 PM](https://user-images.githubusercontent.com/68487520/89936323-7711c800-dbe1-11ea-90a7-edc62509e62f.png)

https://www.theglobeandmail.com/world/article-global-coronavirus-cases-surpass-20-million-doubling-in-just-over-six/

**Comment by iamadamdev** [comment]
Works fine for me, do you have uBlock Origin installed? Do you have the site checked in options? :
![image](https://user-images.githubusercontent.com/36013816/89941543-06ae7b00-dbd0-11ea-92f7-163453bdc5f4.png)

**Comment by senormingus** [comment]
No uBlock installed. Using Adblock Plus... I'm guessing I should change that.

**Comment by jcosentino** [comment]
I have this issue using uBlock Origin. I saw it in this article:
https://www.theglobeandmail.com/canada/article-nursing-homes-with-multibed-wards-left-residents-vulnerable-to/

I played around with my filter subscriptions and pinned it down to the "uBlock filters" built-in one.
When I disable this, the covid popup does not happen.
