### ISSUE TITLE
thetimes.co.uk no longer working

### ISSUE THREAD

**Issue by hardtofin** [iamadamdev/bypass-paywalls-chrome#844]
###
1. Make sure uBlock Origin is installed. - YES
2. Paste the article URL for the site you are having issues with. - https://www.thetimes.co.uk/edition/news/a-level-results-university-chiefs-in-urgent-talks-with-ministers-to-stem-exam-confusion-j0zdc9lvj?utm_medium=Social&utm_source=Twitter#Echobox=1597248752
3. Describe the issue. - Thetimes.co.uk is no longer working as of this evening.  Tried several different articles and all are not available past the first paragraph.

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
What version of Bypass Paywalls are you on?
Still works for me:
![image](https://user-images.githubusercontent.com/36013816/90070415-b7884900-dca8-11ea-9373-bd3a1f0ff3d6.png)

**Comment by hardtofin** [comment]
i actually deleted mine and redownloaded the one that is linked here under "how to install".  The one i have now is 1.75

**Comment by huangshayang** [comment]
yes ,1.75  not working

**Comment by iamadamdev** [comment]
Loads fine for me in Chrome and Firefox.
