### ISSUE TITLE
The Saturday Paper no longer working

### ISSUE THREAD

**Issue by nosetalgia** [iamadamdev/bypass-paywalls-chrome#845]
1. Make sure uBlock Origin is installed. - Yes
2. Paste the article URL for the site you are having issues with. - https://www.thesaturdaypaper.com.au/news/politics/2020/08/08/what-led-victorias-extraordinary-shutdown/159680880010229
3. Describe the issue. - thesaturdaypaper.com.au is no longer working as of yesterday. All articles are paywalled past the article title with immediate request for subscription.

Requests not following these instructions will be ignored.

**Comment by iamadamdev** [comment]
Fixed in latest master.
