### ISSUE TITLE
Is there Bypass Paywalls for android?

### ISSUE THREAD

**Issue by RotterSoft** [iamadamdev/bypass-paywalls-chrome#846]
In case there is - how do I install and configure it?
Thanks!

###
1. Make sure uBlock Origin is installed.
2. Chrome or Firefox?
3. Paste the article URL for the site you are having issues with.
4. Describe the issue.

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/836
