### ISSUE TITLE
Seekingalpha.com Not working

### ISSUE THREAD

**Issue by thelightisthere93** [iamadamdev/bypass-paywalls-chrome#847]
###
1.  UBlock origin downloaded
2. Chrome 
3. https://seekingalpha.com/article/4354518-5-best-cefs-to-buy-this-month-june-2020?source=all_articles_title
4. I used to be able to read articles on Seekingalpha premium. Haven't been able to access for a few weeks. 

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
What version of Bypass Paywalls are you on?
