### ISSUE TITLE
ESPN+ possible?

### ISSUE THREAD

**Issue by bbourdet** [iamadamdev/bypass-paywalls-chrome#848]
###
1. uBlock Orgin is installed
2. Firefox
3. https://www.espn.com/nfl/insider/story/_/id/29602474/ranking-all-32-nfl-teams-their-25-talent-2020
4. Is it possible to add ESPN+ to this? I know you said that some premium sites are behind a "hard paywall". Is this the case with ESPN+?

Thank you for the plugin, I really like it!

**Comment by iamadamdev** [comment]
Hard paywall unfortunately.
