### ISSUE TITLE
The Boson Globe

### ISSUE THREAD

**Issue by Redback813** [iamadamdev/bypass-paywalls-chrome#849]
Firefox Add-ons: Bypass Paywalls by Adam v1.7.5
Chrome Add-ons: Bypass Paywalls by Adam v1.7.3
https://www.bostonglobe.com/2020/08/14/metro/state-police-lost-thousands-e-mails-related-trooper-overtime-fraud-case/

Please and thankyou

**Comment by iamadamdev** [comment]
Add to custom sites:
![image](https://user-images.githubusercontent.com/36013816/91202327-83545580-e6b6-11ea-8f69-4b838ecba619.png)
