### ISSUE TITLE
FT.com does not work any longer

### ISSUE THREAD

**Issue by iscreamcoke** [iamadamdev/bypass-paywalls-chrome#85]
Still works like a charm with the Firefox extension though

Tried with another Chrome profile with no other extension, I don't think the issue is just for me

example: https://www.ft.com/content/380d415c-0ab4-11e9-9fe8-acdb36967cfc

btw: Thanks a lot for this extension, I'm working on a GUI for you project if you're interested: https://github.com/iscreamcoke/trebuchet

**Comment by iamadamdev** [comment]
That article loads fine for me on Chrome. You should be using this extension along with uBlock Origin.

**Comment by zhenyulin** [comment]
used it along with uBlock Origin, but access to the above content is restricted

**Comment by iscreamcoke** [comment]
Already tried with no extension, re-tried with uBlock Origin => same issue

It's not only this article but any article on FT.com

**Comment by iamadamdev** [comment]
Are you guys both located in EU? It's working fine for me in U.S. Also removed the extension and confirmed the paywall appeared, then I reinstalled the extension and the article loaded fine. I clicked accept on the cookies popup.
