### ISSUE TITLE
New site request: [https://www.scmp.com/hk]

### ISSUE THREAD

**Issue by johntosmith** [iamadamdev/bypass-paywalls-chrome#851]
Confirmed.

**Comment by iamadamdev** [comment]
Where are you seeing a paywall on scmp.com?

**Comment by johntosmith** [comment]
Every reader will have access to some free articles each month before they will be prompted with a subscription message.

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed?
I just loaded 20+ articles w/o seeing a subscription message.

**Comment by madzae** [comment]
Hei, Quartz (or qz.com) still can't be bypassed by this extensions.

**Comment by iamadamdev** [comment]
qz.com is free articles only (removes limitation).
