### ISSUE TITLE
New site request: [hbrturkiye.com]

### ISSUE THREAD

**Issue by dr-norton** [iamadamdev/bypass-paywalls-chrome#852]
harvard business review turkish website, seems the same structure as hbr.org.

**Comment by devnetkc** [comment]
unfortunately, this doesn't url doesn't seem to give any free samples.  White the urls are similar, and the page content, the functionality was not.  You have to be logged in to gain access to the articles on this domain.

I even added it to the extension, trying to by removing `.paywall-register`, but no luck.


You have any example steps I could follow to see what you want blocked?


### hbr.org
<img width="435" alt="Screen Shot 2020-08-23 at 1 52 36 PM" src="https://user-images.githubusercontent.com/26221344/90986419-58e48a00-e548-11ea-9344-9a7c7468bdc6.png">

### hbrturkiye.com
<img width="583" alt="Screen Shot 2020-08-23 at 1 53 18 PM" src="https://user-images.githubusercontent.com/26221344/90986441-731e6800-e548-11ea-8638-ce1bd3025894.png">

**Comment by devnetkc** [comment]
White the sites are similar.  You have to be logged in to gain access to the articles on this domain.

I even added it to the extension, trying to by removing `.paywall-register`, but no luck.

I could not both be logged in and using the bypass paywall option at the same time.

hbr.org
Screen Shot 2020-08-23 at 1 52 36 PM

hbrturkiye.com
Screen Shot 2020-08-23 at 1 53 18 PM

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/91202165-44be9b00-e6b6-11ea-8b87-6cb7e507956f.png)
