### ISSUE TITLE
Mobile 

### ISSUE THREAD

**Issue by horizonblue5** [iamadamdev/bypass-paywalls-chrome#853]
###
1. Make sure uBlock Origin is installed.
2. Chrome or Firefox?
3. Paste the article URL for the site you are having issues with.
4. Describe the issue.

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
Not on the latest version https://blog.mozilla.org/blog/2020/08/25/introducing-a-new-firefox-for-android-experience/
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/836
