### ISSUE TITLE
Quartz no longer working (?)

### ISSUE THREAD

**Issue by vhoanghac** [iamadamdev/bypass-paywalls-chrome#857]
###
**1. Make sure uBlock Origin is installed.** YES. Tried to turn it off but still doesn't working.
**2. Chrome or Firefox?** Microsoft Edge
**3. URL:** https://qz.com/1206229/this-is-the-best-book-for-learning-modern-statistics-its-free/
**4. Describe the issue.**

![img](https://i.imgur.com/d5phaSD.png)

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
It only works on free articles. That article is behind a hard paywall.
