### ISSUE TITLE
Bypass for The Athletic not working

### ISSUE THREAD

**Issue by jayiyer** [iamadamdev/bypass-paywalls-chrome#859]
###
1. Make sure uBlock Origin is installed. Yes
2. Bypass Paywalls version? 1.7.5
3. Chrome or Firefox? Chrome
4. Paste the article URL for the site you are having issues with. https://theathletic.com/2016781/2020/08/25/jose-mourinho-amazon-documentary-tottenham-all-or-nothing/
5. Describe the issue.

Hello,

Thank you for this Chrome extension.

Paywall bypass for The Athletic appears not to be working at the moment. Please see the attached screenshot.

I followed all the recommended steps and also deleted and re-installed the extension -- both did not seem to fix the issue.

Thanks
![the athletic](https://user-images.githubusercontent.com/6980237/91385182-2acfa600-e7e5-11ea-86ea-c909dbf305e9.png)

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
uBlock doesn't look enabled in your screenshot?
The article loads for me:

![image](https://user-images.githubusercontent.com/36013816/91386156-4176fc80-e7e7-11ea-9bda-51bf04c4bb86.png)

**Comment by jayiyer** [comment]
Hello,

Thanks for your quick reply. Still not working:

![the athletic 2](https://user-images.githubusercontent.com/6980237/91386298-93b81d80-e7e7-11ea-8754-b0d0404c657a.png)

**Comment by iamadamdev** [comment]
Try clearing cookies? https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce

**Comment by jayiyer** [comment]
Same outcome. I already had the Cookie Remover extension prior to this. I also cleared my cache/cookies and even re-installed Chrome:

![the athletic 3](https://user-images.githubusercontent.com/6980237/91499163-d7596880-e875-11ea-9a01-6860df0441ee.png)

**Comment by iamadamdev** [comment]
Maybe an IP check. Where are you located?

**Comment by jayiyer** [comment]
California

**Comment by iamadamdev** [comment]
Maybe try Firefox? I can load that article fine in Chrome and FF.

**Comment by DNohlen** [comment]
I can confirm this problem both on Chrome and Firefox with uorigin and cookies removed.

**Comment by Nashdiz** [comment]
Also confirming this problem in Microsoft Edge/Google Chrome

**Comment by Du117** [comment]
I was able to read articles from the Athletic up until yesterday ! But, it is not working for me today ! I have tried on Windows Edge, Chrome and Firefox, and also, on Firefox and Chrome on Linux. I have also tried the recommended troubleshoots, bit to no effect ! I, however am able to read articles from the Financial Times, the New York Times and the WashingtonPost. So, I suppose the issue exists only for The Athletic's Paywall. Thank You for your effort !

**Comment by bbourdet** [comment]
Same issue right now for me. Using Firefox 1.75 on this link, does not work.

https://theathletic.com/2037121/2020/09/03/vecenie-2020-nba-mock-draft-7-1-a-mini-update-based-on-what-im-hearing/

**Comment by SixteenDollars** [comment]
Same issue for me on Chrome, stopped working when I checked this morning.

**Comment by fw88** [comment]
Same issue for me. Stopped working today in Chrome and Firefox. Was working yesterday.

**Comment by Venkataragavan** [comment]
Having the same issue as @fw88. Was working yesterday.

**Comment by iamadamdev** [comment]
Looks like that article is behind a hard paywall?

**Comment by SixteenDollars** [comment]
> Looks like that article is behind a hard paywall?
> All articles might be behind a hard paywall now.

Is it possible to get around hard paywalls?

**Comment by iamadamdev** [comment]
> > Looks like that article is behind a hard paywall?
> > All articles might be behind a hard paywall now.
> 
> Is it possible to get around hard paywalls?

Buying a subscription? or try the free trial

**Comment by fw88** [comment]
All good things must come to an end. Thanks for making it work before.

**Comment by jayiyer** [comment]
@iamadamdev -- any plan for a workaround? If you did it once, I'm sure you can do it again ;)

**Comment by tlarkin584** [comment]
Please can you find a solution for this, I will happily donate if this is resolved.

**Comment by D-Pyro** [comment]
Install the apk and you can read for free. Then clear cache after number of free articles have been reached.

**Comment by iamadamdev** [comment]
Removed in latest version.
