### ISSUE TITLE
lesechos.fr is in the list, but bypass doesn't work.

### ISSUE THREAD

**Issue by stephan-dev** [iamadamdev/bypass-paywalls-chrome#861]
1. uBo installed
2. v 1.7.5
3. Firefox
4. https://www.lesechos.fr/tech-medias/medias/amber-capital-le-cauchemar-de-lagardere-1161809
5. "This article is reserved to subscribers"

What do you mean "don't delete cookies before loading the page?" What cookies do I need?
What do you mean (from the Quartz closed issue) "This is a hard paywall. Bypass Paywalls works with free articles." Isn't the point of Bypass Paywalls to be able to read more than free articles?

**Comment by iamadamdev** [comment]
Fixed in latest master.

**Comment by stephan-dev** [comment]
I tested on Chrome, it works, thanks a lot for the update!
I thought maybe only one line of text in the article was missing, but it was 20 screens!

Sorry for the harsh question above, I'll try to browse this repo more, to understand the different types of paywalls, from simple to hard, to too hard.
