### ISSUE TITLE
Extension doesn't work for certain Medium articles

### ISSUE THREAD

**Issue by YeoBL** [iamadamdev/bypass-paywalls-chrome#862]
<img width="806" alt="Temp" src="https://user-images.githubusercontent.com/70051808/91650919-86858200-eab8-11ea-9607-53839723a5ce.PNG">
1. Make sure uBlock Origin is installed. (Yes)
2. Bypass Paywalls version? (1.7.5)
3. Chrome or Firefox? (Chrome)
4. Paste the article URL for the site you are having issues with. (https://medium.com/the-atlantic/the-mythology-of-karen-8e5bc0505541)
5. Describe the issue. (Can't read article)

**Comment by iamadamdev** [comment]
Try unchecking Medium and logging in with Google.
