### ISSUE TITLE
subdomain of wsj.com dose not work!

### ISSUE THREAD

**Issue by kristalSonny** [iamadamdev/bypass-paywalls-chrome#865]
###
1. Make sure uBlock Origin is installed.
 yes

2. Bypass Paywalls version?
v1.7.5

3. Chrome or Firefox?
Chrome

4. Paste the article URL for the site you are having issues with.
https://cn.wsj.com/articles/%E5%8F%97%E4%B8%AD%E5%9B%BD%E6%8A%80%E6%9C%AF%E5%87%BA%E5%8F%A3%E6%96%B0%E8%A7%84%E5%BD%B1%E5%93%8D%EF%BC%8Ctiktok%E4%B8%9A%E5%8A%A1%E5%87%BA%E5%94%AE%E4%BA%A4%E6%98%93%E8%B0%88%E5%88%A4%E6%94%BE%E7%BC%93-11598834822

5. Describe the issue.
main domain wsj.com works well, but the subdomain "cn.wsj.com" dose not work, every article in these subdomain is the same result.

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
Cn.wsj.com is behind a hard paywall.

**Comment by kristalSonny** [comment]
> Cn.wsj.com is behind a hard paywall.

Sorry! Thanks a lot!
