### ISSUE TITLE
New site request: [www.businessoffashion.com]

### ISSUE THREAD

**Issue by kristalSonny** [iamadamdev/bypass-paywalls-chrome#866]
Confirmed.

**Comment by iamadamdev** [comment]
Not a major newspaper. Try using custom sites.

**Comment by LuyangCAT** [comment]
> Not a major newspaper. Try using custom sites.

after use "custom sites " mode, it shows "Sorry, you have been blocked!You are unable to access businessoffashion.com"
I can't even access this website, what's wrong with this?
<img width="963" alt="截屏2020-09-01 23 56 29" src="https://user-images.githubusercontent.com/11739785/91876170-fcebd500-ecae-11ea-8879-18acc8671d90.png">
