### ISSUE TITLE
washingtonpost stopped working

### ISSUE THREAD

**Issue by pabloemma** [iamadamdev/bypass-paywalls-chrome#868]
My version is Chrome.
Here is the article:
https://www.washingtonpost.com/opinions/2020/08/31/ohio-republicans-are-embroiled-scandal-could-they-lose-election-trump/

All of a sudden, the Washingtonpost site is not working anymore.

###
1. Make sure uBlock Origin is installed.
2. Bypass Paywalls version?
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
Failed to read instructions.

Btw still works for me:
![image](https://user-images.githubusercontent.com/36013816/91794215-5da3e080-ebcf-11ea-90d6-6e6367fc4b17.png)

**Comment by pdxsam** [comment]
I'm having the same issue.

1.  Ublock is installed and active 
2. Version 1.7.5
3. Firefox 
4. https://www.washingtonpost.com/politics/2020/09/01/thats-why-trump-gives-more-interviews-fox-news-than-anyone-else/
5. Head to that link, and the page gets faded or blurred and there's a "subscribe" popup. See attached image
![wapo](https://user-images.githubusercontent.com/13408715/91904613-1151b280-ec5a-11ea-96a4-ed4555b849c8.png)

Misc:

In Umatrix, if I go in and disallow XHR in umatrix for subscribe.washingtonpost.com and www.washingtonpost.com, then this works fine. I've disabled umatrix as a test and the same is observed.
I hadn't needed to do that before, so I'm not sure if something has changed on the back end of WaPo

**Comment by llacb47** [comment]
add this to your filters @pdxsam 
```
||washingtonpost.com^*/pwapi-$script
||washingtonpost.com/subscribe/paywall/
||washingtonpost.com/subscribe/pw/
||washingtonpost.com/wp-stat/pb/prod/pmbl.txt
||washingtonpost.com/subscribe/logging/
```

from my list `https://github.com/llacb47/miscfilters/raw/master/antipaywall.txt`

**Comment by pdxsam** [comment]
Outstanding!  That dealt with it  and a couple of other sides as well.
Thanks!
