### ISSUE TITLE
washington post not working, again

### ISSUE THREAD

**Issue by meeotch** [iamadamdev/bypass-paywalls-chrome#871]
###
1. Make sure uBlock Origin is installed. = yes
2. Bypass Paywalls version?  = 1.7.5
3. Chrome or Firefox?  = FF 80.0
4. Paste the article URL for the site you are having issues with.
https://www.washingtonpost.com/opinions/2020/09/02/ady-barkan-op-ed-scalise-video/
5. Describe the issue.
Washington Post seems to have implemented a new pop-up box that offers subscription ("Try one month for $1"), and blocks access to many/most of the articles.

Requests not following these instructions will be ignored.
###

**Comment by llacb47** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/868#issuecomment-685137724

**Comment by meeotch** [comment]
Weird, it spontaneously started working again, just as I was going to apply the filters you linked to.  (Applying the filters cleaned up some other stuff, like the pop-up footer, though.  So thanks.)
