### ISSUE TITLE
Washington Post not working

### ISSUE THREAD

**Issue by tliron** [iamadamdev/bypass-paywalls-chrome#873]
[It used to work!](https://www.washingtonpost.com/)

**Comment by llacb47** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/868#issuecomment-685137724

**Comment by tliron** [comment]
Thanks, the workaround filters there worked! But is that going to be merged into this plugin?

**Comment by iamadamdev** [comment]
Try latest master.
