### ISSUE TITLE
The Athletic not working

### ISSUE THREAD

**Issue by riker86** [iamadamdev/bypass-paywalls-chrome#875]
###
1. Make sure uBlock Origin is installed. - Yes it is
2. Bypass Paywalls version? - 1.7.5
3. Chrome or Firefox? - Chrome
4. Paste the article URL for the site you are having issues with.
https://theathletic.co.uk/2030794/2020/09/06/daniel-taylor-alexis-sanchez-manchester-united-training-piano/
Also any link on that site

5. Describe the issue.
Article still asks to signup for the subscription

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/859
