### ISSUE TITLE
Bypass for Washington Post not working

### ISSUE THREAD

**Issue by YeoBL** [iamadamdev/bypass-paywalls-chrome#876]
###
1. Make sure uBlock Origin is installed. (Yes)
2. Bypass Paywalls version? (1.7.5)
3. Chrome or Firefox? (Chrome)
4. Paste the article URL for the site you are having issues with. (https://www.washingtonpost.com/media/2020/09/05/jennifer-griffin-defended-by-fox-news-colleagues-after-trump-twitter-attack-over-her-confirmation-atlantic-reporting/)
5. Describe the issue. (Can't view article)

Requests not following these instructions will be ignored.
###

**Comment by iamadamdev** [comment]
Did you try latest master? That article loads for me.

**Comment by bengaywins** [comment]
The above linked article works for me too, but this one does not. 

https://www.washingtonpost.com/investigations/louis-dejoy-campaign-contributions/2020/09/06/1187bc2c-e3fe-11ea-8181-606e603bb1c4_story.html

**Comment by niclasmattsson** [comment]
Both links above work for me - at the moment. But I know that Jennifer Griffin article did not work for me yesterday. They seem to cycle paywall articles frequently and randomly, possibly to make it harder to bypass.  Here's one that's broken for me right now:
https://www.washingtonpost.com/opinions/2020/09/05/trumps-bad-marriage-with-military-has-finally-exploded/

**Comment by YeoBL** [comment]
I think @niclasmattsson is right that they cycle paywall articles... 
The link I posted and @bengaywins's works for me too but not @niclasmattsson's
In response to @iamadamdev, yes I am using the latest one

**Comment by niclasmattsson** [comment]
I dug a bit deeper. Paywalled articles load if you block this url in uBlock. Only problem is that images in that article remain super-blurry.
https://www.washingtonpost.com/_next/static/chunks/1f5fab072f3a949b74fa74a1935f354a27253440.59fd0a834fee704e0adc.module.js

**Comment by erickhavel** [comment]
> Only problem is that images in that article remain super-blurry.

Same happens if you have JS disabled.

**Comment by llacb47** [comment]
> > Only problem is that images in that article remain super-blurry.
> 
> Same happens if you have JS disabled.

Yes, it's called lazy-loading, it's not some nefarious plot to take your money.

**Comment by niclasmattsson** [comment]
> Yes, it's called lazy-loading, it's not some nefarious plot to take your money.

Sure, but to bundle the lazy-loading of images inside the same js-file that implements the paywall is almost certainly deliberate/nefarious.

**Comment by erickhavel** [comment]
> it's not some nefarious plot to take your money.

Never claimed it was. They could however use `<noscript>` for example to show regular non-lazyloaded images for non-JS visitors. But I suppose that's outside of their scope of giving fucks.
