### ISSUE TITLE
TheAthletic

### ISSUE THREAD

**Issue by rasoulmajidi** [iamadamdev/bypass-paywalls-chrome#878]
i have install u in firefox and cant read TheAthletic articles.
for example this url:
https://theathletic.co.uk/2004755/2020/09/07/manchester-united-season-preview-solskjaer-third/

**Comment by dobuziewicz** [comment]
already opened #859

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/859
