### ISSUE TITLE
Business Journals site

### ISSUE THREAD

**Issue by rlaymandc** [iamadamdev/bypass-paywalls-chrome#879]
doesn't seem to be working anymore.  Once the graphics load, the article no longer displays.

**Comment by iamadamdev** [comment]
article link?

**Comment by ODTisBACK** [comment]
https://www.bizjournals.com/nashville/news/2020/09/04/joey-jacobs-out-as-quorum-health-corp-ceo.html?iana=hpmvp_nsh_news_headline

**Comment by rlaymandc** [comment]
Wow, thanks for being so responsive.

This is one:

https://www.bizjournals.com/washington/news/2020/08/12/douglas-moves-to-kick-off-work-on-new-city-dc.html

I am not a programmer, but maybe it has something to do with graphics and
messages.  For example, with the Wall Street Journal, once an article
loads, a subscriber notice covers the "graphic" and the article doesn't
stops loading.  But when you close that graphic, by hitting "x" the article
loads.

e.g.,
https://www.wsj.com/articles/production-problems-prompt-broad-faa-review-of-boeing-dreamliner-lapses-11599498118?mod=hp_lead_pos1

That doesn't work with the Business Journals.  They don't give you a way to
hit "x" to get rid of that message.

Best wishes.

**Comment by llacb47** [comment]
add to ublock origin: `bizjournals.com##+js(set-constant, __page__.isPremium, false)`

**Comment by iamadamdev** [comment]
Still working for me:
![image](https://user-images.githubusercontent.com/36013816/92431845-635c7180-f14d-11ea-82f7-1658597fe85c.png)

**Comment by TimBardet** [comment]
I am seeing this problem on Firefox. For example: https://www.bizjournals.com/sacramento/news/2020/09/08/long-planned-west-sac-housing-projects-near-start.html

![image](https://user-images.githubusercontent.com/16932604/92666771-041e6e80-f2bf-11ea-9ad9-67db01e5ac2a.png)

**Comment by iamadamdev** [comment]
Firefox:
![image](https://user-images.githubusercontent.com/36013816/92668496-da1b7b00-f2c3-11ea-8a8b-830f21a6753a.png)
