### ISSUE TITLE
The Athletic is cannot be opened

### ISSUE THREAD

**Issue by apicahaya** [iamadamdev/bypass-paywalls-chrome#880]
###
1. Make sure uBlock Origin is installed.
2. Chrome or Firefox?
3. Paste the article URL for the site you are having issues with.
4. Describe the issue.
###
1. I have installed uBlock Origin
2. Chrome and Firefox
3. https://theathletic.com/
4. It still showing the bypass, it is a new issue I think, since a week ago I remain open it without this issue.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/859
