### ISSUE TITLE
The Athletic + The Athletic UK

### ISSUE THREAD

**Issue by Alim1236** [iamadamdev/bypass-paywalls-chrome#881]
###
1. Make sure uBlock Origin is installed.
2. Chrome or Firefox?
3. Paste the article URL for the site you are having issues with.
4. Describe the issue.
###

https://theathletic.co.uk/2007154/
- all articles on theathletic.com and theathletic.co.uk are paywalled
- Firefox
- still paywalled, asking to login and content is blocked
- uBlock Origin is installed, tried turning it off + reloading, etc
- disabled general paywall option

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/859
