### ISSUE TITLE
https://theathletic.com/2049395/2020/09/08/explained-left-foot-centre-back-ake-laporte/

### ISSUE THREAD

**Issue by Yupadej** [iamadamdev/bypass-paywalls-chrome#882]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/859
