### ISSUE TITLE
WSJ isn't working

### ISSUE THREAD

**Issue by themarketking** [iamadamdev/bypass-paywalls-chrome#883]
Paywall comes up. Also, can I suggest adding daily wire? Love the extension overall.

**Comment by themarketking** [comment]
https://www.wsj.com/articles/global-stock-markets-dow-update-09-09-2020-11599629144?mod=rsswn

Here's an article link

**Comment by braceletboy** [comment]
I am able to access the above link and it's contents.

**Comment by themarketking** [comment]
I've been using this for the past week and now it appears for me they have the paywall I can't X out of. I cant imagine anything is wrong with my other extensions.

![Screen Shot 2020-09-09 at 12 53 56 PM](https://user-images.githubusercontent.com/53065636/92635752-f99ead80-f29b-11ea-9038-7ca94e1c6e96.png)
![Screen Shot 2020-09-09 at 12 54 27 PM](https://user-images.githubusercontent.com/53065636/92635761-fc999e00-f29b-11ea-87c9-7b5a25754731.png)
![Screen Shot 2020-09-09 at 12 54 27 PM](https://user-images.githubusercontent.com/53065636/92635772-002d2500-f29c-11ea-8951-266b818ff912.png)

**Comment by Castle999** [comment]
Same issue here! Worth noting that Chrome is updated...

**Comment by Castle999** [comment]
For reference... 

![1](https://user-images.githubusercontent.com/59456656/92644741-a8d98580-f298-11ea-9aa7-3ad2f866f715.png)
![2](https://user-images.githubusercontent.com/59456656/92644744-a9721c00-f298-11ea-882c-1140e0d6c5d4.png)

**Comment by iamadamdev** [comment]
Updated to latest master:
![image](https://user-images.githubusercontent.com/36013816/92645305-81cf8380-f299-11ea-940e-95de277eb22d.png)

**Comment by Castle999** [comment]
Updated to v1.5.5
Error below for reference, thank you!

![1](https://user-images.githubusercontent.com/59456656/92645963-8f393d80-f29a-11ea-9092-7c5c9c4e9955.png)
![2](https://user-images.githubusercontent.com/59456656/92645966-8fd1d400-f29a-11ea-9ec9-c7428bdcaa94.png)
