### ISSUE TITLE
Bypass not working for Wall Street Journal

### ISSUE THREAD

**Issue by YeoBL** [iamadamdev/bypass-paywalls-chrome#885]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported. (Not yet reported)
2. Make sure uBlock Origin is installed. (Yes)
3. Chrome or Firefox? (Chrome)
4. Paste the article URL for the site you are having issues with. (https://www.wsj.com/articles/apple-countersues-fortnite-maker-epic-games-seeking-to-halt-in-app-payments-11599592017?mod=djemwhatsnews)
5. Describe the issue. (Website still asks me to sign in to read the article)
###

Edit: Thanks, it works for me now. I found that it didn't load because I had blocked cookies. Sorry for the trouble and thanks for your help.

**Comment by iamadamdev** [comment]
Should be redirecting to AMP version:
![image](https://user-images.githubusercontent.com/36013816/92694359-c855ca00-f2fb-11ea-8802-4d636d0d2d51.png)

**Comment by patfla** [comment]
Doesn't redirect (to AMP) for me.  FF 80.0.1 on win7.

**Comment by iamadamdev** [comment]
Article not redirecting to AMP anymore, FF 80.0.1:
![image](https://user-images.githubusercontent.com/36013816/92978297-3dccb200-f444-11ea-9e12-442901dfdd0f.png)
