### ISSUE TITLE
New site request: [Project Syndicate ( https://www.project-syndicate.org)]

### ISSUE THREAD

**Issue by Rwisegenya** [iamadamdev/bypass-paywalls-chrome#886]
### 
I tried to do all the steps described, but unfortunately, I didn't work. I'm asking if anyone has a better idea to help.

Project Syndicate is an international media organization that publishes and syndicates commentary and analysis on a variety of global topics.

**Comment by iamadamdev** [comment]
The premium articles seem to be behind a hard paywall.
