### ISSUE TITLE
Site not working: Washington Post shows pop up window

### ISSUE THREAD

**Issue by pavankjadda** [iamadamdev/bypass-paywalls-chrome#887]
Browser: Chrome and Microsoft Edge(new)
URL: Link to [page](https://www.washingtonpost.com/politics/bernie-sanders-expresses-concerns-about-biden-campaign/2020/09/12/a0ccc4fa-f4a1-11ea-b796-2dd09962649c_story.html)
Issue: When I open the URL in Chrome or Microsoft Edge, I see the following pop up.

<img width="1027" alt="Screen Shot 2020-09-13 at 12 23 55 AM" src="https://user-images.githubusercontent.com/17564080/93010214-f2a3c380-f557-11ea-8378-1984e5a08212.png">

**Comment by iamadamdev** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/36013816/93013187-f08f3400-f55a-11ea-97b3-9959fcbe1016.png)

**Comment by pjpreilly** [comment]
Selectively blocking some articles... Like **[THIS](https://www.washingtonpost.com/opinions/white-evangelicals-and-catholics-may-finally-be-opening-their-ears/2020/09/14/9c9d05f2-f6b3-11ea-a275-1a2c2d36e1f1_story.html)** one!

**Comment by fooeynet** [comment]
Yep, and [this](https://www.washingtonpost.com/opinions/i-cant-stand-trump-but-democrats-may-force-me-to-vote-for-him/2020/09/14/1cf10518-f6c4-11ea-a275-1a2c2d36e1f1_story.html).  Don't work in Private mode either.

**Comment by iamadamdev** [comment]
Unable to repro:
![image](https://user-images.githubusercontent.com/36013816/93163042-f99f1300-f6ca-11ea-9214-3efe1ad3e2ff.png)

**Comment by pjpreilly** [comment]
> Should work on latest master for Chrome.

Yep! thx

**Comment by ArizonaCowboy** [comment]
OK, here is something weird, Wapo hasn't worked for a week on Firefox, not even with the previous patch, however, I just deleted the Honey coupon applying add-on, which is in wide use, and now it seems to be working, so perhaps folks who are getting that subscribe pop-up should restart Firefox with add-ons disabled, as an add-on extension may be inadvertently crippling Bypass Firewalls

**Comment by pjpreilly** [comment]
@ArizonaCowboy Selectively blocking some articles... not other add-on extensions.

**Comment by billxsand** [comment]
I'm also having this problem, i disabled all my extensions but it didn't fix it

**Comment by pjpreilly** [comment]
Should work on latest master for Chrome.
Firefox will be fixed in the next release.

**Comment by pjpreilly** [comment]
.. on Chrome ..... reinstall from the code link...

**Comment by cocampbe** [comment]
I am getting the following error after updating.

> Access Denied
> You don't have permission to access "http://www.washingtonpost.com/lifestyle/2020/09/22/autistic-girl-spaghettios-every- . meal-food-shortage/" on this server.
> Reference #18.6d33ca17.1600817965.2381f45f

excuse the link. seemed like an interesting read.

**Comment by pjpreilly** [comment]
> I am getting the following error after updating.

Are you on Chrome/Chromium and did you reinstall not just check for updates? Firefox is not updated YET.

**Comment by slondr** [comment]
I hit a paywall on this page: https://www.washingtonpost.com/opinions/2020/09/22/vote-biden-is-vote-one-party-state/?itid=hp_opinions

**Comment by pulkitpatel95** [comment]
> I hit a paywall on this page: https://www.washingtonpost.com/opinions/2020/09/22/vote-biden-is-vote-one-party-state/?itid=hp_opinions

Works for me
![Screenshot 2020-09-23 121355](https://user-images.githubusercontent.com/59560083/93976227-4e5f1f80-fd96-11ea-863d-b62b53e5c10e.png)

**Comment by cocampbe** [comment]
> > I am getting the following error after updating.
> 
> Are you on Chrome/Chromium and did you reinstall not just check for updates? Firefox is not updated YET.
> 
> ... & your link is not formatted correctly....

I am running Chrome Version 85.0.4183.121. I removed the extension. Downloaded, unzipped, and dragged the folder to the chrome window. The link was a copy and paste. But I get it an any WP site.

If I disable BP I can get to the site, but am greeted with the paywall.

**Comment by iamadamdev** [comment]
Released v1.7.6, fixed in Firefox now.
