### ISSUE TITLE
New site request: www.globes.co.il

### ISSUE THREAD

**Issue by ohadcn** [iamadamdev/bypass-paywalls-chrome#888]
This has been reported few time before: (#620 by @electric3055 #760 by @RotterSoft, pull request [532](https://github.com/iamadamdev/bypass-paywalls-firefox/pull/532) on old firefox version) - but all of them where closed.

Few things to mention:
A. This site allows any user (even not registered one) to view 10 articles every month - so **there is not a single paywalled page**, to get to the paywall you need to open 10 different articles on the web site - and the 11th is going to be blocked for you.
B. To unblock - as I mentioned in my pull request - put the website in the "remove_cookies" list.
C. See the paywall in the attached image - the content just became blurred at the bottom (adblock blocks "register to view this page" section)

![image](https://user-images.githubusercontent.com/905635/93025135-263c2780-f604-11ea-9075-a0927dd59871.png)

**Comment by iamadamdev** [comment]
I just opened 12+ articles and didn't see a paywall. Do you have uBlock Origin installed?
If you scroll down and wait it eventually loads?
![image](https://user-images.githubusercontent.com/36013816/93025658-91f6a400-f5b4-11ea-9151-4ac99ab44ead.png)

**Comment by ohadcn** [comment]
A. i have uBlock installed (see attached screenshot)
B. scrolling down and waiting has no effect..
C. I tried using tor browser - and I never get blocked...
do they only block Israeli IP's? this is going to be much harder to investigate from your side

![image](https://user-images.githubusercontent.com/905635/93025961-02c8ab00-f60b-11ea-8dfc-e4eb5346f685.png)

**Comment by iamadamdev** [comment]
But your PR fixes this for you? If so I'll just go ahead and add it anyway.

**Comment by ohadcn** [comment]
This solved it for me.
I'll do it again and test it on the merged version when I have time, hopefully tomorrow.
