### ISSUE TITLE
New site request: [Apple Daily of HK and Caixin]

### ISSUE THREAD

**Issue by kchio0331** [iamadamdev/bypass-paywalls-chrome#891]
Hello,

Will you be able to make these two websites paywall free?

1. Apple Daily of HK at https://hk.appledaily.com. After I clicked on the second article https://hk.appledaily.com/local/20200915/IPF62GVOLJGPNATE2RKOL5BMIU/, the webpage asked me to pay. This is a widely read newspaper for those who follow Hong Kong's political development. Its leader has been accused of violating Hong Kong's national security law, and the U.S. has voiced support for the newspaper's leader and the newspaper. I think it has a wide international readership. 

2. Caixin at http://www.caixin.com/. It is a widely read financial magazine in China. You have already made its English version paywall free. Will you be able to make the Chinese version paywall free? I think it has a wide international readership, too. 

Thank you!

**Comment by iamadamdev** [comment]
Try testing them out in the custom sites on the Chrome version of Bypass Paywalls:
![image](https://user-images.githubusercontent.com/36013816/93171052-3bd15000-f6dd-11ea-9d8f-d40f340ab704.png)
