### ISSUE TITLE
Site not working: Scientific American

### ISSUE THREAD

**Issue by MrAureliusR** [iamadamdev/bypass-paywalls-chrome#894]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
I checked both closed and open issues since the last release.
2. Make sure uBlock Origin is installed.
It is. Tried reloading with it disabled, no change.
3. Chrome or Firefox?
Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)
4. Paste the article URL for the site you are having issues with.
https://www.scientificamerican.com/article/seeing-forbidden-colors/
5. Describe the issue.
Article gets cut off in the first paragraph with the options to subscribe. I tried both the release 1.7.5 (which is what I had installed when I came across this article) and then I also tried the current master branch. Same result - article is paywalled.
###

**Comment by MrAureliusR** [comment]
Ah, it looks like this was reported quite a long time ago and it's apparently a hardcoded paywall. That sucks. Why is Scientific American in the list of supported websites then? Anyway, closing so I don't waste the dev's time.

**Comment by iamadamdev** [comment]
It's on the list because free articles (but limited with soft paywall) still work, e.g.: https://www.scientificamerican.com/article/life-on-venus-breakthrough-initiatives-funds-study-of-possible-biosignature/
