### ISSUE TITLE
New site request: [ET Prime ,Business Standard Premium articles]

### ISSUE THREAD

**Issue by Rajarsee** [iamadamdev/bypass-paywalls-chrome#897]
Hello please see if you can help out in these two cases
1.ET Prime
2.Business Standard Premium articles
Incase of Business standard the articles appearing with a key on left are the ones that require pay system and are not opening. for example this one
https://www.business-standard.com/article/current-affairs/mobile-firms-stare-at-gloomy-festive-season-amid-covid-led-disruption-120091602225_1.html?utm_source=Spotlight&utm_medium=website&utm_campaign=Premium_11072018

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
