### ISSUE TITLE
Globe And Mail not working

### ISSUE THREAD

**Issue by senormingus** [iamadamdev/bypass-paywalls-chrome#898]
Hey there,
Any article with a key is no longer accessible.
uBlock is installed. Firefox.
URL: https://www.theglobeandmail.com/opinion/article-the-enduring-unpopularity-of-jason-kenney/?ref=premium
Warming come up saying I must be a subscriber. New as of the last few days.
Thanks

**Comment by bpither** [comment]
Same here with the Globe and Mail on Chrome

**Comment by janvier25** [comment]
Me three.

**Comment by tahanzania** [comment]
I was under the assumption that G&M uses similar base tech as WaPo(I think they license it from them). No Issue on WaPo but issues on G&M

**Comment by jacquesbedard** [comment]
Same here, any article with a key icon.

**Comment by jacquesbedard** [comment]
![Fullscreen capture 2020-09-21 14256 PM](https://user-images.githubusercontent.com/68446201/93801824-9c4a1b00-fc10-11ea-928b-5657693f72ee.jpg)
