### ISSUE TITLE
Bloomberg US version isn't working

### ISSUE THREAD

**Issue by DrKita** [iamadamdev/bypass-paywalls-chrome#907]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

Thankyou for your addon! I'm using MS Edge Chromium, and I'm using bloomberg. I'm accessing at South Korea, and when your addon is turned on, I can't go to bloomberg US version. Only redirecting to bloomberg asia. But bloomberg europe, africa, and japan is working. I'm wondering why this bug is occur, and if you solve this bug, I'll be pleased! thankyou!

**Comment by bdhood** [comment]
I was able to reproduce this on chrome using a VPN. Something about the site runs differently when you access the site from south korea

Recording: [https://ibb.co/fnrGXpH](https://ibb.co/fnrGXpH)

Easiest solution should be using a US vpn

**Comment by iamadamdev** [comment]
Works on U.S. VPN.
