### ISSUE TITLE
Boston Globe

### ISSUE THREAD

**Issue by rlaymandc** [iamadamdev/bypass-paywalls-chrome#910]
Chrome:
https://www.bostonglobe.com/2020/09/24/business/with-andrea-campbell-running-mayor-who-should-worry-more-michelle-wu-or-marty-walsh/?s_campaign=breakingnews:newsletter

https://www.bostonglobe.com/2020/09/24/metro/boston-city-councilor-andrea-campbell-announces-run-mayor/?s_campaign=breakingnews:newsletter

When you click on a URL the article returns the headline and photo but no text.

If I enter the URL (with the text removed from the ? after) into www.printfriendly.com, the article is readable.

**Comment by iamadamdev** [comment]
Boston Globe is not on the list of sites?

**Comment by rlaymandc** [comment]
It's listed under "The Boston Globe."

**Comment by iamadamdev** [comment]
Where? You must be on an older version, it was removed months ago.
