### ISSUE TITLE
Your file couldn’t be accessed

### ISSUE THREAD

**Issue by maxkozlov1** [iamadamdev/bypass-paywalls-chrome#911]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

Getting a "Your file couldn’t be accessed" error when I press on the extension.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#installation-instructions
