### ISSUE TITLE
not bypassing paywall on The Washington Post 

### ISSUE THREAD

**Issue by abramjanzie** [iamadamdev/bypass-paywalls-chrome#912]
After following all instructions, including desabling ublock origin and refreashing, the add-on is still not bypassing the paywall on washington post

~ firefox 81.0 (64-bit), Mac os 10.14.6

**Comment by iamadamdev** [comment]
Which article?

**Comment by abramjanzie** [comment]
the issue was with [this article](https://www.washingtonpost.com/opinions/2020/09/25/this-is-not-drill-reichstag-is-burning/?utm_campaign=wp_follow_dana_milbank&utm_medium=email&utm_source=newsletter&wpisrc=nl_danamilbank)

it has been resolved. Thank you
