### ISSUE TITLE
Please Add Globe & Mail

### ISSUE THREAD

**Issue by A1MB1G** [iamadamdev/bypass-paywalls-chrome#918]
Any chance of adding "The Globe & Mail"? Link is https://www.theglobeandmail.com

Thanks!

**Comment by iamadamdev** [comment]
It's already added, which article are you having trouble with? I just need to update the list of sites supported.

**Comment by A1MB1G** [comment]
> It's already been added, which article are you having trouble with?

Seems to be working now... A few minutes ago I had tried an article and it didn't work so I thought the site wasn't on the list but turns out it is. Working well now. Thanks!
