### ISSUE TITLE
New site request: [editorialedomani.it]

### ISSUE THREAD

**Issue by elax46** [iamadamdev/bypass-paywalls-chrome#920]
I have performed the procedure for inserting a new site but a strange phenomenon occurs. Opening the article, with an incognito window with activated Cookie Remover and uBlock Origin extensions, the whole article is displayed for a few moments and then disappears behind the paywall. The same phenomenon occurs with both firefox and chrome.

**Comment by iamadamdev** [comment]
You added it to Custom Sites?

**Comment by elax46** [comment]
Of course, but there are no changes, but I do not think it is a non-perforable paywall as the full text of the article, even if for a few seconds, appears.

**Comment by ftruzzi** [comment]
Ciao @elax46, you also needed to disable paywall-related scripts. Take a look at my PR to see how

**Comment by elax46** [comment]
Quite right!
