### ISSUE TITLE
Globe and Mail not working for 1.7.6.

### ISSUE THREAD

**Issue by bpither** [iamadamdev/bypass-paywalls-chrome#923]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by iamadamdev** [comment]
article?

**Comment by bpither** [comment]
https://www.theglobeandmail.com/opinion/article-bc-liberals-pst-gambit-is-an-election-hail-mary/

**Comment by bpither** [comment]
can't open this one and several other articles ...

**Comment by iamadamdev** [comment]
Working for me:
![image](https://user-images.githubusercontent.com/36013816/94639475-19b8ff80-0291-11eb-9506-71ea0f612a9b.png)

What version are you on?

**Comment by bpither** [comment]
As in what version of Chrome? Version 85.0.4183.121 (Official Build) (64-bit)
Using bypass paywall 1.7.6 for this Chrome version.

Still doesn't work.

**Comment by bpither** [comment]
Got it to work ... figured if _you_ can open it why can't I? So I deleted the file and cookies on Chrome and reinstalled bypass paywall 1.7.6
