### ISSUE TITLE
I have conceded defeat to Washington Post developers

### ISSUE THREAD

**Issue by ArizonaCowboy** [iamadamdev/bypass-paywalls-chrome#925]
I have conceded defeat to Washington Post developers, they are just too skilled - Bypass Paywalls cannot seem to hold them off for even one or two days on Firefox, even after new version after new version, including the latest 1.76, so taking their $29/year introductory subscription offer - I surrender!! 🤣

However, Bypass Paywalls is continuing to do a fantastic job on countless other publications I read - thanks Adam - you are incredibly talented!

**Comment by iamadamdev** [comment]
Still works fine for me. Try a U.S. VPN?
