### ISSUE TITLE
The Times doesn't work anymore

### ISSUE THREAD

**Issue by atmazzerexe** [iamadamdev/bypass-paywalls-chrome#930]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###
1. Yes
2. Already installed
3. Both
4. https://www.thetimes.co.uk/edition/news/academics-face-flying-restrictions-as-cambridge-heads-for-carbon-neutral-future-nwvfxsr6d
5. Looks like The Times has enforced hard paywall now, no more free read allowed. I am currently using the latest version (1.7.6).

**Comment by iamadamdev** [comment]
I can still read it:
![image](https://user-images.githubusercontent.com/36013816/94843999-6821e780-03d2-11eb-81b0-c79cb1722584.png)

**Comment by atmazzerexe** [comment]
Ah, turns out I have to reinstall it. My bad.
