### ISSUE TITLE
New site request: [sitehttps://www.sportbusiness.com/news/levis-stadium-to-go-fully-cashless-with-49ers-visa-partnership-extension/?registered_metered=1]

### ISSUE THREAD

**Issue by meganinj4** [iamadamdev/bypass-paywalls-chrome#935]
### New site requests - Before submitting an issue please read the following:

Only large or major sites will be considered. Usually premium articles cannot be bypassed as they are behind a hard paywall.

Comfirmed (may need some login config tho, but i maneged to get it with free login, only needs a way to stop the news count to reach 0)

**Comment by iamadamdev** [comment]
This might be a hard paywall w/o login.
