### ISSUE TITLE
Request for new paywalls

### ISSUE THREAD

**Issue by Decopi** [iamadamdev/bypass-paywalls-chrome#937]
Hi!

Firstly, thanks for your great add-on.
Excellent work! Congrats.

I'm a Firefox' user.
Please, if possible, I would like to request you 3 paywalls to bypass:

https://mais.oantagonista.com/#/brasil/renan-calheiros-aplaude-bolsonaro-por-desmonte-da-lava-jato/?subcategoria=

https://crusoe.com.br/diario/pf-quer-informacoes-sobre-cpmi-das-fake-news/

https://valor.globo.com/financas/noticia/2020/10/06/eua-enfrentam-riscos-tragicos-se-fizerem-pouco-para-apoiar-economia-diz-powell.ghtml

Thank you in advance!

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
