### ISSUE TITLE
nzherald.co.nz stopped working

### ISSUE THREAD

**Issue by hexitnz** [iamadamdev/bypass-paywalls-chrome#938]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported. - None found.
2. Make sure uBlock Origin is installed. - Yes.
3. Chrome or Firefox? - Chrome
4. Paste the article URL for the site you are having issues with.
https://www.nzherald.co.nz/business/continuous-disclosure-death-of-the-cinema-the-surprise-in-store-for-fletcher-shareholders-and-the-shortest-directorship/XFGQ36QLW7ZXBOUDGUAFVPKQ6Q/
5. Describe the issue.
Bypass firewall has been working fine on nzherald.co.nz until today 9th Oct when it no longer bypasses the paywall.  Tested on W10 Chromium 86.0.4240.0 and Android 10 Kiwibrowser.  Both were working previously until yesterday.

If you could have a look it would be much apprciated.

**Comment by zacwebb** [comment]
Yeah The Herald released some layout updates today as well so probably happened at the same time

**Comment by alastairR** [comment]
Pull request has been created to fix.

**Comment by hexitnz** [comment]
Many thanks Alastair.

**Comment by DetexianAdrian** [comment]
Just merged your fix into my local copy @alastairR. Works perfectly. Thanks!

**Comment by iamadamdev** [comment]
Fixed thanks to @alastairR !

**Comment by Buckchoi** [comment]
@alastairR With your fix applied the navigation menu on the left side of the website does not open, and videos cannot be played.
Is there anyway around this? Thank you.

**Comment by Buckchoi** [comment]
@alastairR With your fix applied the navigation menu on the left side of the website does not open, and videos cannot be played.
Is there any way around this issue? Thank you.

**Comment by alastairR** [comment]
Sorry, not yet. It means unpicking individual functions within the default.js code that is blocked. It is probably possible, but may take some time.
