### ISSUE TITLE
Uncaught TypeError - Chrome v86 - washingtonpost.com

### ISSUE THREAD

**Issue by jmg999** [iamadamdev/bypass-paywalls-chrome#942]
I'm receiving an Uncaught TypeError for Bypass Paywalls v1.7.6 for which I've attached an image of the context and the stack trace.  I'm running Chrome v86.0.4240.75 (Official Build) (64-bit) in concert w/ uBlock Origin v1.30.2 on a Windows 10 Home v2004 laptop.  The URL I'm having issues w/ is as follows: 

https://www.washingtonpost.com/national-security/michigan-governor-kidnap-plot/2020/10/08/0032e206-0980-11eb-9be6-cf25fb429f1a_story.html

When I access the URL, I'm met w/ the subscription request pop-up, which effectively blocks all content on the page.

![Paywall Error](https://user-images.githubusercontent.com/33406288/95548721-897a6900-09ba-11eb-91a1-946809cba5dc.png)

**Comment by iamadamdev** [comment]
Try latest master

**Comment by jmg999** [comment]
I am using the latest available version, v1.7.6.  Is this not the master
version?  Is there another version I should be aware of?  Thank you.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#installation-instructions
The version doesn't go up with every single commit, so while you may be on v1.7.6, that isn't necessarily latest master.

**Comment by jmg999** [comment]
I see what you're saying now.  I didn't realize that the version number
sometimes didn't iterate.  I just tried reinstalling the latest commit
again, and it seems to have resolved the issue.  Thank you.
