### ISSUE TITLE
WSJ - Internal server Error 

### ISSUE THREAD

**Issue by achutammurarka** [iamadamdev/bypass-paywalls-chrome#947]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported. => Do not see this issue
2. Make sure uBlock Origin is installed. => Yes
3. Chrome or Firefox? => Chrome on a Mac Catalina 10/15.7
4. Paste the article URL for the site you are having issues with.
5. Describe the issue. => Can't open WSJ. Says Internal Server Error
###

Here is the log file getting generated:

Unchecked runtime.lastError: No tab with id: 746.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)
Nothing to see here, move along.

**Comment by achutammurarka** [comment]
still seeing the error.. how do i resolve this at my end?

**Comment by iamadamdev** [comment]
Works fine for me. Maybe try disabling all other extensions. Test in incognito mode?
