### ISSUE TITLE
New site request: https://theathletic.com/

### ISSUE THREAD

**Issue by kkjcheng** [iamadamdev/bypass-paywalls-chrome#948]
### New site requests - Before submitting an issue please read the following:

Only large or major sites will be considered. Usually premium articles cannot be bypassed as they are behind a hard paywall.

1. Install the uBlock Origin extension if it hasn't been installed already. See if you are still getting a paywall.
2. Check if using Cookie Remover can bypass the paywall. If not, continue to the next step.
3. First search 'Issues' to see if the site has been requested already.
4. Visit an article on the site you want to bypass the paywall for and copy the article title.
5. Open up a new incognito window (Ctrl+Shift+N on Chrome) or Private window (Ctrl+Shift+P on Firefox), and paste the article title into Google.
6. Click on the same article from the Google search results page.
7. If it loads without a paywall replace this entire template text with the word "Confirmed" and submit the request. Otherwise please do not submit an issue as this extension cannot bypass it either.

**Comment by iamadamdev** [comment]
Site was removed.

**Comment by kkjcheng** [comment]
Sorry, not sure what you mean by the site being removed. I am still able to visit the site and it is blocked without a subscription. Let me know what other information you may need.

**Comment by iamadamdev** [comment]
It was removed because it's behind a hard paywall now.
