### ISSUE TITLE
Premium articles on New Zealand Herald no longer works. 

### ISSUE THREAD

**Issue by thisistony** [iamadamdev/bypass-paywalls-chrome#950]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

Premium articles on New Zealand Herald no longer works. 

https://www.nzherald.co.nz/nz/election-2020-audrey-young-the-awkward-problem-labour-could-have-over-deputy-prime-minister/VK5USKZAGUPFAGPOT2YMPC6GGU/

![image](https://user-images.githubusercontent.com/11093702/95695546-ec5a5180-0c93-11eb-9b8b-f3e0a3aa8cbf.png)

**Comment by iamadamdev** [comment]
Fixed in latest master

**Comment by thisistony** [comment]
Can confirm that it's fixed in the latest master. 

Thanks again.
