### ISSUE TITLE
Medium : Impossible to connect with extension on

### ISSUE THREAD

**Issue by AmauryFaure** [iamadamdev/bypass-paywalls-chrome#952]
Hi, 

I'm having troubles getting inside medium with the extension. 
This is on both Firefox (with ublock) and Brave (chromium browser, also with ublock). 
I can not connect to this webiste  : https://medium.com/

However it seems that once logged in, if you acess a blog article that you can not read, reloading works to see the content. 
But going back to you homepage will redirect you to the default homepage with the sign in option. 

Hope this is clear, 

Thanks in advance.

**Comment by iamadamdev** [comment]
Uncheck medium if you want to sign in
