### ISSUE TITLE
Website now showing paywall.

### ISSUE THREAD

**Issue by rileypriddle** [iamadamdev/bypass-paywalls-chrome#953]
###
1. nope
2. Yes
3. Chrome andFirefox
4. https://www[.]nzherald[.]co[.]nz/business/on-facebook-misinformation-is-more-popular-now-than-in-2016/2MPEXD2YSMD553SJOISXCZZ5VI/
5. All premium articles on nzherald[.]co[.]nz are now showing the paywall on both chrome and firefox. May need to be removed from the list of websites
###

**Comment by 36wish** [comment]
Download the newest version.

**Comment by 36wish** [comment]
Duplicate of #938 
Please search next time.

**Comment by iamadamdev** [comment]
Works for me, try latest master for Chrome:
![image](https://user-images.githubusercontent.com/36013816/95804815-9e0b7980-0cb8-11eb-89bb-018c3ba93784.png)
