### ISSUE TITLE
Certain page of smh.com.au not working

### ISSUE THREAD

**Issue by realtable** [iamadamdev/bypass-paywalls-chrome#956]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
Done
2. Make sure uBlock Origin is installed.
Done
3. Chrome or Firefox?
Firefox
4. Paste the article URL for the site you are having issues with.
https://www.smh.com.au/todays-newspaper
5. Describe the issue.
Other pages work fine, but subscription paywall still pops up here
###

**Comment by iamadamdev** [comment]
That section is behind a hard paywall.
