### ISSUE TITLE
The Athletic UK not working

### ISSUE THREAD

**Issue by devanshbhinde** [iamadamdev/bypass-paywalls-chrome#958]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported. - Searched
2. Make sure uBlock Origin is installed. Yes
3. Chrome or Firefox? Chrome/Edge
4. Paste the article URL for the site you are having issues with. https://theathletic.co.uk/2132829/2020/10/13/project-big-picture-premier-league-efl/
5. Describe the issue. Does not bypass the paywalls anymore
###

**Comment by iamadamdev** [comment]
Not a supported site anymore.
