### ISSUE TITLE
Washington Post bypass has stopped working

### ISSUE THREAD

**Issue by seagoon51** [iamadamdev/bypass-paywalls-chrome#959]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

In recent weeks, the bypass for Washington Post has gone from working, to working sporadically, to not working at all on Firefox (latest version). uBlock Origin is installed and running. General Paywall Bypass is unchecked, WP is checked. Deleting cookies has no effect.

Here's a URL for a sample article: https://www.washingtonpost.com/politics/north-carolina-ballot-errors/2020/10/12/cd7bd50a-0981-11eb-a166-dc429b380d10_story.html.

Using the procedure under New Site Requests, I can read the article without the paywall. 

Thanks for your help.

**Comment by iamadamdev** [comment]
Still working for me:
![image](https://user-images.githubusercontent.com/36013816/95919010-ad92cd00-0d61-11eb-97b5-f206f86f3f88.png)

**Comment by seagoon51** [comment]
Is this on Firefox? I haven't tried Chrome.
Best,Peter

    On Tuesday, October 13, 2020, 5:38:14 PM EDT, Adam <notifications@github.com> wrote:  
 
 


Still working for me:

**Comment by seagoon51** [comment]
I've just installed in Chrome and it works fine there. In Firefox, it shows a truncated page, pops up a subscribe dialog, and changes the URL.
Best,Peter

    On Tuesday, October 13, 2020, 5:38:14 PM EDT, Adam <notifications@github.com> wrote:  
 
 


Still working for me:

**Comment by iamadamdev** [comment]
Where are you located?
In FF it's still working for me:
![image](https://user-images.githubusercontent.com/36013816/95939031-08431d80-0d90-11eb-9341-6f0b3ccc87ef.png)

**Comment by seagoon51** [comment]
North Carolina. Using an HP laptop, Windows 10 Home. No addons but BP, Cookie Remover and uBlock. No malware that I could find. I thought the Post had updated their paywall, but apparently not.
Best,Peter

    On Tuesday, October 13, 2020, 11:10:00 PM EDT, Adam <notifications@github.com> wrote:  
 
 


Where are you located?
In FF it's still working for me:

**Comment by technoweenie1** [comment]
I am also seeing this issue. Followed 5 troubleshooting steps.
1) Searched and followed all closed posts advice on issue - no luck
2) uBlock Origin is installed.
3) Both Chrome and Firefox. Both updated to latest.
4) URL: https://www.washingtonpost.com/opinions/2020/10/15/these-states-tell-us-gop-is-deep-trouble/ but many others fail. 
5) Latest master installed. WP was working well but stopped blocking paywall about 3 days ago. Issue on both FF and Chrome. Tried uBlock on and off. Tried disabling generic paywall filtering. Tried various combos of disabling other extensions I have; Adblock Plus, Privacy Badger. Tried disabling all then clearing cache and using only firewall bypass and ublock. All combinations no luck. I notice that the article's text is truncated just before the buy subscription popup appears.

Bryan.

**Comment by TheMegamind** [comment]
I've had this issues for several days now on FF. I followed essentially the same process as Bryan with no joy.  Located in California.

**Comment by randokam** [comment]
I'm also having this problem in Firefox 81.02, Windows 10.
uBlock Origin Installed
tried Cookie Remover

Installed Chrome (86.0.4240.75) and that version has been working for me.

San Jose, CA

**Comment by marksabbatini** [comment]
Also having this problem on Chrome with a Mac. Just adding to the total "count" of folks experiencing it.

**Comment by waynezo** [comment]
I am having the same problem with Chrome 86 and Firefox.  I tried troubleshooting to no avail.

**Comment by vic958420** [comment]
No issues here in Chicago

**Comment by Phane7** [comment]
I'm having issues as well.  Seems like all articles are popping up with a subscription requirement after about 5 seconds of being loaded

**Comment by llacb47** [comment]
Try adding these filters to ublock origin
```
||washingtonpost.com^*/pwapi-$script
||washingtonpost.com/subscribe/paywall/
||washingtonpost.com/subscribe/pw/
||washingtonpost.com/wp-stat/pb/prod/pmbl.txt
||washingtonpost.com/subscribe/logging/
```

**Comment by Phane7** [comment]
> 
> 
> Try adding these filters to ublock origin
> 
> ```
> ||washingtonpost.com^*/pwapi-$script
> ||washingtonpost.com/subscribe/paywall/
> ||washingtonpost.com/subscribe/pw/
> ||washingtonpost.com/wp-stat/pb/prod/pmbl.txt
> ||washingtonpost.com/subscribe/logging/
> ```

That seems to have resolved the issue for me.

**Comment by randokam** [comment]
> 
> 
> Try adding these filters to ublock origin
> 
> ```
> ||washingtonpost.com^*/pwapi-$script
> ||washingtonpost.com/subscribe/paywall/
> ||washingtonpost.com/subscribe/pw/
> ||washingtonpost.com/wp-stat/pb/prod/pmbl.txt
> ||washingtonpost.com/subscribe/logging/
> ```

This worked perfectly. Thank you for sharing it!

**Comment by seagoon51** [comment]
This has worked for me as well -- many thanks.

    On Friday, October 16, 2020, 12:03:20 PM EDT, LE <notifications@github.com> wrote:  
 
 


Try adding these filters to ublock origin
||washingtonpost.com^*/pwapi-$script
||washingtonpost.com/subscribe/paywall/
||washingtonpost.com/subscribe/pw/
||washingtonpost.com/wp-stat/pb/prod/pmbl.txt
||washingtonpost.com/subscribe/logging/
