### ISSUE TITLE
wall st. journal not working

### ISSUE THREAD

**Issue by firestorm31** [iamadamdev/bypass-paywalls-chrome#966]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###
I use firefox.  I don't have ublock origin installed.
tried getting a wall street article.  
https://www.wsj.com/articles/an-american-coup-attempt-11602181261
I got "internal server error" message.

**Comment by vic958420** [comment]
Visit [https://bgp.he.net/](url) and reply with the number after AS. 

The "internal server error" message basically means your IP or AS (Autonomous System) is blocked by WSJ.
