### ISSUE TITLE
New site request: ETPrime economictimes.indiatimes.com/

### ISSUE THREAD

**Issue by cbhat5** [iamadamdev/bypass-paywalls-chrome#967]
https://economictimes.indiatimes.com/mf/analysis/pharma-funds-offering-70-returns-should-you-invest/articleshow/78673737.cms

Can't bypass with either method or the extension.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
