### ISSUE TITLE
WaPo on Chrome

### ISSUE THREAD

**Issue by dentaljosh** [iamadamdev/bypass-paywalls-chrome#969]
Hi, I tried all troubleshooting and still having trouble.

Washington Post on Chrome

link: https://www.washingtonpost.com/politics/2020/10/20/poll-north-carolina-presidential-race/

overlay telling me to subscribe, doesn't let me read the article. thanks!

###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

**Comment by patfla** [comment]
That link works for me in the latest Chrome on Win 7.  Bypass 1.7.6 with uBlock installed.

**Comment by iamadamdev** [comment]
Still works for me

**Comment by dentaljosh** [comment]
it works if you havent hit the limit of articles
