### ISSUE TITLE
The Times doesn't work (again)

### ISSUE THREAD

**Issue by BellmannRichard** [iamadamdev/bypass-paywalls-chrome#970]
###
1. I searched the [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) and found this one https://github.com/iamadamdev/bypass-paywalls-chrome/issues/930 which has been closed. The problem persists, however.
2. uBlock Origin is installed.
3. Browser: Chrome. Version of Bypass Paywalls: 1.7.6
4. https://www.thetimes.co.uk/article/cambridge-academics-face-flying-restrictions-as-university-goes-carbon-neutral-nwvfxsr6d
5. I cannot access the website without a subscription.
###

**Comment by iamadamdev** [comment]
Still working for me:
![Uploading image.png…]()

**Comment by BellmannRichard** [comment]
Working for me too, today. Weird!
