### ISSUE TITLE
New site request: https://www.thecut.com/

### ISSUE THREAD

**Issue by jcosentino** [iamadamdev/bypass-paywalls-chrome#972]
The site will give you an article limit per month. I opened articles in a private window and the articles come up then.
Example:
https://www.thecut.com/2020/10/amy-coney-barrett-affordable-care-act-aca.html

**Comment by CalvinWu4** [comment]
Added in [PR#963](https://github.com/iamadamdev/bypass-paywalls-chrome/pull/963)
