### ISSUE TITLE
NyTimes.com blocking content

### ISSUE THREAD

**Issue by rpodric** [iamadamdev/bypass-paywalls-chrome#973]
This is a new issue as of the last several days. It's not every article, but a fair number of them, depending on the type of content. The version of Bypass hasn't changed in that time and is the latest.

Chrome or Firefox. In the case of Chrome, you'll see a grey block with a "refused to connect" message if you hover over it. In Firefox, it'll say "Can’t Open This Page" in the block.

Example URL: `https://www.nytimes.com/2020/10/20/technology/google-antitrust.html`

In that particular article, you'll see the issue right after the the 5th paragraph, but the issue varies by article. It's always obvious when it's present though due to the big blocks of missing content.

Thanks, and love the extension!

**Comment by iamadamdev** [comment]
Even w/o my extension and with uBlock Origin disabled that section doesn't load for me:
![image](https://user-images.githubusercontent.com/36013816/96665113-04237c80-1309-11eb-8497-766f7b527dc1.png)

**Comment by rpodric** [comment]
Try Ctrl+Shift+R, because otherwise it's cached.

I should note that unchecking NYT in Options doesn't help for some reason (not that that would be a good solution). The extension needs to be disabled.

**Comment by CalvinWu4** [comment]
![image](https://user-images.githubusercontent.com/26044296/96669850-12cf5b00-132c-11eb-9851-c4b22223c8c8.png)
This is the error message
This could be solved by making a request to the iframe's src and adding that html response in the place of the iframe

**Comment by CalvinWu4** [comment]
[Made a PR](https://github.com/iamadamdev/bypass-paywalls-chrome/pull/981)
