### ISSUE TITLE
ScientificAmerican not working

### ISSUE THREAD

**Issue by patfla** [iamadamdev/bypass-paywalls-chrome#976]
https://www.scientificamerican.com/article/everything-scientists-know-so-far-about-the-first-interstellar-objects-ever-detected/

The link works in neither FF 81.0.2 nor Chrome 85.0.4183.121 on Win 7.  Bypass 1.7.6.  uBlock Origin installed.

**Comment by iamadamdev** [comment]
That article is behind a hard paywall. This extension only works for free (but limited count) articles.
