### ISSUE TITLE
New York Times message "Something went wrong. Please try again later."

### ISSUE THREAD

**Issue by paravantis** [iamadamdev/bypass-paywalls-chrome#977]
In Google **Chrome version 86.0.4240.111 (Official Build) (64-bit)** in Windows 10, I upgraded Bypass Paywals from version 1.7.0 (which I had kept to be able to access Boston Globe) to version 1.7.6.

Now I get a brief "Something went wrong. Please try again later" message every time I access **New York Times** at https://www.nytimes.com/

_EDIT: The page is loading, I just get the previous annoying message._

I tried deleting all Chrome data, uninstalling and reinstalling, to no avail. The newly installed Chrome has the same behavior.

Some part messages make references to this problem. Is there anything I can do or just wait for a newer release?

**Comment by iamadamdev** [comment]
Main page still loading for me.
