### ISSUE TITLE
nzherald.co.nz not working

### ISSUE THREAD

**Issue by leemarrett** [iamadamdev/bypass-paywalls-chrome#978]
###
3. Chrome or Firefox? **Firefox 82.0**

4. Paste the article URL for the site you are having issues with.
https://www.nzherald.co.nz/business/300m-data-centres-for-hobsonville-silverdale/UFT5ON7Q63QLTOCPBDTQY4DD2Y/

5. Describe the issue.
Article shows title, image, first one or two sentences then hides rest of content under paywall block

###

**Comment by iamadamdev** [comment]
It's fixed in latest master for Chrome. You can wait for the next FF release or build the FF version yourself if you have a linux environment setup.

**Comment by sjclark** [comment]
@iamadamdev I'm on the latest release for chrome (1.7.6?) which doesn't seem to have the update?

![Screen Shot 2020-10-22 at 4 03 35 PM](https://user-images.githubusercontent.com/4531017/96826955-3c999680-1480-11eb-8ec1-61e799be2bdf.png)

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/96831574-2c3ada80-13f2-11eb-9199-ebc03ebdd03d.png)

**Comment by sjclark** [comment]
> Latest master is not necessarily the latest "release".

Cools, I can't get it to build successfully so guess I'll just wait for release 👍
