### ISSUE TITLE
Repubblica.it paywall changed

### ISSUE THREAD

**Issue by nanny07** [iamadamdev/bypass-paywalls-chrome#98]
The actual bypass method is not working, I suggest to change the script to delete the attribute `subscriptions-section="content"` on the `div.paywall`

**Comment by iamadamdev** [comment]
Please submit a PR for the fix.

**Comment by nanny07** [comment]
I haven't done yet because the images from the original article will not show: it could be needed some more code but actually I haven't figured out.
Maybe @sub could help us

**Comment by sub** [comment]
They changed something a few days ago, I'm gonna check and provide a fix.
