### ISSUE TITLE
Washington Post not working

### ISSUE THREAD

**Issue by Vanessa6162** [iamadamdev/bypass-paywalls-chrome#980]
Hi, 

I am using the extension on Firefox and I can still see the pay wall up on washington post. Can you please check?

Thanks!

**Comment by whoiscoos** [comment]
same issue here. firefox v82.0 running macOS

**Comment by iamadamdev** [comment]
url?

**Comment by hhwong** [comment]
Try this one: 

https://www.washingtonpost.com/lifestyle/wellness/mouthwash-inactivate-covid-study/2020/10/22/1735cdd4-13c5-11eb-bc10-40b25382f1be_story.html

**Comment by iamadamdev** [comment]
![image](https://user-images.githubusercontent.com/36013816/97040446-c9952c00-1522-11eb-88be-765519a5bde1.png)

**Comment by FWSquatch** [comment]
I am getting the same result as Vanessa6162. 
![wapo](https://user-images.githubusercontent.com/150116/97083833-86959000-15d8-11eb-85e4-59e7bf2c1695.png)

**Comment by Ventuz** [comment]
Can confirm, 1.7.6. Getting paywall'd by Washington Post.

**Comment by diehard88** [comment]
@hhwong working fine here.  My browser is Fennec 68.12.0.
