### ISSUE TITLE
Extension conflict with ABS

### ISSUE THREAD

**Issue by ShintoPlasm** [iamadamdev/bypass-paywalls-chrome#982]
Hello.

I have reported an extension conflict with ABS at the other dev's page: https://github.com/mikeyaworski/ABS/issues/29

In brief:

I've noticed that Bypass Paywall conflicts with the spoofing option of the ABS extension in Opera (but not in EdgeC, Chrome, Brave or Vivaldi): the spoofing mode doesn't work when Bypass Paywall is installed and enabled in Opera.

When running automated searches on Bing, while the search rewards do tally up as expected, the Edge-specific tally remains on zero for both the 'desktop' and 'mobile device' categories. This only happens when the Bypass Paywall extension is enabled in Opera (irrespective of which paywalled websites are enabled/disabled).

I'm using Opera Stable 72.0.3815.148 on Windows 10 x64. I have eliminated all other extension conflicts; only ABS and Bypass Paywall appear to conflict in Opera when both are enabled.

ABS's dev has provided the following feedback (see the ticket on his own page):

_"Unfortunately, I don't believe there's anything that can be done about this (from either of the extensions). I assume this is a deficiency of Opera. What both extensions are doing is modifying the request headers (ABS is doing this to spoof User-Agent). Now, it seems like Opera is only allowing one of the extensions to modify the headers, or they're letting ByPass Paywall take precedence over ABS."_

Thanks!

**Comment by iamadamdev** [comment]
Looks like that dev already answered.
