### ISSUE TITLE
Simple questions

### ISSUE THREAD

**Issue by AniaBerthelot** [iamadamdev/bypass-paywalls-chrome#983]
Hello,
I'd like to thank you first for this amazing work that is very useful to me.

For an AI project I'd like to reproduce the same idea as this project but with ASP.NET. So here's my questions :

1- Where Can I find documentation to master "cookies hacking" and "paywall bypass" logic and tools?
2- Is this goal achievable without browser help and specialy via ASP.NET?

Best wishes,

**Comment by iamadamdev** [comment]
Not a relevant issue.
