### ISSUE TITLE
Orlando Sentinal is ferocious about their cookies!

### ISSUE THREAD

**Issue by uruiamme** [iamadamdev/bypass-paywalls-chrome#986]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.
###

1. No other open issues
2. Installed, checked the Orlando Sentinel in options, disabled generic to test that, disabled uBlock on that page to test that.
3. Firefox 81.0.1
4. https://www.orlandosentinel.com/news/breaking-news/os-judge-fred-schott-blows-up-20150323-story.html
5. Running in a private browsing window, this site has detected it and demands that I login to see it.

"YOU'RE BROWSING IN PRIVATE MODE.
TO KEEP READING, PLEASE LOG IN OR SUBSCRIBE NOW.

Unlimited Digital Access
4 WEEKS 8 WEEKS FOR ONLY 99¢
continue to checkout
no commitment, cancel anytime
Access includes:

Our
website

Fewer
ads

Our
eNewspaper

Exclusive
app access
Go to homepage | Terms of Service | Privacy Policy"
[Large pop-over window and disabled scrolling]

I was not willing to open this URL in my regular browser, so I attempted to open the URL in a TOR browser. This was stopped because they ban EU users! And finally, I opened the URL in a completely different browser and I was able to see the content of the page without ad-blocking and without a popup to login. Is there a way to make the plugin or Firefox's Private Browsing able to view articles at the Orlando Sentinel? They detect private mode better than some sites do.

**Comment by iamadamdev** [comment]
Article loads fine for me in FF. Maybe try connected to a U.S. VPN?
