### ISSUE TITLE
Volkskrant: Article blocked

### ISSUE THREAD

**Issue by Woudart** [iamadamdev/bypass-paywalls-chrome#987]
1. uBlock Origin installed.
2. Firefox 82.0 (64-bit)
3. Article URL: https://www.volkskrant.nl/kijkverder/v/2020/de-schallmaier-index-trump-middle-finger~v405137/
4. Describe the issue:
Content blocked with message "Dit artikel is exclusief voor abonnees"
(###ANON_USER_CB_SUBSCRIBERS_EXCLUSIVE_OVERLAY)

**Comment by diehard88** [comment]
this bypass is for chrome, isn't it?

**Comment by Woudart** [comment]
> this bypass is for chrome, isn't it?

Repo looks to be merged with Chrome
https://github.com/iamadamdev/bypass-paywalls-firefox

**Comment by iamadamdev** [comment]
That article might be behind a hard paywall.
