### ISSUE TITLE
Impossible to use the Glassdoor Salary page [https://fr.glassdoor.ch/Pr%C3%A9sentation/Travailler-chez-UBS-EI_IE3419.16,19.htm]

### ISSUE THREAD

**Issue by Highlight96** [iamadamdev/bypass-paywalls-chrome#988]
<img width="1284" alt="Screenshot 2020-10-25 at 09 49 27" src="https://user-images.githubusercontent.com/73421524/97102628-61238780-16a7-11eb-902f-e406d0f555ff.png">

**Comment by iamadamdev** [comment]
Please read the instructions:
![image](https://user-images.githubusercontent.com/36013816/97112493-d9874a00-16a1-11eb-8eb3-90e068354409.png)

Otherwise trying google glassdoor <company> to land on a company's page w/o being logged in
