### ISSUE TITLE
Update to 1.4.7?

### ISSUE THREAD

**Issue by mxxmxm** [iamadamdev/bypass-paywalls-chrome#99]
Can you update to 1.4.7, consistent with Firefox version?

**Comment by iamadamdev** [comment]
Why? This version is different.

**Comment by mxxmxm** [comment]
The Firefox version has www.afr.com and this Chrome version doesn't ?

**Comment by iamadamdev** [comment]
Please submit a PR to add afr. All the source code is there from Firefox.
