### ISSUE TITLE
The Times no longer works

### ISSUE THREAD

**Issue by sheikhijat** [iamadamdev/bypass-paywalls-chrome#990]
Hello

The Times was working for me a few weeks ago but it doesn't anymore. Here's an example page:
https://www.thetimes.co.uk/article/i-looked-at-dominic-calvert-lewin-and-thought-hes-got-everything-p75rtfhl0

Thanks.

**Comment by sheikhijat** [comment]
Btw I'm using Firefox.

**Comment by iamadamdev** [comment]
Try latest master for Chrome
