### ISSUE TITLE
Washington Post not working

### ISSUE THREAD

**Issue by marcmarina** [iamadamdev/bypass-paywalls-chrome#994]
[The Washington Post](https://www.washingtonpost.com/) is not working at the moment. I checked the extension's errors and I found this one.

![Error](https://i.imgur.com/WnsHdMW.png)

I am using this extension on Brave, and it has always worked fine. Let me know if you need more info! 😄

**Comment by pjpreilly** [comment]
On certain Articles...
https://www.washingtonpost.com/religion/2020/10/26/trump-christian-nationalism-patriot-church/

**Comment by pjpreilly** [comment]
... chrome 1.7.6...

**Comment by pjpreilly** [comment]
sme error on chrome too...

**Comment by geckolinux** [comment]
This fixed it for me:
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/959#issuecomment-710143551

**Comment by pjpreilly** [comment]
> This fixed it for me:
> [#959 (comment)](https://github.com/iamadamdev/bypass-paywalls-chrome/issues/959#issuecomment-710143551)

Yes it does, thx
