### ISSUE TITLE
FT is not working

### ISSUE THREAD

**Issue by stamatgeorge** [iamadamdev/bypass-paywalls-chrome#995]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed. 
Yes Installed
3. Chrome or Firefox? 
Using Firefox 82.0 & Bypass Paywalls 1.7.6
4. Paste the article URL for the site you are having issues with.
https://www.ft.com/content/cff96ef6-9872-11e7-8c5c-c8d8fa6961bb

5. Describe the issue.
###
Not able to read article

**Comment by iamadamdev** [comment]
Still works for me.

**Comment by stamatgeorge** [comment]
I Updated to 1.7.7 — same issue

On October 27, 2020 at 7:13:01 AM, George Stamatis ❤️ (
stamatgeorge@gmail.com) wrote:

Weird. Still doesn’t work lol
Other articles on FT are not working as well.

See 2 Screenshots



On October 27, 2020 at 12:16:48 AM, Adam (notifications@github.com) wrote:

Still works for me.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iamadamdev/bypass-paywalls-chrome/issues/995#issuecomment-716968982>,
or unsubscribe
