### ISSUE TITLE
Statista - Key Market Indicators blurred out

### ISSUE THREAD

**Issue by funkyfliam** [iamadamdev/bypass-paywalls-chrome#996]
###
1. First search [Issues](https://github.com/iamadamdev/bypass-paywalls-chrome/issues) to see if your problem has already been reported.
2. Make sure uBlock Origin is installed.
3. Chrome
4. https://www.statista.com/outlook/16020600/107/toasters/australia
5. Describe the issue.
###
Towards the bottom of the page, the Key Market Indicators section is still blurred out.

**Comment by iamadamdev** [comment]
Only basic info works, you will need to buy a subscription for that.
